UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Order_Stage__c.field-meta.xml
<CustomField>
    <fullName>Order_Stage__c</fullName>
    <label>Order Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Clean Order</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Clean Order</fullName>
            </value>
            <value>
                <fullName>CNP Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>CPM In Progress</fullName>
            </value>
            <value>
                <fullName>Credit Check</fullName>
            </value>
            <value>
                <fullName>Customer Network Provisioning</fullName>
            </value>
            <value>
                <fullName>DPI/CMS Provisioning</fullName>
            </value>
            <value>
                <fullName>DPI Billing</fullName>
            </value>
            <value>
                <fullName>DPI Provisioning</fullName>
            </value>
            <value>
                <fullName>ECR/EWO In Progress</fullName>
                <label>ECR/PSR In Progress</label>
            </value>
            <value>
                <fullName>EWO In Progress</fullName>
            </value>
            <value>
                <fullName>Hot Cuts</fullName>
            </value>
            <value>
                <fullName>IMPM</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>ISP Engineering</fullName>
            </value>
            <value>
                <fullName>Issuing Orders</fullName>
            </value>
            <value>
                <fullName>MSA Review</fullName>
            </value>
            <value>
                <fullName>NCM Pending Billing</fullName>
            </value>
            <value>
                <fullName>Needs more information</fullName>
            </value>
            <value>
                <fullName>Network COE</fullName>
            </value>
            <value>
                <fullName>Network Cost Management</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Order Engineering Desk</fullName>
            </value>
            <value>
                <fullName>Ordering</fullName>
            </value>
            <value>
                <fullName>OSP Engineering</fullName>
            </value>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Service_Order__c.field-meta.xml
<CustomField>
    <fullName>Service_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Order #</label>
    <referenceTo>Service_Order__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/Service_Order__c.object-meta.xml
<CustomObject>
    <description>This is the DPI Service Order(s) that are related to the associated order</description>
    <label>Service Order</label>
    <nameField>
        <label>Service Order #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Service Orders</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Service_Order_Stage__c.field-meta.xml
<CustomField>
    <fullName>Service_Order_Stage__c</fullName>
    <label>Service Order Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stage 1 - Order Entry</fullName>
                <label>Order Entry</label>
            </value>
            <value>
                <fullName>Stage 2 - Engineering Review</fullName>
                <label>Engineering Review</label>
            </value>
            <value>
                <fullName>Stage 3 - Construction / Build</fullName>
                <label>Construction / Build</label>
            </value>
            <value>
                <fullName>Stage 4 - Design / Provisioning</fullName>
                <label>Design / Provisioning</label>
            </value>
            <value>
                <fullName>Stage 5 - Physical / Virtual Turn up</fullName>
                <label>Physical / Virtual Turn up</label>
            </value>
            <value>
                <fullName>Stage 6 - Customer Acceptance / Billing</fullName>
                <label>Customer Acceptance / Billing</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>ESB Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/BatchServiceOrderStageUpdate.cls
/**
 * @description       : class is for updating service order stage in bulk number
 * @author            : Yasin Khan
 * @version           : 1 
**/

global with sharing class BatchServiceOrderStageUpdate implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
    
    private String sOrderStageExcluded = 'Completed';
    private String orderStageExcluded = 'Complete';
    private String orderStageExcluded2 = 'Cancelled';
    private String orderStageExcluded3 = 'New';
    private Date todaysDate = Date.today();
    private Date exactDate = todaysDate.addDays(-365);
    private Id devRecordTypeId = Schema.SObjectType.Service_Order__c.getRecordTypeInfosByName().get('M6 Service Order').getRecordTypeId();
    boolean exceptionFlag = false;
    public Map<String, String> listOfSOUpdated = new Map<String, String>();
    public Map<String, String> listOfSONotUpdated = new Map<String, String>();
    public Map<String, String> listOfSOWithExceptions = new Map<String, String>();
    public Integer count = 0;
    Public String s = '';
    
    public BatchServiceOrderStageUpdate() {

    }

    public Database.QueryLocator start(Database.BatchableContext BC){

        String query = 'SELECT Id, Name'
                        +' From Service_Order__c'
                        +' WHERE RecordTypeId = :devRecordTypeId and CreatedDate >= :exactDate AND'
                        +' (Service_Order_Stage__c != :sOrderStageExcluded AND Order__r.Order_Stage__c != :orderStageExcluded AND'
                        +' Order__r.Order_Stage__c != :orderStageExcluded2 AND Order__r.Order_Stage__c != :orderStageExcluded3)';

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Service_Order__c> sOrderList){
        String currentItem = '';
        String currentItemId = '';
        if(sOrderList.size() > 0) {
            try{
                for(Service_Order__c item : sOrderList) {
                    currentItem = item.Name;
                    currentItemId = item.Id;
                    Service_Order__c serviceOrder = ServiceOrderStage_Ctrl.updateOrderStage(item.Id, item.Name, true);
                    if(serviceOrder != null) {
                        listOfSONotUpdated.put(item.Id, item.Name);
                    } else {
                        listOfSOUpdated.put(item.Id, item.Name);
                    }
                }
            }catch(Exception e) {
                count++;
                listOfSOWithExceptions.put(currentItemId, currentItem);
                s = currentItem+'!'+e.getMessage();
                exceptionFlag = true;
            }
        }
    }

    global void finish(Database.BatchableContext BC){

        if(listOfSOUpdated.size() > 0) {
            CSVCreationForM6SOrderStageUpdate.createCsv(listOfSOUpdated, 'Updated');
        }

        if(listOfSONotUpdated.size() > 0) {
            CSVCreationForM6SOrderStageUpdate.createCsv(listOfSONotUpdated, 'Not Updated');
        }

        if(listOfSOWithExceptions.size() > 0) {
            CSVCreationForM6SOrderStageUpdate.createCsv(listOfSOWithExceptions, 'With Exception');
        }

        if(exceptionFlag) {
            System.debug('Exception occured for : '+count);
        }
    }
}