UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Service_Order__c.field-meta.xml
<CustomField>
    <fullName>Service_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Order #</label>
    <referenceTo>Service_Order__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/Service_Order__c.object-meta.xml
<CustomObject>
    <description>This is the DPI Service Order(s) that are related to the associated order</description>
    <label>Service Order</label>
    <nameField>
        <label>Service Order #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Is_Created_By_Velocity__c.field-meta.xml
<CustomField>
    <fullName>Is_Created_By_Velocity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Synced With M6?</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Item_Spec_Id__c.field-meta.xml
<CustomField>
    <fullName>Item_Spec_Id__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1001</fullName>
                <label>Retail Circuit Service</label>
            </value>
            <value>
                <fullName>1002</fullName>
                <label>Broadband Services - Retail</label>
            </value>
            <value>
                <fullName>1003</fullName>
                <label>ATM/FR Connection</label>
            </value>
            <value>
                <fullName>1005</fullName>
                <label>PVC Connection</label>
            </value>
            <value>
                <fullName>1007</fullName>
                <label>Circuit Services - Wholesale</label>
            </value>
            <value>
                <fullName>1009</fullName>
                <label>Broadband Services - Whsl Resale</label>
            </value>
            <value>
                <fullName>1010</fullName>
                <label>ATM/FR Connection.</label>
            </value>
            <value>
                <fullName>1011</fullName>
                <label>Ethernet Connection</label>
            </value>
            <value>
                <fullName>1012</fullName>
                <label>PVC Connection.</label>
            </value>
            <value>
                <fullName>1013</fullName>
                <label>EVC Connections - Retail.</label>
            </value>
            <value>
                <fullName>1040</fullName>
                <label>Circuit Services - Whsl Resale</label>
            </value>
            <value>
                <fullName>1041</fullName>
                <label>Wholesale Resale Circuit Service</label>
            </value>
            <value>
                <fullName>1042</fullName>
                <label>Wholesale UNE Loop/Circuit Service</label>
            </value>
            <value>
                <fullName>1060</fullName>
                <label>Trunk Group Data - Retail</label>
            </value>
            <value>
                <fullName>1061</fullName>
                <label>Data Trunk</label>
            </value>
            <value>
                <fullName>1062</fullName>
                <label>Trunk Group Data - Whsl Resale</label>
            </value>
            <value>
                <fullName>1063</fullName>
                <label>Trunk Group ISDN - Retail</label>
            </value>
            <value>
                <fullName>1064</fullName>
                <label>ISDN Trunk</label>
            </value>
            <value>
                <fullName>1065</fullName>
                <label>Data Trunk.</label>
            </value>
            <value>
                <fullName>1066</fullName>
                <label>Trunk Group ISDN - Whsl Resale</label>
            </value>
            <value>
                <fullName>1067</fullName>
                <label>ISDN Trunk.</label>
            </value>
            <value>
                <fullName>1068</fullName>
                <label>Trunk Group Voice/DCS - Retail</label>
            </value>
            <value>
                <fullName>1069</fullName>
                <label>Trunk Group Voice/DCS - Whsl Resale</label>
            </value>
            <value>
                <fullName>1070</fullName>
                <label>Voice/DCS Trunk</label>
            </value>
            <value>
                <fullName>1071</fullName>
                <label>Voice/DCS Trunk.</label>
            </value>
            <value>
                <fullName>1080</fullName>
                <label>EVC Connections - Retail</label>
            </value>
            <value>
                <fullName>1101</fullName>
                <label>EVPL</label>
            </value>
            <value>
                <fullName>1102</fullName>
                <label>EIA</label>
            </value>
            <value>
                <fullName>1103</fullName>
                <label>ELAN</label>
            </value>
            <value>
                <fullName>1111</fullName>
                <label>UNI Connections - Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/M6_dd_task_date__c.field-meta.xml
<CustomField>
    <fullName>M6_dd_task_date__c</fullName>
    <label>M6 Due Date</label>
    <type>DateTime</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/M6_Order_Notes__c.field-meta.xml
<CustomField>
    <fullName>M6_Order_Notes__c</fullName>
    <label>M6 Order Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Priloc_Address__c.field-meta.xml
<CustomField>
    <fullName>Priloc_Address__c</fullName>
    <label>Primary Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Secloc_Address__c.field-meta.xml
<CustomField>
    <fullName>Secloc_Address__c</fullName>
    <label>Secondary Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Service_Order_Stage__c.field-meta.xml
<CustomField>
    <fullName>Service_Order_Stage__c</fullName>
    <label>Service Order Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stage 1 - Order Entry</fullName>
                <label>Order Entry</label>
            </value>
            <value>
                <fullName>Stage 2 - Engineering Review</fullName>
                <label>Engineering Review</label>
            </value>
            <value>
                <fullName>Stage 3 - Construction / Build</fullName>
                <label>Construction / Build</label>
            </value>
            <value>
                <fullName>Stage 4 - Design / Provisioning</fullName>
                <label>Design / Provisioning</label>
            </value>
            <value>
                <fullName>Stage 5 - Physical / Virtual Turn up</fullName>
                <label>Physical / Virtual Turn up</label>
            </value>
            <value>
                <fullName>Stage 6 - Customer Acceptance / Billing</fullName>
                <label>Customer Acceptance / Billing</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>ESB Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/ServiceOrderStage_Ctrl.cls
global without sharing class ServiceOrderStage_Ctrl {
    
    webservice static void updateSOStage(Id soId,String orderNum){
        updateOrderStage(soId,orderNum,true);
    }
    @AuraEnabled
    public static Service_Order__c updateOrderStage(Id soId,String orderNum,Boolean isCalledFromQuickAction){
        system.debug('soId :: '+soId);
         system.debug('orderNum :: '+orderNum);
        HttpResponse response = ServiceOrderStageVlocityM6.retrieveM6SoStage(orderNum);//3369393
        system.debug('response :: '+response.getBody());
        
        ServiceOrderResponse sor = parseResponse(response);
        //if(String.isBlank(sor.items[0].order_stage)){
            //throw new ServiceOrderStage_Exception(JSON.serialize(new ErrorMessage('UNKNOWN ERROR','We did not get any Orger Stage For Order Number '+orderNum)));
        //}
        if(sor.items == null || sor.items.size() == 0){
            return null;
        }
        try{
            String dateInISOFormate = String.isNotBlank(sor.items[0].dd_task_date)?'"'+sor.items[0].dd_task_date+'"':null;
            Integer offset = UserInfo.getTimezone().getOffset(System.now()) * (-1);
            
            //String orderStage = String.isBlank(sor.items[0].order_stage) ? '':sor.items[0].order_stage;
            String orderStage = '';

            if(String.isBlank(sor.items[0].order_stage) && !String.isBlank(sor.items[0].order_status)) {
                if(sor.items[0].order_status == 'Complete') {
                    orderStage = 'Completed';
                } else {
                    orderStage = '';
                }
            } else if(String.isBlank(sor.items[0].order_stage) && String.isBlank(sor.items[0].order_status)) {
                orderStage = '';
            } else {
                orderStage = sor.items[0].order_stage;
            }

            Service_Order__c so = new Service_Order__c();
            so.Id = soId;
            so.Service_Order_Stage__c = orderStage;
            so.M6_Order_Notes__c = sor.items[0].last_cust_note;
            so.M6_dd_task_date__c = dateInISOFormate!=null?DateTime.valueOf(JSON.deserialize(dateInISOFormate, Datetime.class)).addSeconds(offset/1000):null;
            so.Priloc_Address__c=sor.items[0].priloc_address;
            so.Secloc_Address__c=sor.items[0].secloc_address;
			so.Item_Spec_Id__c = String.valueOf(sor.items[0].item_spec_id);
            if(so.Item_Spec_Id__c != null || so.Item_Spec_Id__c != 'null' || so.Item_Spec_Id__c != ''){
                	so.Is_Created_By_Velocity__c = false;
            }
            if(isCalledFromQuickAction){
                if(!String.isBlank(orderStage)) {
                    update so;
                } else {
                    return so;
                }
            }else{
                return so;
            }
        }catch(Exception ee){
            if(ee.getMessage().contains('INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST'))
                throw new ServiceOrderStage_Exception(JSON.serialize(new ErrorMessage('DML ERROR','Please add '+'\''+sor.items[0].order_stage+'\''+' Stage value to Service Order Stage')));
            else
                throw new ServiceOrderStage_Exception(JSON.serialize(new ErrorMessage('DML ERROR',ee.getMessage())));
        }
        return null;
    }
    public static ServiceOrderResponse parseResponse(HttpResponse response){
        if (response.getStatusCode() == 200) return new ServiceOrderResponse().parse(response.getBody());
        
        else throw new ServiceOrderStage_Exception(JSON.serialize(new ErrorMessage('Bad Request','Something went wrong . Status code is '+response.getStatusCode())));
        
    }
    
    public class ServiceOrderStage_Exception extends Exception {}
    
    public class ErrorMessage{
        @AuraEnabled public String cause;
        @AuraEnabled public String errorMessage;
        public ErrorMessage(String cause,String errorMessage){
            this.cause = cause;
            this.errorMessage = errorMessage;
        }
    }
    
}