UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Service_Order__c.field-meta.xml
<CustomField>
    <fullName>Service_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Order #</label>
    <referenceTo>Service_Order__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/vlocity_cmt__OrchestrationPlanId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__OrchestrationPlanId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orchestration Plan</label>
    <referenceTo>vlocity_cmt__OrchestrationPlan__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/Service_Order__c.object-meta.xml
<CustomObject>
    <description>This is the DPI Service Order(s) that are related to the associated order</description>
    <label>Service Order</label>
    <nameField>
        <label>Service Order #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Circuit_ID__c.field-meta.xml
<CustomField>
    <fullName>Circuit_ID__c</fullName>
    <description>M5 Service Order Circuit ID</description>
    <label>Circuit ID</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>DPI Service Order Description</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Service Orders</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Schedule_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Due_Date__c</fullName>
    <description>This is the date that the work is to be ready by... (TBD)</description>
    <label>Schedule Due Date</label>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASR</fullName>
            </value>
            <value>
                <fullName>DPI</fullName>
            </value>
            <value>
                <fullName>EWO</fullName>
            </value>
            <value>
                <fullName>ISR</fullName>
            </value>
            <value>
                <fullName>PSR</fullName>
            </value>
            <value>
                <fullName>TBD</fullName>
                <isActive>false</isActive>
                <label>TBD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Working_Number__c.field-meta.xml
<CustomField>
    <fullName>Working_Number__c</fullName>
    <description>This is the DPI Service Order Working Number.</description>
    <inlineHelpText>This is the DPI Service Order Working Number.</inlineHelpText>
    <label>Working #</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/recordTypes/M6_Service_Order.recordType-meta.xml
<RecordType>
    <fullName>M6_Service_Order</fullName>
    <active>true</active>
    <description>Use this is for M6 Service Orders</description>
    <label>M6 Service Order</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/classes/XOMAutoTask_CreateM6ServiceOrder.cls
/**
 * @description       : 
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 3 
**/
global class XOMAutoTask_CreateM6ServiceOrder implements vlocity_cmt.XOMOrchestrationInterfaces.IAutoTask {
    private static final Integer MAX_ATTEMPTS = 3;
    global void executeBatch(List <vlocity_cmt__OrchestrationItem__c> items) {
        ftr_Logger.writeInfo('Enter XOMAutoTask_CreateM6ServiceOrder.executeBatch');
        try {
            Set<Id> frlIds = new Set<Id>();
            for (vlocity_cmt__OrchestrationItem__c item : items) {
                frlIds.add(item.vlocity_cmt__fulfilmentRequestLineId__c);
            }
            vlocity_cmt__FulfilmentRequestLine__c[] frls = [SELECT Id, vlocity_cmt__JSONAttribute__c, vlocity_cmt__FulfilmentRequestID__r.vlocity_cmt__orchestrationPlanId__r.vlocity_cmt__OrderId__r.OrderNumber, vlocity_cmt__Product2Id__r.Name 
                                                            FROM vlocity_cmt__FulfilmentRequestLine__c
                                                            WHERE Id=:frlIds];

            RecordType rt = [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName ='M6_Service_Order'];

            // Create Service Order
            List<Service_Order__c> soList = new List<Service_Order__c>();
            for (vlocity_cmt__FulfilmentRequestLine__c frl : frls) {
                Service_Order__c so = new Service_Order__c(
                    Name = (String)ftr_CpqHelper.getJSONAttributeValue(frl.vlocity_cmt__JSONAttribute__c, 'documentNumber'),
                    Circuit_ID__c = (String)ftr_CpqHelper.getJSONAttributeValue(frl.vlocity_cmt__JSONAttribute__c, 'documentNumber'),
                    Working_Number__c = (String)ftr_CpqHelper.getJSONAttributeValue(frl.vlocity_cmt__JSONAttribute__c, 'WTN'),
                    Type__c = 'PSR',
                    Order__c = frl.vlocity_cmt__FulfilmentRequestID__r.vlocity_cmt__orchestrationPlanId__r.vlocity_cmt__OrderId__r.Id,
                    Order_Number__c = frl.vlocity_cmt__FulfilmentRequestID__r.vlocity_cmt__orchestrationPlanId__r.vlocity_cmt__OrderId__r.OrderNumber,
                    Description__c = 'Auto generated for "' + frl.vlocity_cmt__Product2Id__r.Name + '" by Vlocity OM',
                    RecordTypeId = rt.Id,
                    Schedule_Due_Date__c = Date.today()
                );
                
                soList.add(so);
            }
           // insert soList;
            Integer attempts = MAX_ATTEMPTS;
            while(attempts > 0){
                System.debug('insert save attempt number is:{0} ' +attempts);
                try {
                    attempts--; 
                    if(!Test.isRunningTest()){
                   
                        insert soList;
                    }
                     attempts = 0;
                } catch (System.DmlException dmlEx) {
                            if (!dmlEx.getMessage().contains('UNABLE_TO_LOCK_ROW')) { 
                                attempts = 0;  // exit on any other exception
                        throw dmlEx;  // throw exception after MAX_ATTEMPTS
                    }
                       }
                      
            } 
            
        } catch (Exception ex) { 
            ftr_Logger.write(ex);

            throw ex;
        } finally {
            ftr_Logger.writeInfo('Exit XOMAutoTask_CreateM6ServiceOrder.executeBatch');
        }
    }


    
}