UCF-APR2.4/ftr main/force-app/main/default/objects/Agreement_Contracts__c/Agreement_Contracts__c.object-meta.xml
<CustomObject>
    <label>Agreement Contracts</label>
    <nameField>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Agreement_Contracts__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <referenceTo>echosign_dev1__SIGN_Agreement__c</referenceTo>
    <relationshipLabel>Agreement Contracts</relationshipLabel>
    <relationshipName>Agreement_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Agreement_Contracts__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Agreement Contracts</relationshipLabel>
    <relationshipName>Agreement_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/Contract_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status__c</fullName>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Signed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Declined/Cancelled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Terminated by Frontier</fullName>
            </value>
            <value>
                <fullName>Terminated by Partner</fullName>
            </value>
            <value>
                <fullName>Terminated by Customer</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Redlined</fullName>
            </value>
            <value>
                <fullName>Sent Redline Document to Customer</fullName>
            </value>
            <value>
                <fullName>FTR Received Redline Document from Customer</fullName>
            </value>
            <value>
                <fullName>FTR Generated Final Clean Document</fullName>
            </value>
            <value>
                <fullName>AE sent Redline to Legal</fullName>
            </value>
            <value>
                <fullName>AE sent Redline to Risk Management</fullName>
            </value>
            <value>
                <fullName>AE sent Redline to Engineering</fullName>
            </value>
            <value>
                <fullName>Redline Approved by Legal</fullName>
            </value>
            <value>
                <fullName>Redline Approved by Risk Management</fullName>
            </value>
            <value>
                <fullName>Redline Approved</fullName>
            </value>
            <value>
                <fullName>Fully Signed</fullName>
            </value>
            <value>
                <fullName>Document Generated</fullName>
            </value>
            <value>
                <fullName>Document Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Awaiting for Customer Signature</fullName>
            </value>
            <value>
                <fullName>FTR Signed</fullName>
            </value>
            <value>
                <fullName>Sent Document back to Customer</fullName>
            </value>
            <value>
                <fullName>Up for Renewal</fullName>
            </value>
            <value>
                <fullName>Retirement</fullName>
            </value>
            <value>
                <fullName>Customer Requests Negotiations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/ftr_CreateContractAgrement.cls
/*
** Class Name:ftr_CreateContractAgrement
** Created Date: 2021-06-24
** Created By: Vinod kakantala of EagleCreek
** Description:
**
** History:
** 2021-06-17: Class created date
**/
global class ftr_CreateContractAgrement implements vlocity_cmt.VlocityOpenInterface  {
    public Boolean invokeMethod(String methodName, Map<String,Object> input,Map<String,Object> output,Map<String,Object> options){
        if(methodName.equals('Contractagreement')){
            Contractagreement(input,output,options);
        }
     
        
        
        return true;
    }
public Boolean Contractagreement(Map<String,Object> input,Map<String,Object> output,Map<String,Object> options){
    //string aggid = 'a6G5Y000002djLGUAY';
    //string oppid = '0065Y00001WiM5HQAV';
    string aggid = (Id)input.get('AgreementId');
    string oppid = (Id)input.get('OpportunityId');
    string acctid = (Id)input.get('AccountId');
    list<String> REC_TYPES = new List<String>{'Frontier Services Agreement','Community Connections - Agreement','VZ3 Agreement - VEC','VZ3 Agreement - VES', 'Product Schedule'};//all recordtypes
    list<Contract> contractlist  = [SELECT id,vlocity_cmt__ActiveContractVersionId__c,	Opportunity__c  FROM Contract WHERE (Opportunity__c = :oppid or (AccountId= :acctid AND RecordType.Name = 'Frontier Services Agreement'))  AND RecordType.Name IN: REC_TYPES AND (Contract_Status__c = 'Draft')];
 	set<string>contractversionId= new set<string>();
    for(Contract c : Contractlist){
        contractversionId.add(c.vlocity_cmt__ActiveContractVersionId__c);
    }
    list<vlocity_cmt__ContractVersion__c>contversion = [SELECT id, vlocity_cmt__ContractId__c FROM vlocity_cmt__ContractVersion__c where Id IN :contractversionId];
    set<string>versionid= new set<string>();
    map<string,string>versn2contract = new map<string,string>();
    for(vlocity_cmt__ContractVersion__c cv : contversion){
        versionid.add(cv.id);
        versn2contract.put(cv.vlocity_cmt__ContractId__c,cv.Id);
    }
    map<string,string>versn2attachment = new map<string,string>();
    list<Attachment>attachlist=[SELECT Id,Name,ParentId FROM Attachment where ParentId IN :versionid];
    for(Attachment a : attachlist){
        versn2attachment.put(a.ParentId,a.Name);
        ftr_DocumentAttachmentConverter.convertAttachmentToContent(a.Id,aggid);
    }
    //Passing AttachmentId and AgreementId
    //ftr_DocumentAttachmentConverter.convertAttachmentToContent(attachlist[0].Id,aggid);
    
    //// SELECT Agreement__c,Contract__c,Name FROM Agreement_Contracts__c
    list<Agreement_Contracts__c>listac = new list<Agreement_Contracts__c>();
    for(String conid : versn2contract.keyset()){
        Agreement_Contracts__c acon = new Agreement_Contracts__c();
        acon.Contract__c = conid;
        acon.Name = versn2attachment.get(versn2contract.get(conid));
        acon.Agreement__c=aggid;
        listac.add(acon);
        system.debug('Adding listac@@@@@'+listac);
    }
    
    insert listac;
    system.debug('Insertion listac@@@@@'+listac);
    output.put('BooleanValue', true);
    return true;
}
}