UCF-APR2.4/ftr main/force-app/main/default/objects/vlocity_cmt__Premises__c/objects/vlocity_cmt__Premises__c.object
<CustomObject>
    <fields>
        <fullName>Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vlocity_cmt__City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PostalCode__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__StreetAddress__c</fullName>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__UnitNumber__c</fullName>
        <description>Unit / Apartment number of this Premises.</description>
        <label>Unit / Apartment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Premises</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/classes/premisesUtility.cls
public with sharing class premisesUtility {
    public static void setKey(List<vlocity_cmt__Premises__c> premisesList) {
        for(vlocity_cmt__Premises__c prem:premisesList){
            String retsha256Hash = getAddressHashKey(prem.vlocity_cmt__StreetAddress__c, 
            prem.vlocity_cmt__City__c, prem.vlocity_cmt__State__c, prem.vlocity_cmt__PostalCode__c, 
            prem.vlocity_cmt__Country__c, prem.vlocity_cmt__UnitNumber__c);
            if(retsha256Hash != null){
                prem.Key__c = retsha256Hash;
            }
        }
    }
    public static string getAddressHashKey(string streetAddress, String city, String state, String postalCode, String country, String addressUnit){
        String addressLine = '';
        if(!String.isBlank(streetAddress)){
            addressLine = streetAddress;
        }
        if(!String.isBlank(city)){
            addressLine += ', ' + city;
        }
        if(!String.isBlank(state)){
            addressLine += ', ' + state;
        }
        if(!String.isBlank(postalCode)){
            addressLine += ', ' + postalCode;
        }
        if(!String.isBlank(country)){
            addressLine += ', ' + country;
        }
        
        addressLine = addressLine.toLowerCase();
        String retsha256Hash = convertStringToSha256Hash(addressLine);
        if (!String.isBlank(addressUnit)){
            return retsha256Hash+'-'+addressUnit.toLowerCase();
        }else {
            return retsha256Hash;
        }
    }
    public static vlocity_cmt__Premises__c getPremise(string streetAddress, String city, String state, String postalCode, String country, String addressUnit){
        string key = getAddressHashKey(streetAddress, city, state, postalCode, country, addressUnit);
        if (key!= null){
            List<vlocity_cmt__Premises__c> lstPremises = new List<vlocity_cmt__Premises__c>([select Id, vlocity_cmt__StreetAddress__c, key__c,
            vlocity_cmt__City__c,vlocity_cmt__State__c, vlocity_cmt__PostalCode__c,
            vlocity_cmt__Country__c, vlocity_cmt__UnitNumber__c from vlocity_cmt__Premises__c  where
            Key__c =:key ]);
            if (lstPremises.size()>0){
                return lstPremises[0];
            }else {
                return null;
            }
        }else {
            return null;
        }
    }
    public static String convertStringToSha256Hash(String address){
        String sha256Hash;
        if(!String.isBlank(address)){
            Blob targetBlob = Blob.valueOf(address);
            Blob hash = Crypto.generateDigest('SHA-256', targetBlob);
            sha256Hash = EncodingUtil.base64Encode(hash);
        }
        return sha256Hash;
    }
}