UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Floor_Price_One_Time__c.field-meta.xml
<CustomField>
    <fullName>Floor_Price_One_Time__c</fullName>
    <label>Floor Price (One Time)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Floor_Price_Recurring__c.field-meta.xml
<CustomField>
    <fullName>Floor_Price_Recurring__c</fullName>
    <label>Floor Price (Recurring)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__OneTimeCharge__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__OneTimeCharge__c</fullName>
    <label>One Time Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__RecurringCharge__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__RecurringCharge__c</fullName>
    <description>Initial Recurring charge from Pricelist</description>
    <label>Recurring Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account that identifies the service location or subscriber that is the user of the service.</description>
    <label>Service Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>ServiceAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/QuoteLinesController.cls
public class QuoteLinesController
{ 
    public String vquoteId {get; set;} 
  
    
    public List<QuoteLineItem> quotelines {
        get
      {
          return [select Id,
                    Floor_Price_One_Time__c,
                    Floor_Price_Recurring__c,
                    //Product2Id__r.name 
                    Product2.Name,
                  	vlocity_cmt__ServiceAccountId__r.Name,
                    vlocity_cmt__Recurringcharge__c,
                    vlocity_cmt__OnetimeCharge__c
                    from QuoteLineItem 
                    where quoteid= : vquoteId ];
           }
    }      
 
}