UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/ftr_MRC_Discounted__c.field-meta.xml
<CustomField>
    <fullName>ftr_MRC_Discounted__c</fullName>
    <description>MRC Discounted Percentage</description>
    <formula>MRC_Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ftr MRC Discounted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/ftr_NRC_Discounted__c.field-meta.xml
<CustomField>
    <fullName>ftr_NRC_Discounted__c</fullName>
    <description>NRC Discounted Percent</description>
    <formula>((vlocity_cmt__BaseOneTimeCharge__c - vlocity_cmt__OneTimeCharge__c)/vlocity_cmt__BaseOneTimeCharge__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ftr NRC Discounted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <description>This is used to store the attribute value selected for Speed.</description>
    <label>Speed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>Bound to Attribute = Term</description>
    <label>Term</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__BaseRecurringCharge__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__BaseRecurringCharge__c</fullName>
    <description>Holds the recurring charge of the quote line items before applying overrides or adjustments.</description>
    <label>Base Recurring Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DEPRECATED, Use the standard Product2Id field.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__RecurringCharge__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__RecurringCharge__c</fullName>
    <description>Initial Recurring charge from Pricelist</description>
    <label>Recurring Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account that identifies the service location or subscriber that is the user of the service.</description>
    <label>Service Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>ServiceAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/QuoteEmail.cls
public class QuoteEmail {
	public Id QuoteID {get;set;}
    public List<QuoteLineItem> getQuoteLineItems()
    {
        List<QuoteLineItem> QuoteLineItems = [SELECT Id, QuoteId, Quantity, vlocity_cmt__BaseRecurringCharge__c,ftr_MRC_Discounted__c, 
                                              		vlocity_cmt__RecurringCharge__c,vlocity_cmt__ServiceAccountId__c,
                                              		UnitPrice, Product2Id, vlocity_cmt__ServiceAccountId__r.Name, 
                                              		vlocity_cmt__Product2Id__r.Name, Speed__c,Term__c,
                                              		vlocity_cmt__ServiceAccountId__r.ShippingStreet,
                                                      vlocity_cmt__ServiceAccountId__r.ShippingCity,
                                                      vlocity_cmt__ServiceAccountId__r.ShippingState,
                                                      vlocity_cmt__ServiceAccountId__r.ShippingCountry,
                                                      vlocity_cmt__ServiceAccountId__r.ShippingPostalCode,
                                              		PricebookEntry.Product2.ProductCode, TotalPrice 
                 								FROM QuoteLineItem WHERE QuoteId =: QuoteID AND 
                                              		(ftr_MRC_Discounted__c > 0 OR ftr_NRC_Discounted__c > 0)
                                              ];
        // PricebookEntry.Product2.ProductCode IN ('ENT_ETH_EIA_0002')
        // BaseRecurringCharge__c > vlocity_cmt__RecurringCharge__c
        return QuoteLineItems;
    }
}