UCF-APR2.4/ftr main/force-app/main/default/objects/WS_ESB_Settings__c/WS_ESB_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ESB Service Settings</label>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/WS_ESB_Settings__c/fields/EC_ApplicationID__c.field-meta.xml
<CustomField>
    <fullName>EC_ApplicationID__c</fullName>
    <description>Execution Context - Application ID</description>
    <inlineHelpText>Execution Context - Application ID</inlineHelpText>
    <label>Application ID</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WS_ESB_Settings__c/fields/EC_EmployeeID__c.field-meta.xml
<CustomField>
    <fullName>EC_EmployeeID__c</fullName>
    <description>Execution Context - Employee ID</description>
    <inlineHelpText>Execution Context - Employee ID</inlineHelpText>
    <label>Employee ID</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WS_ESB_Settings__c/fields/EC_UserID__c.field-meta.xml
<CustomField>
    <fullName>EC_UserID__c</fullName>
    <description>Execution Context - User ID</description>
    <inlineHelpText>Execution Context - User ID</inlineHelpText>
    <label>User ID</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WS_ESB_Settings__c/fields/FBV_Apigee_Token__c.field-meta.xml
<CustomField>
    <fullName>FBV_Apigee_Token__c</fullName>
    <label>FBV Apigee Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/AgentTools_GetTechnologyForAddressTest.cls
@isTest
public class AgentTools_GetTechnologyForAddressTest {
    // version 1 
    /*@testSetup
    static void testSetup() {
        WS_ESB_Settings__c objSetting = new WS_ESB_Settings__c(FBV_Apigee_Token__c = 'MW35cUl3YX0F4V23qd9ZWGuVocmRz10o', EC_ApplicationID__c = 'SFDC', EC_EmployeeID__c = '123456', EC_UserID__c = 'ESB_REG');
        insert objSetting;
    }*/
    public static testMethod void getTechnologyForAddressTest() { 
         Test.setMock(HttpCalloutMock.class, new AgentTools_GetTechforAdrRespMock());
        String evCode ='FT';
        Integer serviceControlNumber=536670;
        Boolean b = AgentTools_GetTechnologyForAddress.getTechnologyForAddress(evCode, serviceControlNumber);
        System.debug('b');
    }
     static testmethod void testIncrement() {
        Test.startTest();
       // AgentTools_GetTechnologyForAddress.dummytestcoverage();
        Test.stopTest(); 
        
 }

}