UCF-APR2.4/ftr main/force-app/main/default/objects/FulfilmentRequestEvent__e/FulfilmentRequestEvent__e.object-meta.xml
<CustomObject>
    <label>Fulfilment Request Event</label>
    <pluralLabel>Fulfilment Request Events</pluralLabel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FulfilmentRequestEvent__e/fields/FRL_Id__c.field-meta.xml
<CustomField>
    <fullName>FRL_Id__c</fullName>
    <label>FRL_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FulfilmentRequestEvent__e/fields/JSONAttribute__c.field-meta.xml
<CustomField>
    <fullName>JSONAttribute__c</fullName>
    <label>JSONAttribute</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/FulfilmentRequestSubscriber.cls
global class FulfilmentRequestSubscriber {

    global Boolean invokeMethod(String methodName, Map<String, Object> inputMap, Map<String, Object> outputMap, Map<String, Object> options) {
        System.debug('Enter FulfilmentRequestSubscriber.' + methodName);
        try {
            if (methodName == 'updateFRLs') {
                return updateFRLs(inputMap);
            }
            return true;
        } catch (Exception ex) {
            System.debug(ex.getLineNumber() + ': ' + ex.getMessage());
            return false;
        } finally {
            System.debug('Exit FulfilmentRequestSubscriber.' + methodName);
        }
    }

    public Boolean updateFRLs(Map<String, Object> input) {
        vlocity_cmt__FulfilmentRequestLine__c[] frlList = new vlocity_cmt__FulfilmentRequestLine__c[]{};
        for (FulfilmentRequestEvent__e event : (List<FulfilmentRequestEvent__e>) input.get('events')) {
            frlList.add(new vlocity_cmt__FulfilmentRequestLine__c(
                Id=event.FRL_Id__c,
                vlocity_cmt__JSONAttribute__c=event.JSONAttribute__c
            ));
        }
        if (frlList.size() > 0) update frlList;
        return true;
    }
}