UCF-APR2.4/ftr main/force-app/main/default/objects/Email_Distribution__c/Email_Distribution__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This object is used to hold email address</description>
    <label>Email Distribution</label>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Email_Distribution__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is used to maintain the email ids of admins who would like to receive emails after their bulk account update job is finished</description>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/ServiceAccountOwnerChange.cls
public class ServiceAccountOwnerChange implements Queueable {
    private List<Account> lstServiceAccounts ; 
    private Integer count = 0;
    
    
    public ServiceAccountOwnerChange(List<Account> lstServiceAccounts,Boolean isItParentJob){
        this.lstServiceAccounts = lstServiceAccounts;
        count = lstServiceAccounts.size();
        
        if(isItParentJob){
            sendEmail('Hi, Queueable Job to update service accounts has been set in queue.','Queueable Job Queued');
        }
    }
    
    public void execute(QueueableContext context) {
        if(count <= 500){ 
            update lstServiceAccounts;
            sendEmail('Hi, This is to inform you that Queueable job to update service accounts is completed.','Queueable Job Ended');
            if(!Test.isRunningTest()) return;
        } 
        
        List<Account> maxAccToUpdate = new List<Account>();
        List<Account> remainingAccounts = new List<Account>();
        count = 0;
        for(Account acc : lstServiceAccounts){
            if(count <= 500) maxAccToUpdate.add(acc);
            else remainingAccounts.add(acc);
            count++;
        }
        
        if(!Test.isRunningTest()){ 
            update maxAccToUpdate;
            System.enqueueJob(new ServiceAccountOwnerChange(remainingAccounts,false));
        }
    }
    public void sendEmail(String emailContent,String subject){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        //Getting the mail list from custom setting 
        List<String> emailList = new List<String>();
        for(Email_Distribution__c emails :[SELECT Id, Email__c FROM Email_Distribution__c WHERE Email__c != '']) emailList.add(emails.Email__c);
        if(emailList.size() == 0 && !Test.isRunningTest()) return;
        mail.setToAddresses(emailList);
        mail.setSubject(subject);
        mail.setHtmlBody(emailContent);
        try{
             Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{mail});
        }catch(exception ee){}
    }
}