UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Carrier_Service.recordType-meta.xml
<RecordType>
    <fullName>Carrier_Service</fullName>
    <active>true</active>
    <label>Carrier Service</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAcna__c/FTRWSAcna__c.object-meta.xml
<CustomObject>
    <label>Wholesale ACNA</label>
    <nameField>
        <label>FTRWSAcna Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesale ACNAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAcna__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wholesale ACNAs</relationshipLabel>
    <relationshipName>Wholesale_ACNAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSPnum__c/FTRWSPnum__c.object-meta.xml
<CustomObject>
    <label>Wholesale Pnum</label>
    <nameField>
        <label>FTRWSPnum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesale Pnums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSPnum__c/fields/PNum__c.field-meta.xml
<CustomField>
    <fullName>PNum__c</fullName>
    <description>Purchase Order Number</description>
    <label>PNum</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSPnum__c/fields/Wholesale_ACNA__c.field-meta.xml
<CustomField>
    <fullName>Wholesale_ACNA__c</fullName>
    <label>Wholesale ACNA</label>
    <referenceTo>FTRWSAcna__c</referenceTo>
    <relationshipLabel>Wholesale Pnums</relationshipLabel>
    <relationshipName>Wholesale_Pnums</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/FTRWSDummyPnumSetupTest.cls
/**
* @description       : This test class covers the following Apex classes:
*      FTRWSDummyPnumSetup
*      TBD_CLASS2
*      TBD_CLASS3
* @author            : TBD
* @version           : 5 
*
**/
@isTest
public class FTRWSDummyPnumSetupTest {
    
    @testSetup static void makeData() {
         Id carrierRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='Carrier_Service' LIMIT 1]?.Id;
        Account acc = new Account();
        acc.Name='testAccount';
        acc.RecordTypeId = carrierRecId;
        insert acc;
        
        FTRWSAcna__c acna = new FTRWSAcna__c();
        acna.Name = 'GIM';
        acna.Company__c = acc.id;
        insert acna;
        
        FTRWSAcna__c acna2 = new FTRWSAcna__c();
        acna2.Name = 'ATX';
        acna2.Company__c = acc.id;
        insert acna2;
        
        FTRWSPnum__c pnumObj1 = new FTRWSPnum__c();
        pnumObj1.PNum__c = 'EDGECOLOBASICICB';
        pnumObj1.Name = 'EDGECOLOBASICICB';
        pnumObj1.Wholesale_ACNA__c = acna.Id;
        insert pnumObj1;
        
        FTRWSPnum__c pnumObj2 = new FTRWSPnum__c();
        pnumObj2.PNum__c = 'DKFIBERBASICICB';
        pnumObj2.Name = 'DKFIBERBASICICB';
        pnumObj2.Wholesale_ACNA__c = acna.Id;
        insert pnumObj2;        
        
    }
    
    @isTest
    public static void codeCoverage() {
        Test.startTest();
        FTRWSDummyPnumSetup.createDummyPnumsForWholsaleACNA();
        Test.stopTest();
    }
    
}