UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Carrier_Service.recordType-meta.xml
<RecordType>
    <fullName>Carrier_Service</fullName>
    <active>true</active>
    <label>Carrier Service</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAcna__c/FTRWSAcna__c.object-meta.xml
<CustomObject>
    <label>Wholesale ACNA</label>
    <nameField>
        <label>FTRWSAcna Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesale ACNAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAcna__c/fields/ACNA__c.field-meta.xml
<CustomField>
    <fullName>ACNA__c</fullName>
    <label>ACNA</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAcna__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wholesale ACNAs</relationshipLabel>
    <relationshipName>Wholesale_ACNAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Wholesale_ACNA__c.field-meta.xml
<CustomField>
    <fullName>Wholesale_ACNA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACNA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>FTRWSAcna__c.Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FTRWSAcna__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Wholesale_Pnum__c.field-meta.xml
<CustomField>
    <fullName>Wholesale_Pnum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PNUM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Wholesale_ACNA__c</field>
            <operation>equals</operation>
            <valueField>FTRWSPnum__c.Wholesale_ACNA__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FTRWSPnum__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/recordTypes/Carrier_Service.recordType-meta.xml
<RecordType>
    <fullName>Carrier_Service</fullName>
    <active>true</active>
    <businessProcess>Wholesale_Sales_Stages</businessProcess>
    <description>Carrier Service</description>
    <label>Carrier Service</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/classes/FTRWSCVDBatchTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 2 
 * 
**/
@isTest
public class FTRWSCVDBatchTest {
    
    @testSetup static void methodName() {
     Id carrierRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='Carrier_Service' LIMIT 1]?.Id;
    Account acc = new Account();
    acc.Name='testAccount';
    acc.RecordTypeId = carrierRecId;
    insert acc;
    
    
 Opportunity opp = new Opportunity();
    opp.Name='Test Opp';
    opp.StageName='Decision';
    opp.AccountId=acc.id;
    //opp.Wholesale_ACNA__c=;
    //opp.Wholesale_Pnum__c=;
    opp.CloseDate= System.today();
    opp.ForecastCategoryName='Commit';
    insert opp;
        
        FTRWSAcna__c ac = new FTRWSAcna__c();
        ac.Name ='GIM';
        ac.ACNA__c='GIM';
        ac.Company__c=acc.id;
       insert ac;
}
    
    public static testmethod void getPnumsTest(){
        String acna = 'GIM';
        Test.startTest();
      	Test.setMock(HttpCalloutMock.class, new FTRWSCVDPnumsMock());
        FTRWSCVDBatch btch = new FTRWSCVDBatch();
        database.executeBatch(btch, 200);
        Test.stopTest();
        
    }
    public static testmethod void getPnumsTest1(){
        String acna = 'GIM';
        Test.startTest();
      	Test.setMock(HttpCalloutMock.class, new FTRWSCVDPnumsMock());
        FTRWSCVDBatchScheduler btch = new FTRWSCVDBatchScheduler();
        String sch = '0 0 23 * * ?'; 
        system.schedule('FTRWSCVDBatchSchedule', sch, btch);
        Test.stopTest();
        
    }
    
}