UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This is the describe the SEER/SRQ on the Oppt</description>
    <inlineHelpText>In detail please communicate to the best of your ability the scope of work for this opportunity.</inlineHelpText>
    <label>Description for SEER</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Description_of_customer_needs__c.field-meta.xml
<CustomField>
    <fullName>Description_of_customer_needs__c</fullName>
    <label>Description of customer needs</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Lead_Product_List__c.field-meta.xml
<CustomField>
    <fullName>Lead_Product_List__c</fullName>
    <label>Lead Product List</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cloud IT</fullName>
            </value>
            <value>
                <fullName>Connect Cloud</fullName>
            </value>
            <value>
                <fullName>CPE</fullName>
            </value>
            <value>
                <fullName>Enterprise WiFi</fullName>
            </value>
            <value>
                <fullName>Ethernet</fullName>
            </value>
            <value>
                <fullName>FAW UCaaS</fullName>
            </value>
            <value>
                <fullName>Fiber 1gb</fullName>
            </value>
            <value>
                <fullName>Fiber 2gb</fullName>
            </value>
            <value>
                <fullName>Fiber 500mb</fullName>
            </value>
            <value>
                <fullName>Fiber 700mmb</fullName>
            </value>
            <value>
                <fullName>Fiber Office</fullName>
            </value>
            <value>
                <fullName>FiOS or BHSI</fullName>
                <label>FiberOptic or BHSI</label>
            </value>
            <value>
                <fullName>Frontier Calling with Cloud Phone</fullName>
                <label>Frontier Direct Calling</label>
            </value>
            <value>
                <fullName>HBE</fullName>
            </value>
            <value>
                <fullName>HSI 12m</fullName>
            </value>
            <value>
                <fullName>HSI 3m</fullName>
            </value>
            <value>
                <fullName>HSI 45m</fullName>
            </value>
            <value>
                <fullName>Managed Firewall</fullName>
            </value>
            <value>
                <fullName>Managed Network Services</fullName>
            </value>
            <value>
                <fullName>Premium Tech Pro</fullName>
            </value>
            <value>
                <fullName>Ring Central</fullName>
            </value>
            <value>
                <fullName>SD-WAN</fullName>
            </value>
            <value>
                <fullName>Secure Pro</fullName>
            </value>
            <value>
                <fullName>Simply WiFi Secure</fullName>
            </value>
            <value>
                <fullName>SIP Trunking</fullName>
            </value>
            <value>
                <fullName>Smart Voice</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>Voice (TDM)</fullName>
            </value>
            <value>
                <fullName>Voice Product - Business Voice</fullName>
            </value>
            <value>
                <fullName>Voice Product - OneVoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/New_Logo__c.field-meta.xml
<CustomField>
    <fullName>New_Logo__c</fullName>
    <label>New Logo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <description>Opportunity Type defines if the opportunity is classified as existing, new, renewal or winback.</description>
    <inlineHelpText>New – New logo or New product existing customer
Existing – Renewal or Product changes
Renewal – Straight renewal
Winback - (Do not use)</inlineHelpText>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Partner_Sales_Stages__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sales_Stages__c</fullName>
    <label>Sales Stage (Partner)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed/Lost</fullName>
            </value>
            <value>
                <fullName>Closed/Won</fullName>
            </value>
            <value>
                <fullName>Decision</fullName>
            </value>
            <value>
                <fullName>Evaluating</fullName>
            </value>
            <value>
                <fullName>Defining</fullName>
                <isActive>false</isActive>
                <label>Defining</label>
            </value>
            <value>
                <fullName>Evaluation</fullName>
                <isActive>false</isActive>
                <label>Evaluation</label>
            </value>
            <value>
                <fullName>Evaulating</fullName>
                <isActive>false</isActive>
                <label>Evaulating</label>
            </value>
            <value>
                <fullName>Investigating</fullName>
                <isActive>false</isActive>
                <label>Investigating</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Data - Copper</fullName>
            </value>
            <value>
                <fullName>Data - Fiber</fullName>
            </value>
            <value>
                <fullName>DIRECTV Stream</fullName>
            </value>
            <value>
                <fullName>Ftr Secure</fullName>
            </value>
            <value>
                <fullName>Ftr Video</fullName>
            </value>
            <value>
                <fullName>Instant Activation</fullName>
            </value>
            <value>
                <fullName>Managed Wi-Fi</fullName>
            </value>
            <value>
                <fullName>Self Install</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Service_Address__c</fullName>
    <description>This field is for SEER section in the Oppt. To record the Address. This is the same as the service address on the SRQ.</description>
    <label>Service Address for SEER</label>
    <type>TextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Circuit__c.field-meta.xml
<CustomField>
    <fullName>Circuit__c</fullName>
    <label>Circuit #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Customer_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Requested_Date__c</fullName>
    <label>Customer Requested Date</label>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Order_Point_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Order_Point_of_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please select the Account Executive that is the primary point of contact for this order.</inlineHelpText>
    <label>Order Point of Contact</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2 - Wire Circuit</fullName>
            </value>
            <value>
                <fullName>4 - Wire Circuit</fullName>
            </value>
            <value>
                <fullName>56K</fullName>
            </value>
            <value>
                <fullName>64K</fullName>
            </value>
            <value>
                <fullName>BRI</fullName>
            </value>
            <value>
                <fullName>Broadband</fullName>
            </value>
            <value>
                <fullName>Circuit</fullName>
            </value>
            <value>
                <fullName>CPE</fullName>
            </value>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>E-LAN</fullName>
            </value>
            <value>
                <fullName>E-LAN &amp; EIA</fullName>
            </value>
            <value>
                <fullName>Ethernet</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>FOTS</fullName>
            </value>
            <value>
                <fullName>Fractional Circuit</fullName>
            </value>
            <value>
                <fullName>Frontier Anyware Mitel Hosted</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS</fullName>
            </value>
            <value>
                <fullName>Frontier Calling with Cloud Phone</fullName>
                <label>Frontier Direct Calling</label>
            </value>
            <value>
                <fullName>IP/VPN</fullName>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi</fullName>
            </value>
            <value>
                <fullName>Managed Router</fullName>
            </value>
            <value>
                <fullName>Managed Services</fullName>
            </value>
            <value>
                <fullName>OC-12</fullName>
            </value>
            <value>
                <fullName>OC-3</fullName>
            </value>
            <value>
                <fullName>OC-48</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Private Line T1 / DS1</fullName>
            </value>
            <value>
                <fullName>Private Line T3 / DS3</fullName>
            </value>
            <value>
                <fullName>Ring Central</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/ftr_OrdersRecordTypePageControllerTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      ftr_OrdersRecordTypePageController
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 2
 * 
**/
/*************************************************************************************************
Name        :  ftr_OrdersRecordTypePageControllerTest
Developer   :  RajuM
Description :  Test class for ftr_OrdersRecordTypePageController
**************************************************************************************************/

@istest
public class ftr_OrdersRecordTypePageControllerTest {
    
    static testmethod void OrdersRecordTypePageControllerTest(){
        
        List<Order> ordersList = new List<Order>();
          Id globalRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='global' LIMIT 1]?.Id;
        Account globalAcc = new Account();
        globalAcc.Name = 'GLOBAL ACCOUNT';
        globalAcc.RecordTypeId = globalRecId;
        insert globalAcc;
         
         Id masterRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='Master' LIMIT 1]?.Id;
        
        Account a = new Account();
        a.RecordTypeId=masterRecId; 
        a.name = 'TestAccount';
        a.Phone='2487958700';
        a.ParentId = globalAcc.Id;
        insert a;
        
        Opportunity opp = new Opportunity();
        opp.Name ='TestOppty';
        opp.AccountId=a.id;
        opp.Opportunity_Type__c = 'New';
        opp.Partner_Sales_Stages__c = 'Decision';
        opp.CloseDate= system.today();
        opp.ForecastCategoryName='Commit';
        opp.Campaign__c ='No';
        opp.Lead_Product_List__c = 'Ethernet';
        opp.New_Logo__c ='No';
        opp.RecordTypeId ='012E0000000dgAK';
        opp.StageName='Decision';
        opp.Description__c ='Test for SEER'; 
        opp.Description_of_customer_needs__c = 'Test SEER';
        opp.Service_Address__c = '2120 Cannes Dr,Dallas,TX';
        
        insert opp;    
        
        //List<RecordType> rtList = [SELECT Id,Name,DeveloperName FROM RecordType WHERE SObjectType='Order' AND (NOT DeveloperName LIKE 'UCaaS%') ];//UCaaS New Order
          Id orderRecordTypeId;
          Boolean isRecordTypeAvailable = Schema.sObjectType.Order.getRecordTypeInfosByName().get('Change Order').isAvailable();
          system.debug('isRecordTypeAvailable-->' +isRecordTypeAvailable);
        if(isRecordTypeAvailable == true){
            orderRecordTypeId = Schema.sObjectType.Order.getRecordTypeInfosByName().get('Change Order').getRecordTypeId();
        }else  {
            orderRecordTypeId = Schema.sObjectType.Order.getRecordTypeInfos()[0].getRecordTypeId();
        }
              Order ord = new Order();
        ord.EffectiveDate = system.today();
        ord.Customer_Requested_Date__c = system.today();
        ord.AccountId = a.id;
        ord.OpportunityId = opp.id;
        ord.Product_Type__c = 'EIA';
        ord.Status='Draft';
        ord.Order_Point_of_Contact__c=UserInfo.getUserId();
        ord.RecordTypeId=orderRecordTypeId;
        ord.Circuit__c='Test';
        ord.BillingStreet='1200 TURBINE';
        ord.BillingCity='SANDPOINT';
        ord.BillingState='Idaho';
        ord.BillingPostalCode='83864-7942';
        ord.BillingCountry='United States';
        ord.ShippingCity='SANDPOINT';
        ord.ShippingState='Idaho';
        ord.ShippingStreet='1200 TURBINE';
        ord.ShippingPostalCode='83864-7942';
        ord.ShippingCountry='United States';
        insert ord;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ord);
        ftr_OrdersRecordTypePageController testAccPlan = new ftr_OrdersRecordTypePageController(sc);
        
        PageReference pageRef = Page.Order;
        pageRef.getParameters().put('id', String.valueOf(ord.Id));
        Test.setCurrentPage(pageRef); 
        
        testAccPlan.getRecordTypeList();
        testAccPlan.getUCaaSRecordTypeList(); 
        testAccPlan.redirect();
        String order;
        
        ftr_OrdersRecordTypePageController.fetchRecordTypeValues(order);
        ftr_OrdersRecordTypePageController.fetchUCaaSRecordTypeList(order);
        ftr_OrdersRecordTypePageController.fetchCircuitRecordTypeList(order);
        ftr_OrdersRecordTypePageController.fetchVoiceRecordTypeList(order);
        ftr_OrdersRecordTypePageController.getOpportunityData(opp.Id);
        
             
    }

}