UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAcna__c/FTRWSAcna__c.object-meta.xml
<CustomObject>
    <label>Wholesale ACNA</label>
    <nameField>
        <label>FTRWSAcna Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesale ACNAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAcna__c/fields/ACNA__c.field-meta.xml
<CustomField>
    <fullName>ACNA__c</fullName>
    <label>ACNA</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAcna__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wholesale ACNAs</relationshipLabel>
    <relationshipName>Wholesale_ACNAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSPnum__c/FTRWSPnum__c.object-meta.xml
<CustomObject>
    <label>Wholesale Pnum</label>
    <nameField>
        <label>FTRWSPnum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesale Pnums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSPnum__c/fields/PNum__c.field-meta.xml
<CustomField>
    <fullName>PNum__c</fullName>
    <description>Purchase Order Number</description>
    <label>PNum</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSPnum__c/fields/Wholesale_ACNA__c.field-meta.xml
<CustomField>
    <fullName>Wholesale_ACNA__c</fullName>
    <label>Wholesale ACNA</label>
    <referenceTo>FTRWSAcna__c</referenceTo>
    <relationshipLabel>Wholesale Pnums</relationshipLabel>
    <relationshipName>Wholesale_Pnums</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/FTRWSCVDBatch.cls
global class FTRWSCVDBatch implements Database.Batchable<sObject>,Database.AllowsCallouts{
    
    /*List<Id> adrList = new List<Id>();
global FTRWSCVDBatch(List<Id> listAdr)
{
adrList = listAdr;
}*/
    
    global DataBase.QueryLocator start(Database.BatchableContext BC)
    {
        return DataBase.getQueryLocator([select ID, ACNA__c, Company__r.name, Name from FTRWSAcna__c]);
    }
    
    global void execute(Database.BatchableContext BC,List<FTRWSAcna__c> acnaList)
    {
        List<String> ExpnumList = new List<String>();
        List<FTRWSPnum__c> UpsertPnumList= new List<FTRWSPnum__c>();
        
        for (FTRWSAcna__c acna: acnaList){
            String response = FTRWSCVDInterface.getPNUMs(acna.ACNA__c);
            if(response != null && response != '') {
                response =  response.substring(response.indexOf('PNum')+7, response.length()-2);
                
                List<String> pnumList = response.split(',');
                
                List<FTRWSPnum__c> existingPnums = [SELECT ID, PNum__c,Active__c from FTRWSPnum__c where Wholesale_ACNA__c =: acna.id];
                
                for(FTRWSPnum__c pnum : existingPnums){
                    ExpnumList.add(pnum.PNum__c);
                    if(pnumList.contains(pnum.PNum__c)){
                        pnum.Active__c = True;                        
                    }
                    else{
                        pnum.Active__c = False;
                    }
                    UpsertPnumList.add(pnum);
                }
                
                for (string p: pnumList){
                    if (!ExpnumList.contains(p)){
                        FTRWSPnum__c pnum = new FTRWSPnum__c();
                        pnum.Name=p;
                        pnum.PNum__c=p;
                        pnum.Wholesale_ACNA__c=acna.id;
                        pnum.Active__c = True;
                        UpsertPnumList.add(pnum);
                    }        
                }
            }
        }
        upsert UpsertPnumList;
    }
    global void finish(Database.BatchableContext BC)
    {
    }
}