UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/ftr_FieldLevelDiscounting__mdt.object-meta.xml
<CustomObject>
    <description>Config Item for Field Level Discounting.</description>
    <label>ftr FieldLevelDiscounting</label>
    <pluralLabel>ftr FieldLevelDiscountings</pluralLabel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Approval_Needed__c.field-meta.xml
<CustomField>
    <fullName>Approval_Needed__c</fullName>
    <label>Approval_Needed</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Discount_Max__c.field-meta.xml
<CustomField>
    <fullName>Discount_Max__c</fullName>
    <label>Discount Max</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Discount_Min__c.field-meta.xml
<CustomField>
    <fullName>Discount_Min__c</fullName>
    <label>Discount Min</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/FiberTier__c.field-meta.xml
<CustomField>
    <fullName>FiberTier__c</fullName>
    <label>FiberTier</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Pricing_Group__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Group__c</fullName>
    <label>Pricing Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <inlineHelpText>Product Code</inlineHelpText>
    <label>ProductCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <label>Speed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MRC</fullName>
                <default>true</default>
                <label>MRC</label>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscountingMapping__mdt/ftr_FieldLevelDiscountingMapping__mdt.object-meta.xml
<CustomObject>
    <label>ftr FieldLevelDiscountingMapping</label>
    <pluralLabel>ftr FieldLevelDiscountingMappings</pluralLabel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <label>Speed</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Used to capture approval eligibility and status.</description>
    <inlineHelpText>Used to capture approval eligibility and status.</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Pending Approval - ICB</fullName>
            </value>
            <value>
                <fullName>Pending Approval - RSM</fullName>
            </value>
            <value>
                <fullName>Pending Approval - Pricing</fullName>
            </value>
            <value>
                <fullName>Pending Approval - Product</fullName>
            </value>
            <value>
                <fullName>Pending Approval - Finance</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
                <isActive>false</isActive>
                <label>Pending Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/ftr_Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>ftr_Approval_Type__c</fullName>
    <description>Ftr Approval Type</description>
    <label>ftr Approval Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Floor_Price_One_Time__c.field-meta.xml
<CustomField>
    <fullName>Floor_Price_One_Time__c</fullName>
    <label>Floor Price (One Time)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Floor_Price_Recurring__c.field-meta.xml
<CustomField>
    <fullName>Floor_Price_Recurring__c</fullName>
    <label>Floor Price (Recurring)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/ftr_MRC_Discounted__c.field-meta.xml
<CustomField>
    <fullName>ftr_MRC_Discounted__c</fullName>
    <description>MRC Discounted Percentage</description>
    <formula>MRC_Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ftr MRC Discounted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/ftr_NRC_Discounted__c.field-meta.xml
<CustomField>
    <fullName>ftr_NRC_Discounted__c</fullName>
    <description>NRC Discounted Percent</description>
    <formula>((vlocity_cmt__BaseOneTimeCharge__c - vlocity_cmt__OneTimeCharge__c)/vlocity_cmt__BaseOneTimeCharge__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ftr NRC Discounted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <description>This is used to store the attribute value selected for Speed.</description>
    <label>Speed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>Bound to Attribute = Term</description>
    <label>Term</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__OneTimeCharge__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__OneTimeCharge__c</fullName>
    <label>One Time Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__PremisesId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__PremisesId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premises</label>
    <referenceTo>vlocity_cmt__Premises__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>QuoteLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__RecurringCharge__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__RecurringCharge__c</fullName>
    <description>Initial Recurring charge from Pricelist</description>
    <label>Recurring Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account that identifies the service location or subscriber that is the user of the service.</description>
    <label>Service Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>ServiceAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/vlocity_cmt__Premises__c/objects/vlocity_cmt__Premises__c.object
<CustomObject>
    <fields>
        <fullName>Pricing_Group__c</fullName>
        <label>Pricing Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pricing_Group</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>WC_CLLI__c</fullName>
        <label>WC CLLI</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Premises</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Wire_Center__c/Wire_Center__c.object-meta.xml
<CustomObject>
    <label>Wire Center</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wire Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Wire_Center__c/fields/CLLI__c.field-meta.xml
<CustomField>
    <fullName>CLLI__c</fullName>
    <description>CLLI code for the wire center, unique identifier for WC. Set this field as unique identifier of Wire Center</description>
    <externalId>true</externalId>
    <label>CLLI</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Wire_Center__c/fields/Default_Pricing_Group__c.field-meta.xml
<CustomField>
    <fullName>Default_Pricing_Group__c</fullName>
    <label>Default Pricing Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pricing_Group</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/FieldLevelDiscountingController.cls
global without sharing class FieldLevelDiscountingController {
	private Id contextId;
	private Map<String, String> fieldPathMap = new Map<String, String>();
    global Boolean isLogging = false;

	global FieldLevelDiscountingController(String contextId) {
		this.contextId = contextId;
	}

    global FieldLevelDiscountingController(String contextId, Boolean debug) {
		this.contextId = contextId;
        this.isLogging = debug;
	}

	public List<QuoteLineItem> getLineItems() {
		List<String> lineItemFields = new List<String>();
		List<ftr_FieldLevelDiscountingMapping__mdt> fldms = [SELECT Id, Field__c, Path__c FROM ftr_FieldLevelDiscountingMapping__mdt];
		for (ftr_FieldLevelDiscountingMapping__mdt FLDM : fldms) {
			lineItemFields.add(FLDM.Path__c);
			fieldPathMap.put(FLDM.Field__c, FLDM.path__c);
		}
		String query = 'SELECT Id, PricebookEntry.Product2.ProductCode, vlocity_cmt__ServiceAccountId__r.vlocity_cmt__PremisesId__r.WC_CLLI__c, vlocity_cmt__OneTimeCharge__c,Floor_Price_One_Time__c,vlocity_cmt__RecurringCharge__c,Floor_Price_Recurring__c,ftr_MRC_Discounted__c, ftr_NRC_Discounted__c';
		for (String field : lineItemFields) {
			query += ', ' + field;
		}

		query += ' FROM QuoteLineItem WHERE QuoteId =:contextId AND Quote.ftr_IsBundle__c = false AND (ftr_MRC_Discounted__c > 0 OR ftr_NRC_Discounted__c >0)';
        if (isLogging) {
            System.debug('string query: ' + query);
        }
		return Database.query(query);
	}

	public Map<String, List<ftr_FieldLevelDiscounting__mdt>> getFieldLevelDiscountingMap() {
		Map<String, List<ftr_FieldLevelDiscounting__mdt>> fldm = new Map<String, List<ftr_FieldLevelDiscounting__mdt>>();
		List<ftr_FieldLevelDiscounting__mdt> mdt = [
			SELECT
				Id,
				Priority__c,
				ProductCode__c,
				FiberTier__c,
				Speed__c,
				Type__c,
				Discount_Max__c,
				Discount_Min__c,
				Term__c,
				Approval_Needed__c,
				Pricing_Group__c
			FROM ftr_FieldLevelDiscounting__mdt
			ORDER BY Priority__c ASC
		];
		for (ftr_FieldLevelDiscounting__mdt record : mdt) {
			String key = record.ProductCode__c;
			if (!fldm.containskey(key)) {
				fldm.put(key, new List<ftr_FieldLevelDiscounting__mdt>());
			}
			fldm.get(key).add(record);
		}
		return fldm;
	}

	//Hemantha
	//
	public void updateApprovalTypeNew(Boolean updateLineItems) {
		update new Quote(Id = this.contextId, ftr_Approval_Type__c = null);

		List<QuoteLineItem> lineItemsToUpdate = new List<QuoteLineItem>();
		List<QuoteLineItem> lineItems = getLineItems();
		List<String> clliList = getClliList(lineItems);
		Map<String, String> clliPGMap = getClliPGMap(clliList);
		String pricingGroup;

        if (isLogging) {
            System.debug('fetched lineitems: ' + JSON.serialize(lineItems));
        }
		if (lineItems.size() > 0) {
			Map<String, List<ftr_FieldLevelDiscounting__mdt>> fldm = getFieldLevelDiscountingMap();
			List<FieldLevelDiscountWrapper> comparedRecords = new List<FieldLevelDiscountWrapper>();
			Boolean goToDealDesk = false;

			for (QuoteLineItem record : lineItems) {
				String key = record.PricebookEntry.Product2.ProductCode;
				Boolean matched = false;

				Double nrcDiscount = record.ftr_NRC_Discounted__c != null ? Double.valueOf(record.ftr_NRC_Discounted__c) : 0;
				Double mrcDiscount = record.ftr_MRC_Discounted__c != null ? Double.valueOf(record.ftr_MRC_Discounted__c) : 0;

				if (isLogging) {
					System.debug('checking: ' + key + ' - ' + record.Id);
				}

				if (fldm.containsKey(key)) {
					
					List<ftr_FieldLevelDiscounting__mdt> fldRecords = fldm.get(key);
					// System.debug('all discounting records: ' + JSON.serialize(fldRecords));
					pricingGroup = clliPGMap.get(record.vlocity_cmt__ServiceAccountId__r.vlocity_cmt__PremisesId__r.WC_CLLI__c);
                    if (isLogging) {
                        System.debug('pricingGroup: ' + pricingGroup);
                        System.debug('mrc discount: ' + mrcDiscount);
                        System.debug('nrc discount: ' + nrcDiscount);
                    }
					if (fldRecords != null && fldRecords.size() > 0) {
						for (ftr_FieldLevelDiscounting__mdt fld : fldRecords) {
							Boolean chk =   fld.Pricing_Group__c != null 
                                            && fld.Pricing_Group__c.split(',').contains(pricingGroup) 
                                            && (nrcDiscount <= Double.valueOf(fld.Discount_Max__c) && mrcDiscount <= Double.valueOf(fld.Discount_Max__c));
							if (!chk) {
								continue;
							}

							Integer matchCount = 0;
							String[] fields = new List<String>{};
							for (String fpm : fieldPathMap.keySet()) {
								if (fld.get(fpm) != null) {
									fields.add(fpm);
									for (String field : String.valueOf(fld.get(fpm)).split(',')) {
										if (field == String.valueOf(record.get(fieldPathMap.get(fpm)))) {
                                            if (isLogging) {
                                                System.debug(fpm + ': ' + field + ' matched with: ' + fld.get(fpm));
                                            }
											matchCount++;
											break;
										}
									}
								}
							}
							if (fields.size() == matchCount) {
								if (isLogging) {
									System.debug('matched record: ' + JSON.serialize(fld));
								}
								comparedRecords.add(new FieldLevelDiscountWrapper(fld));
								lineItemsToUpdate.add(record);
								matched = true;
								break;
							} else {
								if (isLogging) {
									System.debug('no record match, checking next');
									System.debug('=====');
								}
							}
						} //end of for loop
						if (!matched) {
							goToDealDesk = true;
							break;
						}
					}
				} else {
					if (nrcDiscount > 0 || mrcDiscount > 0) {
						goToDealDesk = true;
						if (isLogging) {
							System.debug('unsupported product is discounted...');
						}
						break;
					}
				}
			}
            
			Quote quote = new Quote(Id = this.contextId);
            if (goToDealDesk || comparedRecords.size() == 0) {
				quote.ftr_Approval_Type__c = 'Deal Desk';
				quote.Approval_Status__c = 'Pending Approval - ICB';
				update quote;
			} else {
				if (updateLineItems) {
					for (quoteLineItem qli : lineItemsToUpdate) {
						qli.Floor_Price_One_Time__c = qli.vlocity_cmt__OneTimeCharge__c;
						qli.Floor_Price_Recurring__c = qli.vlocity_cmt__RecurringCharge__c;
					}
					update lineItemsToUpdate;
				}
				comparedRecords.sort();
                if (isLogging) {
                    System.debug('matched discount records: ' + JSON.serializePretty(comparedRecords));
                }
				quote.ftr_Approval_Type__c = comparedRecords.get(0).record.Approval_Needed__C;
				update quote;
			}
            System.debug('Approval Needed: ' + quote.ftr_Approval_Type__c);
		}
	}

	private static List<String> getClliList(List<QuoteLineItem> lineItems) {
		List<String> clliList = new List<String>();
		String wc_CLLI;
		for (QuoteLineItem line : lineItems) {
			wc_CLLI = line.vlocity_cmt__ServiceAccountId__r.vlocity_cmt__PremisesId__r.WC_CLLI__c;

			if (wc_CLLI != null) {
				if (!clliList.contains(wc_CLLI)) {
					clliList.add(wc_CLLI);
				}
			}
		}
		return clliList;
	}

	private static Map<String, String> getClliPGMap(List<String> clliList) {
		Map<String, String> clliPGMap = new Map<String, String>();
		List<Wire_Center__c> wcList = [SELECT Id, CLLI__c, Default_Pricing_Group__c FROM Wire_Center__c WHERE CLLI__c = :clliList];
		for (Wire_Center__c wc : wcList) {
			clliPGMap.put(wc.CLLI__c, wc.Default_Pricing_Group__c);
		}
		return clliPGMap;
	}
}