UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Broadband, FiOS &amp; Voice Bundles</fullName>
                <label>Broadband, FiberOptic &amp; Voice Bundles - Existing/Upgrades</label>
            </value>
            <value>
                <fullName>Broadband, FiOS &amp; Voice Bundles - New Service</fullName>
                <label>Broadband, FiberOptic &amp; Voice Bundles - New Service</label>
            </value>
            <value>
                <fullName>Current Broadband Offers</fullName>
            </value>
            <value>
                <fullName>Ethernet/Data Services</fullName>
                <label>Ethernet/Transport Services</label>
            </value>
            <value>
                <fullName>FSA 1 Page</fullName>
            </value>
            <value>
                <fullName>FSA Standard Full Version</fullName>
            </value>
            <value>
                <fullName>Local Services</fullName>
            </value>
            <value>
                <fullName>Managed Services</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>Premier Retail LOA</fullName>
            </value>
            <value>
                <fullName>Premier Retail LOA-MDF</fullName>
            </value>
            <value>
                <fullName>SAA</fullName>
            </value>
            <value>
                <fullName>Twenty-Twenty LOA-MDF</fullName>
            </value>
            <value>
                <fullName>VAL</fullName>
            </value>
            <value>
                <fullName>VoIP</fullName>
            </value>
            <value>
                <fullName>Wi-Fi</fullName>
                <label>Wireless Solutions</label>
            </value>
            <value>
                <fullName>PAL</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>PAL-Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing Agreement</fullName>
            </value>
            <value>
                <fullName>Door to Door LOA-MDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>This field is used to show which products are being quoted.</description>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS</fullName>
            </value>
            <value>
                <fullName>CCaaS</fullName>
            </value>
            <value>
                <fullName>Private Network</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/Schedule_Type__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Type__c</fullName>
    <label>Schedule Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Agreement_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Backup and Recovery</fullName>
            </value>
            <value>
                <fullName>BHSI and FSUV</fullName>
            </value>
            <value>
                <fullName>BHSI and FSUV - CT</fullName>
            </value>
            <value>
                <fullName>BHSI and OneVoice</fullName>
            </value>
            <value>
                <fullName>BHSI and OneVoice - Promo</fullName>
            </value>
            <value>
                <fullName>Broadband and FSUV</fullName>
                <label>Broadband and FSUV - Existing Customers Only</label>
            </value>
            <value>
                <fullName>Broadband and Onevoice - CT</fullName>
                <label>Broadband and Onevoice - CT - Existing Customers Only</label>
            </value>
            <value>
                <fullName>Broadband and OneVoice - CT Promo</fullName>
            </value>
            <value>
                <fullName>Broadband and OneVoice</fullName>
                <label>Broadband and OneVoice - Existing Customers Only</label>
            </value>
            <value>
                <fullName>Broadband and OneVoice Nationwide</fullName>
            </value>
            <value>
                <fullName>Broadband Service - CA-FL-TX</fullName>
            </value>
            <value>
                <fullName>Business Internet Copper Enterprise Only</fullName>
            </value>
            <value>
                <fullName>Business Local-LD</fullName>
            </value>
            <value>
                <fullName>Cabling Service</fullName>
            </value>
            <value>
                <fullName>Converged Voice Bundle</fullName>
            </value>
            <value>
                <fullName>CPE Purchase Install</fullName>
            </value>
            <value>
                <fullName>CPE Purchase install Maintenance</fullName>
            </value>
            <value>
                <fullName>CPE Voice Maintenance</fullName>
            </value>
            <value>
                <fullName>Critical Customer Notification E-911</fullName>
            </value>
            <value>
                <fullName>CyberCenter</fullName>
            </value>
            <value>
                <fullName>DIA Schedule_02012021</fullName>
                <label>DIA</label>
            </value>
            <value>
                <fullName>E-LAN</fullName>
            </value>
            <value>
                <fullName>E-LAN Managed Router</fullName>
            </value>
            <value>
                <fullName>E-LINE</fullName>
                <label>ELINE – EVPL – EPL</label>
            </value>
            <value>
                <fullName>Enterprise Managed WLAN</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>EVPL Managed Router</fullName>
            </value>
            <value>
                <fullName>Fiber and OneVoice Nationwide - Legacy</fullName>
            </value>
            <value>
                <fullName>Fiber First Offer ENTERPRISE ONLY</fullName>
            </value>
            <value>
                <fullName>FiberOffice and OneVoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <label>Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract_Template_List__c/Contract_Template_List__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contract_Template_List for CLM</description>
    <label>Contract_Template_List</label>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract_Template_List__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <description>Agreement Type for CLM</description>
    <label>Agreement Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract_Template_List__c/fields/Schedule_Type__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Type__c</fullName>
    <description>Template Schedule Type for CLM</description>
    <label>Schedule Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract_Template_List__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <description>Template Name for CLM. This template should exist in Document Template (vlocity_cmt__DocumentTemplateId__c)</description>
    <label>Template Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>Bulk_Res</fullName>
                <default>true</default>
                <label>Bulk Res</label>
            </value>
            <value>
                <fullName>BULK-EMA</fullName>
            </value>
            <value>
                <fullName>Bulk Corp</fullName>
            </value>
            <value>
                <fullName>EMA</fullName>
            </value>
            <value>
                <fullName>EMA-DOORFEEONLY</fullName>
            </value>
            <value>
                <fullName>EMA-DOOR-REVSHARE</fullName>
            </value>
            <value>
                <fullName>EMA-REVSHAREONLY</fullName>
            </value>
            <value>
                <fullName>NEMA</fullName>
            </value>
            <value>
                <fullName>No Contract</fullName>
            </value>
            <value>
                <fullName>PAL</fullName>
            </value>
            <value>
                <fullName>Markeing</fullName>
            </value>
            <value>
                <fullName>PAL-Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/CPE_Product__c.field-meta.xml
<CustomField>
    <fullName>CPE_Product__c</fullName>
    <description>Asks Users to check whether a product in the opportunity is a CPE product.</description>
    <inlineHelpText>Must select if a CPE product is a component of the Opportunity being created.</inlineHelpText>
    <label>CPE Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Product2/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <description>Agreement Type</description>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Agreement_Types</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Product2/fields/Schedule_Type__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Type__c</fullName>
    <description>Schedule Type</description>
    <label>Schedule Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Schedule_Types</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>This field is used to show which products are being quoted.</description>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS</fullName>
            </value>
            <value>
                <fullName>CCaaS</fullName>
            </value>
            <value>
                <fullName>Private Network</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/globalValueSets/Agreement_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Broadband FiberOptic &amp; Voice Bundles - Existing/Upgrades</fullName>
    </customValue>
    <customValue>
        <fullName>Broadband FiberOptic &amp; Voice Bundles - New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Do Not Add</fullName>
    </customValue>
    <customValue>
        <fullName>E911</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment (CPE)</fullName>
    </customValue>
    <customValue>
        <fullName>Ethernet/Data Services</fullName>
        <label>Ethernet/Transport Services</label>
    </customValue>
    <customValue>
        <fullName>Local Service (Core products)</fullName>
    </customValue>
    <customValue>
        <fullName>Managed Services</fullName>
    </customValue>
    <customValue>
        <fullName>Manual</fullName>
    </customValue>
    <customValue>
        <fullName>Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>TV Services</fullName>
    </customValue>
    <customValue>
        <fullName>VoIP</fullName>
    </customValue>
    <customValue>
        <fullName>Wireless</fullName>
    </customValue>
    <customValue>
        <fullName>BHSI and FSUV Schedule</fullName>
    </customValue>
    <customValue>
        <fullName>BHSI and OneVoice Schedule</fullName>
    </customValue>
    <customValue>
        <fullName>FiberOffice and OneVoice Schedule CT Business</fullName>
    </customValue>
    <customValue>
        <fullName>FiberOptic Broadband and OneVoice Schedule Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Frontier Business Xtreme</fullName>
    </customValue>
    <customValue>
        <fullName>FiberOffice and OneVoice Schedule Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Voice - Internet Product Schedule for CA-TX-FL</fullName>
    </customValue>
    <customValue>
        <fullName>Business Local-LD Schedule Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Broadband and OneVoice Schedule CT</fullName>
    </customValue>
    <customValue>
        <fullName>Broadband and FSUV Schedule CT</fullName>
    </customValue>
    <description>Agreement Types for CLM</description>
    <masterLabel>Agreement Types</masterLabel>
</GlobalValueSet>

UCF-APR2.4/ftr main/force-app/main/default/classes/ftr_CLMCreateContractFromQuotesTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 2 
 * 
**/
@IsTest
public class ftr_CLMCreateContractFromQuotesTest{
    
    @IsTest
    public static void testGetContractVersion(){
        User userObj = [Select Id from User where profile.Name = 'Frontier System Administrator' AND IsActive=true LIMIT 1];
        System.runAs(userObj){
            Contract_Template_List__c template = new Contract_Template_List__c();
            template.Name = 'CLM_TMPL_00010';
            template.Schedule_Type__c = 'FiberOptic & OneVoice Nationwide (copper)';
            template.Agreement_Type__c = 'Broadband FiberOptic & Voice Bundles - New Service';
            template.Template_Name__c = 'Fiber and OneVoice Schedule';
            insert template;
            
             Id globalRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='global' LIMIT 1]?.Id;
        Account globalAcc = new Account();
        globalAcc.Name = 'GLOBAL ACCOUNT';
        globalAcc.RecordTypeId = globalRecId;
        insert globalAcc;
            
        Id masterRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='Master' LIMIT 1]?.Id;
        Account a = new Account();
        a.Name = 'Test Account';
        a.RecordTypeId = masterRecId;
        a.ParentId = globalAcc.Id;
        insert a;
            
             Id servRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='Service' LIMIT 1]?.Id;
       
             Account testSAccount = new Account();
             testSAccount.Name = 'Test Service Account';
             testSAccount.RecordTypeId = servRecId;
             testSAccount.BillingStreet = '123 Main Street';
             testSAccount.BillingCity = 'Anywhere';
             testSAccount.BillingState = 'Ohio';
             testSAccount.BillingPostalCode = '44088';
             testSAccount.ShippingStreet = '123 Main Street';
             testSAccount.ShippingCity = 'Anywhere';
             testSAccount.ShippingState = 'Ohio';
             testSAccount.ShippingPostalCode = '44088';
             testSAccount.ParentId = a.Id;
             insert testSAccount;
            
             Opportunity opp = new Opportunity();
             opp.Name = 'RefreshTestOpp';
             opp.AccountId = a.id;
             Date d1=Date.newInstance(2019, 05, 11);
             opp.CloseDate=d1;
             opp.StageName='Investigating';
             opp.CPE_Product__c='No';
             insert opp;
            
             id pricebookId = Test.getStandardPricebookId();
             List<Product2> lstProduct2 = new List<Product2>();
             Product2 product = new Product2();
             product.Name = 'EIA';
             product.ProductCode = 'ENT_ETH_EIA_0001';
             product.IsActive = true;
             lstProduct2.add(product);
    
             Product2 prodEVC = new Product2();
             prodEVC.Name = 'EVC';
             prodEVC.ProductCode = 'ENT_ETH_EVC_0001';
             prodEVC.IsActive = true;
             lstProduct2.add(prodEVC);
            
             Product2 prodAccess = new Product2();
             prodAccess.Name = 'Access';
             prodAccess.ProductCode = 'ENT_ETH_ACCESS_0001';
             prodAccess.IsActive = true;
             lstProduct2.add(prodAccess);
             //Insert products
             insert lstProduct2;  
            
             PricebookEntry standardPrice = new PricebookEntry(
                 Pricebook2Id = pricebookId, 
                 Product2Id = lstProduct2[0].Id,
                 UnitPrice = 100, IsActive = true);
             insert standardPrice;
            
             Quote oQuote = new Quote();
             oQuote.Name = 'Testing Quote';
             oQuote.OpportunityId = Opp.id;
             oQuote.Pricebook2Id = pricebookId;
             oQuote.Products__c = 'EVPL';
             insert oQuote;
            Id recordTypeId = Schema.getGlobalDescribe().get('Contract').getDescribe().getRecordTypeInfosByName().get('Frontier Services Agreement').getRecordTypeId();
            Contract ctr = new Contract(Status = 'Draft', AccountId = a.id, Opportunity__c = opp.id, ICB_Flag__c = 'Y', Icb_for_email_for_test__c = true);
            ctr.BillingCity = 'Tampa';
            ctr.BillingCountry = 'United States';
            ctr.BillingState = 'Florida';
            ctr.BillingStreet = '4900 West Kennedy Boulevard';
            ctr.BillingPostalCode = '75068';
            ctr.Status = 'Draft';
            ctr.vlocity_cmt__QuoteId__c = oQuote.Id;
            ctr.ShippingCity = 'Tampa';
            ctr.ShippingCountry = 'United States';
            ctr.ShippingState = 'Florida';
            ctr.ShippingStreet = '321 East Commerce Street';
            ctr.ShippingPostalCode = '75068';
            ctr.RecordTypeId = recordTypeId;
            insert  ctr; 
            
            System.Test.startTest();
                ftr_CLMCreateContractFromQuotes.getContractVersion(oQuote.Id, null, null,null);
            System.Test.stopTest();
        }
    }
}