UCF-APR2.4/ftr main/force-app/main/default/objects/Lead/fields/Follow_Up_Appt_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Appt_Date__c</fullName>
    <label>Follow Up Appt Date</label>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Lead/fields/Q5_Outcome_with_non_DM__c.field-meta.xml
<CustomField>
    <fullName>Q5_Outcome_with_non_DM__c</fullName>
    <label>Q5: Outcome with non-DM?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Q2_Reached_DM__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DM Unavailable</fullName>
            </value>
            <value>
                <fullName>GK Scheduled Call Back</fullName>
            </value>
            <value>
                <fullName>Invalid Appointment</fullName>
            </value>
            <value>
                <fullName>No longer able to reach DM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Lead/fields/Reason_made_with_targeted_account__c.field-meta.xml
<CustomField>
    <fullName>Reason_made_with_targeted_account__c</fullName>
    <label>Reason made with targeted account</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Made_with_targeted_account__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Answer</fullName>
            </value>
            <value>
                <fullName>Hang Up - Quick</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Answering Machine</fullName>
            </value>
            <value>
                <fullName>Already with Frontier</fullName>
            </value>
            <value>
                <fullName>Residential Account</fullName>
            </value>
            <value>
                <fullName>Add to DNC</fullName>
            </value>
            <value>
                <fullName>Wrong Info</fullName>
            </value>
            <value>
                <fullName>Fax/Modem</fullName>
            </value>
            <value>
                <fullName>Disconnected Line</fullName>
            </value>
            <value>
                <fullName>Language Barrier</fullName>
            </value>
            <value>
                <fullName>Corporate/Enterprise Account</fullName>
            </value>
            <value>
                <fullName>Government Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/LeadTriggerTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 1 
**/
@isTest
public class LeadTriggerTest
{
    @isTest
    public static void testLeadInsert ()
    {
        Test.startTest();
        Date dt = DateTime.now().Date();
        //Id recId = [SELECT Id, Name FROM RecordType Where name = 'Alt Channel - OTM' Limit 1].Id;
        Id recId = [SELECT Id, Name FROM RecordType Where name = 'Alt Channel' Limit 1].Id;
	    Lead objLead = new Lead (LastName = 'Test data', 
                                 Email = 'test@gmail.com', 
                                 mobilephone = '+1234567890', 
                                 Company = 'Test company',
                                 Status = 'Open',
                                 Reason_made_with_targeted_account__c = 'No Answer',
                                 Q5_Outcome_with_non_DM__c = 'DM Unavailable',
                                 Follow_Up_Appt_Date__c = dt.addDays(-2),
                                 RecordtypeId = recId);
		Database.SaveResult result = Database.insert(objLead, false);
		Test.stopTest();
    }
}