UCF-APR2.4/ftr main/force-app/main/default/objects/PSROrderUpdate__e/PSROrderUpdate__e.object-meta.xml
<CustomObject>
    <description>Subscribes M6 BCN Complete events from M6 and Process to Wait for BCN Complete Orchestration Item</description>
    <label>PSROrderUpdate</label>
    <pluralLabel>PSROrderUpdates</pluralLabel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/PSROrderUpdate__e/fields/Circuitid__c.field-meta.xml
<CustomField>
    <fullName>Circuitid__c</fullName>
    <label>Circuitid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/PSROrderUpdate__e/fields/PSROrderId__c.field-meta.xml
<CustomField>
    <fullName>PSROrderId__c</fullName>
    <label>PSROrderId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/PSROrderUpdate__e/fields/PSROrderStatus__c.field-meta.xml
<CustomField>
    <fullName>PSROrderStatus__c</fullName>
    <label>PSROrderStatus</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/ftr_M6OrderStatusUpdateEveDispatchTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 1 
**/
@isTest
public with sharing class ftr_M6OrderStatusUpdateEveDispatchTest {
 @isTest  
    static void afterInsertTest() {
          PSROrderUpdate__e obj = new PSROrderUpdate__e();
       	obj.PSROrderId__c = '123';
        obj.Circuitid__c = '456';
        obj.PSROrderStatus__c = 'Complete';
        test.startTest();
        EventBus.publish(obj);
        test.stopTest();
    }
}