UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Avg_MRC__c.field-meta.xml
<CustomField>
    <fullName>Avg_MRC__c</fullName>
    <label>Avg MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Avg_NRC__c.field-meta.xml
<CustomField>
    <fullName>Avg_NRC__c</fullName>
    <label>Avg NRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>This field is used to show which products are being quoted.</description>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS</fullName>
            </value>
            <value>
                <fullName>CCaaS</fullName>
            </value>
            <value>
                <fullName>Private Network</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/SterlingQuote__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Object</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/SterlingQuoteItem__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Item</description>
    <label>Quote Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedMRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedMRC__c</fullName>
    <label>Adjusted MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedNRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedNRC__c</fullName>
    <label>Adjusted NRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>SterlingQuote__r.OpportunityId__r.Id</formula>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/SterlingQuote__c.field-meta.xml
<CustomField>
    <fullName>SterlingQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>SterlingQuote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>SterlingQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/TermLength__c.field-meta.xml
<CustomField>
    <fullName>TermLength__c</fullName>
    <label>Term Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/CalculateMRC_NRC_On_Quote_Items.cls
public class CalculateMRC_NRC_On_Quote_Items 
{
    @InvocableMethod(label='MRC_NRC_AVG' description='Calculating Average MRC and NRC')
/*    public static void updateMRCandNRC(List<id> qitemID) 
    {
        SterlingQuoteItem__c qrec = [select Id,Products__c,TermLength__c,SterlingQuote__c from SterlingQuoteItem__c where Id =: qitemID[0] limit 1];
        List<SterlingQuoteItem__c> qlist =[select Id,AdjustedMRC__c,AdjustedNRC__c 
                                           from SterlingQuoteItem__c where SterlingQuote__c =: qrec.SterlingQuote__c ];
	*/
    public static void updateMRCandNRC(List<id> qitemID) 
    {        
        List<SterlingQuoteItem__c> qlist =[select Id,AdjustedMRC__c,AdjustedNRC__c 
                                           from SterlingQuoteItem__c where SterlingQuote__c =: qitemID[0] ];
        SterlingQuote__c Quote1 = [select Id,OpportunityId__c from SterlingQuote__c where Id=:qitemID[0] limit 1];
        Opportunity op = [select Id,Avg_MRC__c,Avg_NRC__c from Opportunity where Id=:Quote1.OpportunityId__c limit 1];

        // Calculating Total MRC and NRC
        decimal Total_MRC=0,Total_NRC=0,Count_Rec=0,AVG_MRC=0,AVG_NRC=0;
        for(SterlingQuoteItem__c qc : qlist)
        {
            if(qc.AdjustedMRC__c != null || qc.AdjustedMRC__c != 0)
            {
                Total_MRC = Total_MRC + qc.AdjustedMRC__c;              
            }
            if(qc.AdjustedNRC__c != null || qc.AdjustedNRC__c != 0)
            {
                Total_NRC = Total_NRC + qc.AdjustedNRC__c;                                
            }            
                Count_Rec = Count_Rec +1;                            
            System.debug('<=> 1.Each Quote Item :'+qc);
        }
        if(Total_MRC>0){AVG_MRC = Total_MRC/Count_Rec;}
        if(Total_NRC>0){AVG_NRC = Total_NRC/Count_Rec;}
        
        System.debug('Total MRC :'+Total_MRC);
        System.debug('count MRC :'+Count_Rec);
        System.debug('Total NRC :'+Total_NRC);          
        System.debug('Count NRC :'+Count_Rec);    
        System.debug('Average MRC :'+AVG_MRC);
        System.debug('Average NRC :'+AVG_NRC); 
        if(AVG_MRC>0)
        {
            op.Avg_MRC__c =AVG_MRC;
        }
        if(AVG_NRC>0)
        {
           op.Avg_NRC__c =AVG_NRC; 
        }        
        update op;
     }
}