UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/CPE_Gross_Margin__c.field-meta.xml
<CustomField>
    <fullName>CPE_Gross_Margin__c</fullName>
    <label>CPE Gross Margin</label>
    <summarizedField>OpportunityLineItem.CPE_Gross_Margin_Revenue__c</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.ProductFamily__c</field>
        <operation>equals</operation>
        <value>CPE,Smart Voice</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Renewal_MRR__c.field-meta.xml
<CustomField>
    <fullName>Renewal_MRR__c</fullName>
    <label>Renewal MRR</label>
    <summarizedField>OpportunityLineItem.Total_Renewal_MRR__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Service_Address__c</fullName>
    <description>This field is for SEER section in the Oppt. To record the Address. This is the same as the service address on the SRQ.</description>
    <label>Service Address for SEER</label>
    <type>TextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/SterlingQuote__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Object</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/WS_Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>WS_Quote_Number__c</fullName>
    <description>Auto generated number for wholesale quotes for searching and identifying the quick quote&apos;s RFQ string.</description>
    <displayFormat>{YYYY}{MM}{DD}{0000}</displayFormat>
    <label>WS Quote Number</label>
    <type>AutoNumber</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/recordTypes/SFA.recordType-meta.xml
<RecordType>
    <fullName>SFA</fullName>
    <active>true</active>
    <description>For Quotes within the salesforce</description>
    <label>SFA</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/SterlingQuoteItem__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Item</description>
    <label>Quote Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedMRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedMRC__c</fullName>
    <label>Adjusted MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedNRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedNRC__c</fullName>
    <label>Adjusted NRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hardware/Materials</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Maintenance (Post Warr)</fullName>
            </value>
            <value>
                <fullName>Directory</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Features</fullName>
            </value>
            <value>
                <fullName>Long Distance</fullName>
            </value>
            <value>
                <fullName>Seats</fullName>
            </value>
            <value>
                <fullName>Surcharge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/CPE_Gross_Margin__c.field-meta.xml
<CustomField>
    <fullName>CPE_Gross_Margin__c</fullName>
    <label>CPE Gross Margin %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/CPE_NRC_Price__c.field-meta.xml
<CustomField>
    <fullName>CPE_NRC_Price__c</fullName>
    <label>CPE NRC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/CurrentStatus__c.field-meta.xml
<CustomField>
    <fullName>CurrentStatus__c</fullName>
    <label>CurrentStatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending - Business Decision Support</fullName>
            </value>
            <value>
                <fullName>Pending - Credit</fullName>
            </value>
            <value>
                <fullName>Pending - Engineering</fullName>
            </value>
            <value>
                <fullName>Pending - Engineering Wireless</fullName>
            </value>
            <value>
                <fullName>Pending - Engineering Wireless Final</fullName>
            </value>
            <value>
                <fullName>Pending - Finance</fullName>
            </value>
            <value>
                <fullName>Pending - INA</fullName>
            </value>
            <value>
                <fullName>Pending - INA Engineering</fullName>
            </value>
            <value>
                <fullName>Pending - Post Completion Audit Finance</fullName>
            </value>
            <value>
                <fullName>Pending - Post Completion Audit Originator</fullName>
            </value>
            <value>
                <fullName>Pending - Post Engineering Originator</fullName>
            </value>
            <value>
                <fullName>Pending - Post Engineering Originator Wireless</fullName>
            </value>
            <value>
                <fullName>Pending - Regional President</fullName>
            </value>
            <value>
                <fullName>Pending - Sales Engineering</fullName>
            </value>
            <value>
                <fullName>Pending - Sales Engineering Manager</fullName>
            </value>
            <value>
                <fullName>Pending - Site Verification</fullName>
            </value>
            <value>
                <fullName>Pending - State VP</fullName>
            </value>
            <value>
                <fullName>Pending - Wireless Management</fullName>
            </value>
            <value>
                <fullName>Pending - SVP Approval</fullName>
            </value>
            <value>
                <fullName>Pending - RSM Approval</fullName>
            </value>
            <value>
                <fullName>Pending Ready for Review</fullName>
            </value>
            <value>
                <fullName>Pending AE Update</fullName>
            </value>
            <value>
                <fullName>Pending - ICB</fullName>
            </value>
            <value>
                <fullName>Pending - Pricing</fullName>
            </value>
            <value>
                <fullName>Pending - Product</fullName>
            </value>
            <value>
                <fullName>Pending Final Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/DiscountType__c.field-meta.xml
<CustomField>
    <fullName>DiscountType__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SVP</fullName>
            </value>
            <value>
                <fullName>RSM</fullName>
            </value>
            <value>
                <fullName>ICB</fullName>
            </value>
            <value>
                <fullName>CTR</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>ICBA</fullName>
            </value>
            <value>
                <fullName>CTRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/IsPromoProduct__c.field-meta.xml
<CustomField>
    <fullName>IsPromoProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Promo Product</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/NetNewMRR__c.field-meta.xml
<CustomField>
    <fullName>NetNewMRR__c</fullName>
    <label>NetNewMRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/NumInstallments__c.field-meta.xml
<CustomField>
    <fullName>NumInstallments__c</fullName>
    <label>Number of Installments</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/OpportunityLineItemId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItemId__c</fullName>
    <label>Opportunity Line Item ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/OverallStatus__c.field-meta.xml
<CustomField>
    <fullName>OverallStatus__c</fullName>
    <label>OverallStatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>INA Accepted</fullName>
            </value>
            <value>
                <fullName>INA Rejected</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Pending - Business Decision Support</fullName>
            </value>
            <value>
                <fullName>Pending - Credit</fullName>
            </value>
            <value>
                <fullName>Pending - Engineering Wireless</fullName>
            </value>
            <value>
                <fullName>Pending - Engineering Wireless Final</fullName>
            </value>
            <value>
                <fullName>Pending - Finance</fullName>
            </value>
            <value>
                <fullName>Pending - INA</fullName>
            </value>
            <value>
                <fullName>Pending - Post Completion Audit Finance</fullName>
            </value>
            <value>
                <fullName>Pending - Post Completion Audit Originator</fullName>
            </value>
            <value>
                <fullName>Pending - Post Engineering Originator</fullName>
            </value>
            <value>
                <fullName>Pending - Post Engineering originator Wireless</fullName>
            </value>
            <value>
                <fullName>Pending - Regional President</fullName>
            </value>
            <value>
                <fullName>Pending - Sales Engineering</fullName>
            </value>
            <value>
                <fullName>Pending - Site Verification</fullName>
            </value>
            <value>
                <fullName>Pending - State VP</fullName>
            </value>
            <value>
                <fullName>Pending - Wireless Management</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending SIFT Status</fullName>
            </value>
            <value>
                <fullName>Pending SIFT Status-ON HOLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <label>Part Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Renewal_MRR__c.field-meta.xml
<CustomField>
    <fullName>Renewal_MRR__c</fullName>
    <formula>NetNewMRR__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Renewal_MRR_Original__c.field-meta.xml
<CustomField>
    <fullName>Renewal_MRR_Original__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Renewal MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Service_Address__c</fullName>
    <formula>SA_StreetNrFirst__c +&apos; &apos;+SA_StreetDirection__c +&apos; &apos;+SA_StreetName__c +&apos; &apos;+ SA_StreetSubDescription__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Address</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/SterlingQuote__c.field-meta.xml
<CustomField>
    <fullName>SterlingQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>SterlingQuote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>SterlingQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/TermLength__c.field-meta.xml
<CustomField>
    <fullName>TermLength__c</fullName>
    <label>Term Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/recordTypes/SFA.recordType-meta.xml
<RecordType>
    <fullName>SFA</fullName>
    <active>true</active>
    <label>SFA</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/classes/FTRWSQuickQuoteControllerTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 1 
**/
@isTest
public class FTRWSQuickQuoteControllerTest {
    
    public static Opportunity opp;
    //public static SterlingQuote__c quote;
    
    public static Opportunity testOpportunity;
    public static SterlingQuote__c testQuote;
    public static SterlingQuoteItem__c testQuoteItem;
    public static OpportunityLineItem testOpportunityProduct;
    
    @isTest
    public static void testQuickQuoteController() {
        prepareTestData();
        Test.startTest();
        
        FTRWSQuickQuoteController.getCurrentOpportunity(testOpportunity.id);
        FTRWSQuickQuoteController.getSyncedQuote(testOpportunity.id);
        
        FTRWSQuickQuoteController controller  = new FTRWSQuickQuoteController();
        controller.ftrURL = 'https://wholesale.frontier.com';
        controller.rfqString = FTRWSQuickQuoteController.getRFQString(testQuote.WS_Quote_Number__c);
        controller.quoteCreateDate = System.now().format('yyyy-MM-dd');
        controller.init(testOpportunity.Id);
        
controller.totalQQValue = 1000.00;
    controller.totalOnetimeCharge = 500.00;
    controller.totalMonthlyCharge=500.00;
        Test.stopTest();
    }
    
        private static void prepareTestData() {
        			testOpportunity = Test_Fixture_Factory.createTestOpportunity();
			testQuote = Test_Fixture_Factory.createTestQuote(testOpportunity.Id, '', 'Pending - Finance');
			testQuoteItem = [
				SELECT
					DiscountType__c,
					OverallStatus__c,
					OpportunityLineItemId__c,
					Category__c,
					Part_Number__c,
					CurrentStatus__c,
					Quantity__c,
					IsPromoProduct__c,
					TermLength__c,
					NumInstallments__c,
					Renewal_MRR_Original__c,
					NetNewMRR__c,
					AdjustedNRC__c,
					AdjustedMRC__c
				FROM SterlingQuoteItem__c
				WHERE SterlingQuote__c = :testQuote.Id
				LIMIT 1
			];

			testQuoteItem.Category__c = 'Equipment';
			testQuoteItem.Part_Number__c = '1234';
			testQuoteItem.CurrentStatus__c = 'Pending - Finance';
			testQuoteItem.Quantity__c = 1;
			testQuoteItem.IsPromoProduct__c = true;
			testQuoteItem.TermLength__c = 12;
			testQuoteItem.NumInstallments__c = 5;
			testQuoteItem.Renewal_MRR_Original__c = 0;
			testQuoteItem.NetNewMRR__c = 10.00;
			testQuoteItem.AdjustedNRC__c = 2.00;
			testQuoteItem.OverallStatus__c = 'Pending - Finance';
			testQuoteItem.RecordType = [SELECT Id, Name FROM RecordType WHERE sObjectType = 'SterlingQuoteItem__c' AND name = 'SFA' LIMIT 1];
			testQuoteItem.AdjustedMRC__c = 12.00;
			testQuoteItem.Currentstatus__c = 'Pending - Finance';
			testQuoteItem.Overallstatus__c = 'Pending';
			testQuoteItem.DiscountType__c = 'None';
			update testQuoteItem;

			testOpportunityProduct = [
				SELECT
					CPE_Gross_Margin__c,
					CPE_NRC_Price__c,
					NRC_Price__c,
					Product2.Name,
					Service_Address__c,
					CPQ_NetNewMRR__c,
					Renewal_MRR__c,
					Speed__c,
					Quantity,
					OpportunityId,
					TotalPrice,
                    PricebookEntryId,
                    vlocity_cmt__ServiceAccountId__r.Name
				FROM OpportunityLineItem
				WHERE Id = :testQuoteItem.OpportunityLineItemId__c
			];
		}

     public static void createTestOpportunity(Id PriceBookId) {

        Account acc = new Account();
        acc.Name='testAccount';
        insert acc;
        
        opp = new Opportunity();
        opp.Name='Test Opp';
        opp.StageName='Decision';
        opp.AccountId=acc.id;
        opp.CloseDate= System.today();
        opp.ForecastCategoryName='Commit';
        opp.Pricebook2Id = pricebookId;
        insert opp;
        
    }
    
    public static void createQuote() {
         RecordType quoteRecType = [SELECT Id FROM RecordType WHERE Name = 'Carrier Service' AND SobjectType = 'SterlingQuote__c' LIMIT 1];
        
        
       SterlingQuote__c  quote = new SterlingQuote__c(Name = 'Test Quote 1', 
                                                      RecordType = quoteRecType, 
                                                      OpportunityId__c = opp.Id, 
                                                      IsSyncing__c = true);
        
        insert quote;
    }
    
       public static FTRWSQuoteLineItemProdWrapper createWrapperItem(String circuitType, String prodName) {
        
        FTRWSQuoteLineItemProdWrapper wrapper = new FTRWSQuoteLineItemProdWrapper();
     	wrapper.id = 'TestSqId';
        wrapper.quantity = 1;
        
        wrapper.rfqString = System.now().format('yyyyMMddHHmmSS');
        wrapper.serviceType = 'Test';
        
        Integer term = 60;
        
        wrapper.termLength = '5 yr';
        
        wrapper.renewalMRR = 500.00;
        wrapper.netNewMRR = 500.00;
        wrapper.nrc = 100.00;
        wrapper.totalNRC = 100.00;
        wrapper.name = prodName;
        
        wrapper.adjustedNRC = 0.00;
        wrapper.cpenrc = 0.00;
        wrapper.nrc = 100.00;
        wrapper.totalNRC = 100.00;
        
        wrapper.qos = 'Platinum';
        wrapper.circuitType = circuitType;
        wrapper.tier = '1';
        wrapper.pNUM = 'EPATH123456';
        
        if(wrapper.circuitType == 'EVC') {
            wrapper.orderSeq = 1;
        } else if(wrapper.circuitType == 'UNI') {
            wrapper.orderSeq = 2;
        } else if(wrapper.circuitType == 'NNI') {
            wrapper.orderSeq = 3;
        }
        
        wrapper.totalMRC = 400.00;
        wrapper.totalCharge = 400.00;
        wrapper.serviceAddress = '2000 Solar Dr, Oxnard, CA';
        wrapper.zAddress = '';
  
        String prodType = 'EPATH';
        String speed = '2000';
        String qos = 'Platinum';
              
        return wrapper;
    }
}