UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/ftr_NumberOfQuickQuotes__c.field-meta.xml
<CustomField>
    <fullName>ftr_NumberOfQuickQuotes__c</fullName>
    <label>Number of Quick Quotes</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/vlocity_cmt__EffectiveRecurringTotal__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__EffectiveRecurringTotal__c</fullName>
    <label>Effective Recurring Total</label>
    <summarizedField>OpportunityLineItem.vlocity_cmt__EffectiveRecurringTotal__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/ftr_QuoteCreationStatus__c.field-meta.xml
<CustomField>
    <fullName>ftr_QuoteCreationStatus__c</fullName>
    <label>Quote Creation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/IsSyncing__c.field-meta.xml
<CustomField>
    <fullName>IsSyncing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for the vlocity hybrid quote initiative. Determines whether the quote is synced with the opportunity.</description>
    <label>IsSyncing</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/vlocity_cmt__EffectiveRecurringTotal__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__EffectiveRecurringTotal__c</fullName>
    <label>Effective Recurring Total</label>
    <summarizedField>QuoteLineItem.vlocity_cmt__EffectiveRecurringTotal__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/OpportunityQuickQuoteController.cls
/*********************************************************************************************************************
    *@Name        : OpportunityQuickQuoteController
    *@Author      : Dileep Chinthala <dileep.chinthala@ftr.com>
    *@Description : This utility class is called from QuickQuote Omniscript remote action generate QuickQuote.pdf with all quotes 
    				under an opportunity
    
    * UPDATES
    * Version 		Date       		Developer  				Description
    *------------------------------------------------------------------------------------------------------------------
    *1.0    		11/16/2021     Dileep Chinthala      Initial Creation                                                      
    
**********************************************************************************************************************/
    global class OpportunityQuickQuoteController implements vlocity_cmt.VlocityOpenInterface{
        global Boolean invokeMethod(String methodName, Map<String, Object> inputMap, Map<String, Object> outputMap, Map<String, Object> options) {
            String oppId = (String)inputMap.get('recordId');
            Boolean summQ = (Boolean)inputMap.get('summaryQuote');
            String commentStr =  '';
            String dt = Datetime.now().format('yyyy-MM-dd');
            List<Id> syncQ = new List<Id>(QuoteServiceController.getSyncedQuoteIdFromOpportunity(oppId).keySet());
            system.debug('!!!!' +syncQ);
            try {
                PageReference pdfPage;
                pdfPage = Page.CreateQuickQuote; 
                
                pdfPage.getParameters().put('oid', oppId);			
                pdfPage.getParameters().put('c', commentStr);
                If(summQ == true){
                pdfPage.getParameters().put('allQuotes', 'TRUE');
                } else{
                pdfPage.getParameters().put('allQuotes', 'FALSE');
                }
                
                
                pdfPage.setRedirect(true);
                Blob pdfBlob;
                if(!Test.isRunningTest())
                    pdfBlob = pdfPage.getContent();
                else {
                    pdfBlob = Blob.valueOf('Test pdf data');
                }
                System.debug('==========pdfBlob:' + pdfBlob);
                
                Opportunity objopp = [Select Id, RecordType.Name, ftr_NumberOfQuickQuotes__c, Name from Opportunity where Id=:oppId];
                Quote objquo = [Select Id, Name from Quote where OpportunityId =: objopp.Id AND IsSyncing__c = true];
                Integer count = [Select count() from Quote where OpportunityId =:oppId AND ftr_QuoteCreationStatus__c = 'Completed'];
                
                if(objopp.ftr_NumberOfQuickQuotes__c != count){
                    return false;
                }
                Boolean lightningRecordtype = false;
                if (objopp.RecordType.Name == 'Opportunity Lightning'){
                    lightningRecordtype = true;
                }
                if (true || lightningRecordtype || objopp.RecordType.Name == 'Partner Opportunity - New') {
                    ContentVersion conVer = new ContentVersion();
                    conVer.ContentLocation = 'S'; // to use S specify this document is in Salesforce, to use E for external files
                    conVer.PathOnClient = 'QuickQuote.pdf'; // The files name, extension is very important here which will help the file in preview.
                    //conVer.Title = 'QuickQuote.pdf'; // Display name of the files
                     If(summQ == true){
                         if(objopp.Name.contains('_DIA/MNS_')){
                          	conVer.Title = 'Summ-Q_DIA/MNS_'+dt+'.pdf';
                         }else{
                             If(objopp.Name.contains('_MNS_')){
                                 conVer.Title = 'Summ-Q_MNS_'+dt+'.pdf';
                             }else{
                                  conVer.Title = 'Summ-Q_DIA_'+dt+'.pdf';
                             }
                         }         
                     } else{
                         //conVer.Title = objquo.vlocity_cmt__EffectiveRecurringTotal__c+'-Q_DIA_'+dt+'.pdf';
                         //String NotesLowQuoteName='';
                         
                             If(objquo.Name.contains('MNS')){
                                 conVer.Title = 'LowMRC-Q_MNS_'+dt+'.pdf';
                             }else{
                                  conVer.Title = 'LowMRC-Q_DIA_'+dt+'.pdf';
                             }
                         
                     }
                    conVer.VersionData = pdfBlob; // converting your binary string to Blog
                    insert conVer;    //Insert ContentVersion
                    
                    // First get the Content Document Id from ContentVersion Object
                    Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
                    //create ContentDocumentLink  record 
                    ContentDocumentLink conDocLink = new ContentDocumentLink();
                    conDocLink.LinkedEntityId = oppId; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
                    conDocLink.ContentDocumentId = conDoc;  //ContentDocumentId Id from ContentVersion
                    conDocLink.shareType = 'V';
                    insert conDocLink;
                } else {
                    Attachment oAtt = new Attachment(parentId = oppId, name = 'QuickQuote.pdf', body = pdfBlob);
                    insert oAtt;
                } 
                
                
                String userProfile = [SELECT Name
                                      FROM Profile
                                      WHERE Id =: userinfo.getProfileId()
                                      LIMIT 1].Name;
                
                
                return true;
            } catch (Exception ex) {
                System.debug('$$$Exception='+ex.getMessage());
            }
            return false;
        }
        
        
    }