UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Net_New_MRR__c.field-meta.xml
<CustomField>
    <fullName>Net_New_MRR__c</fullName>
    <label>Net New MRR</label>
    <summarizedField>OpportunityLineItem.CPQ_NetNewMRR__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <description>Opportunity Type defines if the opportunity is classified as existing, new, renewal or winback.</description>
    <inlineHelpText>New – New logo or New product existing customer
Existing – Renewal or Product changes
Renewal – Straight renewal
Winback - (Do not use)</inlineHelpText>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Renewal_MRR__c.field-meta.xml
<CustomField>
    <fullName>Renewal_MRR__c</fullName>
    <label>Renewal MRR</label>
    <summarizedField>OpportunityLineItem.Total_Renewal_MRR__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Rev_Incremental_MRR__c.field-meta.xml
<CustomField>
    <fullName>Rev_Incremental_MRR__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rev Incremental MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Rev_Net_New_MRR__c.field-meta.xml
<CustomField>
    <fullName>Rev_Net_New_MRR__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rev Net New MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Rev_Renewal_MRR__c.field-meta.xml
<CustomField>
    <fullName>Rev_Renewal_MRR__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rev Renewal MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/ProdRevenueOppUpdateBatch.cls
/**
 * ───────────────────────────────────────────────────────────────────────────────────────────────┐
* Update Rev_Net_New_MRR__c, Rev_Renewal_MRR__c,Rev_Incremental_MRR__c fields
* Based on the roll-up summary fields
* ────────────────────────────────────────────────────────────────────────────────────────────────
* @param    not applicable
* @return   successfull message on completion via System Debug
* ───────────────────────────────────────────────────────────────────────────────────────────────┘
*/
global without sharing class ProdRevenueOppUpdateBatch implements Database.Batchable<SObject>{
    global static Boolean isProRevRunning = false;
    //fetching current User Id
    Id currentUserId = UserInfo.getUserId();

    global Database.QueryLocator start(Database.BatchableContext bc){
        //only taking updated opportunities
        return Database.getQueryLocator
        ('SELECT Id,Rev_Net_New_MRR__c,Rev_Renewal_MRR__c,Net_New_MRR__c,Renewal_MRR__c,LastModifiedBy.Id, ' +
            'Opportunity_Type__c,Rev_Incremental_MRR__c,LastModifiedDate FROM Opportunity ' +
            'WHERE LastModifiedDate >= Yesterday AND LastModifiedBy.Id !=: currentUserId');
    }

    global void execute(Database.BatchableContext bc, List<Opportunity> opportunityItems){
        isProRevRunning = true;
        try{
            //updating REV Fields
            for(Opportunity op : opportunityItems){
                //opportunity type = NEW, Copy the value from NET NEW MRR to REV NET NEW MRR, Set REV INCREMENTAL MRR to 0
                //opportunity type != NEW, Copy the value from NET NEW MRR to REV INCREMENTAL MRR, Set the REV NET NEW MRR to 0
                if(op.Opportunity_Type__c == 'New'){
                    if(op.Rev_Net_New_MRR__c != op.Net_New_MRR__c){
                        op.Rev_Net_New_MRR__c = op.Net_New_MRR__c;
                    }
                    if(op.Rev_Incremental_MRR__c != 0){
                        op.Rev_Incremental_MRR__c = 0;
                    }
                }
                else{
                    if(op.Rev_Incremental_MRR__c != op.Net_New_MRR__c){
                        op.Rev_Incremental_MRR__c = op.Net_New_MRR__c;
                    }
                    if(op.Rev_Net_New_MRR__c != 0){
                        op.Rev_Net_New_MRR__c = 0;
                    }
                }

                //update only if Renewal_MRR__c is updated
                if(op.Rev_Renewal_MRR__c != op.Renewal_MRR__c){
                    op.Rev_Renewal_MRR__c = op.Renewal_MRR__c;
                }
            }

            Database.update(opportunityItems, false);
        }
        catch(Exception e){
            System.debug('Exception occured: '+ e.getMessage());
        }
    }

    global void finish(Database.BatchableContext bc){
        isProRevRunning = false;
        System.debug('Successfully updated OPP Rev~');
    }
}