UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Other_Reason_Lost_Details__c.field-meta.xml
<CustomField>
    <fullName>Other_Reason_Lost_Details__c</fullName>
    <label>Other Reason Lost Details</label>
    <type>TextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Reason_Won_Lost__c.field-meta.xml
<CustomField>
    <fullName>Reason_Won_Lost__c</fullName>
    <label>Reason Won/Lost</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Carrier Service Account(s)</fullName>
            </value>
            <value>
                <fullName>Competitor Door Fees</fullName>
            </value>
            <value>
                <fullName>Competitor price</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>E-Rate Evaluation</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Installed Base</fullName>
            </value>
            <value>
                <fullName>Lost - Defered (No Decision)</fullName>
            </value>
            <value>
                <fullName>Lost to Competition - Price</fullName>
            </value>
            <value>
                <fullName>Lost to Competition - Product</fullName>
            </value>
            <value>
                <fullName>Lost to Competition - Service</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>No Current Project</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Product Not Available</fullName>
            </value>
            <value>
                <fullName>Property Chose no Marketing Partner</fullName>
            </value>
            <value>
                <fullName>Property Chose to Discontinue Bulk</fullName>
            </value>
            <value>
                <fullName>Property Revenue Share</fullName>
            </value>
            <value>
                <fullName>Referral Agent Lead</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Track Record</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Moved to NWF</fullName>
            </value>
            <value>
                <fullName>Existing Services</fullName>
            </value>
            <value>
                <fullName>Product Offering</fullName>
            </value>
            <value>
                <fullName>Promotion/Campaign</fullName>
            </value>
            <value>
                <fullName>Frontier Reputation</fullName>
            </value>
            <value>
                <fullName>Lost to Competition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/Order_Opportunity_Unlocked__c.field-meta.xml
<CustomField>
    <fullName>Order_Opportunity_Unlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Opportunity Unlocked</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/QuoteOpportunityUnlockControllerTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 1 
**/
@isTest
private class QuoteOpportunityUnlockControllerTest {
    
  
     static testmethod void unlockOpportunity_Test(){
	 Opportunity opp = new Opportunity(Name = 'Test Opportunity', StageName = 'Approved', CloseDate = Date.valueOf('2020-09-23'),Reason_Won_Lost__c = 'Other',Other_Reason_Lost_Details__c = 'Other');
     insert opp;
     approval.lock(opp.id);
     
	 Quote qt = new Quote (Name = 'Test Quote',Order_Opportunity_Unlocked__c = false, OpportunityId =opp.id);
	 insert qt;
       
        test.startTest();
        QuoteOpportunityUnlockController.unlockOpportunity(qt.id);
        test.stopTest();

    }
    
}