UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_911_Notifications__c/ftr_911_Notifications__c.object-meta.xml
<CustomObject>
    <label>911 Notifications</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>911 Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_911_Notifications__c/fields/Department_System__c.field-meta.xml
<CustomField>
    <fullName>Department_System__c</fullName>
    <label>Department/System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_911_Notifications__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cell</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_911_Notifications__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>911 Notifications</relationshipLabel>
    <relationshipName>X911_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/ftr_DID_Location_Details__c.object-meta.xml
<CustomObject>
    <label>DID Location Details</label>
    <nameField>
        <label>DID Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Location Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/ftr_DID_Number_Details__c.object-meta.xml
<CustomObject>
    <label>DID Number Details</label>
    <nameField>
        <label>DID Number Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Number Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/DIDLocationDetailsId__c.field-meta.xml
<CustomField>
    <fullName>DIDLocationDetailsId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DID Location Details</label>
    <referenceTo>ftr_DID_Location_Details__c</referenceTo>
    <relationshipLabel>DID Number Details</relationshipLabel>
    <relationshipName>DID_Number_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Department__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Department__c</fullName>
    <label>Department</label>
    <length>52</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Number_Use__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Number_Use__c</fullName>
    <label>Number Use</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DID</fullName>
                <default>true</default>
                <label>DID</label>
            </value>
            <value>
                <fullName>Auto Attendant</fullName>
            </value>
            <value>
                <fullName>General Voice Mail</fullName>
            </value>
            <value>
                <fullName>Multi-Line Hunting Group</fullName>
                <label>Multi-Line Hunt Group Pilot</label>
            </value>
            <value>
                <fullName>Vacant/Spare/Additional DID</fullName>
            </value>
            <value>
                <fullName>Toll Free</fullName>
            </value>
            <value>
                <fullName>Contact Center as a Service</fullName>
            </value>
            <value>
                <fullName>Not Porting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Additional_UCF_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_UCF_Information__c</fullName>
    <label>Additional UCF Information</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Direct_Page__c.field-meta.xml
<CustomField>
    <fullName>Direct_Page__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Page</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/DSS_BLF_Enhanced_Monitor_Extensions_Btns__c.field-meta.xml
<CustomField>
    <fullName>DSS_BLF_Enhanced_Monitor_Extensions_Btns__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DSS/BLF Enhanced Monitor Extensions Btns</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Group_Page__c.field-meta.xml
<CustomField>
    <fullName>Group_Page__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Group Page</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Group_Pickup__c.field-meta.xml
<CustomField>
    <fullName>Group_Pickup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Group Pickup</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/How_many_park_keys__c.field-meta.xml
<CustomField>
    <fullName>How_many_park_keys__c</fullName>
    <label>How many park keys?</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Is_it_shared_or_location_department__c.field-meta.xml
<CustomField>
    <fullName>Is_it_shared_or_location_department__c</fullName>
    <label>Is it shared or location/department?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Location/Department</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Park_Keys__c.field-meta.xml
<CustomField>
    <fullName>Park_Keys__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Park Keys</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Speed_Calls__c.field-meta.xml
<CustomField>
    <fullName>Speed_Calls__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Speed Calls</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Product2/fields/AvailableButtonCount__c.field-meta.xml
<CustomField>
    <fullName>AvailableButtonCount__c</fullName>
    <description>Stores the available buttons amount for each phone</description>
    <label>AvailableButtonCount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
            <value>
                <fullName>43</fullName>
            </value>
            <value>
                <fullName>47</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>66</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Product2/fields/VendorName__c.field-meta.xml
<CustomField>
    <fullName>VendorName__c</fullName>
    <label>Vendor Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Polycom</fullName>
            </value>
            <value>
                <fullName>Yealink</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/CustomizationsNotesUcfController.cls
/**
 * Author: Alishba
 * Date : 01/Nov/2023
 * @description US-, Controller for CustomizationsNotesUcf LWC
 */
public class CustomizationsNotesUcfController {

    /**
     * @description Method to load data for Customization Notes
     * @param recordId the order record Id
     * @return InitResponse
     */
    @AuraEnabled
    public static InitResponse loadData(String recordId) {
        Set<String> product2IdSet = new Set<String>();
     	InitResponse ir = new InitResponse();
        List<Order> orderList = [SELECT Id, Park_Keys__c, How_many_park_keys__c, Group_Page__c, Group_Pickup__c, Direct_Page__c, Speed_Calls__c,
                          DSS_BLF_Enhanced_Monitor_Extensions_Btns__c, Additional_UCF_Information__c, Is_it_shared_or_location_department__c
                          FROM Order 
                          WHERE Id =: recordId LIMIT 1];
        system.debug('recordId '+recordId);
        system.debug('orderList '+orderList);
        if(orderlist.size()>0){
        ir.orderRecord= orderList[0];
        system.debug('orderList '+orderList[0]);
        }
        else{
            Order emptyList= new Order();
            ir.orderRecord=emptyList;
        }

        for(OrderItem ordrItem :[SELECT Id, Product2Id,Product2.vlocity_cmt__SpecificationSubType__c FROM OrderItem WHERE OrderId =: recordId AND Product2Id != null AND Product2.vlocity_cmt__Type__c!='Accessories' AND Product2.vlocity_cmt__SpecificationSubType__c IN ('Yealink Phones','Conference Models','Poly Phones') AND Product2.vlocity_cmt__SubType__c NOT IN ('Power Cord')]){
            product2IdSet.add(ordrItem.Product2Id);
        }
        ir.lineItemsList = [SELECT Id,Name, VendorName__c, AvailableButtonCount__c
                            FROM Product2
                            WHERE  Id IN: product2IdSet];

        ir.NotificationList = [SELECT  Id,Name,	Department_System__c, Department_Name__c,Method__c,Phone_Number__c,	Email_Address__c,Order__c FROM ftr_911_Notifications__c WHERE Order__c =: recordId];
        					
        return ir;
     }
     
    
      //Methods for getting Product Date
	/*@AuraEnabled(cacheable=true)
	public static List<Product2> productData(String orderId) {
    	List<Product2> productlist = [SELECT Id, Name, VendorName__c, AvailableButtonCount__c FROM Product2 where Order__c = :orderId];
   		 return productlist;
		}*/
    
    /**
     * @description Method to update order record
     * @param orderToUpdate the order record to be updated
     */
    @AuraEnabled
    public static void updateOrder(Order orderToUpdate) {
        system.debug('order to update: '+orderToUpdate);
        try{
            update orderToUpdate;
        } catch(Exception ex){
            throw new AuraHandledException('Transaction Failed. Error: '+ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static String update911Notifications(List<ftr_911_Notifications__c> updatedRecords) {
        try {
            
            System.debug('records: ' +updatedRecords) ;
            update updatedRecords;
            return 'Success';
        } catch(Exception e) {
            // Log the exception and return an error message
            System.debug('Error updating records: ' + e.getMessage());
            return 'Error: ' + e.getMessage();
        }
    }
    @AuraEnabled
    public static List<ftr_DID_Number_Details__c> ftrDIDNumberDetailsDepartment(String recordId) {
        List<ftr_DID_Number_Details__c> DIDNumberDetail = [SELECT Id,Ucf_Department__c
                                                           FROM ftr_DID_Number_Details__c 
                                                           WHERE Ucf_Number_Use__c='DID' 
                                                           AND Ucf_Department__c != null
                                                           AND DIDLocationDetailsId__r.OrderId__c  =: recordId
                                                          ];
        return DIDNumberDetail;
    }

    
        @AuraEnabled
    public static String insertNotification(String name, String departmentSystem, String departmentName, String method, Decimal phoneNumber, String emailAddress, Id recordId) {
        try {
            // Create and insert the new notification record
            ftr_911_Notifications__c newNotification = new ftr_911_Notifications__c(
                Name = name,
                Department_System__c = departmentSystem,
                Department_Name__c = departmentName,
                Method__c = method,
                Phone_Number__c = phoneNumber,
                Email_Address__c = emailAddress,
                Order__c = recordId
            );
            insert newNotification;
    
            // Return success message
            return 'Record inserted successfully.';
        } catch (Exception e) {
            // Handle exceptions
            return 'Error: ' + e.getMessage();
        }
    }
    

    
    /**
     * @description Wrapper class to hold response to display
     */
    public Class InitResponse{
        @AuraEnabled public Order orderRecord;
        @AuraEnabled public list<Product2> lineItemsList;
        @AuraEnabled public list<ftr_911_Notifications__c> NotificationList;
    }
}