UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/ftr_DID_Location_Details__c.object-meta.xml
<CustomObject>
    <label>DID Location Details</label>
    <nameField>
        <label>DID Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Location Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/RecordListWithDeleteController.cls
public with sharing class RecordListWithDeleteController {
    @AuraEnabled
    public static List<ftr_DID_Location_Details__c> getRecords(Id orderId) {
        return [select id,Name,OrderId__c,ServiceAccountId__r.Name,ServiceAccountId__c  from ftr_DID_Location_Details__c where OrderId__c=:orderId];
    }
     @AuraEnabled
    public static void DeleteRecord(List<ftr_DID_Location_Details__c> DeleteIds) {
        
        List<ftr_DID_Location_Details__c> delacccon = new List<ftr_DID_Location_Details__c>();
        for(ftr_DID_Location_Details__c con : [SELECT Id, Name FROM ftr_DID_Location_Details__c WHERE Id IN : DeleteIds]){
            delacccon.add(con);
        }
         
        if(delacccon.size() > 0){
            Delete  delacccon;
        }
         
    }
}