UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/ftr_DID_Location_Details__c.object-meta.xml
<CustomObject>
    <label>DID Location Details</label>
    <nameField>
        <label>DID Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Location Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/ftr_DID_Number_Details__c.object-meta.xml
<CustomObject>
    <label>DID Number Details</label>
    <nameField>
        <label>DID Number Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Number Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/DID_Number__c.field-meta.xml
<CustomField>
    <fullName>DID_Number__c</fullName>
    <label>DID Number (Unique)</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/DIDLocationDetailsId__c.field-meta.xml
<CustomField>
    <fullName>DIDLocationDetailsId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DID Location Details</label>
    <referenceTo>ftr_DID_Location_Details__c</referenceTo>
    <relationshipLabel>DID Number Details</relationshipLabel>
    <relationshipName>DID_Number_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/DIDNumber__c.field-meta.xml
<CustomField>
    <fullName>DIDNumber__c</fullName>
    <label>DID Number</label>
    <type>Phone</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Customize_Extension__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Customize_Extension__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customize Extension</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Email__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Extension__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Extension__c</fullName>
    <label>Extension</label>
    <length>52</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Extension_Lenght__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Extension_Lenght__c</fullName>
    <label>Extension Lenght</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_General_Voice_Mail_Name__c.field-meta.xml
<CustomField>
    <fullName>Ucf_General_Voice_Mail_Name__c</fullName>
    <label>General Voice Mail Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Number_Use__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Number_Use__c</fullName>
    <label>Number Use</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DID</fullName>
                <default>true</default>
                <label>DID</label>
            </value>
            <value>
                <fullName>Auto Attendant</fullName>
            </value>
            <value>
                <fullName>General Voice Mail</fullName>
            </value>
            <value>
                <fullName>Multi-Line Hunting Group</fullName>
                <label>Multi-Line Hunt Group Pilot</label>
            </value>
            <value>
                <fullName>Vacant/Spare/Additional DID</fullName>
            </value>
            <value>
                <fullName>Toll Free</fullName>
            </value>
            <value>
                <fullName>Contact Center as a Service</fullName>
            </value>
            <value>
                <fullName>Not Porting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/UcfGvmController.cls
public class UcfGvmController {

    
    @AuraEnabled
    public static List<ftr_DID_Number_Details__c> ftrDIDNumberDetailsGeneralVoicemail(String recordId) {
        System.debug('Gvm: ' + recordId);
        List<ftr_DID_Number_Details__c> DIDNumberDetail = [
            SELECT Id,
        DIDNumber__c,
        EAS_Pin__c,
        Ucf_Extension__c,
        Ucf_General_Voice_Mail_Name__c,
         Ucf_Number_Use__c,
         Ucf_Customize_Extension__c,
         Ucf_Extension_Lenght__c,
         Ucf_Email__c
         FROM 
         ftr_DID_Number_Details__c 
         WHERE 
         Ucf_Number_Use__c='General Voice Mail'
         AND DIDLocationDetailsId__r.OrderId__c  =: recordId];
         
        return DIDNumberDetail;
    }

    @AuraEnabled
    public static List<ftr_DID_Number_Details__c> downloadFtrDIDNumberDetailsGeneralVoicemail(String recordId) {
        System.debug('Gvm: ' + recordId);
        List<ftr_DID_Number_Details__c> DIDNumberDetail = [
            SELECT Id,
            DIDNumber__c,
            EAS_Pin__c,
            Ucf_Extension__c,
            Ucf_General_Voice_Mail_Name__c,
             Ucf_Email__c
             FROM 
             ftr_DID_Number_Details__c 
             WHERE 
             Ucf_Number_Use__c='General Voice Mail'
             AND DIDLocationDetailsId__r.OrderId__c  =: recordId];
         
        return DIDNumberDetail;
    }
      
       @AuraEnabled
    public static string loadCSVDataForGenralVoicemail(Id contentDocumentId){

        ContentVersion contentVersionObj = [ SELECT Id, VersionData FROM 
                                             ContentVersion WHERE 
                                             ContentDocumentId =:contentDocumentId ];
        
         List<ftr_DID_Number_Details__c> dataToUpesert = new List<ftr_DID_Number_Details__c>();
         
         String data= (String) contentVersionObj.VersionData.toString();

         string[] csvFileLines=data.split('\n');

         for(Integer i=1;i<csvFileLines.size();i++){
            
            string[] csvRecordData = csvFileLines[i].split(',');
            
            ftr_DID_Number_Details__c DIDNumber = new ftr_DID_Number_Details__c();
            DIDNumber.Id = csvRecordData[0];
            DIDNumber.DIDNumber__c = csvRecordData[1] ;             
            DIDNumber.Ucf_Extension__c = csvRecordData[2];
            DIDNumber.Ucf_General_Voice_Mail_Name__c = csvRecordData[3];
            DIDNumber.Ucf_Email__c = csvRecordData[4];
            DIDNumber.DID_Number__c = DIDNumber.DIDNumber__c ;

            System.debug('logLevel'+ csvRecordData[0]);
            dataToUpesert.add(DIDNumber);   
        }

        upsert dataToUpesert;

        return string.valueOf(dataToUpesert.size());
    

    }

     @AuraEnabled
    public static String updateftrDIDNumberDetailsEmployeeTab(List<ftr_DID_Number_Details__c> recordsToUpdate) {
        try {
            // Perform updates on the records
            update recordsToUpdate;

            return 'Records updated successfully.';
        } catch (Exception e) {
            return 'Error updating records: ' + e.getMessage();
        }
    }



}