UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/ftr_DID_Location_Details__c.object-meta.xml
<CustomObject>
    <label>DID Location Details</label>
    <nameField>
        <label>DID Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Location Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/ftr_DID_Number_Details__c.object-meta.xml
<CustomObject>
    <label>DID Number Details</label>
    <nameField>
        <label>DID Number Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Number Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/DID_Number__c.field-meta.xml
<CustomField>
    <fullName>DID_Number__c</fullName>
    <label>DID Number (Unique)</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/DIDLocationDetailsId__c.field-meta.xml
<CustomField>
    <fullName>DIDLocationDetailsId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DID Location Details</label>
    <referenceTo>ftr_DID_Location_Details__c</referenceTo>
    <relationshipLabel>DID Number Details</relationshipLabel>
    <relationshipName>DID_Number_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/MDN_Checkbox__c.field-meta.xml
<CustomField>
    <fullName>MDN_Checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is MDN</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Collaboration__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Collaboration__c</fullName>
    <label>Collaboration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10 Attendees</fullName>
            </value>
            <value>
                <fullName>25 Attendees</fullName>
            </value>
            <value>
                <fullName>100 Attendees</fullName>
            </value>
            <value>
                <fullName>200 Attendees</fullName>
            </value>
            <value>
                <fullName>300 Attendees</fullName>
            </value>
            <value>
                <fullName>500 Attendees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Device_Accessories__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Device_Accessories__c</fullName>
    <label>Device Accessories</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yealink UH36 Mono Headset</fullName>
            </value>
            <value>
                <fullName>Yealink WH62 Dual Cordless Headset</fullName>
            </value>
            <value>
                <fullName>Yealink UH36 Dual Headset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Device_Type__c</fullName>
    <label>Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yealink T31G</fullName>
            </value>
            <value>
                <fullName>Yealink CP960 Conference</fullName>
            </value>
            <value>
                <fullName>Yealink T54W</fullName>
            </value>
            <value>
                <fullName>Yealink T57W</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Install_Type__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Install_Type__c</fullName>
    <label>Install Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New DID Range</fullName>
            </value>
            <value>
                <fullName>Port-In</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
            <value>
                <fullName>Existing # (Regrade)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_License_Type__c.field-meta.xml
<CustomField>
    <fullName>Ucf_License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Analog</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Number_Use__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Number_Use__c</fullName>
    <label>Number Use</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DID</fullName>
                <default>true</default>
                <label>DID</label>
            </value>
            <value>
                <fullName>Auto Attendant</fullName>
            </value>
            <value>
                <fullName>General Voice Mail</fullName>
            </value>
            <value>
                <fullName>Multi-Line Hunting Group</fullName>
                <label>Multi-Line Hunt Group Pilot</label>
            </value>
            <value>
                <fullName>Vacant/Spare/Additional DID</fullName>
            </value>
            <value>
                <fullName>Toll Free</fullName>
            </value>
            <value>
                <fullName>Contact Center as a Service</fullName>
            </value>
            <value>
                <fullName>Not Porting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Screen_Recording__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Screen_Recording__c</fullName>
    <label>Screen Recording</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Storage__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Storage__c</fullName>
    <label>Storage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>30 days(free)</fullName>
            </value>
            <value>
                <fullName>180 days</fullName>
            </value>
            <value>
                <fullName>1 Year</fullName>
            </value>
            <value>
                <fullName>2 Years</fullName>
            </value>
            <value>
                <fullName>3 Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Webinar__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Webinar__c</fullName>
    <label>Webinar</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100 Attendees</fullName>
            </value>
            <value>
                <fullName>500 Attendees</fullName>
            </value>
            <value>
                <fullName>1000 Attendees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/ftr_SubmitUCFOrder_Test.cls
@isTest
private class ftr_SubmitUCFOrder_Test {
    @isTest
    static void testCreateTechnicalProduct() {
        // Test data setup
        // UCF_DID_DPI_Services
        Map<String, String> mapProductNameCode = new Map<String, String>();
        mapProductNameCode.put('UCF Basic', 'UCF_BASIC_LIC');
        mapProductNameCode.put('UCF DID DPI Services', 'UCF_DID_DPI_Services');
        mapProductNameCode.put('UCF Poly Edge 450', 'UCF_POLY_EDGE_E450');
        mapProductNameCode.put('UCF Poly Edge E EM', 'UCF_POLY_EDGE_EEM');
        mapProductNameCode.put('UCF Call Recording Basic', 'UCF_CR_BASIC');
        
        List<Order> liOrders = ftr_TestDataFactory.getOrders(2);
        insert liOrders;
        
        Product2 prod = new Product2(Name = 'UCF Poly Edge 450',
                                    ProductCode = mapProductNameCode.get('UCF Poly Edge 450'),
                                    vlocity_cmt__EffectiveDate__c = System.today(),
                                    IsActive = true);
        insert prod;
        
        List<OrderItem> liOrderItems = ftr_TestDataFactory.getOrderItems(4, mapProductNameCode);
        
        for(OrderItem orderItem :liOrderItems) {
            orderItem.OrderId = liOrders[0].Id;
        }
        
        insert liOrderItems;
        
        List<ftr_DID_Location_Details__c> didLocationDetails = new List<ftr_DID_Location_Details__c>();
        
        for (Integer i = 0; i < liOrders.size(); i++) {
            ftr_DID_Location_Details__c didLocationDetail = new ftr_DID_Location_Details__c();
            didLocationDetail.OrderId__c = liOrders[i].Id;
            
            // Set other fields of didLocationDetail as needed
            // ...
            
            didLocationDetails.add(didLocationDetail);
        }
        
        insert didLocationDetails;
        
        ftr_DID_Number_Details__c newNumberDetail1 = new ftr_DID_Number_Details__c();
        newNumberDetail1.DIDLocationDetailsId__c = didLocationDetails[0].Id;
        newNumberDetail1.Ucf_Number_Use__c = 'Toll Free';
        newNumberDetail1.Ucf_Install_Type__c = 'New DID Range';
        newNumberDetail1.MDN_Checkbox__c = false;
        newNumberDetail1.DID_Number__c = '123' ;
        newNumberDetail1.Ucf_License_Type__c = 'UCF Basic';
        newNumberDetail1.Ucf_Device_Type__c = 'Yealink T31G';
        newNumberDetail1.Ucf_Device_Accessories__c = 'Yealink UH36 Dual Headset';    
        newNumberDetail1.Ucf_Screen_Recording__c='Yes';
        insert newNumberDetail1;
        
        ftr_DID_Number_Details__c newNumberDetail2 = new ftr_DID_Number_Details__c();
        newNumberDetail2.DIDLocationDetailsId__c = didLocationDetails[0].Id;
        newNumberDetail2.Ucf_Number_Use__c = 'Auto Attendant';
        newNumberDetail2.Ucf_Install_Type__c = 'Existing';
        newNumberDetail2.MDN_Checkbox__c = false;
        newNumberDetail2.DID_Number__c = '987' ;
        newNumberDetail2.Ucf_License_Type__c = 'UCF Basic';
        newNumberDetail2.Ucf_Device_Type__c = 'Yealink T31G';
        newNumberDetail2.Ucf_Device_Accessories__c = 'Yealink UH36 Dual Headset';
        newNumberDetail2.Ucf_Screen_Recording__c='Yes';
        insert newNumberDetail2;
        
        ftr_DID_Number_Details__c newNumberDetail3 = new ftr_DID_Number_Details__c();
        newNumberDetail3.DIDLocationDetailsId__c = didLocationDetails[0].Id;
        newNumberDetail3.Ucf_Number_Use__c = 'Auto Attendant';
        newNumberDetail3.Ucf_Install_Type__c = 'New DID Range';
        newNumberDetail3.MDN_Checkbox__c = false;
        newNumberDetail3.DID_Number__c = '123' ;
        newNumberDetail3.Ucf_License_Type__c = 'UCF Basic';
        newNumberDetail3.Ucf_Device_Type__c = 'Yealink T31G';
        newNumberDetail3.Ucf_Device_Accessories__c = 'Yealink UH36 Dual Headset';
        newNumberDetail3.Ucf_Collaboration__c = '';
         newNumberDetail3.Ucf_Webinar__c ='';
         newNumberDetail3.Ucf_Screen_Recording__c='Yes';
          newNumberDetail3.Ucf_Storage__c='1 Year';
        
        
        insert newNumberDetail3;
        
        
        Test.startTest();
        ftr_SubmitUCFOrder obj = new ftr_SubmitUCFOrder();
        obj.createTechnicalProduct(liOrders[0].Id);
        Test.stopTest();
        
    }
    
    @isTest
    static void testUpdateOrderLineItems() {
        
        Map<String, String> mapProductNameCode = new Map<String, String>();
        mapProductNameCode.put('UCF Basic', 'UCF_BASIC_LIC ');
        mapProductNameCode.put('UCF DID DPI Services', 'UCF_DID_DPI_Services');
        mapProductNameCode.put('UCF Poly Edge 450', 'UCF_POLY_EDGE_E450');
        mapProductNameCode.put('UCF DC 711', 'UCF_DC_711');
        mapProductNameCode.put('UCF Poly Edge E EM', 'UCF_POLY_EDGE_EEM');
        
        Product2 prod = new Product2(Name = 'UCF DC 711',
                                    ProductCode = mapProductNameCode.get('UCF DC 711'),
                                    vlocity_cmt__EffectiveDate__c = System.today(),
                                    IsActive = true);
        insert prod;
        List<Order> liOrders = ftr_TestDataFactory.getOrders(2);
        insert liOrders;
        
        List<OrderItem> liOrderItems = ftr_TestDataFactory.getOrderItems(4, mapProductNameCode);
        
        for(OrderItem orderItem :liOrderItems) {
            orderItem.OrderId = liOrders[0].Id;
            orderItem.vlocity_cmt__ServiceAccountId__c = liOrders[0].AccountId; 
        }
        
        insert liOrderItems;
        
        List<ftr_DID_Location_Details__c> didLocationDetails = new List<ftr_DID_Location_Details__c>();
        
        for (Integer i = 0; i < liOrders.size(); i++) {
            ftr_DID_Location_Details__c didLocationDetail = new ftr_DID_Location_Details__c();
            didLocationDetail.OrderId__c = liOrders[i].Id;
            didLocationDetail.ServiceAccountId__c=liOrderItems[0].vlocity_cmt__ServiceAccountId__c;
            didLocationDetails.add(didLocationDetail);
        }
        
        insert didLocationDetails;
        
        ftr_DID_Number_Details__c newNumberDetail1 = new ftr_DID_Number_Details__c();
        newNumberDetail1.DIDLocationDetailsId__c = didLocationDetails[0].Id;
        newNumberDetail1.Ucf_Number_Use__c = 'Toll Free';
        newNumberDetail1.Ucf_Install_Type__c = 'New DID Range';
        newNumberDetail1.MDN_Checkbox__c = true;
        newNumberDetail1.DID_Number__c = '123' ;
        newNumberDetail1.Ucf_License_Type__c = 'UCF Basic';
        newNumberDetail1.Ucf_Device_Type__c = 'Yealink T31G';
        newNumberDetail1.Ucf_Device_Accessories__c = 'Yealink UH36 Dual Headset'; 
        newNumberDetail1.Ucf_Collaboration__c = '';
         newNumberDetail1.Ucf_Webinar__c ='';
         newNumberDetail1.Ucf_Screen_Recording__c='Yes';
          newNumberDetail1.Ucf_Storage__c='1 Year';
        insert newNumberDetail1;
        
        
        Test.startTest();
        ftr_SubmitUCFOrder.updateOrderLineItems(liOrders[0].Id);
        Test.stopTest();
        
    }
}