UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Broadband, FiOS &amp; Voice Bundles</fullName>
                <label>Broadband, FiberOptic &amp; Voice Bundles - Existing/Upgrades</label>
            </value>
            <value>
                <fullName>Broadband, FiOS &amp; Voice Bundles - New Service</fullName>
                <label>Broadband, FiberOptic &amp; Voice Bundles - New Service</label>
            </value>
            <value>
                <fullName>Current Broadband Offers</fullName>
            </value>
            <value>
                <fullName>Ethernet/Data Services</fullName>
                <label>Ethernet/Transport Services</label>
            </value>
            <value>
                <fullName>FSA 1 Page</fullName>
            </value>
            <value>
                <fullName>FSA Standard Full Version</fullName>
            </value>
            <value>
                <fullName>Local Services</fullName>
            </value>
            <value>
                <fullName>Managed Services</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>Premier Retail LOA</fullName>
            </value>
            <value>
                <fullName>Premier Retail LOA-MDF</fullName>
            </value>
            <value>
                <fullName>SAA</fullName>
            </value>
            <value>
                <fullName>Twenty-Twenty LOA-MDF</fullName>
            </value>
            <value>
                <fullName>VAL</fullName>
            </value>
            <value>
                <fullName>VoIP</fullName>
            </value>
            <value>
                <fullName>Wi-Fi</fullName>
                <label>Wireless Solutions</label>
            </value>
            <value>
                <fullName>PAL</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>PAL-Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing Agreement</fullName>
            </value>
            <value>
                <fullName>Door to Door LOA-MDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>This field is used to show which products are being quoted.</description>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS</fullName>
            </value>
            <value>
                <fullName>CCaaS</fullName>
            </value>
            <value>
                <fullName>Private Network</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/ScheduleID__c.field-meta.xml
<CustomField>
    <fullName>ScheduleID__c</fullName>
    <formula>IF(
$RecordType.Name = &quot;Frontier Services Agreement&quot;,
NULL,
IF(
AND (
RecordType.Name =&quot;Product Schedule&quot;,
(vlocity_cmt__QuoteId__r.vlocity_cmt__RecurringTotal__c &gt;0),
Contract_Auto_Number__c != NULL
),
Contract_Auto_Number__c,
IF(
AND(
RecordType.Name =&quot;Product Schedule&quot;,
(vlocity_cmt__QuoteId__r.vlocity_cmt__RecurringTotal__c &gt;0),
Contract_Auto_Number__c == NULL
),
vlocity_cmt__QuoteId__r.Schedule_Number__c,
&quot;S-00&quot;+ ContractNumber
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Schedule ID</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Order_Stage__c.field-meta.xml
<CustomField>
    <fullName>Order_Stage__c</fullName>
    <label>Order Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Clean Order</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Clean Order</fullName>
            </value>
            <value>
                <fullName>CNP Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>CPM In Progress</fullName>
            </value>
            <value>
                <fullName>Credit Check</fullName>
            </value>
            <value>
                <fullName>Customer Network Provisioning</fullName>
            </value>
            <value>
                <fullName>DPI/CMS Provisioning</fullName>
            </value>
            <value>
                <fullName>DPI Billing</fullName>
            </value>
            <value>
                <fullName>DPI Provisioning</fullName>
            </value>
            <value>
                <fullName>ECR/EWO In Progress</fullName>
                <label>ECR/PSR In Progress</label>
            </value>
            <value>
                <fullName>EWO In Progress</fullName>
            </value>
            <value>
                <fullName>Hot Cuts</fullName>
            </value>
            <value>
                <fullName>IMPM</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>ISP Engineering</fullName>
            </value>
            <value>
                <fullName>Issuing Orders</fullName>
            </value>
            <value>
                <fullName>MSA Review</fullName>
            </value>
            <value>
                <fullName>NCM Pending Billing</fullName>
            </value>
            <value>
                <fullName>Needs more information</fullName>
            </value>
            <value>
                <fullName>Network COE</fullName>
            </value>
            <value>
                <fullName>Network Cost Management</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Order Engineering Desk</fullName>
            </value>
            <value>
                <fullName>Ordering</fullName>
            </value>
            <value>
                <fullName>OSP Engineering</fullName>
            </value>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2 - Wire Circuit</fullName>
            </value>
            <value>
                <fullName>4 - Wire Circuit</fullName>
            </value>
            <value>
                <fullName>56K</fullName>
            </value>
            <value>
                <fullName>64K</fullName>
            </value>
            <value>
                <fullName>BRI</fullName>
            </value>
            <value>
                <fullName>Broadband</fullName>
            </value>
            <value>
                <fullName>Circuit</fullName>
            </value>
            <value>
                <fullName>CPE</fullName>
            </value>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>E-LAN</fullName>
            </value>
            <value>
                <fullName>E-LAN &amp; EIA</fullName>
            </value>
            <value>
                <fullName>Ethernet</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>FOTS</fullName>
            </value>
            <value>
                <fullName>Fractional Circuit</fullName>
            </value>
            <value>
                <fullName>Frontier Anyware Mitel Hosted</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS</fullName>
            </value>
            <value>
                <fullName>Frontier Calling with Cloud Phone</fullName>
                <label>Frontier Direct Calling</label>
            </value>
            <value>
                <fullName>IP/VPN</fullName>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi</fullName>
            </value>
            <value>
                <fullName>Managed Router</fullName>
            </value>
            <value>
                <fullName>Managed Services</fullName>
            </value>
            <value>
                <fullName>OC-12</fullName>
            </value>
            <value>
                <fullName>OC-3</fullName>
            </value>
            <value>
                <fullName>OC-48</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Private Line T1 / DS1</fullName>
            </value>
            <value>
                <fullName>Private Line T3 / DS3</fullName>
            </value>
            <value>
                <fullName>Ring Central</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS</fullName>
            </value>
            <value>
                <fullName>CCaaS</fullName>
            </value>
            <value>
                <fullName>Private Network</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/vlocity_cmt__OrchestrationPlanId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__OrchestrationPlanId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orchestration Plan</label>
    <referenceTo>vlocity_cmt__OrchestrationPlan__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/vlocity_cmt__OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__OrderStatus__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Submit</fullName>
                <label>AE Review</label>
            </value>
            <value>
                <fullName>SE Review</fullName>
            </value>
            <value>
                <fullName>Mngd Svc Review</fullName>
            </value>
            <value>
                <fullName>PM Assignment</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Cancel Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Amend Requested</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Discarded</fullName>
            </value>
            <value>
                <fullName>Available In Pool</fullName>
            </value>
            <value>
                <fullName>Cancel In Progress</fullName>
                <isActive>false</isActive>
                <label>Cancel In Progress</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Superseded</fullName>
                <isActive>false</isActive>
                <label>Superseded</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/vlocity_cmt__PriceListId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__PriceListId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price List</label>
    <referenceTo>vlocity_cmt__PriceList__c</referenceTo>
    <relationshipLabel>Orders Using This Price List</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/vlocity_cmt__QuoteId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DEPRECATED. Use the standard QuoteId field.</description>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/XOMAutoTask_UpdateVlocityOrderStatus.cls
global class XOMAutoTask_UpdateVlocityOrderStatus implements vlocity_cmt.XOMOrchestrationInterfaces.IAutoTask{
    global void executeBatch(List<vlocity_cmt__OrchestrationItem__c> items) {
        System.debug('Enter XOMAutoTask_UpdateVlocityOrderStatus.executeBatch');
        try {
        System.debug('XOMAutoTask_UpdateVlocityOrderStatus:items.size()-->'+items.size());
        Set<Id> itemIds = new Set<Id>();
        if(items.size() > 0) {
           
            for(vlocity_cmt__OrchestrationItem__c item : items) {
                System.debug('XOMAutoTask:for loop-->'+JSON.serialize(item));
                itemIds.add(item.Id);              
            }
             vlocity_cmt__OrchestrationItem__c  orchItem = [SELECT Id,Name,vlocity_cmt__OrderItemId__r.Order.Id,  vlocity_cmt__OrchestrationPlanId__c,vlocity_cmt__OrchestrationPlanId__r.vlocity_cmt__OrderId__c
            FROM vlocity_cmt__OrchestrationItem__c where Id IN: itemIds LIMIT 1];
           
           // String OrderNumber=orchItem.vlocity_cmt__OrderItemId__r.Order.Id;
            String OrderNumber=orchItem.vlocity_cmt__OrchestrationPlanId__r.vlocity_cmt__OrderId__c;
            System.debug('OrderNumber-->'+OrderNumber);
            
            Order OrderToUpdate;
            OrderToUpdate =[SELECT Order_Stage__c,ContractId, vlocity_cmt__OrderStatus__c FROM Order WHERE Id=:OrderNumber LIMIT 1];
            // Update the Order Stage.
            OrderToUpdate.Order_Stage__c = 'Complete';
            OrderToUpdate.vlocity_cmt__OrderStatus__c = 'Complete';
            // Make the update call.
            update OrderToUpdate;
            if(OrderToUpdate != null && OrderToUpdate.ContractId != null)
            {
               Contract  conObject = [SELECT id,StatusCode,vlocity_cmt__quoteid__c,agreement_type__c,product_type__c,products__c,scheduleid__c,
                                        shippingstreet,billingstreet,status,recordtypeid,vlocity_cmt__pricelistid__c,accountid,
                                        billingcity,billingcountry,billingpostalcode,billingstate,name,shippingcity,shippingcountry,
                                        shippingpostalcode,shippingstate,recordtype.developername FROM Contract WHERE id =: OrderToUpdate.ContractId limit 1];
                
            conObject.status = 'Activated';
              update conObject;
              System.debug('XOMAutoTask_UpdateVlocityOrderStatus:Order_Stage__c-->'+conObject.status);  
            }
            System.debug('XOMAutoTask_UpdateVlocityOrderStatus:Order_Stage__c-->'+OrderToUpdate.Order_Stage__c);
            System.debug('XOMAutoTask_UpdateVlocityOrderStatus:vlocity_cmt__OrderStatus__c-->'+OrderToUpdate.vlocity_cmt__OrderStatus__c);
        }
        }catch (Exception ex) { ftr_Logger.write(ex);
        } finally {
            ftr_Logger.writeInfo('Exit XOMAutoTask_UpdateVlocityOrderStatus.executeBatch');
        }
    }
}