UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Broadband, FiOS &amp; Voice Bundles</fullName>
                <label>Broadband, FiberOptic &amp; Voice Bundles - Existing/Upgrades</label>
            </value>
            <value>
                <fullName>Broadband, FiOS &amp; Voice Bundles - New Service</fullName>
                <label>Broadband, FiberOptic &amp; Voice Bundles - New Service</label>
            </value>
            <value>
                <fullName>Current Broadband Offers</fullName>
            </value>
            <value>
                <fullName>Ethernet/Data Services</fullName>
                <label>Ethernet/Transport Services</label>
            </value>
            <value>
                <fullName>FSA 1 Page</fullName>
            </value>
            <value>
                <fullName>FSA Standard Full Version</fullName>
            </value>
            <value>
                <fullName>Local Services</fullName>
            </value>
            <value>
                <fullName>Managed Services</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>Premier Retail LOA</fullName>
            </value>
            <value>
                <fullName>Premier Retail LOA-MDF</fullName>
            </value>
            <value>
                <fullName>SAA</fullName>
            </value>
            <value>
                <fullName>Twenty-Twenty LOA-MDF</fullName>
            </value>
            <value>
                <fullName>VAL</fullName>
            </value>
            <value>
                <fullName>VoIP</fullName>
            </value>
            <value>
                <fullName>Wi-Fi</fullName>
                <label>Wireless Solutions</label>
            </value>
            <value>
                <fullName>PAL</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>PAL-Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing Agreement</fullName>
            </value>
            <value>
                <fullName>Door to Door LOA-MDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>Bulk_Res</fullName>
                <default>true</default>
                <label>Bulk Res</label>
            </value>
            <value>
                <fullName>BULK-EMA</fullName>
            </value>
            <value>
                <fullName>Bulk Corp</fullName>
            </value>
            <value>
                <fullName>EMA</fullName>
            </value>
            <value>
                <fullName>EMA-DOORFEEONLY</fullName>
            </value>
            <value>
                <fullName>EMA-DOOR-REVSHARE</fullName>
            </value>
            <value>
                <fullName>EMA-REVSHAREONLY</fullName>
            </value>
            <value>
                <fullName>NEMA</fullName>
            </value>
            <value>
                <fullName>No Contract</fullName>
            </value>
            <value>
                <fullName>PAL</fullName>
            </value>
            <value>
                <fullName>Markeing</fullName>
            </value>
            <value>
                <fullName>PAL-Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/CPE_Product__c.field-meta.xml
<CustomField>
    <fullName>CPE_Product__c</fullName>
    <description>Asks Users to check whether a product in the opportunity is a CPE product.</description>
    <inlineHelpText>Must select if a CPE product is a component of the Opportunity being created.</inlineHelpText>
    <label>CPE Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/aps_GenerateDocument_Test.cls
/**
 * @description       :
 * @author            : Monir Zaman
 * @group             :
 * @last modified on  : 19-01-2024
 * @last modified by  : Monir Zaman
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   19-01-2024   Monir Zaman   Initial Version
 **/
@isTest
public with sharing class aps_GenerateDocument_Test {
  @isTest
  static void testHandle() {
    Id AccRType = [
      SELECT id
      FROM RecordType
      WHERE RecordType.Name = 'MTU Company' AND SobjectType = 'Account'
    ]
    .Id;

    Account testSAccount = new Account(
      RecordTypeId = AccRType,
      Name = 'Test Service Account',
      BillingStreet = '123 Main Street',
      BillingCity = 'Anywhere',
      BillingState = 'Ohio',
      BillingPostalCode = '44088',
      ShippingStreet = '123 Main Street',
      ShippingCity = 'Anywhere',
      ShippingState = 'Ohio',
      ShippingPostalCode = '44088'
    );
    insert testSAccount;

    Id OppRType = [
      SELECT id
      FROM RecordType
      WHERE
        RecordType.Name = 'MTU Opportunities'
        AND SobjectType = 'Opportunity'
    ]
    .Id;

    Opportunity opp = new Opportunity(
      RecordTypeId = OppRType,
      Name = 'RefreshTestOpp',
      AccountId = testSAccount.Id,
      CloseDate = date.today(),
      StageName = 'Investigating',
      CPE_Product__c = 'No'
    );
    insert opp;

    Id ContrRType = [
      SELECT id
      FROM RecordType
      WHERE RecordType.Name = 'MTU Contract' AND SobjectType = 'Contract'
    ]
    .Id;

    Contract PALCon = new Contract(
      RecordTypeId = ContrRType,
      AccountId = testSAccount.Id,
      Opportunity__c = opp.Id,
      Status = 'Draft',
      StartDate = date.today(),
      ContractTerm = 24,
      Agreement_Type__c = 'PAL'
    );
    insert PALCon;

    Contract MarCon = new Contract(
      RecordTypeId = ContrRType,
      AccountId = testSAccount.Id,
      Opportunity__c = opp.Id,
      Status = 'Draft',
      StartDate = date.today(),
      ContractTerm = 24,
      Agreement_Type__c = 'Marketing'
    );
    insert MarCon;

    aps_GenerateDocument.wholesaleData(opp.Id);

    aps_GenerateDocument.mtuData(PALCon.Id);
    aps_GenerateDocument.mtuData(MarCon.Id);

    aps_GenerateDocument.mduData(PALCon.Id);
  }
}