UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/Service_Order__c.object-meta.xml
<CustomObject>
    <description>This is the DPI Service Order(s) that are related to the associated order</description>
    <label>Service Order</label>
    <nameField>
        <label>Service Order #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Item_Spec_Id__c.field-meta.xml
<CustomField>
    <fullName>Item_Spec_Id__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1001</fullName>
                <label>Retail Circuit Service</label>
            </value>
            <value>
                <fullName>1002</fullName>
                <label>Broadband Services - Retail</label>
            </value>
            <value>
                <fullName>1003</fullName>
                <label>ATM/FR Connection</label>
            </value>
            <value>
                <fullName>1005</fullName>
                <label>PVC Connection</label>
            </value>
            <value>
                <fullName>1007</fullName>
                <label>Circuit Services - Wholesale</label>
            </value>
            <value>
                <fullName>1009</fullName>
                <label>Broadband Services - Whsl Resale</label>
            </value>
            <value>
                <fullName>1010</fullName>
                <label>ATM/FR Connection.</label>
            </value>
            <value>
                <fullName>1011</fullName>
                <label>Ethernet Connection</label>
            </value>
            <value>
                <fullName>1012</fullName>
                <label>PVC Connection.</label>
            </value>
            <value>
                <fullName>1013</fullName>
                <label>EVC Connections - Retail.</label>
            </value>
            <value>
                <fullName>1040</fullName>
                <label>Circuit Services - Whsl Resale</label>
            </value>
            <value>
                <fullName>1041</fullName>
                <label>Wholesale Resale Circuit Service</label>
            </value>
            <value>
                <fullName>1042</fullName>
                <label>Wholesale UNE Loop/Circuit Service</label>
            </value>
            <value>
                <fullName>1060</fullName>
                <label>Trunk Group Data - Retail</label>
            </value>
            <value>
                <fullName>1061</fullName>
                <label>Data Trunk</label>
            </value>
            <value>
                <fullName>1062</fullName>
                <label>Trunk Group Data - Whsl Resale</label>
            </value>
            <value>
                <fullName>1063</fullName>
                <label>Trunk Group ISDN - Retail</label>
            </value>
            <value>
                <fullName>1064</fullName>
                <label>ISDN Trunk</label>
            </value>
            <value>
                <fullName>1065</fullName>
                <label>Data Trunk.</label>
            </value>
            <value>
                <fullName>1066</fullName>
                <label>Trunk Group ISDN - Whsl Resale</label>
            </value>
            <value>
                <fullName>1067</fullName>
                <label>ISDN Trunk.</label>
            </value>
            <value>
                <fullName>1068</fullName>
                <label>Trunk Group Voice/DCS - Retail</label>
            </value>
            <value>
                <fullName>1069</fullName>
                <label>Trunk Group Voice/DCS - Whsl Resale</label>
            </value>
            <value>
                <fullName>1070</fullName>
                <label>Voice/DCS Trunk</label>
            </value>
            <value>
                <fullName>1071</fullName>
                <label>Voice/DCS Trunk.</label>
            </value>
            <value>
                <fullName>1080</fullName>
                <label>EVC Connections - Retail</label>
            </value>
            <value>
                <fullName>1101</fullName>
                <label>EVPL</label>
            </value>
            <value>
                <fullName>1102</fullName>
                <label>EIA</label>
            </value>
            <value>
                <fullName>1103</fullName>
                <label>ELAN</label>
            </value>
            <value>
                <fullName>1111</fullName>
                <label>UNI Connections - Retail</label>
            </value>
            <value>
                <fullName>1180</fullName>
                <label>EREACH EVPL - EIA (HUB RTR)</label>
            </value>
            <value>
                <fullName>1181</fullName>
                <label>EREACH EVPL</label>
            </value>
            <value>
                <fullName>1220</fullName>
                <label>EVPL - MULTICONNECT</label>
            </value>
            <value>
                <fullName>1221</fullName>
                <label>SIP/IPCONNECT</label>
            </value>
            <value>
                <fullName>1242</fullName>
                <label>FIS Off-Net EIA</label>
            </value>
            <value>
                <fullName>1260</fullName>
                <label>IP/VPN</label>
            </value>
            <value>
                <fullName>1284</fullName>
                <label>SIP Network</label>
            </value>
            <value>
                <fullName>1300</fullName>
                <label>EREACH (ALL OFFNET) EVPL</label>
            </value>
            <value>
                <fullName>1380</fullName>
                <label>EREACH EIA (LOC RTR)</label>
            </value>
            <value>
                <fullName>1440</fullName>
                <label>SDWAN</label>
            </value>
            <value>
                <fullName>1460</fullName>
                <label>EREACH NAT ELAN</label>
            </value>
            <value>
                <fullName>1480</fullName>
                <label>CONNECT CLOUD</label>
            </value>
            <value>
                <fullName>1481</fullName>
                <label>EREACH  - CONNECT CLOUD</label>
            </value>
            <value>
                <fullName>1500</fullName>
                <label>SDWAN PN EVC</label>
            </value>
            <value>
                <fullName>1501</fullName>
                <label>EREACH SDWAN PN EVC</label>
            </value>
            <value>
                <fullName>1541</fullName>
                <label>EREACH - CLOUD MANAGED SRV</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/M6_dd_task_date__c.field-meta.xml
<CustomField>
    <fullName>M6_dd_task_date__c</fullName>
    <label>M6 Due Date</label>
    <type>DateTime</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Service Orders</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Priloc_Address__c.field-meta.xml
<CustomField>
    <fullName>Priloc_Address__c</fullName>
    <label>Primary Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Schedule_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Due_Date__c</fullName>
    <description>This is the date that the work is to be ready by... (TBD)</description>
    <label>Schedule Due Date</label>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Secloc_Address__c.field-meta.xml
<CustomField>
    <fullName>Secloc_Address__c</fullName>
    <label>Secondary Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Service_Order_Stage__c.field-meta.xml
<CustomField>
    <fullName>Service_Order_Stage__c</fullName>
    <label>Service Order Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stage 1 - Order Entry</fullName>
                <label>Order Entry</label>
            </value>
            <value>
                <fullName>Stage 2 - Engineering Review</fullName>
                <label>Engineering Review</label>
            </value>
            <value>
                <fullName>Stage 3 - Construction / Build</fullName>
                <label>Construction / Build</label>
            </value>
            <value>
                <fullName>Stage 4 - Design / Provisioning</fullName>
                <label>Design / Provisioning</label>
            </value>
            <value>
                <fullName>Stage 5 - Physical / Virtual Turn up</fullName>
                <label>Physical / Virtual Turn up</label>
            </value>
            <value>
                <fullName>Stage 6 - Customer Acceptance / Billing</fullName>
                <label>Customer Acceptance / Billing</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>ESB Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/ServiceOrderCtrl.cls
public class ServiceOrderCtrl {
    
    public final static Set<String> productCode = new Set<String>{
        '1101','1102','1103','1180','1181','1220','1221','1242','1260','1284','1300','1380','1440','1460','1480','1481','1500','1501','1541'
    };
	
    @AuraEnabled
    public static data returnServiceOrders(Id orderId){
        return new data([select id,Name,Item_Spec_Id__c,Service_Order_Stage__c,Priloc_Address__c,Secloc_Address__c, Schedule_Due_Date__c,M6_dd_task_date__c  from Service_Order__c where Order__c =:orderId AND Item_Spec_Id__c IN: productCode],getProductValuesIntoMap());
    }
    
    @AuraEnabled
    public static void syncServiceOrder(Service_Order__c serviceOrder){
        syncServiceOrders(new List<Service_Order__c>{serviceOrder});
    }
    
    public static Map<String,String> getProductValuesIntoMap(){
       Map<String,String> pickListValuesMap = new Map<String,String>();
        
		Schema.DescribeFieldResult fieldResult = Service_Order__c.Item_Spec_Id__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesMap.put(pickListVal.getValue(),pickListVal.getLabel());
		}     
		return pickListValuesMap;
    }
    
    public class data{
        @AuraEnabled
        Public List<Service_Order__c> lstSo;
        @AuraEnabled
        public Map<String,String> pickListValuesMap;
        public data(List<Service_Order__c> lstSo,Map<String,String> pickListValuesMap){
            this.lstSo = lstSo;
            this.pickListValuesMap = pickListValuesMap;
        }
    }
    
    @AuraEnabled
    public static void syncServiceOrders(List<Service_Order__c> serviceOrders){
        List<Service_Order__c> lstSo = new List<Service_Order__c>();
        for(Service_Order__c so : serviceOrders){
            Service_Order__c soUodated = ServiceOrderStage_Ctrl.updateOrderStage(so.Id,so.Name,false);
            if(soUodated != null){
                lstSo.add(soUodated);
            }
        }
        try{
            update lstSo;
        }catch(Exception ee){
            throw new ServiceOrderStage_Exception(JSON.serialize(new ServiceOrderStage_Ctrl.ErrorMessage('DML ERROR',ee.getMessage())));
        }
    }
    
    public class ServiceOrderStage_Exception extends Exception {}
}