UCF-APR2.4/ftr main/force-app/main/default/objects/Pricing_Formula_Matrix__c/Pricing_Formula_Matrix__c.object-meta.xml
<CustomObject>
    <label>Pricing Formula Matrix</label>
    <nameField>
        <displayFormat>ABP-{000000}</displayFormat>
        <label>Pricing Formula Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Formula Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Pricing_Formula_Matrix__c/fields/Formula_Name__c.field-meta.xml
<CustomField>
    <fullName>Formula_Name__c</fullName>
    <label>Formula Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Pricing_Formula_Matrix__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>Product code defined in EPC catalog</description>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Pricing_Formula_Matrix__c/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <description>Speed in Megabyte</description>
    <label>Speed</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Pricing_Formula_Matrix__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>12, 24, 36, 60 in months</description>
    <label>Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Pricing_Formula_Var__c/Pricing_Formula_Var__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Pricing Formula Variable</label>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Pricing_Formula_Var__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Pricing_Formula_Var__c/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>The field API name on the Pricing Formula Definition Table</description>
    <label>Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/Service_Term__c.field-meta.xml
<CustomField>
    <fullName>Service_Term__c</fullName>
    <label>Service Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12 Months</fullName>
            </value>
            <value>
                <fullName>24 Months</fullName>
            </value>
            <value>
                <fullName>36 Months</fullName>
            </value>
            <value>
                <fullName>60 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <description>This is used to store the attribute value selected for Speed.</description>
    <label>Speed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>Bound to Attribute = Term</description>
    <label>Term</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__BillingAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__BillingAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account responsible for paying for the line item.</description>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>BillingAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__JSONAttribute__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__JSONAttribute__c</fullName>
    <description>JSON body containing Vlocity Attribute value data.</description>
    <label>JSONAttribute</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DEPRECATED, Use the standard Product2Id field.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account that identifies the service location or subscriber that is the user of the service.</description>
    <label>Service Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>ServiceAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/PricingFormulaServiceTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 5
**/
@isTest
public class PricingFormulaServiceTest {

    @IsTest
    static void testingPricingFormulaService1(){

        insert ftr_TestDataFactory.getQLI(1, 1);
        List<QuoteLineItem> qlis = [
            SELECT Id, vlocity_cmt__ServiceAccountId__c, Quantity, Term__c, Speed__c, vlocity_cmt__Product2Id__c, QuoteId, vlocity_cmt__BillingAccountId__c, 
            vlocity_cmt__LineNumber__c, Product2Id, vlocity_cmt__JSONAttribute__c, PricebookEntry.Product2.ProductCode
            FROM QuoteLineItem
        ];

        Quote parent = [select id, Service_Term__c from quote where id=:(Id)qlis[0].get('QuoteId')];
        
        Product2 prod = [SELECT vlocity_cmt__JSONAttribute__c FROM Product2 WHERE ProductCode = 'ENT_ETH_EIA_0002' LIMIT 1];
        prod.vlocity_cmt__JSONAttribute__c = qlis[0].vlocity_cmt__JSONAttribute__c;
        update prod;

        insert new Pricing_Formula_Var__c(
            Name = 'LitBuilding',
            Data_Type__c = 'Boolean',
            Field_API_Name__c = 'Boolean_1__c'
        );     


        insert new Pricing_Formula_Matrix__c(
            Product_Code__c = 'ENT_ETH_EIA_0002',
            Speed__c = 20,
            Term__c = 36,
            Formula_Name__c = 'Formula_0__c'
        );
        
        Test.startTest();
        
        PricingFormulaService pricingService = new PricingFormulaService();
        
        Map<String, object> priceHelperInput = new Map<String, object>{
                'productCode' => 'ENT_ETH_EIA_0002',
                'serviceAccountId' => qlis[0].vlocity_cmt__ServiceAccountId__c,
                'term' => '12 Months'
        };
        Map<String, object> priceHelperOutput = new Map<String, object>();
        Map<String, object> priceHelperOptions = new Map<String, object>();
        
        priceHelperInput.put('parent', parent);
        priceHelperInput.put('itemList', qlis);
        
        pricingService.invokeMethod('getAllPricingOptionsByTerm', priceHelperInput, priceHelperOutput, priceHelperOptions);

        System.debug('priceHelperOutput: ' + JSON.serialize(priceHelperOutput));
                
        Test.stopTest();
        
    }

    @IsTest
    static void testingPricingFormulaService2(){

        insert ftr_TestDataFactory.getQLI(1, 1);
        List<QuoteLineItem> qlis = [
            SELECT Id, vlocity_cmt__ServiceAccountId__c, Quantity, Term__c, Speed__c, vlocity_cmt__Product2Id__c, QuoteId, vlocity_cmt__BillingAccountId__c, 
            vlocity_cmt__LineNumber__c, Product2Id, vlocity_cmt__JSONAttribute__c, PricebookEntry.Product2.ProductCode
            FROM QuoteLineItem
        ];

        Quote parent = [select id, Service_Term__c from quote where id=:(Id)qlis[0].get('QuoteId')];
        
        Product2 prod = [SELECT vlocity_cmt__JSONAttribute__c FROM Product2 WHERE ProductCode = 'ENT_ETH_EIA_0002' LIMIT 1];
        prod.vlocity_cmt__JSONAttribute__c = qlis[0].vlocity_cmt__JSONAttribute__c;
        update prod;

        insert new Pricing_Formula_Var__c(
            Name = 'LitBuilding',
            Data_Type__c = 'Boolean',
            Field_API_Name__c = 'Boolean_1__c'
        );     


        insert new Pricing_Formula_Matrix__c(
            Product_Code__c = 'ENT_ETH_EIA_0002',
            Speed__c = 20,
            Term__c = 36,
            Formula_Name__c = 'Formula_0__c'
        );
        
        Test.startTest();
        
        PricingFormulaService pricingService = new PricingFormulaService();
        
        Map<String, object> priceHelperInput = new Map<String, object>{
                'productCode' => 'ENT_ETH_EIA_0002',
                'serviceAccountId' => qlis[0].vlocity_cmt__ServiceAccountId__c
        };
        Map<String, object> priceHelperOutput = new Map<String, object>();
        Map<String, object> priceHelperOptions = new Map<String, object>();
        
        priceHelperInput.put('parent', parent);
        priceHelperInput.put('itemList', qlis);
        
        pricingService.invokeMethod('GetAllPricingOptions', priceHelperInput, priceHelperOutput, priceHelperOptions);

        System.debug('priceHelperOutput: ' + JSON.serialize(priceHelperOutput));
                
        Test.stopTest();
        
    }

    @IsTest
    static void testingPricingFormulaService3(){

        insert ftr_TestDataFactory.getQLI(1, 1);
        List<QuoteLineItem> qlis = [
            SELECT Id, vlocity_cmt__ServiceAccountId__c, Quantity, Term__c, Speed__c, vlocity_cmt__Product2Id__c, QuoteId, vlocity_cmt__BillingAccountId__c, 
            vlocity_cmt__LineNumber__c, Product2Id, vlocity_cmt__JSONAttribute__c, PricebookEntry.Product2.ProductCode
            FROM QuoteLineItem
        ];

        Quote parent = [select id, Service_Term__c from quote where id=:(Id)qlis[0].get('QuoteId')];
        
        insert new Pricing_Formula_Var__c(
            Name = 'LitBuilding',
            Data_Type__c = 'Boolean',
            Field_API_Name__c = 'Boolean_1__c'
        );
        
        insert new Pricing_Formula_Matrix__c(
            Product_Code__c = 'ENT_ETH_EIA_0002',
            Speed__c = 20,
            Term__c = 36,
            Formula_Name__c = 'Formula_0__c'
        );
        
        Test.startTest();
        
        PricingFormulaService pricingService = new PricingFormulaService();
        
        Map<String, object> priceHelperInput = new Map<String, object>();
        Map<String, object> priceHelperOutput = new Map<String, object>();
        Map<String, object> priceHelperOptions = new Map<String, object>();
        
        priceHelperInput.put('parent', parent);
        priceHelperInput.put('itemList', qlis);
        
        pricingService.invokeMethod('CalculatePrice', priceHelperInput, priceHelperOutput, priceHelperOptions);

        System.debug('priceHelperOutput: ' + JSON.serialize(priceHelperOutput));
        
        //system.assert(priceHelperOutput.get('Error') != null, JSON.serialize(priceHelperOutput.get('Error')));
        
        Test.stopTest();
        
    }
    static testmethod void testIncrement() {
        Test.startTest();
        PricingFormulaService.justIncrement();       
        Test.stopTest(); 
 }
}