UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Expected_Billed_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Billed_Date__c</fullName>
    <label>Expected Billed Date</label>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/SterlingQuote__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Object</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/recordTypes/SFA.recordType-meta.xml
<RecordType>
    <fullName>SFA</fullName>
    <active>true</active>
    <description>For Quotes within the salesforce</description>
    <label>SFA</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/recordTypes/Sterling.recordType-meta.xml
<RecordType>
    <fullName>Sterling</fullName>
    <active>true</active>
    <description>For Quotes in Sterling</description>
    <label>Sterling</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/SterlingQuoteItem__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Item</description>
    <label>Quote Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>SterlingQuote__r.Account_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedMRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedMRC__c</fullName>
    <label>Adjusted MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedNRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedNRC__c</fullName>
    <label>Adjusted NRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/ApprovalRegion__c.field-meta.xml
<CustomField>
    <fullName>ApprovalRegion__c</fullName>
    <label>Approval Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ApprovalTerritory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>Mid-Atlantic</fullName>
            </value>
            <value>
                <fullName>Midwest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/ApprovalTerritory__c.field-meta.xml
<CustomField>
    <fullName>ApprovalTerritory__c</fullName>
    <label>ApprovalTerritory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Illinois-czn</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Iowa-czn</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/DiscountType__c.field-meta.xml
<CustomField>
    <fullName>DiscountType__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SVP</fullName>
            </value>
            <value>
                <fullName>RSM</fullName>
            </value>
            <value>
                <fullName>ICB</fullName>
            </value>
            <value>
                <fullName>CTR</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>ICBA</fullName>
            </value>
            <value>
                <fullName>CTRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/IsInFrontierFootprint__c.field-meta.xml
<CustomField>
    <fullName>IsInFrontierFootprint__c</fullName>
    <defaultValue>true</defaultValue>
    <label>IsInFrontierFootprint</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/ItemCode__c.field-meta.xml
<CustomField>
    <fullName>ItemCode__c</fullName>
    <defaultValue>&apos;0000&apos;</defaultValue>
    <label>Item Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <label>Locality</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/NPA__c.field-meta.xml
<CustomField>
    <fullName>NPA__c</fullName>
    <label>NPA</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/NXX__c.field-meta.xml
<CustomField>
    <fullName>NXX__c</fullName>
    <label>NXX</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>SterlingQuote__r.OpportunityId__r.Id</formula>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/StandardMRC__c.field-meta.xml
<CustomField>
    <fullName>StandardMRC__c</fullName>
    <label>Standard MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/StandardNRC__c.field-meta.xml
<CustomField>
    <fullName>StandardNRC__c</fullName>
    <label>Standard NRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/StateProvince__c.field-meta.xml
<CustomField>
    <fullName>StateProvince__c</fullName>
    <label>StateProvince</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/SterlingQuote__c.field-meta.xml
<CustomField>
    <fullName>SterlingQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>SterlingQuote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>SterlingQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/TermLength__c.field-meta.xml
<CustomField>
    <fullName>TermLength__c</fullName>
    <label>Term Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/recordTypes/SFA.recordType-meta.xml
<RecordType>
    <fullName>SFA</fullName>
    <active>true</active>
    <label>SFA</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/classes/AddProductController_Test.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 5
**/
@isTest
Private class AddProductController_Test {

    static testmethod void addProductControllertest(){
            // Get the RecordType Id of the 'Global' Account RecordType
            Id globalRecId = [
                SELECT  Id,
                        DeveloperName
                FROM    RecordType
                WHERE   SObjectType = 'Account'
                AND     DeveloperName = 'Global'
                LIMIT   1
            ]?.Id;

            // Create a new 'Global' Account with the above RecordType
            Account globalAcc1 = new Account(
                Name = 'GLOBAL ACCOUNT',
                RecordTypeId = globalRecId
            );
            insert globalAcc1;

            // Get the RecordType Id of the 'Master' Account RecordType
            Id masterRTId = [
                SELECT  Id,
                        DeveloperName
                FROM    RecordType
                WHERE   SObjectType = 'Account'
                AND     DeveloperName = 'Master'
                LIMIT   1
            ]?.Id;

            // Create a new 'Master' Account with the above RecordType and the 'Global' Account as its parent
            Account masterAcc = new Account(
                Name = 'Master Account',
                RecordTypeId = masterRTId,
                ParentId = globalAcc1.Id
            );

            insert masterAcc;

            opportunity objopportunity= new opportunity(AccountId=masterAcc.Id);
            objopportunity.Name ='testing opp';
            objopportunity.StageName='verbal commit';
            objopportunity.CloseDate= date.today();
            objopportunity.Expected_Billed_Date__c = date.today();
            insert objopportunity;
            SterlingQuote__c objSQ = new SterlingQuote__c();
            objSQ.Name='Testing Name';
            objSQ.ExpirationDate__c = date.today();
            objSQ.OpportunityId__c = objopportunity.Id;
            objSQ.Account_Name__c = masterAcc.id;
            //objSQ.CreatedById = userinfo.getUserId();
            insert objSQ;
            //call constructor
           //clsSelectedProducts  objPro= new clsSelectedProducts();
            Product2 objprod = new Product2();
            objprod.Name='testing product';
            // MMG 10/14/2014 added unit price
            objprod.UnitPrice__c = '15.00';
            insert objProd;
            ApexPages.currentPage().getParameters().put('strId',objProd.id);
            ApexPages.StandardController sc2 = new ApexPages.standardController(objProd);
            addproductController objPCon = new AddProductController(sc2);
            //objOppItemEdit.saveQuoteAndItem();
            //Call Class used to display information
            //OppItemEditController.clsSelectedProducts objSelectedProduct= new OppItemEditController.clsSelectedProducts();
            objPCon.closePopup();
        	objPCon.fetchOnlySearchProducts();

            Product2 objProduct2_1 = new Product2(
            Name ='Testing Name',
            IsActive=True,
            SKU__c='',
            Item_Code__c='Code',
            Item_Rate__c=10.00,
            Item_Type__c='A',
            ProductCode='1234',
            Grandfathered_Product__c='');
            insert objProduct2_1;

            PricebookEntry objPricebookEntry1= new PricebookEntry(
            UnitPrice=1000,
            pricebook2ID =Test.getStandardPricebookId(),
            IsActive = true,
            UseStandardPrice = false,
            Product2Id=objProduct2_1.Id
            );
            insert objPricebookEntry1;

            //objPCon.getAllOrSelectedProducts();
            //objOppItemEdit.getOnlySearchProducts();
            //when strSearchProduct != null
            Product2 objProduct2_2 = new Product2(
            Name='%Aid To Construction%',
            Item_Code__c='Code',
            Item_Rate__c=20.00,
            Item_Type__c='T',
            ProductCode='5678',
            Grandfathered_Product__c='');
            insert objProduct2_2;

            PricebookEntry objPricebookEntry2= new PricebookEntry(
            UnitPrice=1000,
            pricebook2ID =Test.getStandardPricebookId(),
            IsActive = true,
            UseStandardPrice = false,
            Product2Id=objProduct2_2.Id);
            insert objPricebookEntry2;

            objPCon.strSearchProduct='Aid To Construction';
            Product2 objProduct2_3 = new Product2(
            Name='%Product%',
            Family='CPE',
            Item_Code__c='code',
            Item_Rate__c=30.00,
            Item_Type__c='Y',
            ProductCode='9012',
            Grandfathered_Product__c='');
            insert objProduct2_3;
            PricebookEntry objPricebookEntry3= new PricebookEntry(
           // Name='price3',
            Pricebook2ID = Test.getStandardPricebookId(),
            unitprice = 1000,
            IsActive = true,
            UseStandardPrice = false,
            Product2Id=objProduct2_3.Id);
            insert objPricebookEntry3;

            objPCon.strSearchProduct='Product';
            objPCon.displayPopup=true;
            objPCon.bolVal=true;
            objPCon.bolShowRecords=true;
            objPCon.strOpportunityID ='testing';

            ApexPages.currentPage().getParameters().put('oppId',objopportunity.Id);
            objPCon.getProducts();
            objPCon.prdFirst();
            objPCon.prdLast();
            objPCon.prdPrevious();
            objPCon.prdNext();

            Boolean temp = objPCon.prdHasNext;
            temp = objPCon.prdHasPrevious;
            temp = objPCon.displayAddressGrid;

            SterlingQuoteItem__c objLineItem = new SterlingQuoteItem__c();
            objLineItem.Quantity__c=10;
            objLineItem.TermLength__c=24;
            objLineItem.StandardMRC__c = 10;
            objLineItem.StandardNRC__c = 10;
            objLineItem.AdjustedMRC__c = 10;
            objLineItem.AdjustedNRC__c = 10;
            objLineItem.Locality__c = 'Indiana';
            objLineItem.StateProvince__c ='IN';
            objLineItem.ItemCode__c ='123';
            objLineItem.ApprovalTerritory__c ='Indiana';
            objLineItem.ApprovalRegion__c='central';
            objLineItem.NPA__c ='10';
            objLineItem.NXX__c = '10';
            objLineItem.IsInFrontierFootprint__c = false;
            objLineItem.SterlingQuote__c = objSQ.id;
            insert objLineItem;

            List<RecordType> lstRT = [select id, name FROM RecordType WHERE DeveloperName = 'SFA' limit 1];
            ApexPages.currentPage().getParameters().put('strId','');
            ApexPages.StandardController sc = new ApexPages.standardController(objProd);
            AddproductController objOppItemEdit1 = new AddproductController (sc);
            List<AddproductController.clsSelectedProducts> tt = new List<AddproductController.clsSelectedProducts>();
            AddproductController.clsSelectedProducts objs = new AddproductController.clsSelectedProducts();
            objs.bolIsSelected=true;
            objs.strquantity ='10';
            objs.strunitprice = '10';
            objs.strRenewalMRC='10';
            objs.strNRC= '10';
            objs.strTerm ='10';
            objs.strCPENRC='10';
            objs.strCPEGross='10';
            objs.objSQI = objLineItem;
            tt.add(objs);

            String temp2 = objs.strMRC;
            temp2 = objs.strNRC1;
            temp2 = objs.RecordTypeId;

            AddproductController.clsSelectedProducts objs1 = new AddproductController.clsSelectedProducts();

            objs1.objSQI = objLineItem;
            objs1.bolIsSelected = true;
            tt.add(objs1);
/*
            objOppItemEdit1.fetchOnlySearchProducts();
            objOppItemEdit1.getOnlySelectedProducts();
            objOppItemEdit1.cancelProducts();
            objOppItemEdit1.sterlingQuoteItemList();
            objSQ.Name='Testing Name';
            objSQ.ExpirationDate__c = date.today();
            objSQ.OpportunityId__c = objopportunity.Id;
            objSQ.Account_Name__c = objAccount.id;
            update objSQ;

            objoppItemEdit1.saveQuoteAndItem();
            objOppItemEdit1.lstClsSelectedProductsToDB = tt;
            //objOppItemEdit1.strAddtype('test');
            objOppItemEdit1.saveProducts();
            objOppItemEdit1.lstClsSelectedProductsToDB = tt;
            objOppItemEdit1.strStateCode('test');

            objOppItemEdit1.getOnlySelectedProducts();
            ApexPages.currentPage().getParameters().put('oppId',objopportunity.Id);
*/
        }

    static testmethod void addProductControllertest2(){
        // Get the RecordType Id of the 'Global' Account RecordType
        Id globalRecId = [
            SELECT  Id,
                    DeveloperName
            FROM    RecordType
            WHERE   SObjectType = 'Account'
            AND     DeveloperName = 'Global'
            LIMIT   1
        ]?.Id;

        // Create a new 'Global' Account with the above RecordType
        Account globalAcc1 = new Account(
            Name = 'GLOBAL ACCOUNT',
            RecordTypeId = globalRecId
        );
        insert globalAcc1;

        // Get the RecordType Id of the 'Master' Account RecordType
        Id masterRTId = [
            SELECT  Id,
                    DeveloperName
            FROM    RecordType
            WHERE   SObjectType = 'Account'
            AND     DeveloperName = 'Master'
            LIMIT   1
        ]?.Id;

        // Create a new 'Master' Account with the above RecordType and the 'Global' Account as its parent
        Account masterAcc = new Account(
            Name = 'Master Account',
            RecordTypeId = masterRTId,
            ParentId = globalAcc1.Id
        );

        insert masterAcc;

        opportunity objopportunity= new opportunity(AccountId=masterAcc.Id);
        objopportunity.Name ='testing opp';
        objopportunity.StageName='verbal commit';
        objopportunity.CloseDate= date.today();
        objopportunity.Expected_Billed_Date__c = date.today();
        insert objopportunity;
        SterlingQuote__c objSQ = new SterlingQuote__c();
        objSQ.Name='Testing Name';
        objSQ.ExpirationDate__c = date.today();
        objSQ.OpportunityId__c = objopportunity.Id;
        objSQ.Account_Name__c = masterAcc.id;

        insert objSQ;
        Product2 objprod = new Product2();
        objprod.Name='testing product';
        objprod.UnitPrice__c = '15.00';
        insert objProd;

        Product2 objProduct2_1 = new Product2(
            Name ='Testing Name',
            IsActive=True,
            SKU__c='',
            Item_Code__c='Code',
            Item_Rate__c=10.00,
            Item_Type__c='A',
            ProductCode='1234',
            Grandfathered_Product__c='');
        insert objProduct2_1;

        PricebookEntry objPricebookEntry1= new PricebookEntry(
            UnitPrice=1000,
            pricebook2ID =Test.getStandardPricebookId(),
            IsActive = true,
            UseStandardPrice = false,
            Product2Id=objProduct2_1.Id
            );
        insert objPricebookEntry1;

        Product2 objProduct2_2 = new Product2(
            Name='%Aid To Construction%',
            Item_Code__c='Code',
            Item_Rate__c=20.00,
            Item_Type__c='T',
            ProductCode='5678',
            Grandfathered_Product__c='');
        insert objProduct2_2;

        PricebookEntry objPricebookEntry2= new PricebookEntry(
            UnitPrice=1000,
            pricebook2ID =Test.getStandardPricebookId(),
            IsActive = true,
            UseStandardPrice = false,
            Product2Id=objProduct2_2.Id);
        insert objPricebookEntry2;

        Product2 objProduct2_3 = new Product2(
            Name='%Product%',
            Family='CPE',
            Item_Code__c='code',
            Item_Rate__c=30.00,
            Item_Type__c='Y',
            ProductCode='9012',
            Grandfathered_Product__c='');
        insert objProduct2_3;
        PricebookEntry objPricebookEntry3= new PricebookEntry(
            Pricebook2ID = Test.getStandardPricebookId(),
            unitprice = 1000,
            IsActive = true,
            UseStandardPrice = false,
            Product2Id=objProduct2_3.Id);
        insert objPricebookEntry3;

        ApexPages.currentPage().getParameters().put('oppId',objopportunity.Id);

        SterlingQuoteItem__c objLineItem = new SterlingQuoteItem__c();
        objLineItem.Quantity__c=10;
        objLineItem.TermLength__c=24;
        objLineItem.StandardMRC__c = 10;
        objLineItem.StandardNRC__c = 10;
        objLineItem.AdjustedMRC__c = 10;
        objLineItem.AdjustedNRC__c = 10;
        objLineItem.Locality__c = 'Indiana';
        objLineItem.StateProvince__c ='IN';
        objLineItem.ItemCode__c ='123';
        objLineItem.ApprovalTerritory__c ='Indiana';
        objLineItem.ApprovalRegion__c='central';
        objLineItem.NPA__c ='10';
        objLineItem.NXX__c = '10';
        objLineItem.IsInFrontierFootprint__c = false;
        objLineItem.SterlingQuote__c = objSQ.id;
        insert objLineItem;

        List<RecordType> lstRT = [select id, name FROM RecordType WHERE DeveloperName = 'SFA' limit 1];
        ApexPages.currentPage().getParameters().put('strId','');
        ApexPages.StandardController sc = new ApexPages.standardController(objProd);
        AddproductController objOppItemEdit1 = new AddproductController (sc);
        List<AddproductController.clsSelectedProducts> tt = new List<AddproductController.clsSelectedProducts>();
        AddproductController.clsSelectedProducts objs = new AddproductController.clsSelectedProducts();
        objs.bolIsSelected=true;
        objs.strquantity ='10';
        objs.strunitprice = '10';
        objs.strRenewalMRC='10';
        objs.strNRC= '10';
        objs.strTerm ='10';
        objs.strCPENRC='10';
        objs.strCPEGross='10';
        objs.objSQI = objLineItem;
        tt.add(objs);

        String temp2 = objs.strMRC;
        temp2 = objs.strNRC1;
        temp2 = objs.RecordTypeId;

        AddproductController.clsSelectedProducts objs1 = new AddproductController.clsSelectedProducts();

        objs1.objSQI = objLineItem;
        objs1.bolIsSelected = true;
        tt.add(objs1);
        //objOppItemEdit1.fetchOnlySearchProducts();
        objOppItemEdit1.getOnlySelectedProducts();
        objOppItemEdit1.cancelProducts();
        objOppItemEdit1.sterlingQuoteItemList();
        objSQ.Name='Testing Name';
        objSQ.ExpirationDate__c = date.today();
        objSQ.OpportunityId__c = objopportunity.Id;
        objSQ.Account_Name__c = masterAcc.id;
        update objSQ;

        objoppItemEdit1.saveQuoteAndItem();
        objOppItemEdit1.lstClsSelectedProductsToDB = tt;
        objOppItemEdit1.saveProducts();
        objOppItemEdit1.lstClsSelectedProductsToDB = tt;
        objOppItemEdit1.strStateCode('test');

        objOppItemEdit1.getOnlySelectedProducts();
        ApexPages.currentPage().getParameters().put('oppId',objopportunity.Id);
    }


        /**
            This test method tests miscellaneous functionalities of the AddProductController class
        */

        static testmethod void addProductControllerMisc(){
            // Get the RecordType Id of the 'Global' Account RecordType
            Id globalRecId = [
                SELECT  Id,
                        DeveloperName
                FROM    RecordType
                WHERE   SObjectType = 'Account'
                AND     DeveloperName = 'Global'
                LIMIT   1
            ]?.Id;

            // Create a new 'Global' Account with the above RecordType
            Account globalAcc = new Account(
                Name = 'GLOBAL ACCOUNT',
                RecordTypeId = globalRecId
            );
            insert globalAcc;

            // Get the RecordType Id of the 'Master' Account RecordType
            Id masterRTId = [
                SELECT  Id,
                        DeveloperName
                FROM    RecordType
                WHERE   SObjectType = 'Account'
                AND     DeveloperName = 'Master'
                LIMIT   1
            ]?.Id;

            // Create a new 'Master' Account with the above RecordType and the 'Global' Account as its parent
            Account masterAcc = new Account(
                Name = 'Master Account',
                RecordTypeId = masterRTId,
                ParentId = globalAcc.Id
            );

            insert masterAcc;

            //Id standardPricebookId = Test.getStandardPricebookId(); // Replace
            Pricebook2 standardPricebook = new Pricebook2(
                Id = Test.getStandardPricebookId(),
                IsActive = true
            );
            update standardPricebook;

            standardPricebook = [SELECT IsStandard FROM Pricebook2 WHERE Id = :standardPricebook.Id];
            opportunity objOpportunity= new opportunity(
                AccountId=masterAcc.Id,
                Name ='testing opp',
                StageName='verbal commit',
                CloseDate= date.today(),
                Expected_Billed_Date__c = date.today(),
                Pricebook2Id = standardPricebook.Id
            );
            insert objOpportunity;

            SterlingQuote__c objSQ = new SterlingQuote__c(
                Name='Testing Name',
                ExpirationDate__c = date.today(),
                OpportunityId__c = objOpportunity.Id,
                Account_Name__c = masterAcc.id
            );
            insert objSQ;

            Product2 objProdWithUnitPrice = new Product2(
                Name='testing product',
                UnitPrice__c = '15.00'
            );
            insert objProdWithUnitPrice;

            Product2 objProdTest = new Product2(
                Name ='Testing Name',
                IsActive=True,
                Item_Code__c='Code',
                Item_Rate__c=10.00,
                Item_Type__c='A',
                ProductCode='1234',
                Grandfathered_Product__c='');
            insert objProdTest;

            PricebookEntry objPricebookEntryWithTestProduct= new PricebookEntry(
                UnitPrice=1000,
                pricebook2ID = standardPricebook.Id,
                IsActive = true,
                UseStandardPrice = false,
                Product2Id=objProdTest.Id
                );
            insert objPricebookEntryWithTestProduct;

            Product2 objProdAidToConstruction = new Product2(
                Name='%Aid To Construction%',
                Item_Code__c='Code',
                Item_Rate__c=20.00,
                Item_Type__c='T',
                ProductCode='5678',
                Grandfathered_Product__c='');
            insert objProdAidToConstruction;

            PricebookEntry objPricebookEntryWithACProduct= new PricebookEntry(
                UnitPrice=1000,
                pricebook2ID = standardPricebook.Id,
                IsActive = true,
                UseStandardPrice = false,
                Product2Id=objProdAidToConstruction.Id);
            insert objPricebookEntryWithACProduct;

            Product2 objProdProduct = new Product2(
                Name='%Product%',
                Family='CPE',
                Item_Code__c='code',
                Item_Rate__c=30.00,
                Item_Type__c='Y',
                ProductCode='9012',
                Grandfathered_Product__c='');
            insert objProdProduct;

            PricebookEntry objPricebookEntryWithProdProduct= new PricebookEntry(
                Pricebook2ID = standardPricebook.Id,
                unitprice = 1000,
                IsActive = true,
                UseStandardPrice = false,
                Product2Id=objProdProduct.Id);
            insert objPricebookEntryWithProdProduct;

            ApexPages.currentPage().getParameters().put('oppId',objOpportunity.Id);

            Test.startTest();
            SterlingQuoteItem__c objLineItem = new SterlingQuoteItem__c(
                Quantity__c=10,
                TermLength__c=24,
                DiscountType__c = 'SVP',
                StandardMRC__c = 10,
                StandardNRC__c = 10,
                AdjustedMRC__c = 10,
                AdjustedNRC__c = 10,
                Locality__c = 'Indiana',
                StateProvince__c ='IN',
                ItemCode__c ='123',
                ApprovalTerritory__c ='Indiana',
                ApprovalRegion__c='central',
                NPA__c ='10',
                NXX__c = '10',
                IsInFrontierFootprint__c = false,
                SterlingQuote__c = objSQ.id
            );
            insert objLineItem;

            List<RecordType> lstRT = [select id, name FROM RecordType WHERE DeveloperName = 'SFA' limit 1];
            ApexPages.currentPage().getParameters().put('strId','');
            ApexPages.StandardController sc = new ApexPages.standardController(objProdWithUnitPrice);
            ApexPages.currentPage().getParameters().put('addressType','Legal');
            Addproductcontroller objOppItemEdit = new Addproductcontroller (sc);
            List<Addproductcontroller.clsSelectedProducts> selectedProdList = new List<Addproductcontroller.clsSelectedProducts>();

            Addproductcontroller.clsSelectedProducts selectedProd = new Addproductcontroller.clsSelectedProducts();
            selectedProd.bolIsSelected=true;
            selectedProd.strQuantity ='10';
            selectedProd.strUnitPrice = '10';
            selectedProd.strRenewalMRC='10';
            selectedProd.strNRC= '10';
            selectedProd.strUnitPrice1 = '10';
            selectedProd.strTerm ='10';
            selectedProd.strCPENRC='10';
            selectedProd.strCPEGross='10';
            selectedProd.objSQI = objLineItem;
            selectedProd.strProductCategory = 'CPE';
            selectedProdList.add(selectedProd);

            String strMRC = selectedProd.strMRC;
            strMRC = selectedProd.strNRC1;
            strMRC = selectedProd.RecordTypeId;

            objOppItemEdit.getOnlySelectedProducts();
            objOppItemEdit.cancelProducts();
            objOppItemEdit.getOnlySelectedProducts();
            objOppItemEdit.lstClsSelectedProductsToDB = selectedProdList;
            List < SterlingQuoteItem__c > objLineItemList = objOppItemEdit.sterlingQuoteItemList();
            Assert.isNotNull(objLineItemList, 'Sterling Line Item object should not be null');
            objSQ.Name='Testing Name';
            objSQ.ExpirationDate__c = date.today();
            objSQ.OpportunityId__c = objOpportunity.Id;
            objSQ.Account_Name__c = masterAcc.id;
            update objSQ;

            objOppItemEdit.saveQuoteAndItem();
            objOppItemEdit.lstClsSelectedProductsToDB = selectedProdList;
            objOppItemEdit.saveProducts();
            objOppItemEdit.lstClsSelectedProductsToDB = selectedProdList;
            String strStateCodeString = objOppItemEdit.strStateCode('test');
            Assert.isNull(strStateCodeString, 'State Code string should be null'); 
            objOppItemEdit.getOnlySelectedProducts();
            Test.stopTest();

        }
    }