UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Account_Channel__c.field-meta.xml
<CustomField>
    <fullName>Account_Channel__c</fullName>
    <label>Account Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Connected Community</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>VZ3 Agreements</fullName>
            </value>
            <value>
                <fullName>Alternate Channel</fullName>
            </value>
            <value>
                <fullName>Contact Center</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Spring_Folder_Name__c.field-meta.xml
<CustomField>
    <fullName>Spring_Folder_Name__c</fullName>
    <formula>Name + &quot; - &quot; +  Spring_Folder_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Spring Folder Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Broadband, FiOS &amp; Voice Bundles</fullName>
                <label>Broadband, FiberOptic &amp; Voice Bundles - Existing/Upgrades</label>
            </value>
            <value>
                <fullName>Broadband, FiOS &amp; Voice Bundles - New Service</fullName>
                <label>Broadband, FiberOptic &amp; Voice Bundles - New Service</label>
            </value>
            <value>
                <fullName>Current Broadband Offers</fullName>
            </value>
            <value>
                <fullName>Ethernet/Data Services</fullName>
                <label>Ethernet/Transport Services</label>
            </value>
            <value>
                <fullName>FSA 1 Page</fullName>
            </value>
            <value>
                <fullName>FSA Standard Full Version</fullName>
            </value>
            <value>
                <fullName>Local Services</fullName>
            </value>
            <value>
                <fullName>Managed Services</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>Premier Retail LOA</fullName>
            </value>
            <value>
                <fullName>Premier Retail LOA-MDF</fullName>
            </value>
            <value>
                <fullName>SAA</fullName>
            </value>
            <value>
                <fullName>Twenty-Twenty LOA-MDF</fullName>
            </value>
            <value>
                <fullName>VAL</fullName>
            </value>
            <value>
                <fullName>VoIP</fullName>
            </value>
            <value>
                <fullName>Wi-Fi</fullName>
                <label>Wireless Solutions</label>
            </value>
            <value>
                <fullName>PAL</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>PAL-Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing Agreement</fullName>
            </value>
            <value>
                <fullName>Door to Door LOA-MDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>Bulk_Res</fullName>
                <default>true</default>
                <label>Bulk Res</label>
            </value>
            <value>
                <fullName>BULK-EMA</fullName>
            </value>
            <value>
                <fullName>Bulk Corp</fullName>
            </value>
            <value>
                <fullName>EMA</fullName>
            </value>
            <value>
                <fullName>EMA-DOORFEEONLY</fullName>
            </value>
            <value>
                <fullName>EMA-DOOR-REVSHARE</fullName>
            </value>
            <value>
                <fullName>EMA-REVSHAREONLY</fullName>
            </value>
            <value>
                <fullName>NEMA</fullName>
            </value>
            <value>
                <fullName>No Contract</fullName>
            </value>
            <value>
                <fullName>PAL</fullName>
            </value>
            <value>
                <fullName>Markeing</fullName>
            </value>
            <value>
                <fullName>PAL-Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Spring_Folder_Name__c.field-meta.xml
<CustomField>
    <fullName>Spring_Folder_Name__c</fullName>
    <formula>Name + &quot;-&quot; + Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Spring Folder Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/aps_GenerateDocument.cls
/**
 * @description       :
 * @author            : Monir Zaman
 * @group             :
 * @last modified on  : 19-01-2024
 * @last modified by  : Monir Zaman
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   19-01-2024   Monir Zaman   Initial Version
 **/
public with sharing class aps_GenerateDocument {
  public aps_GenerateDocument() {
  }

  @AuraEnabled
  public static List<Opportunity> wholesaleData(Id rId) {
    return [
      SELECT Id, Spring_Folder_Name__c, Account.Spring_Folder_Name__c
      FROM Opportunity
      WHERE Id = :rId
    ];
  }

  @AuraEnabled
  public static List<Contract> mtuData(Id rId) {
    return [
      SELECT
        Id,
        Spring_Contract_Folder_Name__c,
        Account_Channel__c,
        Agreement_Type__c
      FROM Contract
      WHERE Id = :rId
    ];
  }

  @AuraEnabled
  public static List<Contract> mduData(Id rId) {
    return [
      SELECT Id, Spring_Folder_Name__c, Account_Channel__c, Agreement_Type__c
      FROM Contract
      WHERE Id = :rId
    ];
  }
}