UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_City__c.field-meta.xml
<CustomField>
    <fullName>Legal_City__c</fullName>
    <label>Legal City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_State__c.field-meta.xml
<CustomField>
    <fullName>Legal_State__c</fullName>
    <label>Legal State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_Street__c.field-meta.xml
<CustomField>
    <fullName>Legal_Street__c</fullName>
    <label>Legal Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Expected_Billed_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Billed_Date__c</fullName>
    <label>Expected Billed Date</label>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/SterlingQuote__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Object</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/recordTypes/SFA.recordType-meta.xml
<RecordType>
    <fullName>SFA</fullName>
    <active>true</active>
    <description>For Quotes within the salesforce</description>
    <label>SFA</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/SterlingQuoteItem__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Item</description>
    <label>Quote Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>SterlingQuote__r.Account_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedMRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedMRC__c</fullName>
    <label>Adjusted MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedNRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedNRC__c</fullName>
    <label>Adjusted NRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/ApprovalRegion__c.field-meta.xml
<CustomField>
    <fullName>ApprovalRegion__c</fullName>
    <label>Approval Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ApprovalTerritory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>Mid-Atlantic</fullName>
            </value>
            <value>
                <fullName>Midwest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/ApprovalRouting__c.field-meta.xml
<CustomField>
    <fullName>ApprovalRouting__c</fullName>
    <label>ApprovalRouting</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Build</fullName>
            </value>
            <value>
                <fullName>Customer Build - SMB Only</fullName>
            </value>
            <value>
                <fullName>Customer Build - Wireless</fullName>
            </value>
            <value>
                <fullName>Renewal / Special Pricing</fullName>
            </value>
            <value>
                <fullName>Renewal / Special Pricing - SMB Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/ApprovalTerritory__c.field-meta.xml
<CustomField>
    <fullName>ApprovalTerritory__c</fullName>
    <label>ApprovalTerritory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Illinois-czn</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Iowa-czn</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/DiscountType__c.field-meta.xml
<CustomField>
    <fullName>DiscountType__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SVP</fullName>
            </value>
            <value>
                <fullName>RSM</fullName>
            </value>
            <value>
                <fullName>ICB</fullName>
            </value>
            <value>
                <fullName>CTR</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>ICBA</fullName>
            </value>
            <value>
                <fullName>CTRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/IsInFrontierFootprint__c.field-meta.xml
<CustomField>
    <fullName>IsInFrontierFootprint__c</fullName>
    <defaultValue>true</defaultValue>
    <label>IsInFrontierFootprint</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/MinorLine__c.field-meta.xml
<CustomField>
    <fullName>MinorLine__c</fullName>
    <label>Minor Line #</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>SterlingQuote__r.OpportunityId__r.Id</formula>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/OverallStatus__c.field-meta.xml
<CustomField>
    <fullName>OverallStatus__c</fullName>
    <label>OverallStatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>INA Accepted</fullName>
            </value>
            <value>
                <fullName>INA Rejected</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Pending - Business Decision Support</fullName>
            </value>
            <value>
                <fullName>Pending - Credit</fullName>
            </value>
            <value>
                <fullName>Pending - Engineering Wireless</fullName>
            </value>
            <value>
                <fullName>Pending - Engineering Wireless Final</fullName>
            </value>
            <value>
                <fullName>Pending - Finance</fullName>
            </value>
            <value>
                <fullName>Pending - INA</fullName>
            </value>
            <value>
                <fullName>Pending - Post Completion Audit Finance</fullName>
            </value>
            <value>
                <fullName>Pending - Post Completion Audit Originator</fullName>
            </value>
            <value>
                <fullName>Pending - Post Engineering Originator</fullName>
            </value>
            <value>
                <fullName>Pending - Post Engineering originator Wireless</fullName>
            </value>
            <value>
                <fullName>Pending - Regional President</fullName>
            </value>
            <value>
                <fullName>Pending - Sales Engineering</fullName>
            </value>
            <value>
                <fullName>Pending - Site Verification</fullName>
            </value>
            <value>
                <fullName>Pending - State VP</fullName>
            </value>
            <value>
                <fullName>Pending - Wireless Management</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending SIFT Status</fullName>
            </value>
            <value>
                <fullName>Pending SIFT Status-ON HOLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/StandardMRC__c.field-meta.xml
<CustomField>
    <fullName>StandardMRC__c</fullName>
    <label>Standard MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/StandardNRC__c.field-meta.xml
<CustomField>
    <fullName>StandardNRC__c</fullName>
    <label>Standard NRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/SterlingQuote__c.field-meta.xml
<CustomField>
    <fullName>SterlingQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>SterlingQuote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>SterlingQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/recordTypes/SFA.recordType-meta.xml
<RecordType>
    <fullName>SFA</fullName>
    <active>true</active>
    <label>SFA</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/classes/QuoteExtension_Test.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 7
**/
@isTest
private class QuoteExtension_Test{
    static  testMethod  void  QuoteExtensionEdit2() {
        // Get the RecordType Id of the 'Global' Account RecordType
        Id globalRecId = [
            SELECT  Id,
                    DeveloperName
            FROM    RecordType
            WHERE   SObjectType = 'Account'
            AND     DeveloperName = 'Global'
            LIMIT   1
        ]?.Id;
        // Create a new 'Global' Account with the above RecordType
        Account globalAcc1 = new Account(
            Name = 'GLOBAL ACCOUNT',
            RecordTypeId = globalRecId
        );
        insert globalAcc1;

        Account objAcc = new Account();
        objAcc.ParentId = globalAcc1.Id;
        objAcc.Name ='testing Name';
        objAcc.Legal_Street__c='test';
        objAcc.Legal_City__c='test';
        objAcc.Legal_State__c='test';
        objAcc.ShippingStreet='test';
        objAcc.ShippingCity='NY';
        objAcc.ShippingState='New York';
        objAcc.BillingStreet='test';
        objAcc.BillingCity='NY';
        objAcc.BillingState='New York';
        
        insert objAcc;
        
        Opportunity objOpp = new Opportunity();
        objOpp.Name ='Testing Name';
        objOpp.AccountId= objAcc.Id;
        objOpp.CloseDate = date.today();
        objOpp.StageName ='Verbal Commit';
        objOpp.Expected_Billed_Date__c = date.today();
        insert objOpp;
        
        list<RecordType> recordtypeid = [SELECT BusinessProcessId,DeveloperName,Id,Name,SobjectType FROM RecordType WHERE DeveloperName = 'SFA' AND SobjectType = 'SterlingQuote__c'];        
        SterlingQuote__c objquote = new SterlingQuote__c();
        objquote.Name='Testing Name';
        objquote.ExpirationDate__c=date.today();
        objquote.OpportunityId__c=objOpp.id;
        objquote.Account_Name__c= objAcc.Id;
        objquote.RecordTypeId = recordtypeid[0].Id; 
        //objquote.MinorLine__c = 0;
        insert objquote;      

        Id standardPB = Test.getStandardPricebookId();
        Product2 objProduct2_1 = new Product2(
            Name ='Testing Name',
            IsActive=True,
            SKU__c='',
            Item_Code__c='Code',
            Item_Rate__c=10.00,
            MajorProduct__c=true,
            Item_Type__c='A',
            ProductCode='1234',
            Grandfathered_Product__c='');
        insert objProduct2_1;

        PricebookEntry objPricebookEntry1= new PricebookEntry(
            UnitPrice=1000,
            pricebook2ID =standardPB,
            IsActive = true,
            UseStandardPrice = false,
            Product2Id=objProduct2_1.Id
        );
        insert objPricebookEntry1;

        list<SterlingQuoteItem__c> objSQi = new list<SterlingQuoteItem__c>();
        SterlingQuoteItem__c objst = new SterlingQuoteItem__c();
        objst.name='test';
        objst.SterlingQuote__c = objquote.id;
        objst.IsInFrontierFootprint__c=false;
        objst.OverallStatus__c ='pending';
        objst.DiscountType__c ='ICB';
        objst.ApprovalTerritory__c ='Indiana';
        objst.ApprovalRouting__c='Customer Build';
        objst.ApprovalRegion__c='IN';
        objst.StandardMRC__c= 10.00;
        objst.StandardNRC__c=10.00;
        objst.AdjustedMRC__c=10.00;
        objst.AdjustedNRC__c=10.00;
        objst.Quantity__c=10;
        objst.Products__c=objProduct2_1.id;
        objst.OwnerId= userinfo.getUserId(); 
        objst.ItemOwner__c =userinfo.getUserId();
        objst.ApprovalPriority__c='Normal';
        objst.Locality__c='Indiana'; 
        objst.StateProvince__c='IN' ;
        //objst.State__c='IN';  10/16 raj
        objst.NXX__c='10';
        
        objst.SetNextApprover__c= true;
        objst.OverallStatus__c='';
        objst.SIFT_Required__c=true;
        objst.SIFT_InquiryId__c='1234';
        objst.NetNewMRR__c=10.00;
        insert objst;
        objsqi.add(objst);
        Test.startTest();
        ApexPages.currentPage().getParameters().put('Id',objquote.Id);
        ApexPages.StandardController sc = new ApexPages.standardController(objquote);
        Quote_Extension objQuoteExtension = new Quote_Extension(sc);
        objQuoteExtension.redirectToNewSfaProduct(); 
        objQuoteExtension.reDirectToSFAQuote();
        apexpages.currentpage().getparameters().put('id',objQuote.id);
        objQuoteExtension.editAction(); 
        objQuoteExtension.showPopup();
        objQuoteExtension.SaveCustom();
        objQuoteExtension.StrQuote = objquote.Id;
        objQuoteExtension.deleteCustom();
        objQuoteExtension.ShowCreateOrderButton = true;
        objQuoteExtension.ShowLaunchEONButton = true;
        objQuoteExtension.LaunchEON();
        Test.stopTest();
    }
    static  testMethod  void  QuoteExtensionEdit() { 
        // Get the RecordType Id of the 'Global' Account RecordType
        Id globalRecId = [
            SELECT  Id,
                    DeveloperName
            FROM    RecordType
            WHERE   SObjectType = 'Account'
            AND     DeveloperName = 'Global'
            LIMIT   1
        ]?.Id;
        // Create a new 'Global' Account with the above RecordType
        Account globalAcc1 = new Account(
            Name = 'GLOBAL ACCOUNT',
            RecordTypeId = globalRecId
        );
        insert globalAcc1;

        Account objAcc = new Account();
        objAcc.ParentId = globalAcc1.Id;
        objAcc.Name ='testing Name';
        objAcc.Legal_Street__c='test';
        objAcc.Legal_City__c='test';
        objAcc.Legal_State__c='test';
        objAcc.ShippingStreet='test';
        objAcc.ShippingCity='NY';
        objAcc.ShippingState='New York';
        objAcc.BillingStreet='test';
        objAcc.BillingCity='NY';
        objAcc.BillingState='New York';
        
        insert objAcc;
        
        Opportunity objOpp = new Opportunity();
        objOpp.Name ='Testing Name';
        objOpp.AccountId= objAcc.Id;
        objOpp.CloseDate = date.today();
        objOpp.StageName ='Verbal Commit';
        objOpp.Expected_Billed_Date__c = date.today();
        insert objOpp;
        
        list<RecordType> recordtypeid = [SELECT BusinessProcessId,DeveloperName,Id,Name,SobjectType FROM RecordType WHERE DeveloperName = 'SFA' AND SobjectType = 'SterlingQuote__c'];        
        SterlingQuote__c objquote = new SterlingQuote__c();
        objquote.Name='Testing Name';
        objquote.ExpirationDate__c=date.today();
        objquote.OpportunityId__c=objOpp.id;
        objquote.Account_Name__c= objAcc.Id;
        objquote.RecordTypeId = recordtypeid[0].Id; 
        //objquote.MinorLine__c = 0;
        insert objquote;      
        
        Id standardPB = Test.getStandardPricebookId();
        Product2 objProduct2_1 = new Product2(
            Name ='Testing Name',
            IsActive=True,
            SKU__c='',
            Item_Code__c='Code',
            Item_Rate__c=10.00,
            MajorProduct__c=true,
            Item_Type__c='A',
            ProductCode='1234',
            Grandfathered_Product__c='');
        insert objProduct2_1;
        
        PricebookEntry objPricebookEntry1= new PricebookEntry(
            UnitPrice=1000,
            pricebook2ID =standardPB,
            IsActive = true,
            UseStandardPrice = false,
            Product2Id=objProduct2_1.Id
        );
        insert objPricebookEntry1;        
        
        list<SterlingQuoteItem__c> objSQi = new list<SterlingQuoteItem__c>();
        SterlingQuoteItem__c objst = new SterlingQuoteItem__c();
        objst.name='test';
        objst.SterlingQuote__c = objquote.id;
        objst.IsInFrontierFootprint__c=false;
        objst.OverallStatus__c ='pending';
        objst.DiscountType__c ='ICB';
        objst.ApprovalTerritory__c ='Indiana';
        objst.ApprovalRouting__c='Customer Build';
        objst.ApprovalRegion__c='IN';
        objst.StandardMRC__c= 10.00;
        objst.StandardNRC__c=10.00;
        objst.AdjustedMRC__c=10.00;
        objst.AdjustedNRC__c=10.00;
        objst.Quantity__c=10;
        objst.Products__c=objProduct2_1.id;
        objst.OwnerId= userinfo.getUserId(); 
        objst.ItemOwner__c =userinfo.getUserId();
        objst.ApprovalPriority__c='Normal';
        objst.Locality__c='Indiana'; 
        objst.StateProvince__c='IN' ;
        //objst.State__c='IN';  10/16 raj
        objst.NXX__c='10';
        
        objst.SetNextApprover__c= true;
        objst.OverallStatus__c='';
        objst.SIFT_Required__c=true;
        objst.SIFT_InquiryId__c='1234';
        objst.NetNewMRR__c=10.00;
        insert objst;
        objsqi.add(objst);
        
        
        Test.startTest();
        // list<recordtype> lstrType =[select id from recordType where developerName ='SFA' And SobjectType='Sterlinquote__c'];       
        // objquote.RecordTypeId = lstrType[0].Id; 
        ApexPages.currentPage().getParameters().put('Id',objquote.Id);
        ApexPages.StandardController sc = new ApexPages.standardController(objquote);
        Quote_Extension objQuoteExtension = new Quote_Extension(sc);
        objQuoteExtension.BackCustom();
        objQuoteExtension.closePopup();
        ObjQuoteExtension.ClosePopUpCreateOrder();
        //ObjQuoteExtension.createOrder();
        objQuoteExtension.getSterlingQuoteItems();
        objQuoteExtension.getRecordType();
        objQuoteExtension.editQuoteItemMethod();
        Quote_Extension.productSync(objquote.Id,objquote);
        ObjQuoteExtension.deleteCustom();
        //ObjQuoteExtension.deleteAction();
        // ObjQuoteExtension.CreateOrder();
        Test.stopTest();
        
    }
    
    static  testMethod  void  QuoteExtensionEdit3() { 
        // Get the RecordType Id of the 'Global' Account RecordType
        Id globalRecId = [
            SELECT  Id,
                    DeveloperName
            FROM    RecordType
            WHERE   SObjectType = 'Account'
            AND     DeveloperName = 'Global'
            LIMIT   1
        ]?.Id;
        // Create a new 'Global' Account with the above RecordType
        Account globalAcc1 = new Account(
            Name = 'GLOBAL ACCOUNT',
            RecordTypeId = globalRecId
        );
        insert globalAcc1;

        Account objAcc = new Account();
        objAcc.ParentId = globalAcc1.Id;
        objAcc.Name ='testing Name';
        objAcc.Legal_Street__c='test';
        objAcc.Legal_City__c='test';
        objAcc.Legal_State__c='test';
        objAcc.ShippingStreet='test';
        objAcc.ShippingCity='NY';
        objAcc.ShippingState='New York';
        objAcc.BillingStreet='test';
        objAcc.BillingCity='NY';
        objAcc.BillingState='New York';
        
        insert objAcc;
        
        Opportunity objOpp = new Opportunity();
        objOpp.Name ='Testing Name';
        objOpp.AccountId= objAcc.Id;
        objOpp.CloseDate = date.today();
        objOpp.StageName ='Verbal Commit';
        objOpp.Expected_Billed_Date__c = date.today();
        insert objOpp;
        
        list<RecordType> recordtypeid = [SELECT BusinessProcessId,DeveloperName,Id,Name,SobjectType FROM RecordType WHERE DeveloperName = 'SFA' AND SobjectType = 'SterlingQuote__c'];        
        SterlingQuote__c objquote = new SterlingQuote__c();
        objquote.Name='Testing Name';
        objquote.ExpirationDate__c=date.today();
        objquote.OpportunityId__c=objOpp.id;
        objquote.Account_Name__c= objAcc.Id;
        objquote.RecordTypeId = recordtypeid[0].Id; 
        //objquote.MinorLine__c = 0;
        insert objquote;      
        
        Id standardPB = Test.getStandardPricebookId();
        Product2 objProduct2_1 = new Product2(
            Name ='Testing Name',
            IsActive=True,
            SKU__c='',
            Item_Code__c='Code',
            Item_Rate__c=10.00,
            MajorProduct__c=true,
            Item_Type__c='A',
            ProductCode='1234',
            Grandfathered_Product__c='');
        insert objProduct2_1;
        
        PricebookEntry objPricebookEntry1= new PricebookEntry(
            UnitPrice=1000,
            pricebook2ID =standardPB,
            IsActive = true,
            UseStandardPrice = false,
            Product2Id=objProduct2_1.Id
        );
        insert objPricebookEntry1;        
        
        list<SterlingQuoteItem__c> objSQi = new list<SterlingQuoteItem__c>();
        SterlingQuoteItem__c objst = new SterlingQuoteItem__c();
        objst.name='test';
        objst.SterlingQuote__c = objquote.id;
        objst.IsInFrontierFootprint__c=false;
        objst.OverallStatus__c ='pending';
        objst.DiscountType__c ='ICB';
        objst.ApprovalTerritory__c ='Indiana';
        objst.ApprovalRouting__c='Customer Build';
        objst.ApprovalRegion__c='IN';
        objst.StandardMRC__c= 10.00;
        objst.StandardNRC__c=10.00;
        objst.AdjustedMRC__c=10.00;
        objst.AdjustedNRC__c=10.00;
        objst.Quantity__c=10;
        objst.Products__c=objProduct2_1.id;
        objst.OwnerId= userinfo.getUserId(); 
        objst.ItemOwner__c =userinfo.getUserId();
        objst.ApprovalPriority__c='Normal';
        objst.Locality__c='Indiana'; 
        objst.StateProvince__c='IN' ;
        //objst.State__c='IN';  10/16 raj
        objst.NXX__c='10';
        
        objst.SetNextApprover__c= true;
        objst.OverallStatus__c='';
        objst.SIFT_Required__c=true;
        objst.SIFT_InquiryId__c='1234';
        objst.NetNewMRR__c=10.00;
        insert objst;
        objsqi.add(objst);
        
        Test.startTest();
        ApexPages.currentPage().getParameters().put('Id',objquote.Id);
        ApexPages.StandardController sc = new ApexPages.standardController(objquote);
        Quote_Extension objQuoteExtension = new Quote_Extension(sc);
        objQuoteExtension.productSyncClick();
        objQuoteExtension.productUnSyncClick();
        Test.stopTest();
    }
    
}