UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/BTN__c.field-meta.xml
<CustomField>
    <fullName>BTN__c</fullName>
    <label>BTN</label>
    <type>Phone</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/DPI.recordType-meta.xml
<RecordType>
    <fullName>DPI</fullName>
    <active>true</active>
    <description>Represents DPI Account</description>
    <label>DPI</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Case/fields/BTN__c.field-meta.xml
<CustomField>
    <fullName>BTN__c</fullName>
    <label>BTN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Case/fields/Customer_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Requested_Date__c</fullName>
    <label>Customer Requested Date</label>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Case/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Used on the SFA Code Maintenance case for Billing to add products to Salesforce 2/18/2020 case 00590949</description>
    <inlineHelpText>Please enter the data exactly as it should appear as the Product Name.</inlineHelpText>
    <label>Product Name</label>
    <type>TextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Case/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ASE</fullName>
            </value>
            <value>
                <fullName>ATM/Frame Relay</fullName>
            </value>
            <value>
                <fullName>Broadband</fullName>
            </value>
            <value>
                <fullName>Centrex</fullName>
            </value>
            <value>
                <fullName>Cloud Managed</fullName>
            </value>
            <value>
                <fullName>DDS</fullName>
            </value>
            <value>
                <fullName>Digital Channel Service</fullName>
            </value>
            <value>
                <fullName>DS0</fullName>
            </value>
            <value>
                <fullName>DS1</fullName>
            </value>
            <value>
                <fullName>DS3</fullName>
            </value>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>ELAN</fullName>
            </value>
            <value>
                <fullName>E-Reach</fullName>
            </value>
            <value>
                <fullName>Ethernet</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>EVPL w/managed Router</fullName>
            </value>
            <value>
                <fullName>FiOS</fullName>
                <label>FiberOptic</label>
            </value>
            <value>
                <fullName>FIOS/DSL</fullName>
            </value>
            <value>
                <fullName>ISDN BRI</fullName>
            </value>
            <value>
                <fullName>ISDN PRI</fullName>
            </value>
            <value>
                <fullName>OneVoice</fullName>
            </value>
            <value>
                <fullName>OPTEMAN</fullName>
            </value>
            <value>
                <fullName>OtherVoice</fullName>
            </value>
            <value>
                <fullName>POTS</fullName>
            </value>
            <value>
                <fullName>PRI</fullName>
            </value>
            <value>
                <fullName>SD WAN</fullName>
            </value>
            <value>
                <fullName>SIP/IP Connect</fullName>
            </value>
            <value>
                <fullName>UCaaS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Case/fields/Sales_Order_Point_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Point_of_Contact__c</fullName>
    <label>Sales Order Point of Contact</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Case/fields/Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Service_Address__c</fullName>
    <label>Service Address</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Unable to Verify</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/ftr_DID_Location_Details__c.object-meta.xml
<CustomObject>
    <label>DID Location Details</label>
    <nameField>
        <label>DID Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Location Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/BTN__c.field-meta.xml
<CustomField>
    <fullName>BTN__c</fullName>
    <label>Billing Number (BTN)</label>
    <type>Phone</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/Email_List__c.field-meta.xml
<CustomField>
    <fullName>Email_List__c</fullName>
    <label>Email List</label>
    <type>TextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/Location_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Location_Due_Date__c</fullName>
    <label>Location Due Date</label>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/Service_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Name__c</fullName>
    <formula>ServiceAccountId__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Account Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Location_Contact__c/Location_Contact__c.object-meta.xml
<CustomObject>
    <label>Location Contact</label>
    <nameField>
        <label>Location Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Location_Contact__c/fields/Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Contact_Phone__c</fullName>
    <formula>Contact__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Phone</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Location_Contact__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Location Contacts</relationshipLabel>
    <relationshipName>Location_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <inlineHelpText>Who to notify of Firm Order Confirmation -FOC</inlineHelpText>
    <label>Contact Email (FOC)</label>
    <type>Email</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Customer_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Requested_Date__c</fullName>
    <label>Customer Requested Date</label>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/ftrImplementationSpecialistName__c.field-meta.xml
<CustomField>
    <fullName>ftrImplementationSpecialistName__c</fullName>
    <label>Implementation Specialist Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Hot_Cut__c.field-meta.xml
<CustomField>
    <fullName>Hot_Cut__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hot Cut</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Managers_Name__c.field-meta.xml
<CustomField>
    <fullName>Managers_Name__c</fullName>
    <formula>CreatedBy.Manager_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Managers Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Network_Project_Specialist__c.field-meta.xml
<CustomField>
    <fullName>Network_Project_Specialist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Transport Project Manager</inlineHelpText>
    <label>Implementation Specialist</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <errorMessage>User profile does not match the filter criteria.</errorMessage>
        <filterItems>
            <field>User.profileName__c</field>
            <operation>equals</operation>
            <value>#Project Manager</value>
        </filterItems>
        <filterItems>
            <field>User.profileName__c</field>
            <operation>equals</operation>
            <value>#Project Manager - Supervisor Level</value>
        </filterItems>
        <filterItems>
            <field>User.profileName__c</field>
            <operation>equals</operation>
            <value>#Provisioning</value>
        </filterItems>
        <filterItems>
            <field>User.profileName__c</field>
            <operation>equals</operation>
            <value>#Hot Cut Service Consultants</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders6</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Sales_Order_Point_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Point_of_Contact__c</fullName>
    <formula>Opportunity.Owner.Account_Owner_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order Point of Contact</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/vlocity_cmt__OneTimeTotal__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__OneTimeTotal__c</fullName>
    <label>Total: One Time Charges</label>
    <summarizedField>OrderItem.vlocity_cmt__OneTimeTotal__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/Service_Order__c.object-meta.xml
<CustomObject>
    <description>This is the DPI Service Order(s) that are related to the associated order</description>
    <label>Service Order</label>
    <nameField>
        <label>Service Order #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Service Orders</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/System_Order_Info__c/System_Order_Info__c.object-meta.xml
<CustomObject>
    <label>System Order Info</label>
    <nameField>
        <label>System Order Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Order Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/System_Order_Info__c/fields/Email_List__c.field-meta.xml
<CustomField>
    <fullName>Email_List__c</fullName>
    <label>Email List</label>
    <type>TextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/System_Order_Info__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>System Order Infos</relationshipLabel>
    <relationshipName>System_Order_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/System_Order_Info__c/fields/Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Service_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Address</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>System Order Infos</relationshipLabel>
    <relationshipName>System_Order_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/System_Order_Info__c/fields/WTN__c.field-meta.xml
<CustomField>
    <fullName>WTN__c</fullName>
    <label>WTN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/TaskSendEmailAction.cls
public class TaskSendEmailAction {
    
    @InvocableMethod(label='Send DPI Order Email' category='Vlocity CLM')
    public static List<EmailReturnData> sendEmailExpectedUser(List<EmailSendData> emailData){
        
        List<EmailReturnData> results = new List<EmailReturnData>();
        EmailReturnData emailReturn = new EmailReturnData();
        
        //get task recordType Ids for D1 and DC	
        Id dC711RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('DC_711_Order').getRecordTypeId();
        Id dI711RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('D1_711_Order').getRecordTypeId();
        
        //get task Id
        Task t = [Select Id,Priority,WhatId,Owner.Name,Description,Status,Subject,RecordTypeId from Task where Id =:emailData[0].taskId];
        String serviceLocationName = emailData[0].serviceLocationName;
        System.debug('serviceLocationName ::'+serviceLocationName);
        
        //When Task is DI 711 
        if(t.RecordTypeId == dI711RecordTypeId && t.WhatId !=null)
        {
            Order o =[Select Id ,OrderNumber,Customer_Requested_Date__c,Account_Name__c,Sales_Order_Point_of_Contact__c,Network_Project_Specialist__r.Name from Order where Id=:t.WhatId];
            List<Location_Contact__c> locContact = [Select Id,Contact_Email__c,Contact_Phone__c,Name from Location_Contact__c where Order__c=:t.WhatId];
            List<ftr_DID_Location_Details__c> didLocations = [Select Id ,Email_List__c,ServiceAccountId__r.Name from ftr_DID_Location_Details__c where OrderId__c =:t.WhatId];
            List<OrderItem> orderItemUCF = [Select Id,SNE_Code_MRC__c,vlocity_cmt__ServiceAccountId__r.Name,
                                            vlocity_cmt__ServiceAccountId__r.BTN__c, SNE_Code_OTC__c, 
                                            Quantity, vlocity_cmt__RecurringCharge__c, vlocity_cmt__OneTimeCharge__c,
                                            vlocity_cmt__Product2Id__r.Name 
                                            from OrderItem where OrderId=:t.WhatId 
                                            AND vlocity_cmt__ServiceAccountId__r.Name =:serviceLocationName
                                            AND vlocity_cmt__Product2Id__r.Name !='UCF DID DPI Services'
                                            AND vlocity_cmt__Product2Id__r.Name !='UCF DC 711'];
            List<Messaging.SingleEmailMessage> allMail = new List<Messaging.SingleEmailMessage>();
            List<OrgWideEmailAddress> Org = [SELECT id FROM OrgWideEmailAddress WHERE DisplayName = 'Frontier Communication' limit 1];
            system.debug(' :: Org '+Org);  
            
            //Due Date Work
            Date originalDate = Date.today();
            Datetime dt = (DateTime)originalDate;
            Date newDate;
            String BTN='';
            String ProductName;
            String dayOfWeek = dt.format('EEEE');
            if(dayOfWeek == 'Friday'){
                newDate = originalDate.addDays(3);
            }else{
                
                newDate = originalDate.addDays(2);
                
            }
            
            String dueDate = String.ValueOf(newDate);
            List<ftr_DID_Location_Details__c> addEmails = new List<ftr_DID_Location_Details__c>();
            List<String> emailList = emailData[0].EmailTo.split(',');
            
            for (ftr_DID_Location_Details__c emails : didLocations) {
                if (serviceLocationName == emails.ServiceAccountId__r.Name) {
                    // Join the emailList into a single comma-separated string
                    emails.Email_List__c = String.join(emailList, ',');
                    addEmails.add(emails);
                }
            }
            
            if (!addEmails.isEmpty()) {
                update addEmails;
            }
            System.Debug('addEmails:'+ addEmails);
            
            String orderItemTable = '<table border="1px"><tr><th style="text-align: left;">Product Name</th><th>Quantity</th><th>Recurring Charge</th><th>OneTime Charge</th></tr>';
            for(OrderItem ord:orderItemUCF){
                
                if(ord.vlocity_cmt__ServiceAccountId__r.BTN__c !=null && ord.vlocity_cmt__ServiceAccountId__r.BTN__c !='') {
                    BTN = ord.vlocity_cmt__ServiceAccountId__r.BTN__c;
                }
                orderItemTable += '<tr><td>' + ord.vlocity_cmt__Product2Id__r.Name + '</td><td>'+ord.Quantity+'</td><td>'+ord.vlocity_cmt__RecurringCharge__c+'</td><td>'+ord.vlocity_cmt__OneTimeCharge__c+'</td></tr>';
                
            }
            orderItemTable += '</table>';
            // Location Contact Work
            
            String locationContactTable = '<table border="1px"><tr><th>Name</th><th>Email</th><th>Phone</th></tr>';
            for(Location_Contact__c conLoc: locContact){
                locationContactTable += '<tr><td>' + conLoc.Name + '</td><td>'+conLoc.Contact_Email__c+'</td><td>'+conLoc.Contact_Phone__c+'</td></tr>';
                
            }
            locationContactTable += '</table>';
            //Email Template Work
            EmailTemplate emailTemp = [Select Id,HtmlValue,Subject From EmailTemplate Where Name = 'DI 711 Order Detail' Limit 1];
            system.debug(' :: emailTemp '+emailTemp); 
            String Subject = 'Site Survey -'+'UCF '+o.OrderNumber+' - '+serviceLocationName;
            string defaultEmailContent = '';
            defaultEmailContent = emailTemp.HtmlValue;
            defaultEmailContent = defaultEmailContent.replace('{!PMName}', o.Network_Project_Specialist__r != null ? o.Network_Project_Specialist__r.Name : '');
            defaultEmailContent = defaultEmailContent.replace('{!OrderNumber}', o.OrderNumber != null ? o.OrderNumber : '');
            defaultEmailContent = defaultEmailContent.replace('{!BillingTelephoneNumber}', BTN != null ? BTN : '');
            defaultEmailContent = defaultEmailContent.replace('{!Duedate}', dueDate != null ? dueDate : '');
            defaultEmailContent = defaultEmailContent.replace('{!ServiceAddress}', serviceLocationName != null ? serviceLocationName : '');
            defaultEmailContent = defaultEmailContent.replace('{!LocationContact}', locationContactTable != null ? locationContactTable : '');
            defaultEmailContent = defaultEmailContent.replace('{!OrderItem}', orderItemTable != null ? orderItemTable : '');
            
            //List<String> emailList = emailData[0].EmailTo.split(',');
            for (Integer i = 0; i < emailList.size(); i++) {
                emailList[i] = emailList[i].trim();
            }
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            // List<string> sendTo = new List<string>();
            //sendTo.add(emailList);
            mail.setToAddresses(emailList);
            // system.debug(' :: sendTo' + sendTo);
            mail.setOrgWideEmailAddressId(Org[0].Id);
            mail.setHtmlBody(defaultEmailContent);
            mail.setSubject(Subject);
            mail.setWhatId(t.WhatId);
            mail.saveAsActivity = true;
            //mail.setEntityAttachments(emailData[0].fileIds);
            allMail.add(mail);     
            
            if(!allMail.isEmpty()) 
            {
                system.debug(' :: allMail' + allMail);
                t.Status ='Completed';
                update t;
                Messaging.sendEmail(allMail,false); 
            }	
            
        }
        
        else if(t.RecordTypeId == dC711RecordTypeId && t.WhatId !=null)//When Task is DC 711 
        {
            
            Order o =[Select Id ,BillingCity,vlocity_cmt__OneTimeTotal__c,Managers_Name__c,BillingState, 
                      OrderNumber,Customer_Requested_Date__c,Account_Name__c,Sales_Order_Point_of_Contact__c,
                      CreatedDate, Account.BTN__c,ftrImplementationSpecialistName__c, Hot_Cut__r.Name 
                      from Order where Id=:t.WhatId];
            List<ftr_DID_Location_Details__c> didLocations = [Select Id ,ServiceAccountId__r.Name,Service_Account_Name__c,DueDate__c,Email_List__c, Location_Due_Date__c from ftr_DID_Location_Details__c where OrderId__c =:t.WhatId];
            List<System_Order_Info__c> wtnNumber = [select Id, Service_Address__r.Name, WTN__c from System_Order_Info__c where Order__c=:t.WhatId];
            List<OrderItem> orderItemUCF = [Select Id,Product_Name__c,vlocity_cmt__ServiceAccountId__r.Name,vlocity_cmt__ServiceAccountId__r.BTN__c, 
                                            SNE_Code_OTC__c, Quantity, vlocity_cmt__RecurringCharge__c, vlocity_cmt__OneTimeCharge__c 
                                            from OrderItem where OrderId=:t.WhatId AND vlocity_cmt__ServiceAccountId__r.Name =:serviceLocationName
                                            AND ( Product_Type__c = 'Phones' OR Product_Type__c = 'Accessories' OR Product_Type__c = 'Installation')];
            List<Account> serviceAccount = [Select Id, Name, ShippingCity, ShippingState from Account];
            List<Service_Order__c> serviceOrders = [select Id,Name,Order__c,RecordType.Name  from Service_Order__c  where Order__c =:t.WhatId];
            List<Messaging.SingleEmailMessage> allMail = new List<Messaging.SingleEmailMessage>();
            List<OrgWideEmailAddress> Org = [SELECT id FROM OrgWideEmailAddress WHERE DisplayName = 'Frontier Communication' limit 1];
            system.debug(' :: Org '+Org);
            //List<OrderItem> installationChargesOI =[SELECT vlocity_cmt__OneTimeCharge__c FROM OrderItem WHERE OrderId = :t.WhatId AND SNE_Code_OTC__c = 'AWLBR' AND vlocity_cmt__ServiceAccountId__r.Name =:serviceLocationName Limit 1];
            //oneTimeTotal
            //String oneTimeTotal = String.valueOf(installationChargesOI.vlocity_cmt__OneTimeCharge__c);
            // Initialize a default value
            //String oneTimeTotal = '0';
            
            // Check if any records were retrieved
            //if (!installationChargesOI.isEmpty()) {
                //OrderItem firstRecord = installationChargesOI[0];
                // Check if vlocity_cmt__OneTimeCharge__c is not null before converting to String
                //if (firstRecord.vlocity_cmt__OneTimeCharge__c != null) {
                    //oneTimeTotal = String.valueOf(firstRecord.vlocity_cmt__OneTimeCharge__c);
                //}
            //}
            List<OrderItem> installationChargesOI = [SELECT Quantity, vlocity_cmt__OneTimeCharge__c FROM OrderItem WHERE OrderId = :t.WhatId AND SNE_Code_OTC__c = 'AWLBR' AND vlocity_cmt__ServiceAccountId__r.Name = :serviceLocationName LIMIT 1];
            
            // Initialize a default value
            Decimal oneTimeTotal = 0;
            
            // Check if any records were retrieved
            if (!installationChargesOI.isEmpty()) {
                OrderItem firstRecord = installationChargesOI[0];
                
                // Check if vlocity_cmt__OneTimeCharge__c is not null before performing multiplication
                if (firstRecord.vlocity_cmt__OneTimeCharge__c != null) {
                    // Multiply the one-time charge with the quantity
                    oneTimeTotal = firstRecord.vlocity_cmt__OneTimeCharge__c * firstRecord.Quantity;
                }
            }
            
            // Set scale to 2 decimal places
            oneTimeTotal = oneTimeTotal.setScale(2, System.RoundingMode.HALF_UP);
            
            // Convert the result to String
            String oneTimeTotalAsString = String.valueOf(oneTimeTotal);
            
            Date dueDate = null;
            String emailAddresses = '';
            
            for (ftr_DID_Location_Details__c did : didLocations) {
                system.debug('serviceLocationName ::' + serviceLocationName);
                if (serviceLocationName == did.Service_Account_Name__c) {
                    system.debug('did ::'+ did);
                    dueDate = did.DueDate__c;
                    emailAddresses = did.Email_List__c;
                    
                } 
            }
            
            //WTN number
            String wtnNum = '';
            for(System_Order_Info__c wtnn:wtnNumber){
                if(serviceLocationName == wtnn.Service_Address__r.Name){
                    wtnNum = wtnn.WTN__c;
                }
                //else{
                    //wtnNum = '';
                //}
            }
            
            //serviceLocationCityState
            String serviceLocationCityState = '';
            for(Account serAcc:serviceAccount){
                if(serviceLocationName == serAcc.Name){
                    serviceLocationCityState = serAcc.ShippingCity + ', ' + serAcc.ShippingState;
                    system.debug('serviceLocationName ::' + serviceLocationName);
                }
                //else{
                    //serviceLocationCityState = '';
                //}
            }
            
            //Service Order Number
            String dpiServiceOrder = '';
            String infiniumServiceOrder = '';
            List<String> infiniumReqOrderNumbers = new List<String>();
            for(Service_Order__c sOrder:serviceOrders){
                if(sOrder.RecordType.Name == 'DPI Service Order'){
                    dpiServiceOrder = sOrder.Name;
                }
                else if(sOrder.RecordType.Name == 'Infinium REQ'){
                    infiniumServiceOrder = sOrder.Name;
                    infiniumReqOrderNumbers.add(infiniumServiceOrder);
                }
                else{
                    dpiServiceOrder = '';
                    infiniumServiceOrder = '';
                }
            }
            // Convert the list of Infinium REQ order numbers to a comma-separated string
            String infiniumReqNumbersString = String.join(infiniumReqOrderNumbers, ',');
            
            String BTN='';
            String hotCutUser = (o.Hot_Cut__r != null) ? o.Hot_Cut__r.Name : '';
            String implementationSpecialistUser = (o.ftrImplementationSpecialistName__c != null) ? o.ftrImplementationSpecialistName__c : '';
            
            
            // Convert the Date to a String using the format() method
            String formattedDueDate = (dueDate != null) ? String.valueOf(dueDate.month()) + '/' + String.valueOf(dueDate.day()) + '/' + String.valueOf(dueDate.year()) : '';
            // Phones and Assesories Work
            String orderItemTable = '<table border="1px"><tr><th style="text-align: left;">Product Name</th><th>Quantity</th><th>Recurring Charge</th><th>OneTime Charge</th></tr>';
            for(OrderItem ord:orderItemUCF){
                
                if(ord.vlocity_cmt__ServiceAccountId__r.BTN__c !=null && ord.vlocity_cmt__ServiceAccountId__r.BTN__c !='') {
                    BTN = ord.vlocity_cmt__ServiceAccountId__r.BTN__c;
                }
                orderItemTable += '<tr><td>' + ord.Product_Name__c + '</td><td>'+ord.Quantity+'</td><td>'+ord.vlocity_cmt__RecurringCharge__c+'</td><td>'+ord.vlocity_cmt__OneTimeCharge__c+'</td></tr>';
                
            }
            orderItemTable += '</table>';
            
            //Email Template Work
            EmailTemplate emailTemp = [Select Id,HtmlValue,Subject From EmailTemplate Where Name = 'DC 711 Order Detail' Limit 1];
            
            String Subject =  'WIP UCF - '+o.Account_Name__c+' - '+o.OrderNumber;
            string defaultEmailContent = '';
            defaultEmailContent = emailTemp.HtmlValue;
            defaultEmailContent = defaultEmailContent.replace('{!ImplementationSpecialist}', o.ftrImplementationSpecialistName__c != null ? o.ftrImplementationSpecialistName__c : '');
            defaultEmailContent = defaultEmailContent.replace('{!HotCut}', hotCutUser != null ? hotCutUser : '');
            defaultEmailContent = defaultEmailContent.replace('{!DPINumber}', wtnNum != null ? wtnNum : '');
            defaultEmailContent = defaultEmailContent.replace('{!BTNNumber}', BTN != null ? BTN : '');
            defaultEmailContent = defaultEmailContent.replace('{!OrderAccount}', o.Account_Name__c != null ? o.Account_Name__c : '');
            defaultEmailContent = defaultEmailContent.replace('{!OrderNumber}', o.OrderNumber != null ? o.OrderNumber : '');
            defaultEmailContent = defaultEmailContent.replace('{!OneTimeTotal}', oneTimeTotalAsString != null ? oneTimeTotalAsString : '');
            defaultEmailContent = defaultEmailContent.replace('{!Duedate}', formattedDueDate != null ? formattedDueDate : '');
            defaultEmailContent = defaultEmailContent.replace('{!ServiceAdderess}', serviceLocationCityState != null ? serviceLocationCityState : '');
            defaultEmailContent = defaultEmailContent.replace('{Order.Sales_Order_Point_of_Contact__c}', o.Sales_Order_Point_of_Contact__c != null ? o.Sales_Order_Point_of_Contact__c : '');
            defaultEmailContent = defaultEmailContent.replace('{!OrderCreatedDate}', o.CreatedDate != null ? o.CreatedDate.formatGMT('MM/dd/YYYY') : '');
            defaultEmailContent = defaultEmailContent.replace('{!OrderItem}', orderItemTable != null ? orderItemTable : '');
            defaultEmailContent = defaultEmailContent.replace('{!EmailList}', emailAddresses != null ? emailAddresses : '');
            defaultEmailContent = defaultEmailContent.replace('{!ManagerName}', o.Managers_Name__c != null ? o.Managers_Name__c : '');
            defaultEmailContent = defaultEmailContent.replace('{!DPIOrderNumber}', dpiServiceOrder != null ? dpiServiceOrder : '');
            defaultEmailContent = defaultEmailContent.replace('{!InfiniumOrderNumber}', infiniumReqNumbersString != null ? infiniumReqNumbersString : '');
            System.Debug('emailData' + emailData);
            System.Debug('defaultEmailContent' + defaultEmailContent);
            List<String> emailList = emailData[0].EmailTo.split(',');
            for (Integer i = 0; i < emailList.size(); i++) {
                emailList[i] = emailList[i].trim();
            }
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(emailList);
            mail.setOrgWideEmailAddressId(Org[0].Id);
            mail.setHtmlBody(defaultEmailContent);
            mail.setSubject(Subject);
            mail.setWhatId(t.WhatId);
            mail.saveAsActivity = true;
            mail.setEntityAttachments(emailData[0].fileIds);
            allMail.add(mail);     
            
            if(!allMail.isEmpty()) 
            {
                system.debug(' :: allMail' + allMail);
                t.Status ='Completed';
                update t;
                //Messaging.sendEmail(allMail,false); 
            }
            try {
                Messaging.sendEmail(allMail, false);
            } catch (Exception e) {
                System.debug('Error sending email: ' + e.getMessage());
            }
            
            
        }
        
        emailReturn.success = true;
        results.add(emailReturn);
        return results;
    }
    
    
    @AuraEnabled
    public static List<Id> storeContentVersions(Id orderId, String b64) {
        
        // Check if PMEnrichment file already exists for the orderId
        if (!pmEnrichmentFileExists(orderId)) {
            // Check if Order's stage is 'Hot Cut'
            if (orderStageIsInProgress(orderId)) {
                System.debug('orderId: ' + orderId);
                ContentVersion cv = new ContentVersion();
                cv.title = 'PMEnrichment';
                cv.PathOnClient = 'PMEnrichment.xlsx';
                Blob content = EncodingUtil.base64Decode(b64);
                cv.VersionData = content;
                cv.ContentLocation = 'S';
                insert cv;
                
                Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id].ContentDocumentId;
                
                ContentDocumentLink cdl = new ContentDocumentLink();
                cdl.LinkedEntityId = orderId;
                cdl.ContentDocumentId = conDocId;
                cdl.ShareType = 'I';
                insert cdl;
                
                List<Id> contentVersionIds = new List<Id>();
                contentVersionIds.add(cv.Id);
                return contentVersionIds;
            } else {
                // Order's stage is not 'Hot Cut', handle accordingly (e.g., log, throw exception, etc.)
                System.debug('Order stage is not Hot Cut for orderId: ' + orderId);
                // You might want to handle this case based on your specific requirements
                return new List<Id>();
            }
        } else {
            // PMEnrichment file already exists, handle accordingly (e.g., log, throw exception, etc.)
            System.debug('PMEnrichment file already exists for orderId: ' + orderId);
            // You might want to handle this case based on your specific requirements
            return new List<Id>();
        }
    }

    
    // Helper method to check if PMEnrichment file already exists for the given orderId
    private static Boolean pmEnrichmentFileExists(Id orderId) {
        Integer existingFiles = [SELECT COUNT() FROM ContentDocumentLink WHERE LinkedEntityId = :orderId AND ContentDocument.LatestPublishedVersion.Title = 'PMEnrichment'];
        return existingFiles > 0;
    }
    
    // Helper method to check if Order's stage is 'Hot Cut'
    private static Boolean orderStageIsInProgress(Id orderId) {
        Order orderRecord = [SELECT Order_Stage__c FROM Order WHERE Id =:orderId LIMIT 1];
        return orderRecord.Order_Stage__c == 'In Progress';
    }



    
    public class EmailSendData{
        
        @InvocableVariable(required=true)
        public string EmailTo;
        
        @InvocableVariable(required=true)
        public string taskId;
        
        @InvocableVariable(required=true)
        public string serviceLocationName;
        
        @InvocableVariable(label='File Ids *ContentVersionId, AttchmentId or DocumentId')
        public String[] fileIds;
    }
    
    public class EmailReturnData{
        
        @InvocableVariable(required=true)
        public Boolean success;
        
        
    }
    
}