UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract_Template_List__c/Contract_Template_List__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contract_Template_List for CLM</description>
    <label>Contract_Template_List</label>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract_Template_List__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <description>Agreement Type for CLM</description>
    <label>Agreement Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract_Template_List__c/fields/Schedule_Type__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Type__c</fullName>
    <description>Template Schedule Type for CLM</description>
    <label>Schedule Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract_Template_List__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <description>Template Name for CLM. This template should exist in Document Template (vlocity_cmt__DocumentTemplateId__c)</description>
    <label>Template Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>Bulk_Res</fullName>
                <default>true</default>
                <label>Bulk Res</label>
            </value>
            <value>
                <fullName>BULK-EMA</fullName>
            </value>
            <value>
                <fullName>Bulk Corp</fullName>
            </value>
            <value>
                <fullName>EMA</fullName>
            </value>
            <value>
                <fullName>EMA-DOORFEEONLY</fullName>
            </value>
            <value>
                <fullName>EMA-DOOR-REVSHARE</fullName>
            </value>
            <value>
                <fullName>EMA-REVSHAREONLY</fullName>
            </value>
            <value>
                <fullName>NEMA</fullName>
            </value>
            <value>
                <fullName>No Contract</fullName>
            </value>
            <value>
                <fullName>PAL</fullName>
            </value>
            <value>
                <fullName>Markeing</fullName>
            </value>
            <value>
                <fullName>PAL-Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/CPE_Product__c.field-meta.xml
<CustomField>
    <fullName>CPE_Product__c</fullName>
    <description>Asks Users to check whether a product in the opportunity is a CPE product.</description>
    <inlineHelpText>Must select if a CPE product is a component of the Opportunity being created.</inlineHelpText>
    <label>CPE Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Product2/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <description>Agreement Type</description>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Agreement_Types</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Product2/fields/Schedule_Type__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Type__c</fullName>
    <description>Schedule Type</description>
    <label>Schedule Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Schedule_Types</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/IsSyncing__c.field-meta.xml
<CustomField>
    <fullName>IsSyncing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for the vlocity hybrid quote initiative. Determines whether the quote is synced with the opportunity.</description>
    <label>IsSyncing</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/Service_Term__c.field-meta.xml
<CustomField>
    <fullName>Service_Term__c</fullName>
    <label>Service Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12 Months</fullName>
            </value>
            <value>
                <fullName>24 Months</fullName>
            </value>
            <value>
                <fullName>36 Months</fullName>
            </value>
            <value>
                <fullName>60 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <description>Agreement Type used for CLM Template Selection</description>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Agreement_Types</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/IsSyncing__c.field-meta.xml
<CustomField>
    <fullName>IsSyncing__c</fullName>
    <formula>Quote.IsSyncing__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsSyncing</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>Quote.OpportunityId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Schedule_Type__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Type__c</fullName>
    <description>Schedule Type used for CLM Template Selection</description>
    <label>Schedule Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Schedule_Types</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>Bound to Attribute = Term</description>
    <label>Term</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DEPRECATED, Use the standard Product2Id field.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__RootItemId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__RootItemId__c</fullName>
    <description>ID of the ultimate, top-level parent Quote Line Item. Used by Vlocity CPQ to track a full tree of items.</description>
    <label>RootItemId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account that identifies the service location or subscriber that is the user of the service.</description>
    <label>Service Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>ServiceAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/SterlingQuote__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Object</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/IsSyncing__c.field-meta.xml
<CustomField>
    <fullName>IsSyncing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/SterlingQuoteItem__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Item</description>
    <label>Quote Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>SterlingQuote__r.Account_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedMRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedMRC__c</fullName>
    <label>Adjusted MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedNRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedNRC__c</fullName>
    <label>Adjusted NRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <description>Agreement Type for CLM</description>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Agreement_Types</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/ItemCode__c.field-meta.xml
<CustomField>
    <fullName>ItemCode__c</fullName>
    <defaultValue>&apos;0000&apos;</defaultValue>
    <label>Item Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <label>Locality</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>SterlingQuote__r.OpportunityId__r.Id</formula>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Schedule_Type__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Type__c</fullName>
    <description>Schedule Type for CLM</description>
    <label>Schedule Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Schedule_Types</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/StandardMRC__c.field-meta.xml
<CustomField>
    <fullName>StandardMRC__c</fullName>
    <label>Standard MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/StandardNRC__c.field-meta.xml
<CustomField>
    <fullName>StandardNRC__c</fullName>
    <label>Standard NRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/StateProvince__c.field-meta.xml
<CustomField>
    <fullName>StateProvince__c</fullName>
    <label>StateProvince</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/SterlingQuote__c.field-meta.xml
<CustomField>
    <fullName>SterlingQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>SterlingQuote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>SterlingQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/TermLength__c.field-meta.xml
<CustomField>
    <fullName>TermLength__c</fullName>
    <label>Term Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/globalValueSets/Agreement_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Broadband FiberOptic &amp; Voice Bundles - Existing/Upgrades</fullName>
    </customValue>
    <customValue>
        <fullName>Broadband FiberOptic &amp; Voice Bundles - New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Do Not Add</fullName>
    </customValue>
    <customValue>
        <fullName>E911</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment (CPE)</fullName>
    </customValue>
    <customValue>
        <fullName>Ethernet/Data Services</fullName>
        <label>Ethernet/Transport Services</label>
    </customValue>
    <customValue>
        <fullName>Local Service (Core products)</fullName>
    </customValue>
    <customValue>
        <fullName>Managed Services</fullName>
    </customValue>
    <customValue>
        <fullName>Manual</fullName>
    </customValue>
    <customValue>
        <fullName>Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>TV Services</fullName>
    </customValue>
    <customValue>
        <fullName>VoIP</fullName>
    </customValue>
    <customValue>
        <fullName>Wireless</fullName>
    </customValue>
    <customValue>
        <fullName>BHSI and FSUV Schedule</fullName>
    </customValue>
    <customValue>
        <fullName>BHSI and OneVoice Schedule</fullName>
    </customValue>
    <customValue>
        <fullName>FiberOffice and OneVoice Schedule CT Business</fullName>
    </customValue>
    <customValue>
        <fullName>FiberOptic Broadband and OneVoice Schedule Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Frontier Business Xtreme</fullName>
    </customValue>
    <customValue>
        <fullName>FiberOffice and OneVoice Schedule Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Voice - Internet Product Schedule for CA-TX-FL</fullName>
    </customValue>
    <customValue>
        <fullName>Business Local-LD Schedule Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Broadband and OneVoice Schedule CT</fullName>
    </customValue>
    <customValue>
        <fullName>Broadband and FSUV Schedule CT</fullName>
    </customValue>
    <description>Agreement Types for CLM</description>
    <masterLabel>Agreement Types</masterLabel>
</GlobalValueSet>

UCF-APR2.4/ftr main/force-app/main/default/classes/ftr_CLMCreateContractsFromAccountTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 2 
 * 
**/
@IsTest
public class ftr_CLMCreateContractsFromAccountTest{

    @IsTest
    public static void testinvokeMethod(){
        User userObj = [Select Id from User where profile.Name = 'Frontier System Administrator' AND IsActive=true LIMIT 1];
        System.runAs(userObj){
        Contract_Template_List__c template = new Contract_Template_List__c();
        template.Name = 'CLM_TMPL_00010';
        template.Schedule_Type__c = 'FiberOptic & OneVoice Nationwide (copper)';
        template.Agreement_Type__c = 'Broadband FiberOptic & Voice Bundles - New Service';
        template.Template_Name__c = 'Fiber and OneVoice Schedule';
        insert template;
        
        Contract_Template_List__c template1 = new Contract_Template_List__c();
        template1.Name = 'CLM_TMPL_000101';
        template1.Schedule_Type__c = 'FSA_Standard';
        template1.Agreement_Type__c = 'FSA_Standard';
        template1.Template_Name__c = 'FSA_Standard';
        insert template1;
        
            Id globalRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='global' LIMIT 1]?.Id;
        Account globalAcc = new Account();
        globalAcc.Name = 'GLOBAL ACCOUNT';
        globalAcc.RecordTypeId = globalRecId;
        insert globalAcc;
            
        Id masterRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='Master' LIMIT 1]?.Id;
        Account a = new Account();
        a.Name = 'Test Account';
        a.RecordTypeId = masterRecId;
        a.ParentId = globalAcc.Id;
        insert a;
            Id servRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='Service' LIMIT 1]?.Id;
         Account testSAccount = new Account();
         testSAccount.Name = 'Test Service Account';
            testSAccount.RecordTypeId = servRecId;
         testSAccount.BillingStreet = '123 Main Street';
         testSAccount.BillingCity = 'New Milford';
         testSAccount.BillingState = 'Connecticut';
         testSAccount.BillingPostalCode = '44088';
         testSAccount.BillingCountry = 'United States';
         testSAccount.BillingCountryCode = 'US';
         testSAccount.BillingStateCode = 'CT';
         
         testSAccount.ShippingStreet = '123 Main Street';
         testSAccount.ShippingCity = 'New Milford';
         testSAccount.ShippingState = 'Connecticut';
         testSAccount.ShippingPostalCode = '44088';
         testSAccount.ShippingCountry = 'United States';
         testSAccount.ShippingCountryCode = 'US';
         testSAccount.ShippingStateCode = 'CT';
            testSAccount.ParentId = a.Id;
         insert testSAccount;
        
         Opportunity opp = new Opportunity();
         opp.Name = 'RefreshTestOpp';
         opp.AccountId = a.id;
         Date d1=Date.newInstance(2019, 05, 11);
         opp.CloseDate=d1;
         opp.StageName='Investigating';
         opp.CPE_Product__c='No';
         insert opp;
        
         id pricebookId = Test.getStandardPricebookId();
         List<Product2> lstProduct2 = new List<Product2>();
         Product2 product = new Product2();
         product.Name = 'EIA';
         product.ProductCode = 'ENT_ETH_EIA_0001';
         product.IsActive = true;
         lstProduct2.add(product);

         Product2 prodEVC = new Product2();
         prodEVC.Name = 'EVC';
         prodEVC.ProductCode = 'ENT_ETH_EVC_0001';
         prodEVC.IsActive = true;
         lstProduct2.add(prodEVC);
        
         Product2 prodAccess = new Product2();
         prodAccess.Name = 'Access';
         prodAccess.ProductCode = 'ENT_ETH_ACCESS_0001';
         prodAccess.IsActive = true;
         lstProduct2.add(prodAccess);
         //Insert products
         insert lstProduct2;  
        
         PricebookEntry standardPrice = new PricebookEntry(
             Pricebook2Id = pricebookId, 
             Product2Id = lstProduct2[0].Id,
             UnitPrice = 100, IsActive = true);
         insert standardPrice;
        
         Quote oQuote = new Quote();
         //oQuote.Account = testSAccount.Id;
         oQuote.Name = 'Testing Quote';
         oQuote.OpportunityId = opp.id;
         oQuote.Pricebook2Id = pricebookId;
         oQuote.Service_Term__c = '36 Months';
         insert oQuote;
        
         QuoteLineItem oQLI = new QuoteLineItem();
         oQLI.QuoteId = oQuote.id;
         oQLI.PricebookEntryId = standardPrice.id;
         oQLI.vlocity_cmt__ServiceAccountId__c = testSAccount.id;
         oQLI.Quantity = 1;
         oQLI.UnitPrice = 34.50;
         oQLI.Term__c = '36 Months';
         oQLI.vlocity_cmt__Product2Id__c = lstProduct2[0].Id;
         oQLI.Product2Id = lstProduct2[0].Id;
         oQLI.Agreement_Type__c = 'Broadband FiberOptic & Voice Bundles - New Service';
         oQLI.Schedule_Type__c = 'FiberOptic & OneVoice Nationwide (copper)';
         insert oQLI;
        
         oQLI.vlocity_cmt__RootItemId__c = oQLI.id;
         update oQLI;
         
         QuoteLineItem oQLI1 = new QuoteLineItem();
         oQLI1.QuoteId = oQuote.id;
         oQLI1.PricebookEntryId = standardPrice.id;
         oQLI1.vlocity_cmt__ServiceAccountId__c = testSAccount.id;
         oQLI1.Quantity = 1;
         oQLI1.UnitPrice = 34.50;
         oQLI1.Term__c = '36 Months';
         oQLI1.vlocity_cmt__Product2Id__c = lstProduct2[0].Id;
         oQLI1.Product2Id = lstProduct2[0].Id;
         oQLI1.Agreement_Type__c = 'Do Not Add';
         oQLI1.Schedule_Type__c = 'Do Not Add';
         insert oQLI1;
         
         QuoteLineItem oQLI2 = new QuoteLineItem();
         oQLI2.QuoteId = oQuote.id;
         oQLI2.PricebookEntryId = standardPrice.id;
         oQLI2.vlocity_cmt__ServiceAccountId__c = testSAccount.id;
         oQLI2.Quantity = 1;
         oQLI2.UnitPrice = 34.50;
         oQLI2.Term__c = '36 Months';
         oQLI2.vlocity_cmt__Product2Id__c = lstProduct2[0].Id;
         oQLI2.Product2Id = lstProduct2[0].Id;
         oQLI2.Agreement_Type__c = 'Manual';
         oQLI2.Schedule_Type__c = 'Manual';
         insert oQLI2;
         
         QuoteLineItem oQLI3 = new QuoteLineItem();
         oQLI3.QuoteId = oQuote.id;
         oQLI3.PricebookEntryId = standardPrice.id;
         oQLI3.vlocity_cmt__ServiceAccountId__c = testSAccount.id;
         oQLI3.Quantity = 1;
         oQLI3.UnitPrice = 34.50;
         oQLI3.Term__c = '36 Months';
         oQLI3.vlocity_cmt__Product2Id__c = lstProduct2[0].Id;
         oQLI3.Product2Id = lstProduct2[0].Id;
         oQLI3.Agreement_Type__c = null;
         oQLI3.Schedule_Type__c = null;
         insert oQLI3;
         
         String templateName = ftr_CLMContractCreation.getTemplateName('Broadband FiberOptic & Voice Bundles - New Service', 'FiberOptic & OneVoice Nationwide (copper)');
         
         vlocity_cmt__DocumentTemplate__c templateObj = new vlocity_cmt__DocumentTemplate__c();
         templateObj.vlocity_cmt__IsActive__c = true;
         templateObj.Name = 'Fiber and OneVoice Schedule';
         insert templateObj;
         
         vlocity_cmt__DocumentTemplate__c templateObj1 = new vlocity_cmt__DocumentTemplate__c();
         templateObj1.vlocity_cmt__IsActive__c = true;
         templateObj1.Name = 'FSA_Extended';
         insert templateObj1;
         vlocity_cmt__DocumentTemplate__c templateObj2 = new vlocity_cmt__DocumentTemplate__c();
         templateObj2.vlocity_cmt__IsActive__c = true;
         templateObj2.Name = 'Frontier FSA';
         insert templateObj2;
         
         ftr_CLMContractCreation.getContractTemplateId(templateName);
         oQuote.OpportunityId = opp.id;
         update oQuote;
         
         SterlingQuote__c objSQ = new SterlingQuote__c();
         objSQ.Name='Testing Name';
         objSQ.ExpirationDate__c = date.today();
         objSQ.OpportunityId__c = opp.Id;
         objSQ.Account_Name__c = testSAccount.id;
         objSQ.IsSyncing__c = true;
         insert objSQ;
        
         SterlingQuoteItem__c objLineItem = new SterlingQuoteItem__c();
         objLineItem.Quantity__c=10;
         objLineItem.TermLength__c=24;
         objLineItem.StandardMRC__c = 10;
         objLineItem.StandardNRC__c = 10;
         objLineItem.AdjustedMRC__c = 10;
         objLineItem.AdjustedNRC__c = 10;
         objLineItem.Locality__c = 'Indiana';
         objLineItem.StateProvince__c ='IN';
         objLineItem.ItemCode__c ='123'; 
         objLineItem.ApprovalTerritory__c ='Indiana';
         objLineItem.ApprovalRegion__c='central';
         objLineItem.NPA__c ='10';
         objLineItem.NXX__c = '10';
         objLineItem.IsInFrontierFootprint__c = false;
         objLineItem.SterlingQuote__c = objSQ.id;
         objLineItem.Agreement_Type__c = 'Broadband FiberOptic & Voice Bundles - New Service';
         objLineItem.Schedule_Type__c = 'FiberOptic & OneVoice Nationwide (copper)';
         insert objLineItem;
         
         SterlingQuoteItem__c objLineItem1 = new SterlingQuoteItem__c();
         objLineItem1.Quantity__c=10;
         objLineItem1.TermLength__c=24;
         objLineItem1.StandardMRC__c = 10;
         objLineItem1.StandardNRC__c = 10;
         objLineItem1.AdjustedMRC__c = 10;
         objLineItem1.AdjustedNRC__c = 10;
         objLineItem1.Locality__c = 'Indiana';
         objLineItem1.StateProvince__c ='IN';
         objLineItem1.ItemCode__c ='123'; 
         objLineItem1.ApprovalTerritory__c ='Indiana';
         objLineItem1.ApprovalRegion__c='central';
         objLineItem1.NPA__c ='10';
         objLineItem1.NXX__c = '10';
         objLineItem1.IsInFrontierFootprint__c = false;
         objLineItem1.SterlingQuote__c = objSQ.id;
         objLineItem1.Agreement_Type__c = 'Do Not Add';
         objLineItem1.Schedule_Type__c = 'Do Not Add';
         insert objLineItem1;
         
         SterlingQuoteItem__c objLineItem2 = new SterlingQuoteItem__c();
         objLineItem2.Quantity__c=10;
         objLineItem2.TermLength__c=24;
         objLineItem2.StandardMRC__c = 10;
         objLineItem2.StandardNRC__c = 10;
         objLineItem2.AdjustedMRC__c = 10;
         objLineItem2.AdjustedNRC__c = 10;
         objLineItem2.Locality__c = 'Indiana';
         objLineItem2.StateProvince__c ='IN';
         objLineItem2.ItemCode__c ='123'; 
         objLineItem2.ApprovalTerritory__c ='Indiana';
         objLineItem2.ApprovalRegion__c='central';
         objLineItem2.NPA__c ='10';
         objLineItem2.NXX__c = '10';
         objLineItem2.IsInFrontierFootprint__c = false;
         objLineItem2.SterlingQuote__c = objSQ.id;
         objLineItem2.Agreement_Type__c = 'Manual';
         objLineItem2.Schedule_Type__c = 'Manual';
         insert objLineItem2;
         
         SterlingQuoteItem__c objLineItem3 = new SterlingQuoteItem__c();
         objLineItem3.Quantity__c=10;
         objLineItem3.TermLength__c=24;
         objLineItem3.StandardMRC__c = 10;
         objLineItem3.StandardNRC__c = 10;
         objLineItem3.AdjustedMRC__c = 10;
         objLineItem3.AdjustedNRC__c = 10;
         objLineItem3.Locality__c = 'Indiana';
         objLineItem3.StateProvince__c ='IN';
         objLineItem3.ItemCode__c ='123'; 
         objLineItem3.ApprovalTerritory__c ='Indiana';
         objLineItem3.ApprovalRegion__c='central';
         objLineItem3.NPA__c ='10';
         objLineItem3.NXX__c = '10';
         objLineItem3.IsInFrontierFootprint__c = false;
         objLineItem3.SterlingQuote__c = objSQ.id;
         objLineItem3.Agreement_Type__c = null;
         objLineItem3.Schedule_Type__c = null;
         insert objLineItem3;
         
         
         System.Test.startTest();
             Map<String, Object> input = new Map<String, Object>();
             input.put('quoteId',oQuote.Id);
             Map<String, Object> output = new Map<String, Object>();
             Map<String, Object> options = new Map<String, Object>(); 
             System.debug('Opportunity Id: ' + opp.Id);
             System.debug('Quote Opportunity Id: ' + oQuote.Opportunity.Id);
             System.debug('AccountId: ' + oQuote.Account.Id);
             System.debug('Account Shipping Address: ' + oQuote.Account.ShippingAddress);
             ftr_CLMContractCreation.createContracts(input, output, options);
             
             input.clear();
             input.put('quoteId',objSQ.Id);
             ftr_CLMContractCreation.createContracts(input, output, options);
             
                input.clear();
                List<Object> QuoteList = new List<Object>();
                Map<String, Object> quoteMap1 = new Map<String, Object>();
                quoteMap1.put('Id', objSQ.Id);
                
                Map<String, Object> quoteMap2 = new Map<String, Object>();
                quoteMap2.put('Id', oQuote.Id);
                
                QuoteList.add(quoteMap1);
                QuoteList.add(quoteMap2);
                input.put('Quotes', QuoteList);
                input.put('ContractTerm',60);
                input.put('ContractStartDate', '2021-07-15');
                input.put('AccountId',testSAccount.Id);
                input.put('FSATemplateType', '5 Page');
                input.put('WholeSaleTeamFlag',true);
                input.put('PNUMText','Test123');
                input.put('opportunityId',opp.Id);
                input.put('MDUTemplatesflag', true);
                input.put('FSAExistsFlag', false);
                input.put('MDUTemplates','FSA_Standard');
                input.put('ChildContractTemplate','FSA_Standard');
                input.put('CallCenterProfileFlag',true);
                
                ftr_CLMCreateContractsFromAccount obj = new ftr_CLMCreateContractsFromAccount();
                obj.invokeMethod('checkFSAContracts', input, output, options);
                obj.invokeMethod('createContracts', input, output, options);
                
         System.Test.stopTest(); 
        }
    }
}