UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/SterlingQuote__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Object</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/IsSyncing__c.field-meta.xml
<CustomField>
    <fullName>IsSyncing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/SterlingQuoteItem__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Item</description>
    <label>Quote Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>SterlingQuote__r.Account_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AddressDescription__c.field-meta.xml
<CustomField>
    <fullName>AddressDescription__c</fullName>
    <label>Address Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/BuildingNumber__c.field-meta.xml
<CustomField>
    <fullName>BuildingNumber__c</fullName>
    <label>Building Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>SterlingQuote__r.OpportunityId__r.Id</formula>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/SterlingQuote__c.field-meta.xml
<CustomField>
    <fullName>SterlingQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>SterlingQuote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>SterlingQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ZAddress__c/ZAddress__c.object-meta.xml
<CustomObject>
    <description>Contains all Z Addresses for Quote</description>
    <label>ZAddress</label>
    <nameField>
        <displayFormat>ZA-{00000000}</displayFormat>
        <label>ZAddress Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zaddress</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/classes/ZAddressTest.cls
@isTest(seeAllData = true)
private class ZAddressTest {
 static testmethod void unitTest(){
      Id globalRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='global' LIMIT 1]?.Id;
        Account globalAcc1 = new Account();
        globalAcc1.Name = 'GLOBAL ACCOUNT';
        globalAcc1.RecordTypeId = globalRecId;
        //globalAcc.RecordTypeId = '012E0000000fDc3IAE';
        insert globalAcc1;
        Id MasterRTId =[SELECT id FROM RecordType WHERE RecordType.Name = 'Master' AND SobjectType = 'Account'].Id;
      Account acc = new Account(name = 'TestAccount');
     	acc.RecordTypeId = MasterRTId;
        acc.ParentId = globalAcc1.Id;
      insert acc;
      acc = [select id from Account where name = 'TestAccount' limit 1];
      
      Opportunity opp = new Opportunity(name = 'TestOpp 1577216802', StageName='Validating', AccountId=acc.Id, closeDate=Date.Today());
      insert opp;
      opp = [Select id from Opportunity where name = 'TestOpp 1577216802'];
      
      SterlingQuote__c sq = new SterlingQuote__c(name='TestSQ', Account_Name__c = acc.id, OpportunityId__c = opp.id, IsSyncing__c = true);
      insert sq;
      sq = [select id from SterlingQuote__c where name='TestSQ'];
      
      SterlingQuoteItem__c sqi = new SterlingQuoteItem__c(name = 'TestSQI', SterlingQuote__c = sq.id);
      insert sqi;
      sqi = [select id from SterlingQuoteItem__c where name = 'TestSQI'];
     
      //OpportunityLineItem oli = new OpportunityLineItem(QuoteItem__c=sqi.id ,ZAddress__c='Test Address',OpportunityId =opp.id, Quantity=12,TotalPrice =1200 );
      //insert oli;     
      
      ZAddress__c z = new ZAddress__c(SterlingQuoteItem__c= sqi.id, Addressdescription__c = 'New Test', BuildingName__c = 'Test', BuildingNumber__c = '11');
      insert z;
      z = [select id from  ZAddress__c limit 1];
      
     
      update z;
      delete z;
      undelete z;
 }
}
// **