UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Account_Channel__c.field-meta.xml
<CustomField>
    <fullName>Account_Channel__c</fullName>
    <label>Account Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Connected Community</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>VZ3 Agreements</fullName>
            </value>
            <value>
                <fullName>Alternate Channel</fullName>
            </value>
            <value>
                <fullName>Contact Center</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>This field is used to show which products are being quoted.</description>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS</fullName>
            </value>
            <value>
                <fullName>CCaaS</fullName>
            </value>
            <value>
                <fullName>Private Network</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/ftr_DID_Number_Details__c.object-meta.xml
<CustomObject>
    <label>DID Number Details</label>
    <nameField>
        <label>DID Number Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Number Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>DID Number Details</relationshipLabel>
    <relationshipName>DID_Number_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Greetings__c/Greetings__c.object-meta.xml
<CustomObject>
    <label>Greetings</label>
    <nameField>
        <label>Greetings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Greetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Greetings__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Greetings</relationshipLabel>
    <relationshipName>Greetings</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu__c/Menu__c.object-meta.xml
<CustomObject>
    <label>Menu</label>
    <nameField>
        <label>Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu__c/fields/Greeting__c.field-meta.xml
<CustomField>
    <fullName>Greeting__c</fullName>
    <label>Greeting</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Menus</relationshipLabel>
    <relationshipName>Menus</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu_Line__c/Menu_Line__c.object-meta.xml
<CustomObject>
    <label>Menu Line</label>
    <nameField>
        <label>Menu Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menu Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu_Line__c/fields/Menu__c.field-meta.xml
<CustomField>
    <fullName>Menu__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Menu</label>
    <referenceTo>Menu__c</referenceTo>
    <relationshipLabel>Menu Lines</relationshipLabel>
    <relationshipName>Menu_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu_Line__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu_Line__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <label>Options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Options_for_Menu_Line</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Order_Stage__c.field-meta.xml
<CustomField>
    <fullName>Order_Stage__c</fullName>
    <label>Order Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Clean Order</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Clean Order</fullName>
            </value>
            <value>
                <fullName>CNP Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>CPM In Progress</fullName>
            </value>
            <value>
                <fullName>Credit Check</fullName>
            </value>
            <value>
                <fullName>Customer Network Provisioning</fullName>
            </value>
            <value>
                <fullName>DPI/CMS Provisioning</fullName>
            </value>
            <value>
                <fullName>DPI Billing</fullName>
            </value>
            <value>
                <fullName>DPI Provisioning</fullName>
            </value>
            <value>
                <fullName>ECR/EWO In Progress</fullName>
                <label>ECR/PSR In Progress</label>
            </value>
            <value>
                <fullName>EWO In Progress</fullName>
            </value>
            <value>
                <fullName>Hot Cuts</fullName>
            </value>
            <value>
                <fullName>IMPM</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>ISP Engineering</fullName>
            </value>
            <value>
                <fullName>Issuing Orders</fullName>
            </value>
            <value>
                <fullName>MSA Review</fullName>
            </value>
            <value>
                <fullName>NCM Pending Billing</fullName>
            </value>
            <value>
                <fullName>Needs more information</fullName>
            </value>
            <value>
                <fullName>Network COE</fullName>
            </value>
            <value>
                <fullName>Network Cost Management</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Order Engineering Desk</fullName>
            </value>
            <value>
                <fullName>Ordering</fullName>
            </value>
            <value>
                <fullName>OSP Engineering</fullName>
            </value>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS</fullName>
            </value>
            <value>
                <fullName>CCaaS</fullName>
            </value>
            <value>
                <fullName>Private Network</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A Product specific alteration to a contract</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>S-{0000000000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Schedule__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Schedule__c/fields/Schedule_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Start_Date__c</fullName>
    <description>Date that schedule takes effect</description>
    <label>Schedule Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Schedule__c/fields/UCF_Name__c.field-meta.xml
<CustomField>
    <fullName>UCF_Name__c</fullName>
    <label>Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Schedule__c/fields/UCF_Order__c.field-meta.xml
<CustomField>
    <fullName>UCF_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <displayFormat>SL-{0000}</displayFormat>
        <label>Service Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Service_Location__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Time_Period__c/Time_Period__c.object-meta.xml
<CustomObject>
    <label>Time Period</label>
    <nameField>
        <label>Time Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Time_Period__c/fields/Menu__c.field-meta.xml
<CustomField>
    <fullName>Menu__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Menu</label>
    <referenceTo>Menu__c</referenceTo>
    <relationshipLabel>Time Periods</relationshipLabel>
    <relationshipName>Time_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Time_Period__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Time Periods</relationshipLabel>
    <relationshipName>Time_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/vlocity_cmt__Premises__c/objects/vlocity_cmt__Premises__c.object
<CustomObject>
    <fields>
        <fullName>WC_CLLI__c</fullName>
        <label>WC CLLI</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Premises</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/globalValueSets/Options_for_Menu_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Transfer Number</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer Voicemail</fullName>
    </customValue>
    <customValue>
        <fullName>Go to Sub Menu</fullName>
    </customValue>
    <customValue>
        <fullName>Announcement Return</fullName>
    </customValue>
    <customValue>
        <fullName>Announcement Hang Up</fullName>
    </customValue>
    <customValue>
        <fullName>Dial by Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Dial by Name</fullName>
    </customValue>
    <customValue>
        <fullName>Replay Menu</fullName>
    </customValue>
    <customValue>
        <fullName>Previous Menu</fullName>
    </customValue>
    <customValue>
        <fullName>Nothing</fullName>
        <default>true</default>
        <label>Nothing</label>
    </customValue>
    <masterLabel>Options for Menu Line</masterLabel>
</GlobalValueSet>

UCF-APR2.4/ftr main/force-app/main/default/classes/PmEnrichmentController_Test.cls
@isTest
public class PmEnrichmentController_Test {
    @testSetup
    static void setupTestData(){
        Id globalRecId1 = [select id,name,developername from recordtype where sobjecttype='account' and developername='global' LIMIT 1]?.Id;
        Account globalAcc1 = new Account();
        globalAcc1.Name = 'GLOBAL ACCOUNT';
        globalAcc1.RecordTypeId = globalRecId1;
        //globalAcc.RecordTypeId = '012E0000000fDc3IAE';
        insert globalAcc1;
        
        Id masterRecId1 = [select id,name,developername from recordtype where sobjecttype='account' and developername='master' LIMIT 1]?.Id;
        
        Account a = new Account();
        a.RecordTypeId = masterRecId1;
        a.Name = 'Test Account';
        a.ParentId = globalAcc1.Id;
        a.RecordTypeId = masterRecId1;
        a.Account_Channel__c='Connected Community';
        insert a;
        
        vlocity_cmt__Premises__c Prms = new vlocity_cmt__Premises__c();
        Prms.WC_CLLI__c = 'MSTNWIXA';
        insert Prms;
        //Insert service account
        Account serviceAccount = new Account();
        serviceAccount.ParentId = globalAcc1.id;
        serviceAccount.Name = 'Service Account';
        serviceAccount.ShippingStreet = '1480 North Valley Parkway';
        serviceAccount.ShippingCity = 'Lewisville';     
        serviceAccount.ShippingState = 'Texas';
        serviceAccount.ShippingPostalCode = '75077';
        serviceAccount.vlocity_cmt__PremisesId__c= Prms.Id;
        insert serviceAccount;
        
        /////////////Create test data for Contract///////////
        
        Contract newContract = new Contract();
        newContract.Name = 'Sample Contract';
        newContract.BillingStreet = '123 Billing St';
        newContract.BillingCity = 'Medford';
        newContract.BillingState = 'Oregon';
        newContract.BillingPostalCode = '97501';
        newContract.BillingCountry = 'United States	';
        
        newContract.ShippingStreet = '123 Main St';
        newContract.ShippingCity = 'Anytown';
        newContract.ShippingState = 'Texas';
        newContract.ShippingPostalCode = '12345';
        newContract.ShippingCountry = 'United States';
        newContract.AccountId=a.Id;
        
        Insert newContract;
        
        Product2 p = new Product2();
        p.Name = ' Test EIA ';
        p.Description='Test EIA (Ethernet Internet Access)';
        p.productCode = 'ENT_ETH_EIA_0002';
        p.isActive = true;
        insert p;
        
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice1 = new PricebookEntry();
        standardPrice1.Pricebook2Id = pricebookId;
        standardPrice1.Product2Id = p.Id;
        standardPrice1.UnitPrice = 1;
        standardPrice1.IsActive = true;
        standardPrice1.UseStandardPrice = false;
        insert standardPrice1 ;
        
        Pricebook2 standardPb = new Pricebook2(Name = 'vlocitytest', Description = 'Price Book vlocity Products', IsActive = true);
        insert standardPb;
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = standardPb.Id;
        standardPrice.Product2Id = p.Id;
        standardPrice.UnitPrice = 1;
        standardPrice.IsActive = true;
        standardPrice.UseStandardPrice = false;
        insert standardPrice ;
        
        Order o = new Order();
        o.Name = 'Sample Order';
        o.Status = 'Draft';
        o.EffectiveDate = system.today();
        o.EndDate = system.today() + 10;
        o.AccountId = a.id;
        o.Pricebook2Id =  standardPb.Id ;
        o.Products__c = 'SIP;EIA';
        o.Order_Stage__c = 'MSA Review';
        o.Contract__c=newContract.Id;
        Insert o;

        OrderItem i = new OrderItem();
        i.OrderId = o.id;
        i.Quantity = 24;
        i.UnitPrice = 240;
        i.Product2id = p.id;
        i.PricebookEntryId=standardPrice.Id;
        i.vlocity_cmt__ServiceAccountId__c = serviceAccount.Id;
        i.vlocity_cmt__Product2Id__c = p.Id;
        insert i;
        
        /////////////////Create test data for Order//////////////
        
        system.debug('New Order aab'+o.Id);
        
        // Create test data for Schedule__c
        List<Schedule__c> scheduleList = new List<Schedule__c>();
        for(integer sch=0;sch<5;sch++){
            Schedule__c schedule = new Schedule__c();
            Schedule.UCF_Name__c = 'Sample'+sch;
            Schedule.UCF_Order__c = o.Id;
            schedule.Schedule_Start_Date__c=Date.today();
            schedule.Contract__c=o.Contract__c;
            scheduleList.Add(schedule);
        }
        insert scheduleList;
        // Insert Greeting
        Greetings__c greeting = new Greetings__c();
        greeting.Name = 'Test Greeting';
        greeting.Order__c = o.Id;
        insert greeting;
        // Insert Menu
        Menu__c menu = new Menu__c();
        menu.Name = 'Test Menu';
        menu.Order__c = o.Id;
        menu.Greeting__c=greeting.Id;
        insert menu;
        
        // Prepare to insert Menu Line Items
        List<Menu_Line__c> menuLines = new List<Menu_Line__c>();
        for (Integer ml = 1; ml <= 12; ml++) {
            Menu_Line__c line = new Menu_Line__c();
            line.Menu__c = menu.Id; // Assuming a relationship field to Menu__c
            line.Sort_Order__c = ml;
            // Assign Number__c and Options__c based on the loop index
            if (ml <= 9) {
                line.Number__c = String.valueOf(ml);
            } else if (ml == 10) {
                line.Number__c = '0';
            } else if (ml == 11) {
                line.Number__c = '*';
                line.Options__c = 'Replay Menu';
            } else if (ml == 12) {
                line.Number__c = '#';
                line.Options__c = 'Previous Menu';
            }
            menuLines.add(line);
        }
        
        // Insert Menu Lines
        insert menuLines;
        
        
        
        ftr_DID_Location_Details__c did = new ftr_DID_Location_Details__c(
            OrderId__c=o.Id,
            
            BTN__c='1234567890'
        );
        insert did;
        
        ftr_DID_Number_Details__c num = new ftr_DID_Number_Details__c(
            DID_Number__c='1234567890',
            DIDLocationDetailsId__c=did.Id,
            Schedule__c=scheduleList[0].Id
        );
        insert num;
        
        Time_Period__c tp = new Time_Period__c(
            Name='Test Time Period',
            Menu__c=menu.Id,
            Schedule__c=scheduleList[0].Id);

            insert tp;
        Service_Location__c sl=new Service_Location__c(Order__c=o.Id);
        insert sl;
    }
    
    @isTest
    static void testGetAccountList() {
        Test.startTest();
        List<Account> result = PmEnrichmentController.getAccountList();
        Test.stopTest();
        System.assertNotEquals(NULL, result);
    }
   /* 
    @isTest
    static void testIsTranslationUser() {
        Test.startTest();
        String profileName = PmEnrichmentController.isTranslationUser();
        Test.stopTest();
        System.assertNotEquals(NULL, profileName);
    } */
    @isTest
    static void testGetPremises() {
        
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        Test.startTest();
        List<Service_Location__c> existingServiceLocations = PmEnrichmentController.getPremises(orderId);
        Test.stopTest();
        System.assertNotEquals(NULL, existingServiceLocations);
    }
    @isTest
    static void testGetPremises_WithoutServiceLocation() {
        
        
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        Service_Location__c sl=[SELECT Id,Order__c FROM Service_Location__c WHERE Order__c = :orderId];
        Delete sl;
        Test.startTest();
        List<Service_Location__c> existingServiceLocations = PmEnrichmentController.getPremises(orderId);
        Test.stopTest();
        System.assertNotEquals(NULL, existingServiceLocations);
    }
    @isTest
    static void testGetPremises2() {
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        Test.startTest();
        List<Service_Location__c> serviceLocation = PmEnrichmentController.getPremises2(orderId);
        Test.stopTest();
        System.assertNotEquals(NULL, serviceLocation);
    }
    @isTest
    static void testFtrDIDNumberDetailsEmployeeInfo() {
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        Test.startTest();
        List<ftr_DID_Number_Details__c> ftrDIDNumberDetails = PmEnrichmentController.ftrDIDNumberDetailsEmployeeInfo(orderId);
        Test.stopTest();
        System.assertNotEquals(NULL, ftrDIDNumberDetails);
    }
    
    @isTest
    static void testUpdatePremiseFieldsList() {
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        List<Service_Location__c> recordsToUpdate=[select id,Name from Service_Location__c];
        Test.startTest();
        string recordsToUpdate_Response  = PmEnrichmentController.updatePremiseFieldsList(recordsToUpdate,recordsToUpdate,orderId);
        Test.stopTest();
        System.assertNotEquals(NULL, recordsToUpdate_Response);
    }

    @isTest
    static void testUpdateDIDNumbersFieldsListt() {
        String EASPin='123';
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        Test.startTest();
        string updateDIDNumbersFieldsList_Response  = PmEnrichmentController.updateDIDNumbersFieldsList(EASPin,orderId);
        Test.stopTest();
        System.assertNotEquals(NULL, updateDIDNumbersFieldsList_Response);
    }
    @isTest
    static void testUpdatePremisesFieldsList() {
        List<Service_Location__c> recordsToUpdate=[select id,Name from Service_Location__c];
        Test.startTest();
        string recordsToUpdate_Response  = PmEnrichmentController.updatePremisesFieldsList(recordsToUpdate);
        Test.stopTest();
        System.assertNotEquals(NULL, recordsToUpdate_Response);
    }
    @isTest
    static void testUpdateServiceLoacationMoadalFields() {
        String constructionDetails='abc';
        Service_Location__c serLocRec= [select id,Name,Shipping_Address__c,Street__c,City__c,State__c,Zip__c from Service_Location__c ];
        String shippingAddress='12';
        Test.startTest();
        string updateAccountFields_Response  = PmEnrichmentController.updateServiceLoacationMoadalFields(serLocRec.Id,constructionDetails,serLocRec.Shipping_Address__c,serLocRec.Street__c,serLocRec.City__c,serLocRec.State__c,serLocRec.Zip__c);
        Test.stopTest();
        System.assertEquals('Record updated successfully', updateAccountFields_Response);
    }
    @isTest
    static void testGetRatingPicklistValues2() {
        Test.startTest();
        List<string> getRatingPicklistValues2_Response  = PmEnrichmentController.getRatingPicklistValues2();
        Test.stopTest();
        System.assertNotEquals(Null, getRatingPicklistValues2_Response);
    }
    @isTest
    static void testGetRatingPicklistValues() {
        Test.startTest();
        List<string> getRatingPicklistValues_Response  = PmEnrichmentController.getRatingPicklistValues();
        Test.stopTest();
        System.assertNotEquals(Null, getRatingPicklistValues_Response);
    }
    @isTest
    static void testGetAccounts() {
        Test.startTest();
        List<Account> GetAccounts_Response  = PmEnrichmentController.getAccounts();
        Test.stopTest();
        System.assertNotEquals(Null, GetAccounts_Response);
    }
    @isTest
    static void testGetDIDNumbersData() {
        Test.startTest();
        List<ftr_DID_Number_Details__c> GetDIDNumbersData_Response  = PmEnrichmentController.getDIDNumbersData();
        Test.stopTest();
        System.assertNotEquals(Null, GetDIDNumbersData_Response);
    }
    @isTest
    static void testUpsertAccounts() {
        
        String csvData = '[{"PhoneNumber": "123-456-7890", "Name": "Account 1"}, {"PhoneNumber": "987-654-3210", "Name": "Account 2"}]';
        Test.startTest();
        PmEnrichmentController.upsertAccounts(csvData);
   		Test.stopTest();
        List<Account> insertedAccounts = [SELECT Id, Name FROM Account];
        System.assertNotEquals(NULL, insertedAccounts);
    }
    
    @isTest
    static void test_ftrPhoneNumberDetails() {
        
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        Test.startTest();
        List<ftr_DID_Number_Details__c> updateDIDNumbersFieldsList_Response  = PmEnrichmentController.ftrPhoneNumberDetails(orderId);
        Test.stopTest();
        System.assertNotEquals(NULL, updateDIDNumbersFieldsList_Response);
    }
    @isTest
    static void test_isNetworkTranslation() {
        
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        Test.startTest();
        Boolean isNetworkTranslation_Response  = PmEnrichmentController.isNetworkTranslation(orderId);
        Test.stopTest();
        System.assertNotEquals(NULL, isNetworkTranslation_Response);
    }
    
    @isTest
    static void test_getOrderStage() {
        
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        Test.startTest();
        Boolean updateDIDNumbersFieldsList_Response  = PmEnrichmentController.getOrderStage(orderId);
        Test.stopTest();
        
    }
    
}