UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/BTN__c.field-meta.xml
<CustomField>
    <fullName>BTN__c</fullName>
    <label>BTN</label>
    <type>Phone</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/ftr_DID_Location_Details__c.object-meta.xml
<CustomObject>
    <label>DID Location Details</label>
    <nameField>
        <label>DID Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Location Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/BTN__c.field-meta.xml
<CustomField>
    <fullName>BTN__c</fullName>
    <label>Billing Number (BTN)</label>
    <type>Phone</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/ftr_DID_Number_Details__c.object-meta.xml
<CustomObject>
    <label>DID Number Details</label>
    <nameField>
        <label>DID Number Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Number Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/DID_Number__c.field-meta.xml
<CustomField>
    <fullName>DID_Number__c</fullName>
    <label>DID Number (Unique)</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/DIDLocationDetailsId__c.field-meta.xml
<CustomField>
    <fullName>DIDLocationDetailsId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DID Location Details</label>
    <referenceTo>ftr_DID_Location_Details__c</referenceTo>
    <relationshipLabel>DID Number Details</relationshipLabel>
    <relationshipName>DID_Number_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/DIDNumberViewControllerTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 1 
**/
@isTest
public class DIDNumberViewControllerTest {
    @TestSetup
    static void makeData(){
        Order[] o = ftr_TestDataFactory.getOrders(1);
        Account[] servAccs = ftr_TestDataFactory.getServAccountsWithPremise(1);
        update servAccs;
        insert o;
        OrderItem[] oi = ftr_TestDataFactory.getOrderItems(1, new Map<String,String>{
            'SIP_TRUNKING_0010' => 'SIP_TRUNKING_0010'
        });
        oi[0].OrderId = o[0].Id;
        oi[0].vlocity_cmt__ServiceAccountId__c = servAccs[0].Id;
        insert oi;
        
        ftr_DID_Location_Details__c did = new ftr_DID_Location_Details__c(
            OrderId__c=o[0].Id,
            BTN__c='1234567890'
        );
        insert did;

        ftr_DID_Number_Details__c num = new ftr_DID_Number_Details__c(
            DID_Number__c='1234567890',
            DIDLocationDetailsId__c=did.Id
        );
        insert num;
    }

    @IsTest
    static void methodName(){
        
        Test.startTest();
        DIDNumberViewController ctrl = new DIDNumberViewController();
        ctrl.didLocationId = [SELECT Id FROM ftr_DID_Location_Details__c LIMIT 1].Id;
        ctrl.getDIDLocationDetails();
        ctrl.getDIDNumbers();
        ctrl.getAllDIDNumbers();
        ctrl.getX911Options();
        ctrl.nextNumber();
        ctrl.previousNumber();
        ctrl.generateCSV();
        ctrl.generateUcfCSV();
        Test.stopTest();
        
    }
}