UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/BTN__c.field-meta.xml
<CustomField>
    <fullName>BTN__c</fullName>
    <label>BTN</label>
    <type>Phone</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>This field is used to show which products are being quoted.</description>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS</fullName>
            </value>
            <value>
                <fullName>CCaaS</fullName>
            </value>
            <value>
                <fullName>Private Network</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/ftr_DID_Location_Details__c.object-meta.xml
<CustomObject>
    <label>DID Location Details</label>
    <nameField>
        <label>DID Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Location Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/BTN__c.field-meta.xml
<CustomField>
    <fullName>BTN__c</fullName>
    <label>Billing Number (BTN)</label>
    <type>Phone</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/ftr_DID_Number_Details__c.object-meta.xml
<CustomObject>
    <label>DID Number Details</label>
    <nameField>
        <label>DID Number Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Number Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/DID_Number__c.field-meta.xml
<CustomField>
    <fullName>DID_Number__c</fullName>
    <label>DID Number (Unique)</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>DID Number Details</relationshipLabel>
    <relationshipName>DID_Number_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Greetings__c/Greetings__c.object-meta.xml
<CustomObject>
    <label>Greetings</label>
    <nameField>
        <label>Greetings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Greetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Greetings__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Greetings</relationshipLabel>
    <relationshipName>Greetings</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <label>Holiday</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Holiday__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Holidays</relationshipLabel>
    <relationshipName>Holidays</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu__c/Menu__c.object-meta.xml
<CustomObject>
    <label>Menu</label>
    <nameField>
        <label>Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu__c/fields/Greeting__c.field-meta.xml
<CustomField>
    <fullName>Greeting__c</fullName>
    <label>Greeting</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Menus</relationshipLabel>
    <relationshipName>Menus</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu_Line__c/Menu_Line__c.object-meta.xml
<CustomObject>
    <label>Menu Line</label>
    <nameField>
        <label>Menu Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menu Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu_Line__c/fields/Menu__c.field-meta.xml
<CustomField>
    <fullName>Menu__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Menu</label>
    <referenceTo>Menu__c</referenceTo>
    <relationshipLabel>Menu Lines</relationshipLabel>
    <relationshipName>Menu_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu_Line__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Menu_Line__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <label>Options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Options_for_Menu_Line</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Contract_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Contract_Schedule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract/Schedule #</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Orders (Contract/Schedule #)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Order_Stage__c.field-meta.xml
<CustomField>
    <fullName>Order_Stage__c</fullName>
    <label>Order Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Clean Order</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Clean Order</fullName>
            </value>
            <value>
                <fullName>CNP Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>CPM In Progress</fullName>
            </value>
            <value>
                <fullName>Credit Check</fullName>
            </value>
            <value>
                <fullName>Customer Network Provisioning</fullName>
            </value>
            <value>
                <fullName>DPI/CMS Provisioning</fullName>
            </value>
            <value>
                <fullName>DPI Billing</fullName>
            </value>
            <value>
                <fullName>DPI Provisioning</fullName>
            </value>
            <value>
                <fullName>ECR/EWO In Progress</fullName>
                <label>ECR/PSR In Progress</label>
            </value>
            <value>
                <fullName>EWO In Progress</fullName>
            </value>
            <value>
                <fullName>Hot Cuts</fullName>
            </value>
            <value>
                <fullName>IMPM</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>ISP Engineering</fullName>
            </value>
            <value>
                <fullName>Issuing Orders</fullName>
            </value>
            <value>
                <fullName>MSA Review</fullName>
            </value>
            <value>
                <fullName>NCM Pending Billing</fullName>
            </value>
            <value>
                <fullName>Needs more information</fullName>
            </value>
            <value>
                <fullName>Network COE</fullName>
            </value>
            <value>
                <fullName>Network Cost Management</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Order Engineering Desk</fullName>
            </value>
            <value>
                <fullName>Ordering</fullName>
            </value>
            <value>
                <fullName>OSP Engineering</fullName>
            </value>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS</fullName>
            </value>
            <value>
                <fullName>CCaaS</fullName>
            </value>
            <value>
                <fullName>Private Network</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A Product specific alteration to a contract</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>S-{0000000000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Schedule__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Schedule__c/fields/Schedule_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Start_Date__c</fullName>
    <description>Date that schedule takes effect</description>
    <label>Schedule Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Schedule__c/fields/UCF_Name__c.field-meta.xml
<CustomField>
    <fullName>UCF_Name__c</fullName>
    <label>Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Schedule__c/fields/UCF_Order__c.field-meta.xml
<CustomField>
    <fullName>UCF_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Schedule__c/recordTypes/Auto_Attendants.recordType-meta.xml
<RecordType>
    <fullName>Auto_Attendants</fullName>
    <active>true</active>
    <label>Auto Attendants</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Time_Period__c/Time_Period__c.object-meta.xml
<CustomObject>
    <label>Time Period</label>
    <nameField>
        <label>Time Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Time_Period__c/fields/Menu__c.field-meta.xml
<CustomField>
    <fullName>Menu__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Menu</label>
    <referenceTo>Menu__c</referenceTo>
    <relationshipLabel>Time Periods</relationshipLabel>
    <relationshipName>Time_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Time_Period__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Time Periods</relationshipLabel>
    <relationshipName>Time_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/globalValueSets/Options_for_Menu_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Transfer Number</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer Voicemail</fullName>
    </customValue>
    <customValue>
        <fullName>Go to Sub Menu</fullName>
    </customValue>
    <customValue>
        <fullName>Announcement Return</fullName>
    </customValue>
    <customValue>
        <fullName>Announcement Hang Up</fullName>
    </customValue>
    <customValue>
        <fullName>Dial by Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Dial by Name</fullName>
    </customValue>
    <customValue>
        <fullName>Replay Menu</fullName>
    </customValue>
    <customValue>
        <fullName>Previous Menu</fullName>
    </customValue>
    <customValue>
        <fullName>Nothing</fullName>
        <default>true</default>
        <label>Nothing</label>
    </customValue>
    <masterLabel>Options for Menu Line</masterLabel>
</GlobalValueSet>

UCF-APR2.4/ftr main/force-app/main/default/classes/UcfAutoAttendentController_Test.cls
@isTest
public class UcfAutoAttendentController_Test {
    /////// Test SetUp//////////////////
    @testSetup
    static void setupTestData() {
        Id globalRecId1 = [select id,name,developername from recordtype where sobjecttype='account' and developername='global' LIMIT 1]?.Id;
        Account globalAcc1 = new Account();
        globalAcc1.Name = 'GLOBAL ACCOUNT';
        globalAcc1.RecordTypeId = globalRecId1;
        //globalAcc.RecordTypeId = '012E0000000fDc3IAE';
        insert globalAcc1;
        
        Id masterRecId1 = [select id,name,developername from recordtype where sobjecttype='account' and developername='master' LIMIT 1]?.Id;
        
        Account a = new Account();
        a.RecordTypeId = masterRecId1;
        a.Name = 'Test Account';
        a.ParentId = globalAcc1.Id;
        a.RecordTypeId = masterRecId1;
        insert a;
        
        /////////////Create test data for Contract///////////
        
        Contract newContract = new Contract();
        newContract.Name = 'Sample Contract';
        newContract.BillingStreet = '123 Billing St';
        newContract.BillingCity = 'Medford';
        newContract.BillingState = 'Oregon';
        newContract.BillingPostalCode = '97501';
        newContract.BillingCountry = 'United States	';
        
        newContract.ShippingStreet = '123 Main St';
        newContract.ShippingCity = 'Anytown';
        newContract.ShippingState = 'Texas';
        newContract.ShippingPostalCode = '12345';
        newContract.ShippingCountry = 'United States';
        newContract.AccountId=a.Id;
        
        Insert newContract;
        system.debug('New Contract aab'+newContract.Id);
        /////////////////Create test data for Order//////////////
        Order o = new Order();
        o.Name = 'Sample Order';
        o.Status = 'Draft';
        o.EffectiveDate = system.today();
        o.EndDate = system.today() + 10;
        o.AccountId = a.id;
        //o.Pricebook2Id =  standardPb.Id ;
        o.Products__c = 'SIP;EIA';
        o.Order_Stage__c = 'MSA Review';
        o.Contract__c=newContract.Id;
        o.Contract_Schedule__c=newContract.Id;
        Insert o;
        system.debug('New Order aab'+o.Id);

        // Create test data for Schedule__c
        List<Schedule__c> scheduleList = new List<Schedule__c>();
        for(integer i=0;i<5;i++){
            Schedule__c schedule = new Schedule__c();
            Schedule.UCF_Name__c = 'Sample'+i;
            Schedule.UCF_Order__c = o.Id;
            schedule.Schedule_Start_Date__c=Date.today();
            schedule.Contract__c=o.Contract__c;
            scheduleList.Add(schedule);
        }
        insert scheduleList;
        // Insert Greeting
        Greetings__c greeting = new Greetings__c();
        greeting.Name = 'Test Greeting';
        greeting.Order__c = o.Id;
        insert greeting;
        // Insert Menu
        Menu__c menu = new Menu__c();
        menu.Name = 'Test Menu';
        menu.Order__c = o.Id;
        menu.Greeting__c=greeting.Id;
        insert menu;

        // Prepare to insert Menu Line Items
        List<Menu_Line__c> menuLines = new List<Menu_Line__c>();
        for (Integer i = 1; i <= 12; i++) {
            Menu_Line__c line = new Menu_Line__c();
            line.Menu__c = menu.Id; // Assuming a relationship field to Menu__c
            line.Sort_Order__c = i;
            // Assign Number__c and Options__c based on the loop index
            if (i <= 9) {
                line.Number__c = String.valueOf(i);
            } else if (i == 10) {
                line.Number__c = '0';
            } else if (i == 11) {
                line.Number__c = '*';
                line.Options__c = 'Replay Menu';
            } else if (i == 12) {
                line.Number__c = '#';
                line.Options__c = 'Previous Menu';
            }
            menuLines.add(line);
        }

        // Insert Menu Lines
        insert menuLines;
        
        
        
        ftr_DID_Location_Details__c did = new ftr_DID_Location_Details__c(
            OrderId__c=o.Id,
            
            BTN__c='1234567890'
        );
        insert did;

        ftr_DID_Number_Details__c num = new ftr_DID_Number_Details__c(
            DID_Number__c='1234567890',
            DIDLocationDetailsId__c=did.Id,
            Schedule__c=scheduleList[0].Id
        );
        insert num;
        
        Time_Period__c tp = new Time_Period__c(
        	Name='Test Time Period',
            Menu__c=menu.Id,
            Schedule__c=scheduleList[0].Id);
        insert tp;
    }

    
    
    @isTest
    static void testsaveTimePeriods() {
        String menuId= [SELECT Id,Name FROM Menu__c where Name='Test Menu' LIMIT 1].Id;
        Id scheduleId=[SELECT Id, Name FROM Schedule__c Limit 1].Id;
        List<Time_Period__c> timePeriodList = new List<Time_Period__c>();
        Time_Period__c tp;
        for(Integer timep= 0;timep<3;timep++){
            tp = new Time_Period__c(
        	Name='Test Time Period '+timep,
            Menu__c=menuId,
            Schedule__c=scheduleId);
            timePeriodList.add(tp);
        }
        UcfAutoAttendentController.saveTimePeriods(timePeriodList);
        //System.assertNotEquals(null, result);
    }
    @isTest
    static void testFtrDIDNumberDetailsAutoAttendants() {
        List<ftr_DID_Number_Details__c> result = UcfAutoAttendentController.ftrDIDNumberDetailsAutoAttendants();
        System.assertNotEquals(null, result);
    }

    @isTest
    static void testScheduleforAutoAttendantsSetUp() {
        List<Schedule__c> result = UcfAutoAttendentController.ScheduleforAutoAttendantsSetUp();
        System.assertNotEquals(null, result);
    }

    
    @isTest
    static void testScheduleforAutoAttendantsSchedules() {
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        List<Schedule__c> result = UcfAutoAttendentController.ScheduleforAutoAttendantsSchedules(orderId);
        System.assertNotEquals(null, result);

    }
    @isTest
    static void testgetMenuLines() {
        String menuId= [SELECT Id,Name FROM Menu__c where Name='Test Menu' LIMIT 1].Id;
        List<Menu_Line__c> result = UcfAutoAttendentController.getMenuLines(menuId);
        System.assertNotEquals(null, result);

    }
    
    @isTest
    static void testSaveMenuLines() {
        String menuId= [SELECT Id,Name FROM Menu__c where Name='Test Menu' LIMIT 1].Id;
		List<Menu_Line__c> menuLinesToUpdate=[SELECT Menu__c, Greeting__c FROM Menu_Line__c WHERE Menu__c =:menuId];
        String result = UcfAutoAttendentController.saveMenuLines(menuLinesToUpdate);
        System.assertEquals('Menu  Lines Updated Successfully', result);
    }
    @isTest
    static void testSaveMenuLinesError() {
        String menuId='';
		List<Menu_Line__c> menuLinesToUpdate=[SELECT Menu__c, Greeting__c FROM Menu_Line__c WHERE Menu__c =:menuId];
        String result = UcfAutoAttendentController.saveMenuLines(menuLinesToUpdate);
        System.assertEquals(result, result);
    }
    
    @isTest
    static void testUpdateMenuFields() {
        Menu__c testMenu= [SELECT Id,Name FROM Menu__c where Name='Test Menu' LIMIT 1];
        String menuId = testMenu.Id;
        String newGreetingName = 'New Greeting';
        String newMenuName = 'Updated Test Menu';
        String result = UcfAutoAttendentController.updateMenuFields(menuId, newGreetingName, newMenuName);
        System.assertEquals('Menu Updated Successfully', result);
        
    }
    @isTest
    static void testUpdateMenuFieldsError() {
        
        String menuId = '';
        String newGreetingName = 'New Greeting';
        String newMenuName = 'Updated Test Menu';
        String result = UcfAutoAttendentController.updateMenuFields(menuId, newGreetingName, newMenuName);
        System.assertEquals(result, result);
        
    }
    
    @isTest
    static void testInsertSchedule() {
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
		String scheduleName = 'Test Schedule';
        String RecordTypeId = 'Auto_Attendants';
        String result = UcfAutoAttendentController.insertSchedule(scheduleName, orderId, RecordTypeId);
		System.assertEquals('Schedule Created Succesfully', result);

    }
    @isTest
    static void testInsertScheduleError() {
        String orderId='';
		String scheduleName = 'Test Schedule';
        String RecordTypeId = 'Auto_Attendants';
        String result = UcfAutoAttendentController.insertSchedule(scheduleName, orderId, RecordTypeId);
		System.assertEquals(result, result);

    }
    
    @isTest
    static void testDeleteSchedule() {
        Id scheduleId=[SELECT Id, Name FROM Schedule__c Limit 1].Id;
        String result = UcfAutoAttendentController.deleteSchedule(scheduleId);
		System.assertEquals('Schedule deleted successfully', result);
    }
    @isTest
    static void testDeleteScheduleError() {
        String scheduleId='';
        String result = UcfAutoAttendentController.deleteSchedule(scheduleId);
		System.assertEquals(result, result);
    }
    @isTest
    static void testGreetingsforAutoAttendantsGreetings() {
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        List<Greetings__c> result = UcfAutoAttendentController.GreetingsforAutoAttendantsGreetings(orderId);
        System.assertNotEquals(null, result);
    }
    @isTest
    static void testInsertGreeting() {
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
		String greetingName = 'Test Schedule';
        //String RecordTypeId = [select id from recordtype where DeveloperName='Auto_Attendants' limit 1].id;
        String result = UcfAutoAttendentController.insertGreeting(greetingName, orderId);
		System.assertEquals('Greeting Created Succesfully', result);
    }
    @isTest
    static void testInsertGreetingError() {
        String orderId= '';
		String greetingName = 'Test Schedule';
        //String RecordTypeId = [select id from recordtype where DeveloperName='Auto_Attendants' limit 1].id;
        String result = UcfAutoAttendentController.insertGreeting(greetingName, orderId);
		System.assertEquals(result, result);
    }
    @isTest
    static void testDeleteGreeting(){
    	Id greetingId=[SELECT Id, Name FROM Greetings__c where name ='Test Greeting'].Id;
        String result = UcfAutoAttendentController.deleteGreeting(greetingId);
		system.assertEquals('Greetings deleted successfully',result);
    }
    
    @isTest
    static void testDeleteGreetingError(){
    	String greetingId='';
        String result = UcfAutoAttendentController.deleteGreeting(greetingId);
		system.assertEquals(result,result);
    }
    @isTest
    static void testGreetingforEdit(){
    	Id greetingId=[SELECT Id, Name FROM Greetings__c where name ='Test Greeting'].Id;
        Greetings__c result = UcfAutoAttendentController.greetingforEdit(greetingId);
        System.assertNotEquals(null, result);
    }
    
    @isTest
    static void testUpdateGreeting(){
    	Greetings__c greetingrec=[SELECT Id, Name,Message_Board__c FROM Greetings__c where name ='Test Greeting'];
        greetingrec.Message_Board__c= 'ABC';
        String result = UcfAutoAttendentController.UpdateGreeting(greetingrec);
		system.assertEquals('Greeting Updated Successfully',result);
    }
    @isTest
    static void testUpdateGreetingError(){
    	Greetings__c greetingrec = new Greetings__c(); 
        greetingrec.Message_Board__c= 'ABC';
        String result = UcfAutoAttendentController.UpdateGreeting(greetingrec);
		system.assertEquals(result,result);
    }
    @isTest
    static void testMenusforAutoAttendants() {
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        List<Menu__c> result = UcfAutoAttendentController.menusforAutoAttendants(orderId);
        System.assertNotEquals(null, result);
    }
    @isTest
    static void testInsertMenus() {
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
		String menuName = 'Test Menu 2';
        String result = UcfAutoAttendentController.insertMenus(menuName, orderId);
		System.assertEquals('Menu and Menu Lines Created Successfully', result);
    }
    @isTest
    static void testInsertMenusError() {
        String orderId= '';
		String menuName = 'Test Menu 2';
        String result = UcfAutoAttendentController.insertMenus(menuName, orderId);
		System.assertEquals(result, result);
    }
    @isTest
    static void testDeleteMenus(){
    	Id menuId=[SELECT Id, Name FROM Menu__c where name ='Test Menu'].Id;
        String result = UcfAutoAttendentController.deleteMenus(menuId);
		system.assertEquals('Menu deleted successfully',result);
    }
    @isTest
    static void testDeleteMenusError(){
    	String menuId='';
        String result = UcfAutoAttendentController.deleteMenus(menuId);
		system.assertNotEquals('Menu deleted successfully',result);
    }
    @isTest
    static void testgetTimePeriodData2() {
        Id didId=[select id from ftr_DID_Number_Details__c where Schedule__r.UCF_Name__c = 'Sample0' LIMIT 1].Id;
        List<UcfAutoAttendentController.TimePeriodWrapper> result = UcfAutoAttendentController.getTimePeriodData2(didId);
        System.assertNotEquals(null, result);
    }
    @isTest
    static void testgetTimePeriodData() {
        Id didId=[select id from ftr_DID_Number_Details__c where Schedule__r.UCF_Name__c = 'Sample0' LIMIT 1].Id;
        List<Time_Period__c> result = UcfAutoAttendentController.getTimePeriodData(didId);
        System.assertNotEquals(null, result);
    }
    @isTest
    static void testftrDIDNumberDetailsAutoAttendantsSetup() {
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        List<ftr_DID_Number_Details__c> result = UcfAutoAttendentController.ftrDIDNumberDetailsAutoAttendantsSetup(orderId);
        System.assertNotEquals(null, result);
    }
    @isTest
    static void testftrDIDNumberDetailsAutoAttendantsSetupError() {
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        List<ftr_DID_Number_Details__c> result = UcfAutoAttendentController.ftrDIDNumberDetailsAutoAttendantsSetup(orderId);
        System.assertNotEquals(null, result);
    }
    @isTest
    static void testScheduleforAutoAttendantSetUp() {
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        List<Schedule__c> result = UcfAutoAttendentController.ScheduleforAutoAttendantSetUp(orderId);
        System.assertNotEquals(null, result);
    }
    @isTest
    static void testScheduleforAutoAttendantSetUpError() {
        String orderId= 'ldskdsjdkjsdkj';
        List<Schedule__c> result = UcfAutoAttendentController.ScheduleforAutoAttendantSetUp(orderId);
        System.assertNotEquals(null, result);
    }
    /*
    @isTest
    static void testsaveTimePeriodRecords() {
        Id menuId=[SELECT Id, Name FROM Menu__c where name ='Test Menu'].Id;
        Id scheduleId=[SELECT Id, Name FROM Schedule__c Limit 1].Id;
        List<Time_Period__c> listTimePeriod =new List<Time_Period__c>();
        Time_Period__c timePeriod;
        for(integer i=0;i<3;i++){
        timePeriod = new Time_Period__c(
        	Name='Test Time Period '+i,
            Menu__c=menuId,
            Schedule__c=scheduleId);
            listTimePeriod.add(timePeriod);
        }
        List<Time_Period__c> result = UcfAutoAttendentController.saveTimePeriodRecords(listTimePeriod);
		System.assertNotEquals(NULL, result);
    }*/
    @isTest
    static void testAddHoliDays() {
        //Id menuId=[SELECT Id, Name FROM Menu__c where name ='Test Menu'].Id;
        Id scheduleId=[SELECT Id, Name FROM Schedule__c Limit 1].Id;
        List<Holiday__c> listHoliDays =new List<Holiday__c>();
        Holiday__c HoliDay;
        for(integer i=0;i<3;i++){
        HoliDay = new Holiday__c(
        	Name='Holiday '+i,
            Ucf_Menu__c='Holiday',
            Schedule__c=scheduleId);
            listHoliDays.add(HoliDay);
        }
        List<Holiday__c> result = UcfAutoAttendentController.addHoliDays(listHoliDays);
		System.assertNotEquals(NULL, result);
    }
    
    @isTest
    static void testupdateSchedule() {
        //Id menuId=[SELECT Id, Name FROM Menu__c where name ='Test Menu'].Id;
        Schedule__c schedule=[SELECT Id, Name FROM Schedule__c Limit 1];
        String menuName =[SELECT Id, Name FROM Menu__c WHERE Name = 'Test Menu' Limit 1].Name;
        Schedule__c result = UcfAutoAttendentController.updateSchedule(schedule,menuName,menuName,menuName,menuName);
		System.assertNotEquals(NULL, result);
    }
    
    @isTest
    static void test_getGreetings() {
        String orderId= [select id,Name from Order where Name = 'Sample Order' LIMIT 1].Id;
        List<Greetings__c> result = UcfAutoAttendentController.getGreetings(orderId);
        System.assertNotEquals(null, result);
    }
    
    @isTest
    static void test_getHolidaysBySchedule() {
        Id scheduleId=[SELECT Id, Name FROM Schedule__c Limit 1].Id;
        List<Holiday__c> result = UcfAutoAttendentController.getHolidaysBySchedule(scheduleId);
		System.assertNotEquals(NULL, result);
    }
    
    @isTest
    static void test_getHolidaysByScheduleId() {
        Id scheduleId=[SELECT Id, Name FROM Schedule__c Limit 1].Id;
        List<Holiday__c> result = UcfAutoAttendentController.getHolidaysByScheduleId(scheduleId);
		System.assertNotEquals(NULL, result);
    }
    
    @isTest
    static void test_updateAaSetupData(){
    	List<ftr_DID_Number_Details__c > didNumberRec=[SELECT Id,Name  FROM ftr_DID_Number_Details__c];
        UcfAutoAttendentController.updateAaSetupData(didNumberRec);
		//system.assertEquals('Greeting Updated Successfully',result);
    }
    
    
}