UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/BTN__c.field-meta.xml
<CustomField>
    <fullName>BTN__c</fullName>
    <label>BTN</label>
    <type>Phone</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Premise_Detail__c.field-meta.xml
<CustomField>
    <fullName>Premise_Detail__c</fullName>
    <formula>vlocity_cmt__PremisesId__r.Premise_Detail__c</formula>
    <label>Premise Detail</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_911_Option_Details__c/ftr_911_Option_Details__c.object-meta.xml
<CustomObject>
    <label>911 Option Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>911 Option Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_911_Option_Details__c/fields/DIDLocationDetailsId__c.field-meta.xml
<CustomField>
    <fullName>DIDLocationDetailsId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DID Location Details</label>
    <referenceTo>ftr_DID_Location_Details__c</referenceTo>
    <relationshipLabel>911 Option Details</relationshipLabel>
    <relationshipName>X911_Option_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_911_Option_Details__c/fields/FTR_911_Provider__c.field-meta.xml
<CustomField>
    <fullName>FTR_911_Provider__c</fullName>
    <label>FTR 911 Provider</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_911_Option_Details__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <label>911 Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Main Designated #</fullName>
            </value>
            <value>
                <fullName>ELIN/ERL</fullName>
            </value>
            <value>
                <fullName>PS/ALI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_911_Option_Details__c/fields/PremisesId__c.field-meta.xml
<CustomField>
    <fullName>PremisesId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premises</label>
    <referenceTo>vlocity_cmt__Premises__c</referenceTo>
    <relationshipLabel>911 Option Details</relationshipLabel>
    <relationshipName>X911_Option_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/ftr_DID_Location_Details__c.object-meta.xml
<CustomObject>
    <label>DID Location Details</label>
    <nameField>
        <label>DID Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Location Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/BTN__c.field-meta.xml
<CustomField>
    <fullName>BTN__c</fullName>
    <label>Billing Number (BTN)</label>
    <type>Phone</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/ConnectLineIDScreening__c.field-meta.xml
<CustomField>
    <fullName>ConnectLineIDScreening__c</fullName>
    <label>Connect Line ID Screening</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/IncomingCallerID__c.field-meta.xml
<CustomField>
    <fullName>IncomingCallerID__c</fullName>
    <label>Incoming Caller ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/InternationalDialingOptions__c.field-meta.xml
<CustomField>
    <fullName>InternationalDialingOptions__c</fullName>
    <label>International Dialing Options</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/MDN__c.field-meta.xml
<CustomField>
    <fullName>MDN__c</fullName>
    <label>Main Directory Number</label>
    <type>Phone</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/NumberOfCallPaths__c.field-meta.xml
<CustomField>
    <fullName>NumberOfCallPaths__c</fullName>
    <label>Number of Call Paths</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/NumberOfDIDs__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDIDs__c</fullName>
    <label>Number of DIDs for this location</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/PremisesId__c.field-meta.xml
<CustomField>
    <fullName>PremisesId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DID Location Premises</label>
    <referenceTo>vlocity_cmt__Premises__c</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/TestNumber__c.field-meta.xml
<CustomField>
    <fullName>TestNumber__c</fullName>
    <label>Customer Test #</label>
    <type>Phone</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/ftr_DID_Number_Details__c.object-meta.xml
<CustomObject>
    <label>DID Number Details</label>
    <nameField>
        <label>DID Number Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Number Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/DID_Number__c.field-meta.xml
<CustomField>
    <fullName>DID_Number__c</fullName>
    <label>DID Number (Unique)</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/DIDLocationDetailsId__c.field-meta.xml
<CustomField>
    <fullName>DIDLocationDetailsId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DID Location Details</label>
    <referenceTo>ftr_DID_Location_Details__c</referenceTo>
    <relationshipLabel>DID Number Details</relationshipLabel>
    <relationshipName>DID_Number_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/DIDNumberInfo__c.field-meta.xml
<CustomField>
    <fullName>DIDNumberInfo__c</fullName>
    <label>DID Number Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/RateCenter__c.field-meta.xml
<CustomField>
    <fullName>RateCenter__c</fullName>
    <label>Rate Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/ThirdParty__c.field-meta.xml
<CustomField>
    <fullName>ThirdParty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ThirdParty</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Current_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Current_Carrier__c</fullName>
    <label>Current Carrier</label>
    <length>52</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Number_Details__c/fields/Ucf_Install_Type__c.field-meta.xml
<CustomField>
    <fullName>Ucf_Install_Type__c</fullName>
    <label>Install Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New DID Range</fullName>
            </value>
            <value>
                <fullName>Port-In</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
            <value>
                <fullName>Existing # (Regrade)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/vlocity_cmt__Premises__c/objects/vlocity_cmt__Premises__c.object
<CustomObject>
    <fields>
        <fullName>Premise_Detail__c</fullName>
        <formula>IF(isBlank(vlocity_cmt__StreetAddress__c), &apos;&apos;,(vlocity_cmt__StreetAddress__c &amp; &quot;, &quot; &amp;  vlocity_cmt__City__c &amp; &quot;, &quot; &amp;  vlocity_cmt__State__c  &amp; &quot;  &quot; &amp;  vlocity_cmt__PostalCode__c))</formula>
        <label>Premise Detail</label>
        <type>Text</type>
    </fields>
    <label>Premises</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/classes/DIDNumberViewController.cls
public with sharing class DIDNumberViewController {

	public Boolean showSpinner { get; set; }
	public Boolean showDownload { get; set; }
	public Integer countOfDIDNumbers { get; set; }
	public ftr_DID_Location_Details__c didLocationDetails;
	public ftr_DID_Number_Details__c[] didNumbers;
	public List<ftr_DID_Number_Details__c[]> allDIDNumbers;
	public ftr_911_Option_Details__c[] x911Options;
	public Integer didNumberPageSize { get; set; }
	public Integer x911PageSize { get; set; }
    public Integer x911PageNumber { get; set; }
    public Integer didNumberPageNumber { get; set; }
	public String didLocationId { get; set; }
	public String productCode = 'SIP_TRUNKING_0010';
	public String renderAsExcel { get; set; }
	// public Map<String, Schema.SObjectField> qliLIFieldMap { get; set; }
	// public Map<String, Schema.SObjectField> product2FieldMap { get; set; }
	public class DIDNumberViewControllerException extends Exception {
	}

	public ftr_DID_Location_Details__c getDIDLocationDetails() {
		List<String> queryFields = new List<String>{
			'ServiceAccountId__r.vlocity_cmt__PremisesId__r.Premise_Detail__c',
			'Name',
			'PremisesId__r.Premise_Detail__c',
			'BTN__c',
			'TestNumber__c',
			'IncomingCallerID__c',
			'NumberOfCallPaths__c',
			'InternationalDialingOptions__c',
			'ConnectLineIDScreening__c',
			'MDN__c',
			'NumberOfDIDs__c'
		};
		return Database.query(
			'SELECT ' +
			String.join(queryFields, ', ') +
			' FROM ftr_DID_Location_Details__c WHERE Id =:didLocationId '
		);
	}
	public void setDIDLocationDetails(ftr_DID_Location_Details__c location) {
		this.didLocationDetails = location;
	}

	public ftr_DID_Number_Details__c[] getDIDNumbers() {
		List<String> queryFields = new List<String>{
			'DIDLocationDetailsId__r.ServiceAccountId__c',
			'DID_Number__c',
			'DIDNumberInfo__c',
			'Ucf_Current_Carrier__c',
			'Ucf_Install_Type__c',
			'ThirdParty__c',
			'RateCenter__c',
			'Feature__c',
			'CreatedDate',
			'CreatedBy.Name'
		};
		String baseQuery = 'SELECT ' + String.join(queryFields, ', ') + ' FROM ftr_DID_Number_Details__c WHERE DIDLocationDetailsId__c =:didLocationId ORDER BY DID_Number__c ';
		Integer offset = didNumberPageNumber * didNumberPageSize;
		String query = baseQuery + ' LIMIT '+ didNumberPageSize +' OFFSET '+ offset;
		countOfDIDNumbers = [SELECT COUNT() FROM ftr_DID_Number_Details__c WHERE DIDLocationDetailsId__c =:didLocationId ];
		return Database.query(query);
	}
	public void setDIDNumbers(ftr_DID_Number_Details__c[] didNumbers) {
		this.didNumbers = didNumbers;
	}

	public List<ftr_DID_Number_Details__c[]> getAllDIDNumbers() {
		List<String> queryFields = new List<String>{
			'DIDLocationDetailsId__r.ServiceAccountId__c',
			'DID_Number__c',
			'DIDNumberInfo__c',
			'Ucf_Current_Carrier__c',
			'Ucf_Install_Type__c',
			'ThirdParty__c',
			'RateCenter__c',
			'Feature__c',
			'CreatedDate',
			'CreatedBy.Name'
		};
		SObject[] records = Database.query(
			'SELECT ' +
			String.join(queryFields, ', ') +
			' FROM ftr_DID_Number_Details__c WHERE DIDLocationDetailsId__c =:didLocationId ORDER BY DID_Number__c LIMIT 30000 '
		);
		this.countOfDIDNumbers = records.size();
		return (List<List<ftr_DID_Number_Details__c>>) Lists.doPartions(records, 1000, List<List<ftr_DID_Number_Details__c>>.class);

	}
	public void setAllDIDNumbers(List<ftr_DID_Number_Details__c[]> didNumbers) {
		this.allDIDNumbers = didNumbers;
	}
	
	public ftr_911_Option_Details__c[] getX911Options() {
		List<String> queryFields = new List<String>{
			'Name',
			'PhoneNumber__c',
			'Option__c',
			'FTR_911_Provider__c',
			'PremisesId__r.Premise_Detail__c'
		};
		String baseQuery = 'SELECT ' + String.join(queryFields, ', ') + ' FROM ftr_911_Option_Details__c WHERE DIDLocationDetailsId__c =:didLocationId ';
		Integer offset = x911PageNumber * x911PageSize;
		String query = baseQuery + ' LIMIT '+ x911PageSize +' OFFSET '+ offset;
		return Database.query(query);
	}
	public void setX911Options(ftr_911_Option_Details__c[] options) {
		this.x911Options = options;
	}

	public DIDNumberViewController() {
		this.showSpinner = true;
		this.didNumberPageSize = 100;
		this.x911PageSize = 10;
		this.x911PageNumber = 0;
		this.didNumberPageNumber = 0;
		this.showDownload = ApexPages.currentPage().getParameters().get('showDownloadButton') == 'false' ? false : true;
		this.didLocationId = ApexPages.currentPage().getParameters().get('didLocationId');
	}

	public class TableColumn {
		public String label { get; set; }
		public String apiName { get; set; }
		public String type { get; set; }
		public TableColumn(Map<String,Object> fieldMap) {
			this.label = (String) fieldMap.get('label');
			this.apiName = (String) fieldMap.get('apiName');
			this.type = (String) fieldMap.get('type');
		}
	}

	public PageReference generateCSV() {
		this.renderAsExcel = 'application/vnd.ms-excel#DID Number Report - ' + Datetime.now().format().replaceAll('/', '-') + '.xls';
		PageReference pdfPage = Page.DIDNumberViewCSV;
		pdfPage.getParameters().put('didLocationId', this.didLocationId);
		pdfPage.getParameters().put('renderAsExcel', this.renderAsExcel);
		pdfPage.setRedirect(false);
		return pdfPage;
	}

	public PageReference generateUcfCSV() {
		this.renderAsExcel = 'application/vnd.ms-excel#UCF Number Report - ' + Datetime.now().format().replaceAll('/', '-') + '.xls';
		PageReference pdfPage = Page.UCFNumberViewCSV;
		pdfPage.getParameters().put('didLocationId', this.didLocationId);
		pdfPage.getParameters().put('renderAsExcel', this.renderAsExcel);
		pdfPage.setRedirect(false);
		return pdfPage;
	}

	public PageReference nextNumber(){
        didNumberPageNumber++;
        this.didNumbers = getDIDNumbers();
        return null;
    }
 
    public PageReference previousNumber(){
		if (didNumberPageNumber == 0) return null;
        didNumberPageNumber--;
		this.didNumbers = getDIDNumbers();
        return null;
    }

	// public PageReference nextOption(){
    //     x911PageNumber++;
    //     getX911Options();
    //     return null;
    // }
 
    // public PageReference previousOption(){
    //     x911PageNumber--;
    //     if (x911PageNumber < 0)
    //         return null;
    //     getX911Options();
    //     return null;
    // }
}