UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Channel_Affiliations__c.field-meta.xml
<CustomField>
    <fullName>Channel_Affiliations__c</fullName>
    <label>On-Boarding Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aggregators</fullName>
            </value>
            <value>
                <fullName>Big Box</fullName>
            </value>
            <value>
                <fullName>Commercial Agents</fullName>
            </value>
            <value>
                <fullName>Community Connections</fullName>
            </value>
            <value>
                <fullName>CROSS SELL</fullName>
            </value>
            <value>
                <fullName>Dealer Channel - Commercial</fullName>
            </value>
            <value>
                <fullName>DIGITAL PAID SEARCH</fullName>
            </value>
            <value>
                <fullName>Door to Door - Residential</fullName>
            </value>
            <value>
                <fullName>Event Manager</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Local Engagement</fullName>
            </value>
            <value>
                <fullName>NON-CHANNEL SUPPORT COMPANY</fullName>
            </value>
            <value>
                <fullName>Premier Retail</fullName>
            </value>
            <value>
                <fullName>Retail Agent - Residential</fullName>
            </value>
            <value>
                <fullName>Telemarketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_City__c.field-meta.xml
<CustomField>
    <fullName>Legal_City__c</fullName>
    <label>Legal City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_State__c.field-meta.xml
<CustomField>
    <fullName>Legal_State__c</fullName>
    <label>Legal State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_Street__c.field-meta.xml
<CustomField>
    <fullName>Legal_Street__c</fullName>
    <label>Legal Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Primary_ACNA__c.field-meta.xml
<CustomField>
    <fullName>Primary_ACNA__c</fullName>
    <label>Primary ACNA</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/Contract_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status__c</fullName>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Signed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Declined/Cancelled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Terminated by Frontier</fullName>
            </value>
            <value>
                <fullName>Terminated by Partner</fullName>
            </value>
            <value>
                <fullName>Terminated by Customer</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Redlined</fullName>
            </value>
            <value>
                <fullName>Sent Redline Document to Customer</fullName>
            </value>
            <value>
                <fullName>FTR Received Redline Document from Customer</fullName>
            </value>
            <value>
                <fullName>FTR Generated Final Clean Document</fullName>
            </value>
            <value>
                <fullName>AE sent Redline to Legal</fullName>
            </value>
            <value>
                <fullName>AE sent Redline to Risk Management</fullName>
            </value>
            <value>
                <fullName>AE sent Redline to Engineering</fullName>
            </value>
            <value>
                <fullName>Redline Approved by Legal</fullName>
            </value>
            <value>
                <fullName>Redline Approved by Risk Management</fullName>
            </value>
            <value>
                <fullName>Redline Approved</fullName>
            </value>
            <value>
                <fullName>Fully Signed</fullName>
            </value>
            <value>
                <fullName>Document Generated</fullName>
            </value>
            <value>
                <fullName>Document Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Awaiting for Customer Signature</fullName>
            </value>
            <value>
                <fullName>FTR Signed</fullName>
            </value>
            <value>
                <fullName>Sent Document back to Customer</fullName>
            </value>
            <value>
                <fullName>Up for Renewal</fullName>
            </value>
            <value>
                <fullName>Retirement</fullName>
            </value>
            <value>
                <fullName>Customer Requests Negotiations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Contract/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Document Generated</fullName>
            </value>
            <value>
                <fullName>Document Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Customer Signed / Awaiting Approval</fullName>
                <label>Customer Signed</label>
            </value>
            <value>
                <fullName>Pending Signature</fullName>
            </value>
            <value>
                <fullName>Signature Canceled</fullName>
            </value>
            <value>
                <fullName>Customer Redline</fullName>
            </value>
            <value>
                <fullName>Legal Redline</fullName>
            </value>
            <value>
                <fullName>Legal Approved</fullName>
            </value>
            <value>
                <fullName>Declined by Customer</fullName>
            </value>
            <value>
                <fullName>Sent Redline Document to Customer</fullName>
            </value>
            <value>
                <fullName>FTR Received Redline Document from Customer</fullName>
            </value>
            <value>
                <fullName>FTR Generated Final Clean Document</fullName>
            </value>
            <value>
                <fullName>AE sent Redline to Legal</fullName>
            </value>
            <value>
                <fullName>AE sent Redline to Risk Management</fullName>
            </value>
            <value>
                <fullName>AE sent Redline to Engineering</fullName>
            </value>
            <value>
                <fullName>Redline Approved by Legal</fullName>
            </value>
            <value>
                <fullName>Redline Approved by Risk Management</fullName>
            </value>
            <value>
                <fullName>Redline Approved</fullName>
            </value>
            <value>
                <fullName>Fully Signed</fullName>
            </value>
            <value>
                <fullName>Customer Declined</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Document Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Expected_Billed_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Billed_Date__c</fullName>
    <label>Expected Billed Date</label>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/SterlingQuote__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Object</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/SterlingQuoteItem__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Item</description>
    <label>Quote Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <label>Locality</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>SterlingQuote__r.OpportunityId__r.Id</formula>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/SA_StreetName__c.field-meta.xml
<CustomField>
    <fullName>SA_StreetName__c</fullName>
    <label>SA StreetName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/StateProvince__c.field-meta.xml
<CustomField>
    <fullName>StateProvince__c</fullName>
    <label>StateProvince</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/SterlingQuote__c.field-meta.xml
<CustomField>
    <fullName>SterlingQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>SterlingQuote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>SterlingQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/ftr_ContractTokenExtractorTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 2 
 * 
**/
@isTest
public class ftr_ContractTokenExtractorTest {
    @isTest static void testgetTokenData(){    
        User userObj = [Select Id from User where profile.Name = 'Frontier System Administrator' AND IsActive=true LIMIT 1];
        System.runAs(userObj){
            Id globalRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='global' LIMIT 1]?.Id;
        	Account globalAcc1 = new Account();
        	globalAcc1.Name = 'GLOBAL ACCOUNT';
        	globalAcc1.RecordTypeId = globalRecId;
        	//globalAcc.RecordTypeId = '012E0000000fDc3IAE';
        	insert globalAcc1;
        	Id MasterRTId =[SELECT id FROM RecordType WHERE RecordType.Name = 'Master' AND SobjectType = 'Account'].Id;
            Account ac = new Account();
            ac.RecordTypeId = MasterRTId;
			ac.ParentId = globalAcc1.Id;
            ac.Name = 'test Acc';
            ac.Legal_Street__c='test';
            ac.Legal_City__c='test';
            ac.Legal_State__c='test';
            ac.ShippingStreet='test';
            ac.ShippingCity='NY';
            ac.ShippingState='New York';
            ac.BillingStreet='test';
            ac.BillingCity='NY';
            ac.BillingState='New York';
            ac.Primary_ACNA__c = 'AB56';
            ac.Channel_Affiliations__c = 'DIGITAL PAID SEARCH';
            ac.Website = 'www.google.com';
            ac.Phone = '3456789398';
            insert ac;
            
            Opportunity op  = new Opportunity();
            op.AccountId=ac.Id;
            op.Name= 'test';
            op.StageName = 'Prospecting';
            op.CloseDate = Date.newInstance(2016, 12, 9);
            op.Expected_Billed_Date__c = date.today();
            insert op;
    
            SterlingQuote__c strQuote = new SterlingQuote__c();
            strQuote.OpportunityId__c = op.Id;
            strQuote.Name = 'testQuote';
            insert strQuote;
            
            SterlingQuoteItem__c strQuoteItem = new SterlingQuoteItem__c();
            strQuoteItem.Locality__c = 'Queens';
            strQuoteItem.SA_StreetName__c = 'test';
            strQuoteItem.Postcode__c = '67848';
            strQuoteItem.StateProvince__c = 'New York';
            strQuoteItem.SterlingQuote__c = strQuote.Id;
            insert strQuoteItem;
            
            
            Contract c = new Contract();
            c.Name = 'test';
            c.BillingStreet='test';
            c.BillingCity='NY';
            c.BillingState='New York';  
            c.BillingPostalCode = '45678';
            c.BillingCountry='United States';
            c.ShippingStreet='test';
            c.ShippingCity='NY';
            c.ShippingState='New York';  
            c.ShippingPostalCode = '45678';
            c.ShippingCountry='United States';
            c.AccountId = ac.Id;
            c.Status = 'draft';
            c.StartDate =  Date.newInstance(2016, 12, 9);
            c.ContractTerm = 12;
            c.Contract_Status__c ='Pending';
            c.Document_Status__c  ='Document Generated';
            c.vlocity_cmt__OpportunityId__c = op.id;
            c.Opportunity__c = op.id;
            c.ContractTerm = 24; 
            c.Phone__c = '2042164567'; 
            c.Schedule_Type__c = 'Frontier SmartVoice';
            c.StartDate = Date.today();
            c.PNUM__c = '45678';
            c.Requested_Install_Date__c = Date.newInstance(2016,12,12);
            insert c;
            
            Product2 p = new Product2(Name='Fake Name',IsActive=true, Description='This is fake');
            insert p;
            
            vlocity_cmt__ContractLineItem__c cli = new vlocity_cmt__ContractLineItem__c();
            cli.vlocity_cmt__ContractId__c = c.Id;
            cli.vlocity_cmt__Product2Id__c = p.Id;
            cli.Template_Name__c = 'FakeTemplate';
            cli.vlocity_cmt__OnetimeCharge__c = 100;
            cli.vlocity_cmt__Quantity__c = 2;
            cli.vlocity_cmt__RecurringCharge__c = 10;
            cli.vlocity_cmt__RecurringTotal__c = 10;
            cli.SterlingQuoteLineItem__c = strQuoteItem.Id;
            insert cli;
        
        
            Map<String,Object> input = new Map<String,Object>();
            Map<String,Object> output= new Map<String,Object>();
            Map<String,Object> option = new Map<String,Object>();
            input.put('contextId', c.Id);
            ftr_ContractTokenExtractor cte = new ftr_ContractTokenExtractor();
            Boolean check = (Boolean) cte.invokeMethod('getTokenData', input, output, option);
            System.assert(check);
        }
    }
    @isTest static void add2Decimals(){
        string testStr = ftr_ContractTokenExtractor.add2Decimals(12);
        System.assert(testStr == '12.00');
        testStr = ftr_ContractTokenExtractor.add2Decimals(12.1);
        System.assert(testStr == '12.10');
    }
}