UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/DSAT_Ticket__c.field-meta.xml
<CustomField>
    <fullName>DSAT_Ticket__c</fullName>
    <formula>vlocity_cmt__PremisesId__r.DSAT_Ticket__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DSAT Ticket #</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>The status of the customer&apos;s account such as active, inactive, suspended, pending or expired.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Copper_Tier__c.field-meta.xml
<CustomField>
    <fullName>Copper_Tier__c</fullName>
    <description>Created for E-Rate Section for Lisa Barrow case 00772157 6/2021</description>
    <label>Copper Tier</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/CPE_Product__c.field-meta.xml
<CustomField>
    <fullName>CPE_Product__c</fullName>
    <description>Asks Users to check whether a product in the opportunity is a CPE product.</description>
    <inlineHelpText>Must select if a CPE product is a component of the Opportunity being created.</inlineHelpText>
    <label>CPE Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Fiber_Tier__c.field-meta.xml
<CustomField>
    <fullName>Fiber_Tier__c</fullName>
    <description>Created for E-Rate Section for Lisa Barrow case 00772157 6/2021</description>
    <label>Fiber Tier</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/vlocity_cmt__Premises__c/objects/vlocity_cmt__Premises__c.object
<CustomObject>
    <fields>
        <fullName>Copper_Tier__c</fullName>
        <label>Copper Tier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>BDT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DSAT_Ticket__c</fullName>
        <externalId>true</externalId>
        <label>DSAT Ticket #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiber_Tier__c</fullName>
        <label>Fiber Tier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>BDT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_DSAT_Check__c</fullName>
        <label>Last DSAT Check</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>a</fullName>
                </value>
                <value>
                    <fullName>b</fullName>
                </value>
                <value>
                    <fullName>c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WC_QOS__c</fullName>
        <label>WC QOS</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WC_Speed__c</fullName>
        <label>WC Speed</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Address1__c</fullName>
        <description>Additional premises address information - 1.</description>
        <label>Street Supplement 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PostalCode__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Connected</fullName>
                    <default>true</default>
                    <label>Connected</label>
                </value>
                <value>
                    <fullName>Vacant</fullName>
                </value>
                <value>
                    <fullName>Install in Progress</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Premises</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/classes/RefreshDSATClassTest.cls
/**
* @author Rishu Singla
* @date 15 Oct 2019
* @group Vlocity Refresh DSAT Class
* @description Test class for logic needed for Refresh of DSAT Class 
* @version 1
*/  
@isTest
public class RefreshDSATClassTest {

    @isTest
    static void getRefreshAPIDetailsTest(){
        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>(); 
        Map<String, Object> inputMapToUpdate = new Map<String, Object>();
        
        String methodName='getRefreshAPIDetails';
        String methodName1='DSAT_AddLocation';
        RefreshDSATClass rdc = new RefreshDSATClass();
        vlocity_cmt.IntegrationProcedureService intgProSer = new vlocity_cmt.IntegrationProcedureService();
        
        // Create Account
        Id globalRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='global' LIMIT 1]?.Id;
		Account globalAcc1 = new Account();
		globalAcc1.Name = 'GLOBAL ACCOUNT';
		globalAcc1.RecordTypeId = globalRecId;
		//globalAcc.RecordTypeId = '012E0000000fDc3IAE';
		insert globalAcc1;
		Id MasterRTId =[SELECT id FROM RecordType WHERE RecordType.Name = 'Master' AND SobjectType = 'Account'].Id;
        Account testAccount = new Account();
        testAccount.RecordTypeId = MasterRTId;
		testAccount.ParentId = globalAcc1.Id;
        testAccount.Name = 'Test Account';
        testAccount.BillingStreet = '123 Main Street';
        testAccount.BillingCity = 'Anywhere';
        testAccount.BillingState = 'Ohio';
        testAccount.BillingPostalCode = '44088';
        testAccount.ShippingStreet = '123 Main Street';
        testAccount.ShippingCity = 'Anywhere';
        testAccount.ShippingState = 'Ohio';
        testAccount.ShippingPostalCode = '44088';
        insert testAccount;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'RefreshTestOpp';
        opp.AccountId = testAccount.id;
        Date d1=Date.newInstance(2019, 05, 11);
        opp.CloseDate=d1;
        opp.StageName='Investigating';
        opp.CPE_Product__c='No';
        insert opp;
        
        vlocity_cmt__Premises__c oPremise = new vlocity_cmt__Premises__c();
        oPremise.vlocity_cmt__Address1__c = '123 Main Street';
        oPremise.vlocity_cmt__City__c = 'Anywhere';
        oPremise.vlocity_cmt__State__c = 'California';
        oPremise.vlocity_cmt__PostalCode__c = '44076';
        oPremise.vlocity_cmt__Status__c = 'Connected';
        oPremise.DSAT_Ticket__c = '211212';
        oPremise.Copper_Tier__c = 'Tier 1';
        oPremise.Fiber_Tier__c = 'Tier 1';
        oPremise.Last_DSAT_Check__c = system.today();
        oPremise.WC_QOS__c = 'Platinum';
        oPremise.WC_Speed__c = '1000MB';
        oPremise.Market__c = 'B';
        oPremise.Level__c = 'a';
		insert oPremise;   
 
        input.put('ParentAccountId',opp.AccountId);
        input.put('ContextId',opp.Id);
        input.put('PremisesId', oPremise.Id);
        input.put('State','California');
        input.put('OpportunityId', opp.Id);
        
        //WHEN
        Test.startTest();
        Boolean bResult = rdc.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();
    }
}