UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/DSAT_Ticket__c.field-meta.xml
<CustomField>
    <fullName>DSAT_Ticket__c</fullName>
    <formula>vlocity_cmt__PremisesId__r.DSAT_Ticket__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DSAT Ticket #</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>The status of the customer&apos;s account such as active, inactive, suspended, pending or expired.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Copper_Tier__c.field-meta.xml
<CustomField>
    <fullName>Copper_Tier__c</fullName>
    <description>Created for E-Rate Section for Lisa Barrow case 00772157 6/2021</description>
    <label>Copper Tier</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/CPE_Product__c.field-meta.xml
<CustomField>
    <fullName>CPE_Product__c</fullName>
    <description>Asks Users to check whether a product in the opportunity is a CPE product.</description>
    <inlineHelpText>Must select if a CPE product is a component of the Opportunity being created.</inlineHelpText>
    <label>CPE Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Fiber_Tier__c.field-meta.xml
<CustomField>
    <fullName>Fiber_Tier__c</fullName>
    <description>Created for E-Rate Section for Lisa Barrow case 00772157 6/2021</description>
    <label>Fiber Tier</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Copper_Tier__c.field-meta.xml
<CustomField>
    <fullName>Copper_Tier__c</fullName>
    <label>Copper Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/DSAT_Ticket__c.field-meta.xml
<CustomField>
    <fullName>DSAT_Ticket__c</fullName>
    <description>Used to capture DSAT Ticket# from Premise</description>
    <label>DSAT Ticket #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Fiber_Tier__c.field-meta.xml
<CustomField>
    <fullName>Fiber_Tier__c</fullName>
    <label>Fiber Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>a</fullName>
            </value>
            <value>
                <fullName>b</fullName>
            </value>
            <value>
                <fullName>c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <description>This is used to store the attribute value selected for Speed.</description>
    <label>Speed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>Bound to Attribute = Term</description>
    <label>Term</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__ParentItemId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__ParentItemId__c</fullName>
    <description>ID of the parent Quote Line Item. Used by Vlocity CPQ to track the hierarchy of Items.</description>
    <label>ParentItemId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__PremisesId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__PremisesId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premises</label>
    <referenceTo>vlocity_cmt__Premises__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>QuoteLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DEPRECATED, Use the standard Product2Id field.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__RootItemId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__RootItemId__c</fullName>
    <description>ID of the ultimate, top-level parent Quote Line Item. Used by Vlocity CPQ to track a full tree of items.</description>
    <label>RootItemId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account that identifies the service location or subscriber that is the user of the service.</description>
    <label>Service Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>ServiceAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/WC_QOS__c.field-meta.xml
<CustomField>
    <fullName>WC_QOS__c</fullName>
    <label>WC QOS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/WC_Speed__c.field-meta.xml
<CustomField>
    <fullName>WC_Speed__c</fullName>
    <label>WC Speed</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/vlocity_cmt__Premises__c/objects/vlocity_cmt__Premises__c.object
<CustomObject>
    <fields>
        <fullName>Copper_Tier__c</fullName>
        <label>Copper Tier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>BDT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DSAT_Ticket__c</fullName>
        <externalId>true</externalId>
        <label>DSAT Ticket #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiber_Tier__c</fullName>
        <label>Fiber Tier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>BDT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_DSAT_Check__c</fullName>
        <label>Last DSAT Check</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>a</fullName>
                </value>
                <value>
                    <fullName>b</fullName>
                </value>
                <value>
                    <fullName>c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WC_QOS__c</fullName>
        <label>WC QOS</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WC_Speed__c</fullName>
        <label>WC Speed</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Address1__c</fullName>
        <description>Additional premises address information - 1.</description>
        <label>Street Supplement 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PostalCode__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Connected</fullName>
                    <default>true</default>
                    <label>Connected</label>
                </value>
                <value>
                    <fullName>Vacant</fullName>
                </value>
                <value>
                    <fullName>Install in Progress</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Premises</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/classes/CustomCartTest.cls
/**
* @author Nicole McGuire
* @date 14 Oct 2019
* @group Vlocity Custom Cart Implementation
* @description Test class for logic needed for roll-up/roll-down logic, pricing logic  
*/  
@isTest
public class CustomCartTest {
    @isTest
    static void testData() {
        CustomCart createCustomCart = new CustomCart();
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outputMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>(); 

        inputMap.put('cartId','0Q01k0000000l2sCAA');
        String methodName = 'putCartsItems.PreInvoke';

        Boolean bResult = createCustomCart.invokeMethod(methodName,inputMap,outputMap,options);
    }
    //     // Create Account
    //     Account testAccount = new Account();
    //     testAccount.Name = 'Test Account';
    //     testAccount.BillingStreet = '123 Main Street';
    //     testAccount.BillingCity = 'Anywhere';
    //     testAccount.BillingState = 'Ohio';
    //     testAccount.BillingPostalCode = '44088';
    //     testAccount.ShippingStreet = '123 Main Street';
    //     testAccount.ShippingCity = 'Anywhere';
    //     testAccount.ShippingState = 'Ohio';
    //     testAccount.ShippingPostalCode = '44088';
    //     insert testAccount;
        
    //     vlocity_cmt__Premises__c oPremise = new vlocity_cmt__Premises__c();
    //     oPremise.vlocity_cmt__Address1__c = '123 Main Street';
    //     oPremise.vlocity_cmt__City__c = 'Anywhere';
    //     oPremise.vlocity_cmt__State__c = 'California';
    //     oPremise.vlocity_cmt__PostalCode__c = '44076';
    //     oPremise.vlocity_cmt__Status__c = 'Connected';
    //     oPremise.DSAT_Ticket__c = '211212';
    //     oPremise.Copper_Tier__c = 'Tier 1';
    //     oPremise.Fiber_Tier__c = 'Tier 1';
    //     oPremise.Last_DSAT_Check__c = system.today();
    //     oPremise.WC_QOS__c = 'Platinum';
    //     oPremise.WC_Speed__c = '1000MB';
    //     oPremise.Market__c = 'B';
    //     oPremise.Level__c = 'a';
	// 	insert oPremise;
        
    //     Account testSAccount = new Account();
    //     testSAccount.Name = 'Test Service Account';
    //     testSAccount.BillingStreet = '123 Main Street';
    //     testSAccount.BillingCity = 'Anywhere';
    //     testSAccount.BillingState = 'Ohio';
    //     testSAccount.BillingPostalCode = '44088';
    //     testSAccount.ShippingStreet = '123 Main Street';
    //     testSAccount.ShippingCity = 'Anywhere';
    //     testSAccount.ShippingState = 'Ohio';
    //     testSAccount.ShippingPostalCode = '44088';
    //     testSAccount.vlocity_cmt__PremisesId__c = oPremise.id;
    //     insert testSAccount;
        
    //     Opportunity opp = new Opportunity();
    //     opp.Name = 'RefreshTestOpp';
    //     opp.AccountId = testAccount.id;
    //     Date d1=Date.newInstance(2019, 05, 11);
    //     opp.CloseDate=d1;
    //     opp.StageName='Investigating';
    //     opp.CPE_Product__c='No';
    //     insert opp;
        
    //     id pricebookId = Test.getStandardPricebookId();
    //     List<Product2> lstProduct2 = new List<Product2>();
    //     Product2 product = new Product2();
    //     product.Name = 'EIA';
    //     product.ProductCode = 'ENT_ETH_EIA_0001';
    //     product.IsActive = true;
    //     lstProduct2.add(product);

    //     Product2 prodEVC = new Product2();
    //     prodEVC.Name = 'EVC';
    //     prodEVC.ProductCode = 'ENT_ETH_EVC_0001';
    //     prodEVC.IsActive = true;
    //     lstProduct2.add(prodEVC);
        
    //     Product2 prodAccess = new Product2();
    //     prodAccess.Name = 'Access';
    //     prodAccess.ProductCode = 'ENT_ETH_ACCESS_0001';
    //     prodAccess.IsActive = true;
    //     lstProduct2.add(prodAccess);
	// 	//Insert products
    //     insert lstProduct2;  
        
    //     PricebookEntry standardPrice = new PricebookEntry(
    //         Pricebook2Id = pricebookId, 
    //         Product2Id = lstProduct2[0].Id,
    //         UnitPrice = 100, IsActive = true);
    //     insert standardPrice;
        
    //     Quote oQuote = new Quote();
    //     oQuote.Name = 'Testing Quote';
    //     oQuote.OpportunityId = Opp.id;
    //     oQuote.Pricebook2Id = pricebookId;
    //     insert oQuote;
        
    //     QuoteLineItem oQLI = new QuoteLineItem();
    //     oQLI.QuoteId = oQuote.id;
    //     oQLI.PricebookEntryId = standardPrice.id;
    //     oQLI.vlocity_cmt__ServiceAccountId__c = testSAccount.id;
    //     oQLI.Quantity = 1;
    //     oQLI.UnitPrice = 34.50;
    //     oQLI.Term__c = '36 Months';
    //     oQLI.vlocity_cmt__Product2Id__c = lstProduct2[0].Id;
    //     oQLI.Product2Id = lstProduct2[0].Id;
    //     insert oQLI;
        
    //     oQLI.vlocity_cmt__RootItemId__c = oQLI.id;
    //     update oQLI;
        
    //     QuoteLineItem oQLI2 = new QuoteLineItem();
    //     oQLI2.QuoteId = oQuote.id;
    //     oQLI2.PricebookEntryId = standardPrice.id;
    //     oQLI2.vlocity_cmt__RootItemId__c = oQLI.id;
    //     oQLI2.Speed__c = '20 Mbps';
    //     oQLI2.Quantity = 1;
    //     oQLI2.UnitPrice = 34.50;
    //     oQLI2.vlocity_cmt__ParentItemId__c = oQLI.id;
    //     oQLI2.vlocity_cmt__Product2Id__c = lstProduct2[1].Id;
    //     oQLI2.Product2Id = lstProduct2[1].Id;
    //     insert oQLI2;
        
    //     QuoteLineItem oQLI3 = new QuoteLineItem();
    //     oQLI3.QuoteId = oQuote.id;
    //     oQLI3.PricebookEntryId = standardPrice.id;
    //     oQLI3.Quantity = 1;
    //     oQLI3.UnitPrice = 34.50;
    //     oQLI3.vlocity_cmt__Product2Id__c = lstProduct2[2].Id;
    //     oQLI3.Product2Id = lstProduct2[2].Id;
    //     insert oQLI3;
    // }
    // @isTest
    // static void testPutCartsItems_PreInvoke(){
    //     Map<String, Object> inputMap = new Map<String, Object>();
    //     Map<String, Object> outputMap = new Map<String, Object>();
    //     Map<String, Object> options = new Map<String, Object>(); 

    //     Quote oQuote = [select id from Quote limit 1];
    //     inputMap.put('cartId',oQuote.Id);
    //     String methodName = 'putCartsItems.PreInvoke';
        
    //     CustomCart createCustomCart = new CustomCart();
    //     test.startTest();
    //     Boolean bResult = createCustomCart.invokeMethod(methodName,inputMap,outputMap,options);
    //     test.stopTest();
    //     system.assertEquals(true, bResult, 'Upon invoke expecting true on success.');
    // }
    
    // @isTest
    // static void testPutCartsItems_FalseInvoke(){
    //     Map<String, Object> inputMap = new Map<String, Object>();
    //     Map<String, Object> outputMap = new Map<String, Object>();
    //     Map<String, Object> options = new Map<String, Object>(); 

    //     Quote oQuote = [select id from Quote limit 1];
    //     inputMap.put('cartId',oQuote.Id);
    //     String methodName = 'putCartsItems.FalseInvoke';
        
    //     CustomCart createCustomCart = new CustomCart();
    //     test.startTest();
    //     Boolean bResult = createCustomCart.invokeMethod(methodName,inputMap,outputMap,options);
    //     test.stopTest();
    //     system.assertEquals(false, bResult, 'Upon invoke expecting false on success.');
    // }
    
    // @isTest
    // static void testPutCartsItems_BaseEIA(){
    //     Map<String, Object> inputMap = new Map<String, Object>();
    //     Map<String, Object> outputMap = new Map<String, Object>();
    //     Map<String, Object> options = new Map<String, Object>(); 

    //     Quote oQuote = [select id from Quote limit 1];
    //     inputMap.put('cartId',oQuote.Id);
    //     String methodName = 'putCartsItems.PostInvoke';
        
    //     CustomCart createCustomCart = new CustomCart();
    //     test.startTest();
    //     Boolean bResult = createCustomCart.invokeMethod(methodName,inputMap,outputMap,options);
    //     test.stopTest();
    //     system.assertEquals(true, bResult, 'Upon invoke expecting true on success.');
    // }
    
    // @isTest
    // static void testPutCartsItems_BaseEVPL(){
    //     Map<String, Object> inputMap = new Map<String, Object>();
    //     Map<String, Object> outputMap = new Map<String, Object>();
    //     Map<String, Object> options = new Map<String, Object>(); 

    //     Quote oQuote = [select id from Quote limit 1];
    //     Account testSAccount = [Select id from Account where Name = 'Test Service Account' limit 1];
    //     inputMap.put('cartId',oQuote.Id);
    //     String methodName = 'putCartsItems.PostInvoke';
        
    //     Product2 prodEVC = [Select id from Product2 where Name = 'EVC'];
    //     Product2 product = new Product2();
    //     product.Name = 'EVPL';
    //     product.ProductCode = 'ENT_ETH_EVPL_0001';
    //     product.IsActive = true;
    //     insert product;
        
    //     PricebookEntry standardPrice = [Select id from PricebookEntry];

    //     QuoteLineItem oQLI = new QuoteLineItem();
    //     oQLI.QuoteId = oQuote.id;
    //     oQLI.PricebookEntryId = standardPrice.id;
    //     oQLI.vlocity_cmt__ServiceAccountId__c = testSAccount.id;
    //     oQLI.Quantity = 1;
    //     oQLI.UnitPrice = 34.50;
    //     oQLI.Term__c = '36 Months';
    //     oQLI.vlocity_cmt__Product2Id__c = product.Id;
    //     oQLI.Product2Id = product.Id;
    //     insert oQLI;
        
    //     oQLI.vlocity_cmt__RootItemId__c = oQLI.id;
    //     update oQLI;
        
    //     QuoteLineItem oQLI2 = new QuoteLineItem();
    //     oQLI2.QuoteId = oQuote.id;
    //     oQLI2.PricebookEntryId = standardPrice.id;
    //     oQLI2.vlocity_cmt__RootItemId__c = oQLI.id;
    //     oQLI2.Speed__c = '20 Mbps';
    //     oQLI2.Quantity = 1;
    //     oQLI2.UnitPrice = 34.50;
    //     oQLI2.vlocity_cmt__ParentItemId__c = oQLI.id;
    //     oQLI2.vlocity_cmt__Product2Id__c = prodEVC.Id;
    //     oQLI2.Product2Id = prodEVC.Id;
    //     insert oQLI2;
        
    //     CustomCart createCustomCart = new CustomCart();
    //     test.startTest();
    //     Boolean bResult = createCustomCart.invokeMethod(methodName,inputMap,outputMap,options);
    //     test.stopTest();
    //     system.assertEquals(true, bResult, 'Upon invoke expecting true on success.');
    // }

}