UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <description>Updated/Created by Randy Gromlich for D&amp;B/MLR data 3/5/2020</description>
    <inlineHelpText>The angular distance north or south from the earth&apos;s equator measured through 90 degrees.</inlineHelpText>
    <label>Latitude</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <description>Updated/Created by Randy Gromlich for D&amp;B/MLR data 3/5/2020</description>
    <inlineHelpText>The angular distance east or west from the prime meridian measured through 180 degrees.</inlineHelpText>
    <label>Longitude</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <formula>RIGHT(Legal_Street__c,LEN(Legal_Street__c) - FIND(&quot; &quot;, Legal_Street__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Street Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAcna__c/FTRWSAcna__c.object-meta.xml
<CustomObject>
    <label>Wholesale ACNA</label>
    <nameField>
        <label>FTRWSAcna Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesale ACNAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAcna__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wholesale ACNAs</relationshipLabel>
    <relationshipName>Wholesale_ACNAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/FTRWSAddress__c.object-meta.xml
<CustomObject>
    <description>Custom table to store DPI and DSAT address qualification</description>
    <label>FTRWSAddress</label>
    <nameField>
        <label>FTRWSAddress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FTRWSAddress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Concatenated value of street number, street name, city, state and zip.</description>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/DPI_Validated__c.field-meta.xml
<CustomField>
    <fullName>DPI_Validated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set to true/false based on the address is DPI validated or not</description>
    <label>DPI Validated</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/DSAT_Validated__c.field-meta.xml
<CustomField>
    <fullName>DSAT_Validated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set to true/false based on the address is DSAT validated or not</description>
    <label>DSAT Validated</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <label>Opportunity ID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Service Addresses</relationshipLabel>
    <relationshipName>ServiceAddress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <description>Unit Number of DPI service address</description>
    <label>Unit Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSPnum__c/FTRWSPnum__c.object-meta.xml
<CustomObject>
    <label>Wholesale Pnum</label>
    <nameField>
        <label>FTRWSPnum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesale Pnums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSPnum__c/fields/Wholesale_ACNA__c.field-meta.xml
<CustomField>
    <fullName>Wholesale_ACNA__c</fullName>
    <label>Wholesale ACNA</label>
    <referenceTo>FTRWSAcna__c</referenceTo>
    <relationshipLabel>Wholesale Pnums</relationshipLabel>
    <relationshipName>Wholesale_Pnums</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Wholesale_ACNA__c.field-meta.xml
<CustomField>
    <fullName>Wholesale_ACNA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACNA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>FTRWSAcna__c.Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FTRWSAcna__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Wholesale_Pnum__c.field-meta.xml
<CustomField>
    <fullName>Wholesale_Pnum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PNUM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Wholesale_ACNA__c</field>
            <operation>equals</operation>
            <valueField>FTRWSPnum__c.Wholesale_ACNA__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FTRWSPnum__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Product2/fields/evcspeed__c.field-meta.xml
<CustomField>
    <fullName>evcspeed__c</fullName>
    <label>EVC Speed</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Product2/fields/mrcusoc__c.field-meta.xml
<CustomField>
    <fullName>mrcusoc__c</fullName>
    <label>MRC Usoc</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/FTRWSMultipleFileUploaderBatchTest.cls
// version 1
@isTest
global class FTRWSMultipleFileUploaderBatchTest { 
    
    @testSetup static void methodName() { 
        
        Account acc = new Account();
        acc.Name='testAccount';
        insert acc;
        
        Product2 product = new Product2();
        product.Name = 'EPATH 1000M Silver';
        product.evcspeed__c = '1000M';
        product.Family = 'EPATH';
        product.Quantity__c = '1';
        product.mrcusoc__c = 'EPATHUSOC';
        
        insert product;
        
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = product.Id,UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        
        PricebookEntry priceEntrylist = new PricebookEntry(Pricebook2Id = customPB.Id, Product2Id = product.Id,UnitPrice = 12000, IsActive = true);
        insert priceEntrylist;
        
        FTRWSAcna__c acna = new FTRWSAcna__c();
        acna.Name='ATX';
        acna.Company__c = acc.id;
        insert acna;
        
        FTRWSPnum__c pnum = new FTRWSPnum__c();
        pnum.Name='EIA001';
        pnum.Wholesale_ACNA__c = acna.id;
        insert pnum;
        
        Opportunity opp = new Opportunity();
        opp.Name='Test Opp';
        opp.StageName='Decision';
        opp.AccountId=acc.id;
        opp.Wholesale_ACNA__c=acna.id;
        opp.Wholesale_Pnum__c=pnum.id;
        opp.CloseDate= System.today();
        opp.ForecastCategoryName='Commit';
        insert opp;
        
        FTRWSAddress__c adr= new FTRWSAddress__c();
        adr.Address__c = '1 BROOKLYN RD' +' '+'FREEVILLE'+' '+'NY'+' '+'13068';
        adr.Name = '1 BROOKLYN RD' +' '+'FREEVILLE'+' '+'NY'+' '+'13068';
        adr.Street__c = '1 BROOKLYN RD';
        adr.Street_Name__c='1 BROOKLYN RD';            
        adr.City__c  = 'FREEVILLE';
        adr.State__c = 'NY';
        adr.Zip_Code__c = '13068';
        adr.Latitude__c = '';
        adr.Longitude__c =  '';
        adr.Unit_Number__c  = '';
        adr.Opportunity_ID__c = opp.Id;
        adr.DPI_Validated__c = False;
        adr.DSAT_Validated__c = False;
        adr.Comments__c='';
        insert adr;
        
    }
     
        
    
    public static TestMethod void execute(){
        Test.startTest();

        Test.setMock(WebServiceMock.class, new FTRWSDPIAddressValResultMock());
        Test.setMock(HttpCalloutMock.class, new FTRWSDSATAddressControllerPostMock());
        Test.stopTest();
        
    }
    

}