UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_City__c.field-meta.xml
<CustomField>
    <fullName>Legal_City__c</fullName>
    <label>Legal City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_Country1__c.field-meta.xml
<CustomField>
    <fullName>Legal_Country1__c</fullName>
    <label>Legal Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas, The</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Burma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_State__c.field-meta.xml
<CustomField>
    <fullName>Legal_State__c</fullName>
    <label>Legal State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_Street__c.field-meta.xml
<CustomField>
    <fullName>Legal_Street__c</fullName>
    <label>Legal Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_Zip__c.field-meta.xml
<CustomField>
    <fullName>Legal_Zip__c</fullName>
    <label>Legal Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This is the describe the SEER/SRQ on the Oppt</description>
    <inlineHelpText>In detail please communicate to the best of your ability the scope of work for this opportunity.</inlineHelpText>
    <label>Description for SEER</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Description_of_customer_needs__c.field-meta.xml
<CustomField>
    <fullName>Description_of_customer_needs__c</fullName>
    <label>Description of customer needs</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Lead_Product_List__c.field-meta.xml
<CustomField>
    <fullName>Lead_Product_List__c</fullName>
    <label>Lead Product List</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cloud IT</fullName>
            </value>
            <value>
                <fullName>Connect Cloud</fullName>
            </value>
            <value>
                <fullName>CPE</fullName>
            </value>
            <value>
                <fullName>Enterprise WiFi</fullName>
            </value>
            <value>
                <fullName>Ethernet</fullName>
            </value>
            <value>
                <fullName>FAW UCaaS</fullName>
            </value>
            <value>
                <fullName>Fiber 1gb</fullName>
            </value>
            <value>
                <fullName>Fiber 2gb</fullName>
            </value>
            <value>
                <fullName>Fiber 500mb</fullName>
            </value>
            <value>
                <fullName>Fiber 700mmb</fullName>
            </value>
            <value>
                <fullName>Fiber Office</fullName>
            </value>
            <value>
                <fullName>FiOS or BHSI</fullName>
                <label>FiberOptic or BHSI</label>
            </value>
            <value>
                <fullName>Frontier Calling with Cloud Phone</fullName>
                <label>Frontier Direct Calling</label>
            </value>
            <value>
                <fullName>HBE</fullName>
            </value>
            <value>
                <fullName>HSI 12m</fullName>
            </value>
            <value>
                <fullName>HSI 3m</fullName>
            </value>
            <value>
                <fullName>HSI 45m</fullName>
            </value>
            <value>
                <fullName>Managed Firewall</fullName>
            </value>
            <value>
                <fullName>Managed Network Services</fullName>
            </value>
            <value>
                <fullName>Premium Tech Pro</fullName>
            </value>
            <value>
                <fullName>Ring Central</fullName>
            </value>
            <value>
                <fullName>SD-WAN</fullName>
            </value>
            <value>
                <fullName>Secure Pro</fullName>
            </value>
            <value>
                <fullName>Simply WiFi Secure</fullName>
            </value>
            <value>
                <fullName>SIP Trunking</fullName>
            </value>
            <value>
                <fullName>Smart Voice</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>Voice (TDM)</fullName>
            </value>
            <value>
                <fullName>Voice Product - Business Voice</fullName>
            </value>
            <value>
                <fullName>Voice Product - OneVoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/New_Logo__c.field-meta.xml
<CustomField>
    <fullName>New_Logo__c</fullName>
    <label>New Logo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <description>Opportunity Type defines if the opportunity is classified as existing, new, renewal or winback.</description>
    <inlineHelpText>New – New logo or New product existing customer
Existing – Renewal or Product changes
Renewal – Straight renewal
Winback - (Do not use)</inlineHelpText>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Partner_Sales_Stages__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sales_Stages__c</fullName>
    <label>Sales Stage (Partner)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed/Lost</fullName>
            </value>
            <value>
                <fullName>Closed/Won</fullName>
            </value>
            <value>
                <fullName>Decision</fullName>
            </value>
            <value>
                <fullName>Evaluating</fullName>
            </value>
            <value>
                <fullName>Defining</fullName>
                <isActive>false</isActive>
                <label>Defining</label>
            </value>
            <value>
                <fullName>Evaluation</fullName>
                <isActive>false</isActive>
                <label>Evaluation</label>
            </value>
            <value>
                <fullName>Evaulating</fullName>
                <isActive>false</isActive>
                <label>Evaulating</label>
            </value>
            <value>
                <fullName>Investigating</fullName>
                <isActive>false</isActive>
                <label>Investigating</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Service_Address__c</fullName>
    <description>This field is for SEER section in the Oppt. To record the Address. This is the same as the service address on the SRQ.</description>
    <label>Service Address for SEER</label>
    <type>TextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Service_Zip_code__c.field-meta.xml
<CustomField>
    <fullName>Service_Zip_code__c</fullName>
    <label>Service Zip code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/recordTypes/Community_Connections.recordType-meta.xml
<RecordType>
    <fullName>Community_Connections</fullName>
    <active>true</active>
    <businessProcess>Community Connections</businessProcess>
    <description>Only used for Alt Channel MDU Team</description>
    <label>Community Connections</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/classes/newQualifiedQuoteLAC_Controller_Test.cls
@IsTest 
public class newQualifiedQuoteLAC_Controller_Test {
    @IsTest
    private static Void newQualifiedQuoteLAC_Controller_Test(){
        // Get the RecordType Id of the 'Global' Account RecordType
        Id globalRecId = [
            SELECT  Id,
                    DeveloperName
            FROM    RecordType
            WHERE   SObjectType = 'Account'
            AND     DeveloperName = 'Global'
            LIMIT   1
        ]?.Id;
        // Create a new 'Global' Account with the above RecordType
        Account globalAcc1 = new Account(
            Name = 'GLOBAL ACCOUNT',
            RecordTypeId = globalRecId
        );
        insert globalAcc1;
        // Get the RecordType Id of the 'Master' Account RecordType
        Id masterRTId = [
            SELECT  Id,
                    DeveloperName
            FROM    RecordType
            WHERE   SObjectType = 'Account'
            AND     DeveloperName = 'Master'
            LIMIT   1
        ]?.Id;
        // Create a new 'Master' Account with the above RecordType and the 'Global' Account as its parent
        Account masterAcc = new Account(
            Name = 'Master Account',
            RecordTypeId = masterRTId,
            ParentId = globalAcc1.Id
        );
        insert masterAcc;

        Account acc = new Account(Name = 'Test Account',BillingStreet='23100 Avenue San Luis',BillingCity= 'WoodLandHills',ParentId = globalAcc1.Id,
                    BillingState= 'California',BillingCountry ='United States',BillingPostalCode ='91364',Legal_Street__c ='23100 Avenue San Luis',
                    Legal_City__c='WOODLAND HILLS',Legal_State__c='California',Legal_Zip__c ='91364',Legal_Country1__c='United States',ShippingStreet='23100 Avenue San Luis',
                    ShippingCity='WODLAND',ShippingState='California',ShippingCountry='United States',ShippingPostalCode ='91364');
        insert acc;

        // Get the RecordType Id of the 'Community_Connections' Opportunity RecordType
        Id opRecordTypeId = [
            SELECT  Id,
                    DeveloperName
            FROM    RecordType
            WHERE   SObjectType = 'Opportunity'
            AND     DeveloperName = 'Community_Connections'
            LIMIT   1
        ]?.Id;

        // Create a new Opportunity with the 'Community_Connections' RecordType and add it to the 'old' map
        Opportunity opp = new Opportunity(
            Name = 'TestCTOppty',
            AccountId = acc.Id,
            Opportunity_Type__c = 'New',
            Partner_Sales_Stages__c = 'Decision',
            CloseDate = System.today(),
            ForecastCategoryName = 'Commit',
            Campaign__c = 'No',
            New_Logo__c = 'No',
            StageName = 'Decision',
            Lead_Product_List__c = 'Managed Firewall',
            Description_of_customer_needs__c = 'Test SEER',
            Description__c = 'Test for SEER',
            Service_Address__c = '2111 Cannes, Dallas, TX',
            Service_Zip_code__c = '90605',
            RecordTypeId = opRecordTypeId
        );
        insert opp;

        NewQualifiedQuoteLAC_Controller.quoteEdit_SterlingCPQ(opp.Id);
        NewQualifiedQuoteLAC_Controller.reDirectToSterling(opp.Id,'Billing Address');
        NewQualifiedQuoteLAC_Controller.reDirectToSterling(opp.Id,'Legal Address');
        NewQualifiedQuoteLAC_Controller.reDirectToSterling(opp.Id,'Service Address');
        NewQualifiedQuoteLAC_Controller.reDirectToSterling(opp.Id,'None');
    } 
}