UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_City__c.field-meta.xml
<CustomField>
    <fullName>Legal_City__c</fullName>
    <label>Legal City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_State__c.field-meta.xml
<CustomField>
    <fullName>Legal_State__c</fullName>
    <label>Legal State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Legal_Street__c.field-meta.xml
<CustomField>
    <fullName>Legal_Street__c</fullName>
    <label>Legal Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Bypass_Validation__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is to BypassValidation rules created for the OPPT. As they are interfering when the lead is converted.</description>
    <label>Bypass Validation</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Expected_Billed_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Billed_Date__c</fullName>
    <label>Expected Billed Date</label>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/SterlingQuote__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Object</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/SterlingQuoteItem__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Item</description>
    <label>Quote Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/SterlingQuote__c.field-meta.xml
<CustomField>
    <fullName>SterlingQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>SterlingQuote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>SterlingQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/SterlingQuoteItemTriggerHandler_Test.cls
/**
* @description       : This test class covers the following Apex classes:
*      TBD_CLASS1
*      TBD_CLASS2
*      TBD_CLASS3
* @author            : TBD
* @version           : 1 
**/
@isTest
public class SterlingQuoteItemTriggerHandler_Test {
    @TestSetup
    static void makeData(){
        aps_VlocityQuoteHandler.stopTrigger = true;
        Id globalRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='global' LIMIT 1]?.Id;
        Account globalAcc = new Account();
        globalAcc.Name = 'GLOBAL ACCOUNT';
        globalAcc.RecordTypeId = globalRecId;
        insert globalAcc;
        Account objAcc = new Account();
        objAcc.Name ='testing Name';
        objAcc.Legal_Street__c='test';
        objAcc.Legal_City__c='test';
        objAcc.Legal_State__c='test';
        objAcc.ShippingStreet='test';
        objAcc.ShippingCity='NY';
        objAcc.ShippingState='New York';
        objAcc.BillingStreet='test';
        objAcc.BillingCity='NY';
        objAcc.BillingState='New York';
        objAcc.ParentId = globalAcc.Id;
        insert objAcc; 
        Opportunity testOpp = new Opportunity();
        testOpp.Name ='Test 1';
        testOpp.AccountId= objAcc.Id;
        testOpp.CloseDate = date.today();
        testOpp.StageName ='Investigating';
        testOpp.Expected_Billed_Date__c = date.today();
        testOpp.Bypass_Validation__c = true;
        testOpp.Pricebook2Id = Test.getStandardPricebookId();
        insert testOpp;
    }
   /* @isTest
    private static void sqiTriggerHandlerTest() {
        aps_VlocityQuoteHandler.stopTrigger = true;
        Opportunity testOpp = [SELECT Id,Name,StageName,CloseDate,Pricebook2Id FROM Opportunity LIMIT 1];
        Test.startTest();
        SterlingQuote__c testQuote = Test_Fixture_Factory.createTestQuote(testOpp.Id, '', '');
        List<SterlingQuoteItem__c> items = [SELECT Id, Quantity__c FROM SterlingQuoteItem__c WHERE SterlingQuote__c = :testQuote.Id];
        for (SterlingQuoteItem__c item : items) {
            item.Quantity__c = 2;
        }
        update items;
        Test.stopTest();
    }*/
    
    @isTest
    private static void sqiTriggerHandlerTest2() {
        aps_VlocityQuoteHandler.stopTrigger = true;
        Opportunity testOpp = [SELECT Id,Name,StageName,CloseDate,Pricebook2Id FROM Opportunity LIMIT 1];
        
        SterlingQuote__c testQuote = Test_Fixture_Factory.createTestQuote(testOpp.Id, '', '', false);
        List<SterlingQuoteItem__c> items = [SELECT Id, Quantity__c FROM SterlingQuoteItem__c WHERE SterlingQuote__c = :testQuote.Id LIMIT 1];
        for (SterlingQuoteItem__c item : items) {
            item.Quantity__c = 2;
        }
        Test.startTest();
        update items;
        delete items;
        Test.stopTest();
    }
}