UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Premise_Detail__c.field-meta.xml
<CustomField>
    <fullName>Premise_Detail__c</fullName>
    <formula>vlocity_cmt__PremisesId__r.Premise_Detail__c</formula>
    <label>Premise Detail</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/ftr_DID_Location_Details__c.object-meta.xml
<CustomObject>
    <label>DID Location Details</label>
    <nameField>
        <label>DID Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DID Location Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_DID_Location_Details__c/fields/ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DID Location Details</relationshipLabel>
    <relationshipName>DID_Location_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_EVC_Location_Details__c/ftr_EVC_Location_Details__c.object-meta.xml
<CustomObject>
    <label>EVC Location Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EVC Location Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_EVC_Location_Details__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>EVC Details for</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>EVC Location Details</relationshipLabel>
    <relationshipName>EVC_Location_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_UNI_Location_Details__c/ftr_UNI_Location_Details__c.object-meta.xml
<CustomObject>
    <label>UNI Location Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UNI Location Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_UNI_Location_Details__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UNI Details for</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>UNI Location Details</relationshipLabel>
    <relationshipName>ftr_UNI_Location_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/OrderItem/fields/Premise_Detail__c.field-meta.xml
<CustomField>
    <fullName>Premise_Detail__c</fullName>
    <formula>vlocity_cmt__ServiceAccountId__r.vlocity_cmt__PremisesId__r.Premise_Detail__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Premise Detail</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/SIPSummaryController.cls
public with sharing class SIPSummaryController {

	public Boolean showSpinner { get; set; }
	public List<DataWrapper> allData;
	public String recordId { get; set; }
	public String productCode = 'SIP_TRUNKING_0010';
	// public Map<String, Schema.SObjectField> qliLIFieldMap { get; set; }
	// public Map<String, Schema.SObjectField> product2FieldMap { get; set; }
	public class SIPSummaryControllerException extends Exception {
	}

	public SIPSummaryController() {
		this.showSpinner = true;
		this.recordId = ApexPages.currentPage().getParameters().get('id');
	}

	public void setAllData(List<DataWrapper> lst) {
		this.allData = lst;
	}

	public List<DataWrapper> getAllData() {
		try {
			this.allData = new List<DataWrapper>();
			Map<String, List<ftr_UNI_Location_Details__c>> uniDetailsMap = new Map<String, List<ftr_UNI_Location_Details__c>>();
			Map<String, List<ftr_EVC_Location_Details__c>> evcDetailsMap = new Map<String, List<ftr_EVC_Location_Details__c>>();
			Map<String, List<ftr_DID_Location_Details__c>> didDetailsMap = new Map<String, List<ftr_DID_Location_Details__c>>();

			// get service account map
			List<Account> serviceAccounts = [
				SELECT Id, vlocity_cmt__PremisesId__r.Premise_Detail__c
				FROM Account
				WHERE
					ID IN (
						SELECT vlocity_cmt__ServiceAccountId__c
						FROM OrderItem
						WHERE OrderId = :recordId AND vlocity_cmt__Product2Id__r.ProductCode = :productCode
					)
			];

			// UNI Details
			SObject[] uniDetails = Database.query(
				'SELECT Id, OrderItem__r.vlocity_cmt__ServiceAccountId__c FROM ftr_UNI_Location_Details__c WHERE OrderItem__r.OrderId =:recordId Order by Name'
			);
			for (ftr_UNI_Location_Details__c record : (ftr_UNI_Location_Details__c[]) uniDetails) {
				if (uniDetailsMap.containsKey(record.OrderItem__r.vlocity_cmt__ServiceAccountId__c)) {
					uniDetailsMap.get(record.OrderItem__r.vlocity_cmt__ServiceAccountId__c).add(record);
				} else {
					uniDetailsMap.put(record.OrderItem__r.vlocity_cmt__ServiceAccountId__c, new List<ftr_UNI_Location_Details__c>{ record });
				}
			}

			// // DID Details
			// SObject[] didDetails = Database.query(
			// 	'SELECT Id, ServiceAccountId__c FROM ftr_did_Location_Details__c WHERE OrderId__c =:recordId '
			// );
			// for (ftr_did_Location_Details__c record : (ftr_did_Location_Details__c[]) didDetails) {
			// 	if (didDetailsMap.containsKey(record.ServiceAccountId__c)) {
			// 		didDetailsMap.get(record.ServiceAccountId__c).add(record);
			// 	} else {
			// 		didDetailsMap.put(record.ServiceAccountId__c, new List<ftr_did_Location_Details__c>{ record });
			// 	}
			// }

			// EVC Details
			SObject[] evcDetails = Database.query(
				'SELECT Id, OrderItem__r.vlocity_cmt__ServiceAccountId__c FROM ftr_EVC_Location_Details__c WHERE OrderItem__r.OrderId =:recordId  Order by Name '
			);
			for (ftr_EVC_Location_Details__c record : (ftr_EVC_Location_Details__c[]) evcDetails) {
				if (evcDetailsMap.containsKey(record.OrderItem__r.vlocity_cmt__ServiceAccountId__c)) {
					evcDetailsMap.get(record.OrderItem__r.vlocity_cmt__ServiceAccountId__c).add(record);
				} else {
					evcDetailsMap.put(record.OrderItem__r.vlocity_cmt__ServiceAccountId__c, new List<ftr_EVC_Location_Details__c>{ record });
				}
			}

			// Put data into wrapper for display
			for (Account servAcc : serviceAccounts) {
				this.allData.add(new DataWrapper(servAcc, uniDetailsMap.get(servAcc.Id), evcDetailsMap.get(servAcc.Id)));
			}
		} catch (Exception e) {
			System.debug(e.getMessage());
			System.debug(e.getStackTraceString());
			throw new SIPSummaryControllerException(e.getMessage());
		} finally {
			this.showSpinner = false;
		}

		// this.allData.sort();

		return this.allData;
	}

	public class DataWrapper {
		public String serviceAccount { get; set; }
		public ftr_UNI_Location_Details__c[] uniDetails { get; set; }
		public ftr_EVC_Location_Details__c[] evcDetails { get; set; }

		public DataWrapper(Account servAcc, ftr_UNI_Location_Details__c[] unis, ftr_EVC_Location_Details__c[] evcs) {
			this.uniDetails = unis;
			this.evcDetails = evcs;
			this.serviceAccount = servAcc.vlocity_cmt__PremisesId__r.Premise_Detail__c;
		}
	}

}