UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B1 / POTS</fullName>
                <default>true</default>
                <label>B1 / POTS</label>
            </value>
            <value>
                <fullName>Long Distance (Switched)</fullName>
            </value>
            <value>
                <fullName>Toll Free</fullName>
            </value>
            <value>
                <fullName>DSL</fullName>
            </value>
            <value>
                <fullName>Centrex/Centranet</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
            <value>
                <fullName>Voice Mail &amp; additional</fullName>
            </value>
            <value>
                <fullName>Features on existing service</fullName>
            </value>
            <value>
                <fullName>Analog Trunks</fullName>
            </value>
            <value>
                <fullName>IP Address Changes</fullName>
            </value>
            <value>
                <fullName>ISDN BRI</fullName>
            </value>
            <value>
                <fullName>ISDN PRI</fullName>
            </value>
            <value>
                <fullName>MIPT (area specific product)</fullName>
            </value>
            <value>
                <fullName>DIA T1 w/out router</fullName>
            </value>
            <value>
                <fullName>EIA Metro-E</fullName>
            </value>
            <value>
                <fullName>SIP Trunking</fullName>
            </value>
            <value>
                <fullName>IP Connect</fullName>
            </value>
            <value>
                <fullName>Metro-E Upgrade</fullName>
            </value>
            <value>
                <fullName>SONET</fullName>
            </value>
            <value>
                <fullName>Frame Relay</fullName>
            </value>
            <value>
                <fullName>Private Line DS1 (On-Net)</fullName>
            </value>
            <value>
                <fullName>Dedicated PL</fullName>
            </value>
            <value>
                <fullName>Wireless Hot Spots</fullName>
            </value>
            <value>
                <fullName>Wireless Anchor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <description>Opportunity Type defines if the opportunity is classified as existing, new, renewal or winback.</description>
    <inlineHelpText>New – New logo or New product existing customer
Existing – Renewal or Product changes
Renewal – Straight renewal
Winback - (Do not use)</inlineHelpText>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Renewal_MRR__c.field-meta.xml
<CustomField>
    <fullName>Renewal_MRR__c</fullName>
    <label>Renewal MRR</label>
    <summarizedField>OpportunityLineItem.Total_Renewal_MRR__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/OpportunityLineItem/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <description>This field is used for the hybrid opportunity initiative. Holds the configured speed value of the product.</description>
    <label>Speed</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/DGF__c.field-meta.xml
<CustomField>
    <fullName>DGF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data Gathering Form (DGF)</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DGF__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.OpportunityId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DGF__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cloud Managed Solutions</fullName>
            </value>
            <value>
                <fullName>CMS - Existing or BYOA</fullName>
            </value>
            <value>
                <fullName>CMS - New or Upgrade Ethernet</fullName>
            </value>
            <value>
                <fullName>CMS - New or Upgrade FiOS/HSI</fullName>
                <label>CMS - New or Upgrade FiberOptic/HSI</label>
            </value>
            <value>
                <fullName>Data (Only)</fullName>
            </value>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>E-LAN</fullName>
            </value>
            <value>
                <fullName>E-LAN + EIA</fullName>
            </value>
            <value>
                <fullName>E-Reach</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS - BYOA</fullName>
                <label>Existing BB/FiberOptic or BYOA</label>
            </value>
            <value>
                <fullName>FAW 2.5</fullName>
            </value>
            <value>
                <fullName>FAW 3.5</fullName>
            </value>
            <value>
                <fullName>FBH VOIP</fullName>
                <isActive>false</isActive>
                <label>FBH VOIP</label>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS</fullName>
            </value>
            <value>
                <fullName>Frontier Business Hosted VOIP</fullName>
                <isActive>false</isActive>
                <label>Frontier Business Hosted VOIP</label>
            </value>
            <value>
                <fullName>IP Connect</fullName>
                <isActive>false</isActive>
                <label>IP Connect</label>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi - Existing BB/FiOS or BYOA</fullName>
                <label>Managed Enterprise WiFi - Existing BB/FiberOptic or BYOA</label>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi - New or Existing Ethernet</fullName>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi - New or Upgrade BB/FiOS</fullName>
                <label>Managed Enterprise WiFi - New or Upgrade BB/FiberOptic</label>
            </value>
            <value>
                <fullName>Managed Firewall</fullName>
            </value>
            <value>
                <fullName>Managed Network Services</fullName>
            </value>
            <value>
                <fullName>Managed Security</fullName>
                <isActive>false</isActive>
                <label>Managed Security</label>
            </value>
            <value>
                <fullName>National ELAN</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS + Ethernet</fullName>
                <label>New or Existing EIA</label>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS + Broadband</fullName>
                <label>New or Upgrade BB/FiberOptic</label>
            </value>
            <value>
                <fullName>Off-Net Ethernet</fullName>
            </value>
            <value>
                <fullName>Ring Central</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>SDWAN - E-Reach/Off-Net Ethernet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Renewal_MRR__c.field-meta.xml
<CustomField>
    <fullName>Renewal_MRR__c</fullName>
    <label>Renewal MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <label>Speed</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Technical_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Technical_Contact_Name__c</fullName>
    <description>New field based on 25 Day Interval - Ethernet Order / Field Modification project</description>
    <inlineHelpText>Please enter the customer&apos;s Technical Contact Name.</inlineHelpText>
    <label>Technical Contact Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Technical_Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Technical_Contact_Number__c</fullName>
    <description>New field setup - 25 Day Interval - Ethernet Order / Field Modification</description>
    <inlineHelpText>Please enter the customer&apos;s Technical Contact Number.</inlineHelpText>
    <label>Technical Contact Number</label>
    <type>Phone</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/recordTypes/New_Order.recordType-meta.xml
<RecordType>   
     <fullName>New_Order</fullName>
    <active>true</active>
    <description>New Services for a new customer. Requires a Contract.</description>
    <label>New Order</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/VendorJsonSNE__c/VendorJsonSNE__c.object-meta.xml
<CustomObject>
    <label>VendorJsonSNE</label>
    <nameField>
        <displayFormat>VENSNE-{0000000}</displayFormat>
        <label>VendorJsonSNE Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VendorJsonSNEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/VendorJsonSNE__c/fields/Long_Description__c.field-meta.xml
<CustomField>
    <fullName>Long_Description__c</fullName>
    <label>Long Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/VendorJsonSNE__c/fields/SE__c.field-meta.xml
<CustomField>
    <fullName>SE__c</fullName>
    <label>S&amp;E</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/VendorJsonSNE__c/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <label>Speed</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WS_ESB_Settings__c/WS_ESB_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ESB Service Settings</label>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/WS_ESB_Settings__c/fields/Apigee_Token__c.field-meta.xml
<CustomField>
    <fullName>Apigee_Token__c</fullName>
    <label>Apigee Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WS_ESB_Settings__c/fields/CBTS_API_Key__c.field-meta.xml
<CustomField>
    <fullName>CBTS_API_Key__c</fullName>
    <label>CBTS API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WS_ESB_Settings__c/fields/CBTS_Order_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>CBTS_Order_Endpoint__c</fullName>
    <label>CBTS Order Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WS_ESB_Settings__c/fields/EC_ApplicationID__c.field-meta.xml
<CustomField>
    <fullName>EC_ApplicationID__c</fullName>
    <description>Execution Context - Application ID</description>
    <inlineHelpText>Execution Context - Application ID</inlineHelpText>
    <label>Application ID</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WS_ESB_Settings__c/fields/EC_EmployeeID__c.field-meta.xml
<CustomField>
    <fullName>EC_EmployeeID__c</fullName>
    <description>Execution Context - Employee ID</description>
    <inlineHelpText>Execution Context - Employee ID</inlineHelpText>
    <label>Employee ID</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WS_ESB_Settings__c/fields/EC_UserID__c.field-meta.xml
<CustomField>
    <fullName>EC_UserID__c</fullName>
    <description>Execution Context - User ID</description>
    <inlineHelpText>Execution Context - User ID</inlineHelpText>
    <label>User ID</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/SendOrderDetailsToCbtsTest.cls
@isTest
public class SendOrderDetailsToCbtsTest {
    //version 1
    @testSetup
    static void setuptestData() { 
        Test.setMock(HttpCalloutMock.class, new SendOrderDetailsToCbtsMock());
        WS_ESB_Settings__c setting = new WS_ESB_Settings__c(CBTS_API_Key__c = 'r3MUlqybToeRGmBgw1YSW7FnDUTTwWV7',
                                                            CBTS_Order_Endpoint__c = 'https://ky93livxf5.execute-api.us-east-2.amazonaws.com/createorder/testorder',Apigee_Token__c = 'r3MUlqybToeRGmBgw1YSW7FnDUTTwWV7',
                                                            EC_ApplicationID__c = 'SFDC', EC_EmployeeID__c = '123456', EC_UserID__c = 'ESB_REG');
        insert setting;
        List<Account> accList = ftr_TestDataFactory.getAccounts(1);
        insert accList;
        Opportunity testopNew = new Opportunity
                        (Name = 'testOpps', AccountId = accList[0].Id, Opportunity_Type__c ='New', CloseDate= Date.today(), StageName = 'New');
            insert testopNew;
        DGF__c dgf =  DGF_Test_Fixture_Factory.createTestDGF('ELINE', testopNew.Id);
        Physical_Site__c ps = DGF_Test_Fixture_Factory.createTestPhysicalSites(1, dgf.Id)[0];
        Product2 prod = new Product2(Name = 'Laptop X200',Family = 'Hardware', Description =  'TEST MNS TEST');
        insert prod;
        VendorJsonSNE__c sne = new VendorJsonSNE__c(Long_Description__c = 'Laptop X200', Speed__c = '5M', SE__C = 'DIA05');
        insert sne;
        Id pricebookId = Test.getStandardPricebookId();

            PricebookEntry pbe = new PricebookEntry(
                Pricebook2Id = pricebookId, Product2Id = prod.Id,
                UnitPrice = 10000, IsActive = true);
            insert pbe;
        List<OpportunityLineItem> testOppLineItems = new List<OpportunityLineItem>();
            for(Integer i=0;i<2;i++) {
                testOppLineItems.add(new OpportunityLineItem(
                                            PricebookEntryId = pbe.Id,
                                            OpportunityId = testopNew.Id, TotalPrice = 33,
                                            Quantity = 5, Renewal_MRR__c = 33, CPQ_NetNewMRR__c = 333));
            }
            insert testOppLineItems;
        Contact con= new contact();
        con.LastName= 'Test';
        con.MobilePhone= '9898561236';
        con.Email = 'Test@gmail.com';
        insert con; 
        Order o = new Order(Name = 'Test Order',
        AccountId = accList[0].id, OpportunityId = testopNew.Id,
                            Technical_Contact_Name__c = 'Test',
                            Technical_Contact_Number__c = '1234567890',
        Pricebook2Id = Test.getStandardPricebookId(),
        Status = 'Draft',
        Product__c = 'EIA',
        Product_Type__c = 'Ethernet',
        Router_s__c = 'No Router',
        Customer_Requested_Date__c = System.today(),
        EffectiveDate = System.today(),
        BillingStreet = '123 Main Street',
        BillingCity = 'Anywhere',
        BillingState = 'Texas',
        BillingStateCode = 'TX',
        BillingPostalCode = '44088',
        ShippingStreet = '123 Main Street',
        ShippingCity = 'Anywhere',
        ShippingState = 'Texas',
        ShippingStateCode = 'TX',
        ShippingPostalCode = '44088',
        Implementor_PM__c = Userinfo.getUserId(),
        RecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('New_Order').getRecordTypeId(),
                            DGF__c = dgf.Id,
                            Order_Stage__c = 'Customer Network Provisioning',
                            Technical_Contact__c = con.Id);
        insert o;    
        
        Order order1 = new Order(Name = 'Test Order 1',
        AccountId = accList[0].id, OpportunityId = testopNew.Id,
                            Technical_Contact_Name__c = 'Test',
                            Technical_Contact_Number__c = '1234567890',
        Pricebook2Id = Test.getStandardPricebookId(),
        Status = 'Draft',
        Product__c = 'EIA',
        Product_Type__c = 'Ethernet',
        Router_s__c = 'No Router',
        Customer_Requested_Date__c = System.today(),
        EffectiveDate = System.today(),
        BillingStreet = '123 Main Street',
        BillingCity = 'Anywhere',
        BillingState = 'Texas',
        BillingStateCode = 'TX',
        BillingPostalCode = '44088',
        ShippingStreet = '123 Main Street',
        ShippingCity = 'Anywhere',
        ShippingState = 'Texas',
        ShippingStateCode = 'TX',
        ShippingPostalCode = '44088',
        RecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('New_Order').getRecordTypeId(),
                                DGF__c = dgf.Id,
                                Order_Stage__c = 'Customer Network Provisioning',
                                Technical_Contact__c = con.Id);
        insert order1;  
    }
    @isTest
    static void testBatch() {
        Test.startTest();
        List<Service_Order__c> servOrderList = [SELECT Id FROM Service_Order__c];
        System.assert(!servOrderList.isEmpty());
        Test.stopTest();
    }
}