UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B1 / POTS</fullName>
                <default>true</default>
                <label>B1 / POTS</label>
            </value>
            <value>
                <fullName>Long Distance (Switched)</fullName>
            </value>
            <value>
                <fullName>Toll Free</fullName>
            </value>
            <value>
                <fullName>DSL</fullName>
            </value>
            <value>
                <fullName>Centrex/Centranet</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
            <value>
                <fullName>Voice Mail &amp; additional</fullName>
            </value>
            <value>
                <fullName>Features on existing service</fullName>
            </value>
            <value>
                <fullName>Analog Trunks</fullName>
            </value>
            <value>
                <fullName>IP Address Changes</fullName>
            </value>
            <value>
                <fullName>ISDN BRI</fullName>
            </value>
            <value>
                <fullName>ISDN PRI</fullName>
            </value>
            <value>
                <fullName>MIPT (area specific product)</fullName>
            </value>
            <value>
                <fullName>DIA T1 w/out router</fullName>
            </value>
            <value>
                <fullName>EIA Metro-E</fullName>
            </value>
            <value>
                <fullName>SIP Trunking</fullName>
            </value>
            <value>
                <fullName>IP Connect</fullName>
            </value>
            <value>
                <fullName>Metro-E Upgrade</fullName>
            </value>
            <value>
                <fullName>SONET</fullName>
            </value>
            <value>
                <fullName>Frame Relay</fullName>
            </value>
            <value>
                <fullName>Private Line DS1 (On-Net)</fullName>
            </value>
            <value>
                <fullName>Dedicated PL</fullName>
            </value>
            <value>
                <fullName>Wireless Hot Spots</fullName>
            </value>
            <value>
                <fullName>Wireless Anchor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Asset/fields/UNI_Host__c.field-meta.xml
<CustomField>
    <fullName>UNI_Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UNI_Host</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>UNI Host to</relationshipLabel>
    <relationshipName>uni_hosts</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Customer_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Requested_Date__c</fullName>
    <label>Customer Requested Date</label>
    <type>Date</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cloud Managed Solutions</fullName>
            </value>
            <value>
                <fullName>CMS - Existing or BYOA</fullName>
            </value>
            <value>
                <fullName>CMS - New or Upgrade Ethernet</fullName>
            </value>
            <value>
                <fullName>CMS - New or Upgrade FiOS/HSI</fullName>
                <label>CMS - New or Upgrade FiberOptic/HSI</label>
            </value>
            <value>
                <fullName>Data (Only)</fullName>
            </value>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>E-LAN</fullName>
            </value>
            <value>
                <fullName>E-LAN + EIA</fullName>
            </value>
            <value>
                <fullName>E-Reach</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS - BYOA</fullName>
                <label>Existing BB/FiberOptic or BYOA</label>
            </value>
            <value>
                <fullName>FAW 2.5</fullName>
            </value>
            <value>
                <fullName>FAW 3.5</fullName>
            </value>
            <value>
                <fullName>FBH VOIP</fullName>
                <isActive>false</isActive>
                <label>FBH VOIP</label>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS</fullName>
            </value>
            <value>
                <fullName>Frontier Business Hosted VOIP</fullName>
                <isActive>false</isActive>
                <label>Frontier Business Hosted VOIP</label>
            </value>
            <value>
                <fullName>IP Connect</fullName>
                <isActive>false</isActive>
                <label>IP Connect</label>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi - Existing BB/FiOS or BYOA</fullName>
                <label>Managed Enterprise WiFi - Existing BB/FiberOptic or BYOA</label>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi - New or Existing Ethernet</fullName>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi - New or Upgrade BB/FiOS</fullName>
                <label>Managed Enterprise WiFi - New or Upgrade BB/FiberOptic</label>
            </value>
            <value>
                <fullName>Managed Firewall</fullName>
            </value>
            <value>
                <fullName>Managed Network Services</fullName>
            </value>
            <value>
                <fullName>Managed Security</fullName>
                <isActive>false</isActive>
                <label>Managed Security</label>
            </value>
            <value>
                <fullName>National ELAN</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS + Ethernet</fullName>
                <label>New or Existing EIA</label>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS + Broadband</fullName>
                <label>New or Upgrade BB/FiberOptic</label>
            </value>
            <value>
                <fullName>Off-Net Ethernet</fullName>
            </value>
            <value>
                <fullName>Ring Central</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>SDWAN - E-Reach/Off-Net Ethernet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2 - Wire Circuit</fullName>
            </value>
            <value>
                <fullName>4 - Wire Circuit</fullName>
            </value>
            <value>
                <fullName>56K</fullName>
            </value>
            <value>
                <fullName>64K</fullName>
            </value>
            <value>
                <fullName>BRI</fullName>
            </value>
            <value>
                <fullName>Broadband</fullName>
            </value>
            <value>
                <fullName>Circuit</fullName>
            </value>
            <value>
                <fullName>CPE</fullName>
            </value>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>E-LAN</fullName>
            </value>
            <value>
                <fullName>E-LAN &amp; EIA</fullName>
            </value>
            <value>
                <fullName>Ethernet</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>FOTS</fullName>
            </value>
            <value>
                <fullName>Fractional Circuit</fullName>
            </value>
            <value>
                <fullName>Frontier Anyware Mitel Hosted</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS</fullName>
            </value>
            <value>
                <fullName>Frontier Calling with Cloud Phone</fullName>
                <label>Frontier Direct Calling</label>
            </value>
            <value>
                <fullName>IP/VPN</fullName>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi</fullName>
            </value>
            <value>
                <fullName>Managed Router</fullName>
            </value>
            <value>
                <fullName>Managed Services</fullName>
            </value>
            <value>
                <fullName>OC-12</fullName>
            </value>
            <value>
                <fullName>OC-3</fullName>
            </value>
            <value>
                <fullName>OC-48</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Private Line T1 / DS1</fullName>
            </value>
            <value>
                <fullName>Private Line T3 / DS3</fullName>
            </value>
            <value>
                <fullName>Ring Central</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Router_s__c.field-meta.xml
<CustomField>
    <fullName>Router_s__c</fullName>
    <label>Router(s)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>IAD</fullName>
            </value>
            <value>
                <fullName>Managed Router</fullName>
            </value>
            <value>
                <fullName>Managed Router and IAD</fullName>
            </value>
            <value>
                <fullName>No Router</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/OrderItem/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT(Product2.vlocity_cmt__Type__c)</formula>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/OrderItem/fields/UNI_Host__c.field-meta.xml
<CustomField>
    <fullName>UNI_Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UNI Host</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products (UNI Host)</relationshipLabel>
    <relationshipName>Order_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>Used to set product type on Order.</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__Action__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Action__c</fullName>
    <description>The action desired for this line item with values of Add, Change, Existing or Disconnect. Existing means no change is requested. Add is a request to add the item, Change is a request to change it. Disconnect is a request to remove it.</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Suspend</fullName>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__AssetId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__AssetId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For quotes of changes to existing Assets, this identifies the Asset that is being changed by this line item.</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Quoted Changes</relationshipLabel>
    <relationshipName>QuoteLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__AssetReferenceId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__AssetReferenceId__c</fullName>
    <description>Unique identifier of the asset refereced by this line item. Used by Vlocity CPQ to track the asset across various objects in the asset-based ordering lifecycle.</description>
    <label>Asset Reference Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__JSONAttribute__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__JSONAttribute__c</fullName>
    <description>JSON body containing Vlocity Attribute value data.</description>
    <label>JSONAttribute</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/ftr_CpqHelperTest.cls
/**
* @description       : This test class covers the following Apex classes:
*      ftr_CpqHelper
*      TBD_CLASS2
*      TBD_CLASS3
* @author            : TBD
* @version           : 2 
**/ 
@isTest
public class ftr_CpqHelperTest {
    
    //@TestSetup
    static void makeData(){
        vlocity_cmt__CpqConfigurationSetup__c setting = new vlocity_cmt__CpqConfigurationSetup__c();
        setting.Name = 'DefaultPricingPlan';
        setting.vlocity_cmt__SetupValue__c = 'True';
        insert setting;
        
        Integer numOfQLIforEachQuote = 2;
        Integer numOfQuote = 1;
        List<QuoteLineItem> qlis = ftr_TestDataFactory.getQLI(numOfQLIforEachQuote, numOfQuote);
        insert qlis;
    }
    
    @isTest
    static void getCpqConfigurationSetupValueTest(){
        vlocity_cmt__CpqConfigurationSetup__c cpqSetup = new vlocity_cmt__CpqConfigurationSetup__c();
        cpqSetup.name = 'DefaultPricingPlan';
        cpqSetup.vlocity_cmt__SetupValue__c = 'DEFAULT_PRICING_PLAN';
        insert cpqSetup;
        String setupName = 'DefaultPricingPlan';
        test.startTest();
        String retval = ftr_CpqHelper.getCpqConfigurationSetupValue(setupName);
        test.stopTest();
        System.assertEquals('DEFAULT_PRICING_PLAN', retval);
    }
    
    @isTest
    static void getJSONAttributeValuesTest(){
        StaticResource sr = [SELECT Id, Body FROM StaticResource WHERE Name = 'ftr_TD_JSONAttribute_Access' LIMIT 1];
        String jsonAttribute = sr.body.toString();
        
        Map<String, Object> attrVals =  ftr_CpqHelper.getJSONAttributeValues(jsonAttribute);
        
        System.assertEquals('50 Mbps', (String)attrVals.get('ATTR_BANDWIDTH'));
    }
    
    @isTest
    static void getJSONAttributeValueTest(){
        StaticResource sr = [SELECT Id, Body FROM StaticResource WHERE Name = 'ftr_TD_JSONAttribute_Access' LIMIT 1];
        
        String jsonAttribute = sr.body.toString();
        String attribCode = 'ATTR_BANDWIDTH';
        String attVal = (String)ftr_CpqHelper.getJSONAttributeValue(jsonAttribute, attribCode);
        
        System.assertEquals('50 Mbps', attVal);
    }
    
    @isTest
    static void setJSONAttributeTest(){
        StaticResource sr = [SELECT Id, Body FROM StaticResource WHERE Name = 'ftr_TD_JSONAttribute_Access' LIMIT 1];
        String runtimeJSON = sr.body.toString(); 
        String originalJSON = '{}'; 
        
        String code = 'ATTR_CONTRACT_TERM';
        Object val = '12 Months';
        test.startTest();
        String modifiedJSON = ftr_CpqHelper.setJSONAttribute(runtimeJSON, originalJSON, code, val);
        test.stopTest();
        
        System.assertEquals(val, ftr_CpqHelper.getJSONAttributeValue(modifiedJSON, code));
    }
    
    @isTest
    static void setJSONAttributesTest(){
        StaticResource sr = [SELECT Id, Body FROM StaticResource WHERE Name = 'ftr_TD_JSONAttribute_Access' LIMIT 1];
        String runtimeJSON = sr.body.toString(); 
        String originalJSON = '{}'; 
        Map<String, Object> attrVals = new Map<String, Object> {
            'ATTR_CONTRACT_TERM' => '12 Months'
                };
                    test.startTest();
        String modifiedJSON = ftr_CpqHelper.setJSONAttributes(runtimeJSON, originalJSON, attrVals);
        test.stopTest();
        System.assertEquals('12 Months', ftr_CpqHelper.getJSONAttributeValue(modifiedJSON, 'ATTR_CONTRACT_TERM'));
    }
    
    @isTest
    static void setQLIsAttributeTest(){
        String attVal = '12 Months';
        List<QuoteLineItem> qLIs = [SELECT Id, vlocity_cmt__JSONAttribute__c FROM QuoteLineItem];
        String attCode = 'ATTR_CONTRACT_TERM';
        test.startTest();
        List<QuoteLineItem> qLIsOutput = ftr_CpqHelper.setQLIsAttribute(attVal, qLIs, attCode);
        test.stopTest();
    }
    
    @isTest
    static void convertToSpeedTest(){
        String bandWidth = '20 Mbps';
        String bandWidth1 = '30 GB';
        String bandWidth2 = '40 G';
        String bandWidth3 = '50 GBPS';
        String bandWidth4 = '60 Mbps';
        String bandWidth5 = '70 M';
        test.startTest();
        Integer speed = ftr_CpqHelper.convertToSpeed(bandWidth);
        // Integer speed1 = ftr_CpqHelper.convertToSpeed(bandWidth1);
        //Integer speed2 = ftr_CpqHelper.convertToSpeed(bandWidth2);
        //Integer speed3 = ftr_CpqHelper.convertToSpeed(bandWidth3);
        // Integer speed4 = ftr_CpqHelper.convertToSpeed(bandWidth4);
        //Integer speed5 = ftr_CpqHelper.convertToSpeed(bandWidth5);
        test.stopTest();
        System.assertEquals(20, speed);
        // System.assertEquals(30, speed1);
        //System.assertEquals(40, speed2);
        //System.assertEquals(50, speed3);
        //System.assertEquals(60, speed4);
        //System.assertEquals(70, speed5);
    }
    
    @isTest
    static void convertToSpeedGbpsTest(){
        String bandWidth = '20 Gbps';
        test.startTest();
        Integer speed = ftr_CpqHelper.convertToSpeed(bandWidth);
        test.stopTest();
        System.debug('speed gbps..'+ speed);
        System.assertEquals(20000, speed);
    }
    
    @isTest
    static void convertToBandWidthTest(){
        Integer speed = 20;
        test.startTest();
        String bandwidth = ftr_CpqHelper.convertToBandWidth(speed);
        test.stopTest();
        System.assertEquals('20 Mbps', bandwidth);
    }
    
    @isTest
    static void testAsyncCheckout(){
        Quote q = ftr_TestDataFactory.getQuotes(1)[0];
        test.startTest();
        ftr_CpqHelper.checkoutAsync(q.Id);
        test.stopTest();
    }
    
    @isTest
    static void testSetOLIsAttribute(){
        List<OrderItem> oLIs = ftr_TestDataFactory.getOrderItems(2, new Map<string,string>{'Test'=>'TestCode'});
        test.startTest();
        ftr_CpqHelper.setOLIsAttribute('test', oLIs, 'TEST');
        test.stopTest();
    }
    @isTest
    static void testSetQLIsAttribute(){
        List<QuoteLineItem> qLIs = ftr_TestDataFactory.getQLI(2, 1);
        test.startTest();
        ftr_CpqHelper.setQLIsAttribute('test', qLIs, 'TEST');
        test.stopTest();
    }
    
    static Map<String, String> prodNameCodeMap = new Map<String, String>{ 
        'M6 UNI PSR CFS' => 'ENT_ETH_UNI_PSR_001' 
            };
                static Map<String, String> prodNameCodeMap1 = new Map<String, String>{ 
                    'M6 DIA PSR CFS' => 'ENT_ETH_UNI_PSR_001' 
                        };
                            
                            @isTest//TestSetup
                            static void testMACDCompareOLIToAsset() {
                                //  Account[] accounts = ftr_TestDataFactory.getAccounts(1);
                                // insert accounts;
                                Id globalRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='global' LIMIT 1]?.Id;
                                Account globalAcc1 = new Account();
                                globalAcc1.Name = 'GLOBAL ACCOUNT';
                                globalAcc1.RecordTypeId = globalRecId;
                                //globalAcc.RecordTypeId = '012E0000000fDc3IAE';
                                insert globalAcc1;
                                //  Id GlobalRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global').getRecordTypeId();
                                Id MasterRTId =[SELECT id FROM RecordType WHERE RecordType.Name = 'Master' AND SobjectType = 'Account'].Id;
                                
                                Account accounts = new Account(Name = 'TestAccount'); 
                                accounts.RecordTypeId = MasterRTId;
                                accounts.ParentId = globalAcc1.Id;
                                insert accounts;
                                Order order = new Order (
                                    Name = 'Test Order',
                                    AccountId = accounts.Id,
                                    Status = 'Draft',
                                    Pricebook2Id = Test.getStandardPricebookId(),
                                    Product__c = 'EIA',
                                    Product_Type__c = 'Ethernet',
                                    Router_s__c = 'No Router',
                                    //Customer_Requested_Date__c = System.today(),
                                    EffectiveDate = System.today(),
                                    BillingStreet = '123 Main Street',
                                    BillingCity = 'Anywhere',
                                    BillingState = 'Texas',
                                    BillingStateCode = 'TX',
                                    BillingPostalCode = '44088',
                                    ShippingStreet = '123 Main Street',
                                    ShippingCity = 'Anywhere',
                                    ShippingState = 'Texas',
                                    ShippingStateCode = 'TX',
                                    ShippingPostalCode = '44088'
                                );
                                insert order;
                                OrderItem[] orderItems = ftr_TestDataFactory.getOrderItems(2, prodNameCodeMap);
                                orderItems[0].OrderId = order.Id;
                                orderItems[1].OrderId = order.Id;
                                
                                insert orderItems;
                                orderItems[0].UNI_Host__c = orderItems[1].Id;
                                update orderItems;
                                Asset asset1= new Asset(
                                    Name = 'Test',
                                    vlocity_cmt__OrderProductId__c = orderItems[0].Id,
                                    Product2Id = orderItems[0].Product2Id, 
                                    vlocity_cmt__PricebookEntryId__c = orderItems[0].PricebookEntryId,
                                    vlocity_cmt__JSONAttribute__c = orderItems[0].vlocity_cmt__JSONAttribute__c, 
                                    Quantity = 1,
                                    Price = 0.00,
                                    AccountId = order.AccountId
                                );
                                
                                insert asset1;
                                
                                orderItems[0].vlocity_cmt__AssetId__c = asset1.Id;
                                OrderItems[0].vlocity_cmt__AssetReferenceId__c = '123456';
                                OrderItems[0].vlocity_cmt__Action__c = 'Change';
                                update OrderItems[0];
                                
                                List<vlocity_cmt__FulfilmentRequestLine__c> frlList = ftr_TestDataFactory.getFulfilmentRequestLines(1, prodNameCodeMap);
                                vlocity_cmt__FulfilmentRequestLine__c frlLine = frlList.get(0);
                                String originalJSON = '{}'; 
                                String runtimeJSON = frlLine.vlocity_cmt__JSONAttribute__c;
                                ftr_CpqHelper.setJSONAttribute(runtimeJSON, originalJSON, 'ATTR_MACD_Order_Action', 'Change');
                                frlLine.vlocity_cmt__JSONAttribute__c = runtimeJSON;
                                frlLine.vlocity_cmt__Action__c = 'Modify';
                                insert frlLine;
                                ftr_CpqHelper.compareOLIAndAssetJSONAttributesForChangeOrder(frlLine);
                                List<vlocity_cmt__FulfilmentRequestLine__c> frlList1 = ftr_TestDataFactory.getFulfilmentRequestLines(1, prodNameCodeMap1);
                                vlocity_cmt__FulfilmentRequestLine__c frlLine1 = frlList1.get(0);
                                String originalJSON1 = '{}'; 
                                String runtimeJSON1 = frlLine.vlocity_cmt__JSONAttribute__c;
                                ftr_CpqHelper.setJSONAttribute(runtimeJSON1, originalJSON1, 'ATTR_MACD_Order_Action', 'Change');
                                frlLine1.vlocity_cmt__JSONAttribute__c = runtimeJSON1;
                                frlLine1.vlocity_cmt__Action__c = 'Modify';
                                insert frlLine1;
                                ftr_CpqHelper.compareOLIAndAssetJSONAttributesForChangeOrder(frlLine1);
                            }
    @istest
    static void loadChangedJSONAttributesForDIATest() {
        Map<String, Object> oliJsonAttributesMap = new Map<String, Object>{'ATTR_BANDWIDTH' => '50 Mbps',
            'ATTR_TOPO' => '123',
            'ATTR_IP_BLOCKS' => '12','ATTR_VLAN_TAG' => '12', 'ATTR_DECOMP_WTN' => '12345678'};
                Map<String, Object> assetJsonAttributesMap = new Map<String, Object>{'ATTR_BANDWIDTH' => '5 Mbps',
                    'ATTR_TOPO' => '1234',
                    'ATTR_IP_BLOCKS' => '12908','ATTR_VLAN_TAG' => '12867', 'ATTR_DECOMP_WTN' => '12345610'};
                        List<Object> temp = new List<Object>{'123'};
                        Map<String, List<Object>> changedAttributesMap = new Map<String, List<Object>>{'CA_ATTRIBUTES' => temp};
                            Map<String, List<Object>> temp1 = ftr_CpqHelper.loadChangedJSONAttributesForDIA(oliJsonAttributesMap,assetJsonAttributesMap,changedAttributesMap);
    }
}