UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <formula>RIGHT(Legal_Street__c,LEN(Legal_Street__c) - FIND(&quot; &quot;, Legal_Street__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Street Name</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <formula>LEFT( Legal_Street__c , FIND(&quot; &quot;, Legal_Street__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Street Number</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Carrier_Service.recordType-meta.xml
<RecordType>
    <fullName>Carrier_Service</fullName>
    <active>true</active>
    <label>Carrier Service</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAcna__c/FTRWSAcna__c.object-meta.xml
<CustomObject>
    <label>Wholesale ACNA</label>
    <nameField>
        <label>FTRWSAcna Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesale ACNAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAcna__c/fields/ACNA__c.field-meta.xml
<CustomField>
    <fullName>ACNA__c</fullName>
    <label>ACNA</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAcna__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wholesale ACNAs</relationshipLabel>
    <relationshipName>Wholesale_ACNAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/FTRWSAddress__c.object-meta.xml
<CustomObject>
    <description>Custom table to store DPI and DSAT address qualification</description>
    <label>FTRWSAddress</label>
    <nameField>
        <label>FTRWSAddress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FTRWSAddress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/ACNA__c.field-meta.xml
<CustomField>
    <fullName>ACNA__c</fullName>
    <label>ACNA</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/G_Latitude__c.field-meta.xml
<CustomField>
    <fullName>G_Latitude__c</fullName>
    <label>G Latitude</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/G_Longitude__c.field-meta.xml
<CustomField>
    <fullName>G_Longitude__c</fullName>
    <description>Google longitude for an address</description>
    <label>G Longitude</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <description>DSAT ID</description>
    <label>DSAT Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <label>Opportunity ID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Service Addresses</relationshipLabel>
    <relationshipName>ServiceAddress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/PNUM__c.field-meta.xml
<CustomField>
    <fullName>PNUM__c</fullName>
    <label>PNUM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSPnum__c/FTRWSPnum__c.object-meta.xml
<CustomObject>
    <label>Wholesale Pnum</label>
    <nameField>
        <label>FTRWSPnum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesale Pnums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSPnum__c/fields/PNum__c.field-meta.xml
<CustomField>
    <fullName>PNum__c</fullName>
    <description>Purchase Order Number</description>
    <label>PNum</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSPnum__c/fields/Wholesale_ACNA__c.field-meta.xml
<CustomField>
    <fullName>Wholesale_ACNA__c</fullName>
    <label>Wholesale ACNA</label>
    <referenceTo>FTRWSAcna__c</referenceTo>
    <relationshipLabel>Wholesale Pnums</relationshipLabel>
    <relationshipName>Wholesale_Pnums</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This is the describe the SEER/SRQ on the Oppt</description>
    <inlineHelpText>In detail please communicate to the best of your ability the scope of work for this opportunity.</inlineHelpText>
    <label>Description for SEER</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Wholesale_ACNA__c.field-meta.xml
<CustomField>
    <fullName>Wholesale_ACNA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACNA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>FTRWSAcna__c.Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FTRWSAcna__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Wholesale_Pnum__c.field-meta.xml
<CustomField>
    <fullName>Wholesale_Pnum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PNUM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Wholesale_ACNA__c</field>
            <operation>equals</operation>
            <valueField>FTRWSPnum__c.Wholesale_ACNA__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FTRWSPnum__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/recordTypes/Carrier_Service.recordType-meta.xml
<RecordType>
    <fullName>Carrier_Service</fullName>
    <active>true</active>
    <businessProcess>Wholesale_Sales_Stages</businessProcess>
    <description>Carrier Service</description>
    <label>Carrier Service</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Product2/fields/evcspeed__c.field-meta.xml
<CustomField>
    <fullName>evcspeed__c</fullName>
    <label>EVC Speed</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Product2/fields/mrcusoc__c.field-meta.xml
<CustomField>
    <fullName>mrcusoc__c</fullName>
    <label>MRC Usoc</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Product2/recordTypes/Carrier_Service.recordType-meta.xml
<RecordType>
    <fullName>Carrier_Service</fullName>
    <active>true</active>
    <label>Carrier Service</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>This field is used to show which products are being quoted.</description>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS</fullName>
            </value>
            <value>
                <fullName>CCaaS</fullName>
            </value>
            <value>
                <fullName>Private Network</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/SterlingQuote__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Object</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/QuoteType__c.field-meta.xml
<CustomField>
    <fullName>QuoteType__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Renew</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/recordTypes/Carrier_Service.recordType-meta.xml
<RecordType>
    <fullName>Carrier_Service</fullName>
    <active>true</active>
    <description>Carrier Service</description>
    <label>Carrier Service</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/SterlingQuoteItem__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Item</description>
    <label>Quote Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Adjusted_MRC_Notes__c.field-meta.xml
<CustomField>
    <fullName>Adjusted_MRC_Notes__c</fullName>
    <description>Notes added by the user when MRC is adjusted for wholesale</description>
    <label>Adjusted MRC Notes</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Adjusted_NRC_Notes__c.field-meta.xml
<CustomField>
    <fullName>Adjusted_NRC_Notes__c</fullName>
    <description>Notes added by the user when NRC is adjusted for wholesale</description>
    <label>Adjusted NRC Notes</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedMRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedMRC__c</fullName>
    <label>Adjusted MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedNRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedNRC__c</fullName>
    <label>Adjusted NRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/FTRWSAddress__c.field-meta.xml
<CustomField>
    <fullName>FTRWSAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FTRWSAddress</label>
    <referenceTo>FTRWSAddress__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/ItemCode__c.field-meta.xml
<CustomField>
    <fullName>ItemCode__c</fullName>
    <defaultValue>&apos;0000&apos;</defaultValue>
    <label>Item Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>SterlingQuote__r.OpportunityId__r.Id</formula>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/PNum__c.field-meta.xml
<CustomField>
    <fullName>PNum__c</fullName>
    <description>Wholesale Product rates source PNUM</description>
    <label>PNum</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/StandardMRC__c.field-meta.xml
<CustomField>
    <fullName>StandardMRC__c</fullName>
    <label>Standard MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/StandardNRC__c.field-meta.xml
<CustomField>
    <fullName>StandardNRC__c</fullName>
    <label>Standard NRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/SterlingQuote__c.field-meta.xml
<CustomField>
    <fullName>SterlingQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>SterlingQuote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>SterlingQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/TermLength__c.field-meta.xml
<CustomField>
    <fullName>TermLength__c</fullName>
    <label>Term Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/FTRWSAdjustmentControllerTest.cls
@isTest
public class FTRWSAdjustmentControllerTest {
    
        @isTest(seealldata=true)
    public static void codeCoverage(){

        Id globalRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='Carrier_Service' LIMIT 1]?.Id;
        Account acc = new Account();
        acc.Name='testAccount';
        acc.RecordTypeId= globalRecId;
        insert acc;
        
        
        Opportunity opp = new Opportunity();
        opp.Name='Test Opp';
        opp.StageName='Decision';
        opp.AccountId=acc.id;
        opp.CloseDate= System.today();
        opp.ForecastCategoryName='Commit';
        insert opp;
        
        String gAddressStr = '{"actionStr":"CREATE","streetNo":"2001","streetName":"Solar Drive","city":"Oxnard", '+ 
            '"state":"California","unitNo":"","zipcode":"93036","gLat":34.2203155,"gLng":-119.1458787}';
        FTRWSGoogleAddress gAddress = (FTRWSGoogleAddress)JSON.deserialize(gAddressStr, FTRWSGoogleAddress.class);
        FTRWSAddress__c  address = new FTRWSAddress__c();
        address.Street_Number__c = gAddress.streetNo;
        address.Street_Name__c = gAddress.streetName;
        address.Street_Number__c = gAddress.streetNo;
        address.City__c = gAddress.city;
        address.State__c = gAddress.state;
        address.Zip_Code__c = gAddress.zipcode;
        address.Opportunity_ID__c = opp.id;
        address.G_Latitude__c = gAddress.gLat;
        address.G_Longitude__c = gAddress.gLng;
        
        insert address;
        
        Id prodRecId = [select id,name,developername from recordtype where sobjecttype='product2' and developername='Carrier_Service' LIMIT 1]?.Id;
        
        Product2 product = [SELECT Id, Name, evcspeed__c, Family, Quantity__c,mrcusoc__c , RecordTypeId from PRODUCT2 where RecordTypeId=:prodRecId LIMIT 1];
        /*
        Product2 product = new Product2();
        product.Name = 'EIA 200M';
        product.evcspeed__c = '200M';
        product.Family = 'FOTS';
        product.Quantity__c = '1';
        product.mrcusoc__c = 'EIAUSOC';
        product.RecordTypeId = prodRecId;
        insert product;
        
        
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = product.Id,UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        
        PricebookEntry priceEntrylist = new PricebookEntry(Pricebook2Id = customPB.Id, Product2Id = product.Id,UnitPrice = 12000, IsActive = true);
        insert priceEntrylist;
        */
        
        FTRWSAcna__c acna = new FTRWSAcna__c();
        acna.ACNA__c = 'GIM';
        acna.Company__c = acc.id;
        acna.Name = 'GIM';
        INSERT acna;
        
        FTRWSPnum__c pnum = new FTRWSPnum__c();
        pnum.PNum__c = 'EIAV001GIM300484';
        pnum.Name = 'EIAV001GIM300484';
        pnum.Wholesale_ACNA__c = acna.Id;
        INSERT pnum;
        
        Opportunity opp2 = new Opportunity();
        opp2.Name='Test Opp2';
        opp2.StageName='Decision';
        opp2.AccountId=acc.id;
        opp2.CloseDate= System.today();
        opp2.ForecastCategoryName='Commit';
        opp2.Wholesale_ACNA__c = acna.Id;
        opp2.Wholesale_Pnum__c = pnum.Id;
        //opp2.Pricebook2Id = pricebookId;//customPB.Id;
        insert opp2;
        
        list<RecordType> recordtypeid = [SELECT BusinessProcessId,DeveloperName,Id,Name,SobjectType FROM RecordType WHERE DeveloperName = 'Carrier_Service' AND SobjectType = 'SterlingQuote__c'];        
        SterlingQuote__c quote = new SterlingQuote__c();
        quote.Name = 'Demo';
        quote.OpportunityId__c = opp2.Id;
        quote.QuoteType__c = 'New';
        quote.RecordTypeId = recordtypeid[0].Id;
        quote.ExpirationDate__c = System.today();
        
        insert quote;        
        
        //System.debug('pricebookId:' + pricebookId);
        //System.debug('opp.Pricebook2Id: ' + opp2.Pricebook2Id);
        
        SterlingQuoteItem__c quoteItem = new SterlingQuoteItem__c();
        quoteItem.Name = 'EIA 200M';
        quoteItem.Description__c = 'EIA 200M';
        quoteItem.SterlingQuote__c = quote.Id;
        quoteItem.Products__c = product.Id;

        quoteItem.Quantity__c = 1;
        quoteItem.StandardMRC__c = decimal.valueOf('1000.00');
        quoteItem.AdjustedMRC__c = decimal.valueOf('9000.00');
        quoteItem.Adjusted_MRC_Notes__c = 'MRC Discount TEST';
        quoteItem.Adjusted_NRC_Notes__c = 'NRC Discount TEST';
        quoteItem.StandardNRC__c = decimal.valueOf('50.00');
        quoteItem.AdjustedNRC__c = decimal.valueOf('15.00');
        quoteItem.ItemCode__c = product.mrcusoc__c;
        quoteItem.TermLength__c = 36;        
        
        quoteItem.SA_StreetNrFirst__c = address.Street_Number__c;
        quoteItem.SA_StreetName__c = address.Street_Name__c;
        quoteItem.SA_UnitNumber__c = address.Unit_Number__c;
        quoteItem.Zipcode__c = address.Zip_Code__c;
        quoteItem.Locality__c = address.City__c;
        quoteItem.DSAT_AddressID__c = address.Id__c;
        quoteItem.ST_AddressID__c = address.Id;
        INSERT quoteItem;
        
        FTRWSDiscountRequest req = new FTRWSDiscountRequest();
        req.quoteItem = quoteItem;
        req.recurringType = 'MRC';
        req.discountType = 'AMOUNT';
        req.discountVal = 100.00;
        req.mrcDiscountNotes = quoteItem.Adjusted_MRC_Notes__c;
        String reqStr = Json.serialize(req);
        FTRWSAdjustmentController.getQuoteLineItemDiscountInfo(reqStr);
        FTRWSAdjustmentController.applyDiscount(reqStr);
        FTRWSAdjustmentController.removeDiscount(reqStr);
        
        req.discountType = 'OVERRIDE';
        req.discountVal = 800.00;
        reqStr = Json.serialize(req);
        FTRWSAdjustmentController.applyDiscount(reqStr);
        
        req.discountType = 'PERCENTAGE';
        req.discountVal = 10;
        reqStr = Json.serialize(req);
        FTRWSAdjustmentController.applyDiscount(reqStr);

        
        req = new FTRWSDiscountRequest();
        req.quoteItem = quoteItem;
        req.recurringType = 'NRC';
        req.discountType = 'AMOUNT';
        req.discountVal = 15.00;
        req.NrcDiscountNotes = quoteItem.Adjusted_nRC_Notes__c;
        reqStr = Json.serialize(req);
        FTRWSAdjustmentController.getQuoteLineItemDiscountInfo(reqStr);
        FTRWSAdjustmentController.applyDiscount(reqStr);
        FTRWSAdjustmentController.removeDiscount(reqStr); 
        
        req.discountType = 'OVERRIDE';
        req.discountVal = 800.00;
        reqStr = Json.serialize(req);
        FTRWSAdjustmentController.applyDiscount(reqStr);
        
        req.discountType = 'PERCENTAGE';
        req.discountVal = 10;
        reqStr = Json.serialize(req);
        FTRWSAdjustmentController.applyDiscount(reqStr);
        
    }

}