UCF-APR2.4/ftr main/force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Global.recordType-meta.xml
<RecordType>
    <fullName>Global</fullName>
    <active>true</active>
    <label>Global</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/FieldAssignment__c.object-meta.xml
<CustomObject>
    <label>Field Assignment</label>
    <nameField>
        <displayFormat>Assignment{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Field Assignments</relationshipLabel>
    <relationshipName>Field_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <formula>CASE(WorkGroupId__r.Field__c,
  &quot;Network_Project_Specialist__c&quot;, &quot;Network Project Specialist&quot;,
  &quot;Order_Provisioner__c&quot;, &quot;Order Provisioner&quot;,
  &quot;Implementor_PM__c&quot;, &quot;Project Manager&quot;, 
  &quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Field</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/OutOfOffice__c.field-meta.xml
<CustomField>
    <fullName>OutOfOffice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of Office?</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary?</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/States__c.field-meta.xml
<CustomField>
    <fullName>States__c</fullName>
    <label>States</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Field_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/WorkGroupId__c.field-meta.xml
<CustomField>
    <fullName>WorkGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Group</label>
    <referenceTo>WorkGroup__c</referenceTo>
    <relationshipLabel>Field Assignments</relationshipLabel>
    <relationshipName>Field_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/WorkGroup__c/WorkGroup__c.object-meta.xml
<CustomObject>
    <label>Work Group</label>
    <nameField>
        <label>Work Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/WorkGroup__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Network_Project_Specialist__c</fullName>
                <default>true</default>
                <label>Network Project Specialist</label>
            </value>
            <value>
                <fullName>Implementor_PM__c</fullName>
                <label>Project Manager</label>
            </value>
            <value>
                <fullName>Order_Provisioner__c</fullName>
                <label>Order Provisioner</label>
            </value>
            <value>
                <fullName>Network Cost Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WorkGroup__c/fields/ProductsForCheckingExistingRecords__c.field-meta.xml
<CustomField>
    <fullName>ProductsForCheckingExistingRecords__c</fullName>
    <label>Products for checking existing orders</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FOTS</fullName>
            </value>
            <value>
                <fullName>Ethernet</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS</fullName>
            </value>
            <value>
                <fullName>Frontier Anyware Mitel Hosted</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS/UCF</fullName>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>EIAE-LAN</fullName>
            </value>
            <value>
                <fullName>E-LAN + EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>Managed Router</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
            <value>
                <fullName>SIP Trunking</fullName>
            </value>
            <value>
                <fullName>IP Connect</fullName>
            </value>
            <value>
                <fullName>E-Reach</fullName>
            </value>
            <value>
                <fullName>Off-Net</fullName>
            </value>
            <value>
                <fullName>IPVPN</fullName>
            </value>
            <value>
                <fullName>SDWAN - E-Reach/Off-Net Ethernet</fullName>
            </value>
            <value>
                <fullName>SDWAN - New or Upgrade Ethernet</fullName>
            </value>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>E-LAN</fullName>
            </value>
            <value>
                <fullName>Off-Net Ethernet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WorkGroup__c/fields/SupportedProducts__c.field-meta.xml
<CustomField>
    <fullName>SupportedProducts__c</fullName>
    <label>Products workgroup will support</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ethernet</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS</fullName>
            </value>
            <value>
                <fullName>Frontier Anyware Mitel Hosted</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS/UCF</fullName>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>FOTS</fullName>
            </value>
            <value>
                <fullName>EIAE-LAN</fullName>
            </value>
            <value>
                <fullName>E-LAN + EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>Managed Router</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
            <value>
                <fullName>SIP Trunking</fullName>
            </value>
            <value>
                <fullName>IP Connect</fullName>
            </value>
            <value>
                <fullName>E-Reach</fullName>
            </value>
            <value>
                <fullName>Off-Net</fullName>
            </value>
            <value>
                <fullName>IPVPN</fullName>
            </value>
            <value>
                <fullName>SDWAN - E-Reach/Off-Net Ethernet</fullName>
            </value>
            <value>
                <fullName>SDWAN - New or Upgrade Ethernet</fullName>
            </value>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>E-LAN</fullName>
            </value>
            <value>
                <fullName>Off-Net Ethernet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WorkGroup__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/classes/FieldAssignmentTriggerHandlerTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 2 
 * 
**/
@isTest
public class FieldAssignmentTriggerHandlerTest {
    @testSetup static void prepareTestData() {
         Id globalRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='global' LIMIT 1]?.Id;
        Account globalAcc1 = new Account();
        globalAcc1.Name = 'GLOBAL ACCOUNT';
        globalAcc1.RecordTypeId = globalRecId;
        //globalAcc.RecordTypeId = '012E0000000fDc3IAE';
        insert globalAcc1;
       //  Id GlobalRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global').getRecordTypeId();
        Id MasterRTId =[SELECT id FROM RecordType WHERE RecordType.Name = 'Master' AND SobjectType = 'Account'].Id;
        Account a = new Account();
        a.RecordTypeId = MasterRTId;
        a.ParentId = globalAcc1.Id;
        a.Name = 'Test Account';
        insert a;
        WorkGroup__c wgrp1 = new WorkGroup__c();
        wgrp1.Name = 'Customer';
        wgrp1.Field__c = 'Network_Project_Specialist__c';
        wgrp1.Priority__c = 2;
        wgrp1.SupportedProducts__c = 'SDWAN;SDWAN - New or Upgrade Ethernet;Ethernet;IP Connect';
        wgrp1.ProductsForCheckingExistingRecords__c = 'SDWAN;Ethernet;SIP';
        insert wgrp1;
        FieldAssignment__c fAssmnt = new FieldAssignment__c();
        fAssmnt.UserId__c =  UserInfo.getUserId();
        fAssmnt.WorkGroupId__c = wgrp1.Id; 
        fAssmnt.AccountId__c = a.Id;
        fAssmnt.Primary__c= true; 
        fAssmnt.State__c = 'TX';
        fAssmnt.OutOfOffice__c = false;
        insert fAssmnt;
    }
    @isTest static void testOooSync() {
        Id globalRecId = [select id,name,developername from recordtype where sobjecttype='account' and developername='global' LIMIT 1]?.Id;
        Account globalAcc1 = new Account();
        globalAcc1.Name = 'GLOBAL ACCOUNT';
        globalAcc1.RecordTypeId = globalRecId;
        //globalAcc.RecordTypeId = '012E0000000fDc3IAE';
        insert globalAcc1;
       //  Id GlobalRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global').getRecordTypeId();
        Id MasterRTId =[SELECT id FROM RecordType WHERE RecordType.Name = 'Master' AND SobjectType = 'Account'].Id;
        Account a = new Account();
         a.RecordTypeId = MasterRTId;
        a.ParentId = globalAcc1.Id;
        a.Name = 'Test Account';
        insert a;
        
        WorkGroup__c wgrp2 = new WorkGroup__c();
        wgrp2.Name = 'Complex';
        wgrp2.Field__c = 'Network_Project_Specialist__c';
        wgrp2.Priority__c = 3;
        wgrp2.SupportedProducts__c = 'SDWAN;SDWAN - New or Upgrade Ethernet;Ethernet;IP Connect';
        wgrp2.ProductsForCheckingExistingRecords__c = 'SDWAN;Ethernet;SIP';
        insert wgrp2;
        FieldAssignment__c fAssmnt = new FieldAssignment__c();
        fAssmnt.UserId__c =  UserInfo.getUserId();
        fAssmnt.WorkGroupId__c = wgrp2.Id; 
        //fAssmnt.AccountId__c = a.Id;
        fAssmnt.Primary__c= true; 
        fAssmnt.State__c = 'TX';
        fAssmnt.States__c = 'TX;CT;CA;IL';
        fAssmnt.OutOfOffice__c = true;
        insert fAssmnt;
        Integer count = [Select count() from FieldAssignment__c where OutOfOffice__c = true];
        System.assertEquals(2, count);
        fAssmnt.OutOfOffice__c = false;
        update fAssmnt;
    }
}