UCF-APR2.4/ftr main/force-app/main/default/objects/Location_Contact__c/Location_Contact__c.object-meta.xml
<CustomObject>
    <label>Location Contact</label>
    <nameField>
        <label>Location Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/Location_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Location Contacts</relationshipLabel>
    <relationshipName>Location_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Location_Contact__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Location Contacts</relationshipLabel>
    <relationshipName>Location_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Location_Contact__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Location Contacts</relationshipLabel>
    <relationshipName>Location_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Location_Contact__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Location Contact</fullName>
            </value>
            <value>
                <fullName>Maintenance Contact</fullName>
            </value>
            <value>
                <fullName>Order Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/CustomFieldValidationTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 2 
**/ 
@isTest
public class CustomFieldValidationTest {
    @TestSetup
    static void makeData(){
        List<Order> orderList = ftr_TestDataFactory.getOrders(1);
        insert orderList;
        CustomFieldValidation__mdt[] cfvList = new List<CustomFieldValidation__mdt>();
        Orderitem[] oLIs = ftr_TestDataFactory.getOrderItems(1, new Map<String,String> {
            'ENT_ETH_UNI_0001' => 'ENT_ETH_UNI_0001'
        });
        oLIs[0].OrderId =orderList[0].id;
        insert oLIs;
        Contact c = new Contact(
        	LastName = 'Test',
            FirstName= 'User',
            Email='Test@User.com',
            Phone= '1234581021'
        );
        insert c;
        insert new Location_Contact__c(
        	Role__c = 'Location Contact', 
            Order__c = orderList[0].Id, 
            Order_Product__c =olis[0].Id, 
            Name = 'John',
            Contact__c = c.Id
        );
    }

    @IsTest
    static void methodName(){
        String contextId = [SELECT Id FROM Order LIMIT 1].Id;
        Test.startTest();
        CustomFieldValidation cfv = new CustomFieldValidation(contextId, 'Submit Order');
        cfv.isValid();
        cfv.getErrors();
        Test.stopTest(); 
    }
}