UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/FieldAssignment__c.object-meta.xml
<CustomObject>
    <label>Field Assignment</label>
    <nameField>
        <displayFormat>Assignment{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Field Assignments</relationshipLabel>
    <relationshipName>Field_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/Backup_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Backup_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Backup  Assignment</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Field_Assignments1_del</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <formula>CASE(WorkGroupId__r.Field__c,
  &quot;Network_Project_Specialist__c&quot;, &quot;Network Project Specialist&quot;,
  &quot;Order_Provisioner__c&quot;, &quot;Order Provisioner&quot;,
  &quot;Implementor_PM__c&quot;, &quot;Project Manager&quot;, 
  &quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Field</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/Out_Of_Office_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Out_Of_Office_End_Date__c</fullName>
    <label>Out Of Office End Date</label>
    <type>DateTime</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/Out_Of_Office_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Out_Of_Office_Start_Date__c</fullName>
    <label>Out Of Office Start Date</label>
    <type>DateTime</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/OutOfOffice__c.field-meta.xml
<CustomField>
    <fullName>OutOfOffice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of Office?</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary?</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/ProcessedRecord__c.field-meta.xml
<CustomField>
    <fullName>ProcessedRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processed Record?</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Field_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/WorkGroupId__c.field-meta.xml
<CustomField>
    <fullName>WorkGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Group</label>
    <referenceTo>WorkGroup__c</referenceTo>
    <relationshipLabel>Field Assignments</relationshipLabel>
    <relationshipName>Field_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/recordTypes/NCM.recordType-meta.xml
<RecordType>
    <fullName>NCM</fullName>
    <active>true</active>
    <description>Network Cast Management</description>
    <label>NCM</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Order_Provisioner__c.field-meta.xml
<CustomField>
    <fullName>Order_Provisioner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Order Provisioner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders_Provisioner</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/recordTypes/Contract_Renewal.recordType-meta.xml
<RecordType>
    <fullName>Contract_Renewal</fullName>
    <active>true</active>
    <description>Contract renewed- billing changes may take place. Requires a Contract.</description>
    <label>Contract Renewal</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/recordTypes/Disconnect_Order.recordType-meta.xml
<RecordType>
    <fullName>Disconnect_Order</fullName>
    <active>true</active>
    <description>Customer is disconnecting services or Equipment Account</description>
    <label>Disconnect Order</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/recordTypes/New_Order.recordType-meta.xml
<RecordType>   
     <fullName>New_Order</fullName>
    <active>true</active>
    <description>New Services for a new customer. Requires a Contract.</description>
    <label>New Order</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/User/fields/Backup_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Backup_Assignment__c</fullName>
    <label>Backup Assignment</label>
    <relationshipName>Backup_Assignment</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WorkGroup__c/WorkGroup__c.object-meta.xml
<CustomObject>
    <label>Work Group</label>
    <nameField>
        <label>Work Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/WorkGroup__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Network_Project_Specialist__c</fullName>
                <default>true</default>
                <label>Network Project Specialist</label>
            </value>
            <value>
                <fullName>Implementor_PM__c</fullName>
                <label>Project Manager</label>
            </value>
            <value>
                <fullName>Order_Provisioner__c</fullName>
                <label>Order Provisioner</label>
            </value>
            <value>
                <fullName>Network Cost Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WorkGroup__c/fields/ProductsForCheckingExistingRecords__c.field-meta.xml
<CustomField>
    <fullName>ProductsForCheckingExistingRecords__c</fullName>
    <label>Products for checking existing orders</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FOTS</fullName>
            </value>
            <value>
                <fullName>Ethernet</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS</fullName>
            </value>
            <value>
                <fullName>Frontier Anyware Mitel Hosted</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS/UCF</fullName>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>EIAE-LAN</fullName>
            </value>
            <value>
                <fullName>E-LAN + EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>Managed Router</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
            <value>
                <fullName>SIP Trunking</fullName>
            </value>
            <value>
                <fullName>IP Connect</fullName>
            </value>
            <value>
                <fullName>E-Reach</fullName>
            </value>
            <value>
                <fullName>Off-Net</fullName>
            </value>
            <value>
                <fullName>IPVPN</fullName>
            </value>
            <value>
                <fullName>SDWAN - E-Reach/Off-Net Ethernet</fullName>
            </value>
            <value>
                <fullName>SDWAN - New or Upgrade Ethernet</fullName>
            </value>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>E-LAN</fullName>
            </value>
            <value>
                <fullName>Off-Net Ethernet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WorkGroup__c/fields/SupportedProducts__c.field-meta.xml
<CustomField>
    <fullName>SupportedProducts__c</fullName>
    <label>Products workgroup will support</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ethernet</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS</fullName>
            </value>
            <value>
                <fullName>Frontier Anyware Mitel Hosted</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS/UCF</fullName>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>FOTS</fullName>
            </value>
            <value>
                <fullName>EIAE-LAN</fullName>
            </value>
            <value>
                <fullName>E-LAN + EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>Managed Router</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
            <value>
                <fullName>SIP Trunking</fullName>
            </value>
            <value>
                <fullName>IP Connect</fullName>
            </value>
            <value>
                <fullName>E-Reach</fullName>
            </value>
            <value>
                <fullName>Off-Net</fullName>
            </value>
            <value>
                <fullName>IPVPN</fullName>
            </value>
            <value>
                <fullName>SDWAN - E-Reach/Off-Net Ethernet</fullName>
            </value>
            <value>
                <fullName>SDWAN - New or Upgrade Ethernet</fullName>
            </value>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>E-LAN</fullName>
            </value>
            <value>
                <fullName>Off-Net Ethernet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/WorkGroup__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/WorkGroup__c/recordTypes/NCM.recordType-meta.xml
<RecordType>
    <fullName>NCM</fullName>
    <active>true</active>
    <description>Network Cast Management</description>
    <label>NCM</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/classes/NCMAutomationOrderHandler.cls
/* Author - Anil A
   SDDD-4526 (01103949)- NCM Order Assignment Automation process.
   This class is used for NCM order automation i.e, owner assigment,outofoffice, backup assignment and roundrobin logic
*/
public class NCMAutomationOrderHandler{ 

    public static String orderRecordTypeName ;    
    /* This method  is used for Ownerassignment logic */
    public static void ownerAssignmentForNCM(Order newOrder, Order oldOrder){
    
        orderRecordTypeName = Schema.SObjectType.Order.getRecordTypeInfosById().get(newOrder.recordtypeId).getname();
        Map<String, List<FieldAssignment__c>> assignmentsByWorkGroupMap = new Map<String, List<FieldAssignment__c>>();
        List<FieldAssignment__c> lstFieldAssignmentUsers = new List<FieldAssignment__c>();        
        
        Map<Id,Id> customerUserIdMap = new Map<Id,Id>();
        Map<Id,FieldAssignment__c> customerUserFaMap = new Map<Id,FieldAssignment__c>(); // Added
        String  assigneeid =null;
        
        String  backupassigneeid =null;
        Boolean outofoff =false;                
        
        if( newOrder.Order_Provisioner__c!= null ){          
            newOrder.ownerId = newOrder.Order_Provisioner__c;
        } 
        else if( string.valueOf(newOrder.ownerId).startsWith('005')  && newOrder.Order_Provisioner__c == null ) {   
            newOrder.Order_Provisioner__c = newOrder.ownerId;
        } else { 
            for(FieldAssignment__c fa : [SELECT Id,Out_Of_Office_Start_Date__c,Out_Of_Office_End_Date__c ,recordtype.Name,OutOfOffice__c,Backup_Assignment__c,UserId__c, AccountId__c, Primary__c, 
                                            WorkGroupId__r.Name, ProcessedRecord__c, WorkGroupId__r.SupportedProducts__c, 
                                            WorkGroupId__r.ProductsForCheckingExistingRecords__c 
                                            FROM FieldAssignment__c  WHERE WorkGroupId__r.Field__c =:System.Label.Network_Cost_Management and Recordtype.name=:System.Label.NCM ]){
                if(!fa.Primary__c){
                    if (assignmentsByWorkGroupMap.containsKey(fa.WorkGroupId__r.Name)) {
                        assignmentsByWorkGroupMap.get(fa.WorkGroupId__r.Name).add(fa);
                    } else {
                        assignmentsByWorkGroupMap.put(fa.WorkGroupId__r.Name, new List<FieldAssignment__c>{ fa });
                    }
                }
                else {
                        if(fa.UserId__c !=null){                                                
                            customerUserIdMap.put(fa.AccountId__c,fa.UserId__c);
                            customerUserFaMap.put(fa.AccountId__c,fa);
                        }                    
                }                
            }
        
        } 
        //if(customerUserIdMap.containsKey(newOrder.AccountId)){
        if(customerUserFaMap.containsKey(newOrder.AccountId)){
            //assigneeid = customerUserIdMap.get(newOrder.AccountId);
            assigneeid = customerUserFaMap.get(newOrder.AccountId).UserId__c;
            backupassigneeid = customerUserFaMap.get(newOrder.AccountId).Backup_Assignment__c ;
            outofoff = customerUserFaMap.get(newOrder.AccountId).OutOfOffice__c;
            
            if(outofoff){                
                newOrder.ownerId = backupassigneeid ;
                newOrder.Order_Provisioner__c = backupassigneeid ;   
            } else{
                newOrder.ownerId = assigneeid ;
                newOrder.Order_Provisioner__c = assigneeid ;
            }
        } 
        else {
            System.debug('newOrder.ownerId12==='+newOrder.ownerId); 
                //if(orderRecordTypeName == 'Contract Renewal'){
                if(orderRecordTypeName == System.Label.Contract_Renewal){
                    if(assignmentsByWorkGroupMap.containsKey(System.Label.Contract_Renewal_Customer)){
                        //lstFieldAssignmentUsers = assignmentsByWorkGroupMap.get('Contract Renewal Customer');
                        lstFieldAssignmentUsers = assignmentsByWorkGroupMap.get(System.Label.Contract_Renewal_Customer);
                    }
                }
                else if(orderRecordTypeName == System.Label.Disconnect_Order){
                //else if(orderRecordTypeName == 'Disconnect Order'){
                    if(assignmentsByWorkGroupMap.containsKey(System.Label.Disconnect_Customer)){
                        //lstFieldAssignmentUsers = assignmentsByWorkGroupMap.get('Disconnect Customer');
                        lstFieldAssignmentUsers = assignmentsByWorkGroupMap.get(System.Label.Disconnect_Customer);
                    }
                }
                else if(orderRecordTypeName == System.Label.New_Order){
                //else if(orderRecordTypeName == 'New Order'){
                    if(assignmentsByWorkGroupMap.containsKey(System.Label.New_Order_Customer)){
                        //lstFieldAssignmentUsers = assignmentsByWorkGroupMap.get('New Order Customer');
                        lstFieldAssignmentUsers = assignmentsByWorkGroupMap.get(System.Label.New_Order_Customer);
                    }
                }
                else{
                    if(assignmentsByWorkGroupMap.containsKey(System.Label.NCM_Other_Customer)){    
                    //if(assignmentsByWorkGroupMap.containsKey('NCM Other Customer')){
                        //lstFieldAssignmentUsers = assignmentsByWorkGroupMap.get(System.Label.NCM Other Customer');
                        lstFieldAssignmentUsers = assignmentsByWorkGroupMap.get(System.Label.NCM_Other_Customer);
                    }
                    
                }                
                
              if(lstFieldAssignmentUsers.size()>0){               
                   assigneeid = getNCMUserByRoundRobin(lstFieldAssignmentUsers);
                   if(assigneeid !=null){
                            newOrder.ownerId = assigneeid ;
                            newOrder.Order_Provisioner__c = assigneeid ;
                    }
                }         
        }
        User us = new User();
        if(newOrder.ownerId != null && string.valueOf(newOrder.ownerId).startsWith('005') ){
            us = [select id,Name,Email from User where id =: newOrder.ownerId];
            sendEmail(newOrder,us.Email);
        }
        // sendEmail(newOrder,us.Email); 
        System.debug('====newOrder.owner==='+newOrder.ownerId+'====newOrder.owner.Email==='+newOrder.owner.Email+'====newOrder====='+newOrder);                     
    
    }
    /* This method  is used for Roundrobin logic */
     public static string getNCMUserByRoundRobin(List<FieldAssignment__c> fieldAssignments) {    
        //Id NCMRecordtypeId = Schema.SObjectType.FieldAssignment__c.getRecordTypeInfosByName().get('NCM').getRecordTypeId();
        FieldAssignment__c fieldAssignment ; 
        List<FieldAssignment__c> records = new List<FieldAssignment__c>();
        
        for (FieldAssignment__c fa : fieldAssignments) {
            if (!fa.ProcessedRecord__c) {
                fieldAssignment = fa;
                break;
            }
        }         
        if (fieldAssignment != null) {
            // if we find an assignment, flag it as processed
            fieldAssignment.ProcessedRecord__c=true;
            Database.update(fieldAssignment); 
        } else {
            // if we dont find an assignment, grab the first person and reset the flags
            fieldAssignment = fieldAssignments[0];
            fieldAssignments.remove(0);
            for (FieldAssignment__c fa : fieldAssignments) {
                fa.ProcessedRecord__c = false;
            }  
            records.addAll(fieldAssignments);
            Database.update(records);            
        }
        
        string userId ;        
        if(fieldAssignment.OutOfOffice__c && isOutOfOffice(fieldAssignment.UserId__c) && fieldAssignment.Backup_Assignment__c !=null){          
               userId = fieldAssignment.Backup_Assignment__c;        
        }
        else{
            userId = fieldAssignment.UserId__c ;
        }        
        return userId ;
       
    }
    /* This method  is used for OutofOffice logic */
    public static Boolean isOutOfOffice(String OutOfficeUserid){    
        //Date assignmentDate = Date.today(); 
        Datetime assignmentDate = DateTime.now();
        system.debug('System DateTime is ' + DateTime.now()+'======='+ DateTime.now().format() + '===System.now ======'+ System.now() + '===========' +System.now().format());
        Boolean assigndate;
        try{        
            OutOfOffice userOutOffice =[select id,startDate,EndDate from OutOfOffice where userId =:OutOfficeUserid limit 1];
            assigndate = assignmentDate >= userOutOffice.startDate-1 && assignmentDate <=userOutOffice.EndDate;
            return assigndate;
            
        }
        catch(Exception Ex){    return false;    }           
    }
    
    // To Send Email to Order Owner.
    public static  void sendEmail(order ords, string userMail) {
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        Order ord = [Select id,OrderNumber,OwnerId,Owner.Name,Owner.Email from Order where id =: ords.id];        
        //String[] toAddresses = new String[]{'vinoth.ethiraj@ftr.com'};
        String[] toAddresses = new String[] {userMail};
        //toAddresses.add(ord.Owner.Email);
        mail.setToAddresses(toAddresses);
        
        mail.setSubject('Order transferred to you');    
        String body = '<html><body>Order ' + ord.OrderNumber  + ' has been assigned to you. Please click on the link below to view the record. <br><br>'+ URL.getSalesforceBaseUrl().toExternalForm()+ '/'+ord.id+'</body></html>';
        mail.setHtmlBody(body);   // mail.setHtmlBody(et.body); 
        mails.add(mail);    
        try{
            Messaging.sendEmail(mails);
        }
        catch(Exception e){
            system.debug('-------------exception------'+e.getMessage());
        }
    }
                  
}