UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/FieldAssignment__c.object-meta.xml
<CustomObject>
    <label>Field Assignment</label>
    <nameField>
        <displayFormat>Assignment{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <formula>CASE(WorkGroupId__r.Field__c,
  &quot;Network_Project_Specialist__c&quot;, &quot;Network Project Specialist&quot;,
  &quot;Order_Provisioner__c&quot;, &quot;Order Provisioner&quot;,
  &quot;Implementor_PM__c&quot;, &quot;Project Manager&quot;, 
  &quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Field</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FieldAssignment__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Add_On_Products__c.field-meta.xml
<CustomField>
    <fullName>Add_On_Products__c</fullName>
    <description>Field is used to add other available services to current Product Type (Family) and Product selected via the orders</description>
    <inlineHelpText>Items will display based on availability of other Products that can be added to the Product selected.</inlineHelpText>
    <label>Add-On Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BOT</fullName>
            </value>
            <value>
                <fullName>Broadband</fullName>
            </value>
            <value>
                <fullName>Centrex/CustoPak/CentraLink/Versaline</fullName>
            </value>
            <value>
                <fullName>Cloud Managed Solutions</fullName>
            </value>
            <value>
                <fullName>Connect Cloud</fullName>
            </value>
            <value>
                <fullName>Ethernet - BYOA</fullName>
            </value>
            <value>
                <fullName>Fiber Optics</fullName>
            </value>
            <value>
                <fullName>Hunting</fullName>
            </value>
            <value>
                <fullName>IP Connect</fullName>
            </value>
            <value>
                <fullName>IPVPN</fullName>
            </value>
            <value>
                <fullName>Managed Cellular Failover</fullName>
            </value>
            <value>
                <fullName>Managed Firewall</fullName>
            </value>
            <value>
                <fullName>Managed Security</fullName>
                <isActive>false</isActive>
                <label>Managed Security</label>
            </value>
            <value>
                <fullName>Managed Security - Advanced</fullName>
            </value>
            <value>
                <fullName>Managed Security - Standard</fullName>
            </value>
            <value>
                <fullName>Managed Wi-Fi</fullName>
                <label>Managed Wi-Fi - Indoor</label>
            </value>
            <value>
                <fullName>Managed Wi-Fi - Outdoor</fullName>
            </value>
            <value>
                <fullName>OneVoice</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other (3 way calling, Call Forwarding, Frontier Texting, etc.)</fullName>
            </value>
            <value>
                <fullName>POTS</fullName>
            </value>
            <value>
                <fullName>Remote Call Forward</fullName>
            </value>
            <value>
                <fullName>SDWAN - BYOA</fullName>
            </value>
            <value>
                <fullName>SIP Trunking</fullName>
            </value>
            <value>
                <fullName>Smart Voice</fullName>
            </value>
            <value>
                <fullName>Toll Free</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Voicemail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Order_Stage__c.field-meta.xml
<CustomField>
    <fullName>Order_Stage__c</fullName>
    <label>Order Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Clean Order</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Clean Order</fullName>
            </value>
            <value>
                <fullName>CNP Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>CPM In Progress</fullName>
            </value>
            <value>
                <fullName>Credit Check</fullName>
            </value>
            <value>
                <fullName>Customer Network Provisioning</fullName>
            </value>
            <value>
                <fullName>DPI/CMS Provisioning</fullName>
            </value>
            <value>
                <fullName>DPI Billing</fullName>
            </value>
            <value>
                <fullName>DPI Provisioning</fullName>
            </value>
            <value>
                <fullName>ECR/EWO In Progress</fullName>
                <label>ECR/PSR In Progress</label>
            </value>
            <value>
                <fullName>EWO In Progress</fullName>
            </value>
            <value>
                <fullName>Hot Cuts</fullName>
            </value>
            <value>
                <fullName>IMPM</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>ISP Engineering</fullName>
            </value>
            <value>
                <fullName>Issuing Orders</fullName>
            </value>
            <value>
                <fullName>MSA Review</fullName>
            </value>
            <value>
                <fullName>NCM Pending Billing</fullName>
            </value>
            <value>
                <fullName>Needs more information</fullName>
            </value>
            <value>
                <fullName>Network COE</fullName>
            </value>
            <value>
                <fullName>Network Cost Management</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Order Engineering Desk</fullName>
            </value>
            <value>
                <fullName>Ordering</fullName>
            </value>
            <value>
                <fullName>OSP Engineering</fullName>
            </value>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>QA Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cloud Managed Solutions</fullName>
            </value>
            <value>
                <fullName>CMS - Existing or BYOA</fullName>
            </value>
            <value>
                <fullName>CMS - New or Upgrade Ethernet</fullName>
            </value>
            <value>
                <fullName>CMS - New or Upgrade FiOS/HSI</fullName>
                <label>CMS - New or Upgrade FiberOptic/HSI</label>
            </value>
            <value>
                <fullName>Data (Only)</fullName>
            </value>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>E-LAN</fullName>
            </value>
            <value>
                <fullName>E-LAN + EIA</fullName>
            </value>
            <value>
                <fullName>E-Reach</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS - BYOA</fullName>
                <label>Existing BB/FiberOptic or BYOA</label>
            </value>
            <value>
                <fullName>FAW 2.5</fullName>
            </value>
            <value>
                <fullName>FAW 3.5</fullName>
            </value>
            <value>
                <fullName>FBH VOIP</fullName>
                <isActive>false</isActive>
                <label>FBH VOIP</label>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS</fullName>
            </value>
            <value>
                <fullName>Frontier Business Hosted VOIP</fullName>
                <isActive>false</isActive>
                <label>Frontier Business Hosted VOIP</label>
            </value>
            <value>
                <fullName>IP Connect</fullName>
                <isActive>false</isActive>
                <label>IP Connect</label>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi - Existing BB/FiOS or BYOA</fullName>
                <label>Managed Enterprise WiFi - Existing BB/FiberOptic or BYOA</label>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi - New or Existing Ethernet</fullName>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi - New or Upgrade BB/FiOS</fullName>
                <label>Managed Enterprise WiFi - New or Upgrade BB/FiberOptic</label>
            </value>
            <value>
                <fullName>Managed Firewall</fullName>
            </value>
            <value>
                <fullName>Managed Network Services</fullName>
            </value>
            <value>
                <fullName>Managed Security</fullName>
                <isActive>false</isActive>
                <label>Managed Security</label>
            </value>
            <value>
                <fullName>National ELAN</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS + Ethernet</fullName>
                <label>New or Existing EIA</label>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS + Broadband</fullName>
                <label>New or Upgrade BB/FiberOptic</label>
            </value>
            <value>
                <fullName>Off-Net Ethernet</fullName>
            </value>
            <value>
                <fullName>Ring Central</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>SDWAN - E-Reach/Off-Net Ethernet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2 - Wire Circuit</fullName>
            </value>
            <value>
                <fullName>4 - Wire Circuit</fullName>
            </value>
            <value>
                <fullName>56K</fullName>
            </value>
            <value>
                <fullName>64K</fullName>
            </value>
            <value>
                <fullName>BRI</fullName>
            </value>
            <value>
                <fullName>Broadband</fullName>
            </value>
            <value>
                <fullName>Circuit</fullName>
            </value>
            <value>
                <fullName>CPE</fullName>
            </value>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>E-LAN</fullName>
            </value>
            <value>
                <fullName>E-LAN &amp; EIA</fullName>
            </value>
            <value>
                <fullName>Ethernet</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>FOTS</fullName>
            </value>
            <value>
                <fullName>Fractional Circuit</fullName>
            </value>
            <value>
                <fullName>Frontier Anyware Mitel Hosted</fullName>
            </value>
            <value>
                <fullName>Frontier AnyWare UCaaS</fullName>
            </value>
            <value>
                <fullName>Frontier Calling with Cloud Phone</fullName>
                <label>Frontier Direct Calling</label>
            </value>
            <value>
                <fullName>IP/VPN</fullName>
            </value>
            <value>
                <fullName>Managed Enterprise WiFi</fullName>
            </value>
            <value>
                <fullName>Managed Router</fullName>
            </value>
            <value>
                <fullName>Managed Services</fullName>
            </value>
            <value>
                <fullName>OC-12</fullName>
            </value>
            <value>
                <fullName>OC-3</fullName>
            </value>
            <value>
                <fullName>OC-48</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Private Line T1 / DS1</fullName>
            </value>
            <value>
                <fullName>Private Line T3 / DS3</fullName>
            </value>
            <value>
                <fullName>Ring Central</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Router_s__c.field-meta.xml
<CustomField>
    <fullName>Router_s__c</fullName>
    <label>Router(s)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>IAD</fullName>
            </value>
            <value>
                <fullName>Managed Router</fullName>
            </value>
            <value>
                <fullName>Managed Router and IAD</fullName>
            </value>
            <value>
                <fullName>No Router</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/recordTypes/Vlocity_OM_Order.recordType-meta.xml
<RecordType>
    <fullName>Vlocity_OM_Order</fullName>
    <active>true</active>
    <description>Vlocity OM Order</description>
    <label>Vlocity OM Order</label>
</RecordType>

UCF-APR2.4/ftr main/force-app/main/default/classes/ftr_OrderTriggerTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      FieldAssignmentService
 *      ftr_OrderTriggerHandler
 * @author            : TBD
 * @version           : 2
**/
@isTest
public class ftr_OrderTriggerTest {
    @testSetup 
    static void prepareTestData() {

        Order[] orderList = ftr_TestDataFactory.getOrders(1);

        String orderRecordType = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('Vlocity_OM_Order').getRecordTypeId();
        for (Order o : orderList) {
            o.RecordTypeId = orderRecordType;
        }
        insert orderList;
        
        insert ftr_TestDataFactory.getFieldAssignments(4);
    }
	
	@isTest 
    static void CNPTest() {

        Order ordObj = [SELECT Id, Order_Stage__c FROM Order LIMIT 1];
        ordObj.Order_Stage__c = 'Customer Network Provisioning';
        ordObj.Add_On_Products__c = 'SIP Trunking';
        
        Test.startTest();
        
        update ordObj;

        Test.stopTest();
	}

    @isTest 
    static void SDWANTest() {
        
        Order ordObj = [SELECT Id, Product_Type__c, Product__c, Router_s__c, Order_Stage__c FROM Order LIMIT 1];
        ordObj.Order_Stage__c = 'QA Review';
        ordObj.Product_Type__c = 'SDWAN';
        ordObj.Product__c = 'SDWAN - E-Reach/Off-Net Ethernet';
        ordObj.Add_On_Products__c = 'SIP Trunking';
        ordObj.Router_s__c = null;
        
        Test.startTest();
        
        update ordObj;

        Test.stopTest();
	}

    @isTest 
    static void sendOrderDetailsTest() {
        
        Order ordObj = [SELECT Id, Product_Type__c, OrderNumber, AccountId, OwnerId, Product__c, Router_s__c, Order_Stage__c FROM Order LIMIT 1];
        
        Test.startTest();
        
        FieldAssignmentService.sendOrderDetails(ordObj, ordObj, ordObj.OwnerId);

        Test.stopTest();
	}

    @isTest 
    static void noProvisionersTest() {
        delete [SELECT Id FROM FieldAssignment__c WHERE Field__c = 'Order Provisioner'];

        Order ordObj = [SELECT Id, Product_Type__c, Product__c, Router_s__c, Order_Stage__c FROM Order LIMIT 1];
        ordObj.Order_Stage__c = 'Customer Network Provisioning';
        ordObj.Product_Type__c = 'SDWAN';
        ordObj.Product__c = 'SDWAN - E-Reach/Off-Net Ethernet';

        Group q;
        try {
            q = [SELECT Id, Email FROM Group WHERE DeveloperName = 'CNP_Assignment_Notice' AND Type='Queue'];
            q.Email = 'test@test.com';
            update q;
        } catch (Exception e) {
            q = new Group (Email='test@test.com', DeveloperName = 'CNP_Assignment_Notice', Name='CNP_Assignment_Notice', Type='Queue');
            insert q;
            System.runAs(new User(Id=UserInfo.getUserId())) {
                QueuesObject testQueue = new QueueSObject(QueueID = q.id, SObjectType = 'Task');
                insert testQueue;
            }
        }
        
                
        Test.startTest();
        
        update ordObj;

        // FieldAssignmentService service = new FieldAssignmentService(ordObj, ordObj);
        // service.sendOrderExceptionEmail(q);

        Test.stopTest();
	}

    @isTest 
    static void deleteOrderTest() {

        Order ordObj = [SELECT Id, Product_Type__c, Product__c, Router_s__c, Order_Stage__c FROM Order LIMIT 1];
                
        Test.startTest();
        
        delete ordObj;

        Test.stopTest();
	}


}