UCF-APR2.4/ftr main/force-app/main/default/objects/FRL_Status_Update__e/FRL_Status_Update__e.object-meta.xml
<CustomObject>
    <description>published by the &quot;Publish Status Update Event&quot; Auto Task (M6 Plan)</description>
    <label>FRL Status Update</label>
    <pluralLabel>FRL Status Updates</pluralLabel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FRL_Status_Update__e/fields/FRL_Id__c.field-meta.xml
<CustomField>
    <fullName>FRL_Id__c</fullName>
    <label>FRL Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FRL_Status_Update__e/fields/FRL_Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>FRL_Reference_Id__c</fullName>
    <label>FRL Reference Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FRL_Status_Update__e/fields/Orchestration_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Orchestration_Item_Id__c</fullName>
    <label>Orchestration Item Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FRL_Status_Update__e/fields/Plan_Id__c.field-meta.xml
<CustomField>
    <fullName>Plan_Id__c</fullName>
    <label>Plan Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FRL_Status_Update__e/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/ftr_FRLStatusUpdateEventDispatcherTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 3 
**/
@isTest
public with sharing class ftr_FRLStatusUpdateEventDispatcherTest {

    @isTest  
    static void afterInsertTest() {

        FRL_Status_Update__e testEvent = new FRL_Status_Update__e();
        testEvent.FRL_Id__c = '1234567890';
        testEvent.FRL_Reference_Id__c = '0987654321';
        testEvent.JSONAttribute__c = 'jsonAttribute';
        testEvent.Object_Type__c = 'TestObjectType';
        testEvent.Orchestration_Item_Id__c = '1111111';
        testEvent.Plan_Id__c = '2222222';
        testEvent.Product_Code__c = 'ENT_ETH_UNI_PSR_001';
        testEvent.Status__c = 'Completed';

        test.startTest();
        EventBus.publish(testEvent);
        test.stopTest();
        
    }
}