UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/ftr_FieldLevelDiscounting__mdt.object-meta.xml
<CustomObject>
    <description>Config Item for Field Level Discounting.</description>
    <label>ftr FieldLevelDiscounting</label>
    <pluralLabel>ftr FieldLevelDiscountings</pluralLabel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Approval_Needed__c.field-meta.xml
<CustomField>
    <fullName>Approval_Needed__c</fullName>
    <label>Approval_Needed</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Discount_Max__c.field-meta.xml
<CustomField>
    <fullName>Discount_Max__c</fullName>
    <label>Discount Max</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Discount_Min__c.field-meta.xml
<CustomField>
    <fullName>Discount_Min__c</fullName>
    <label>Discount Min</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/FiberTier__c.field-meta.xml
<CustomField>
    <fullName>FiberTier__c</fullName>
    <label>FiberTier</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Pricing_Group__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Group__c</fullName>
    <label>Pricing Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <inlineHelpText>Product Code</inlineHelpText>
    <label>ProductCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <label>Speed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_FieldLevelDiscounting__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MRC</fullName>
                <default>true</default>
                <label>MRC</label>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Order/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <label>Speed</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/FieldLevelDiscountWrapperTest.cls
@isTest
public with sharing class FieldLevelDiscountWrapperTest {
    public FieldLevelDiscountWrapperTest() {

    }

    @isTest
    public static void main(){

        List<ftr_FieldLevelDiscounting__mdt> fldRecords = [SELECT Id, Priority__c, ProductCode__c, FiberTier__c, Speed__c, Type__c, Discount_Max__c, Discount_Min__c, Term__c, Approval_Needed__c 
                                                    , Pricing_Group__c FROM ftr_FieldLevelDiscounting__mdt order by Priority__c desc LIMIT 2];
        List<FieldLevelDiscountWrapper> comparedRecords = new List<FieldLevelDiscountWrapper>();
        for (ftr_FieldLevelDiscounting__mdt fld:fldRecords){
            FieldLevelDiscountWrapper fldwrapper = new FieldLevelDiscountWrapper(fld);
            comparedRecords.add(fldwrapper);
        }
        comparedRecords.sort();
    } 
}