UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/FTRWSAddress__c.object-meta.xml
<CustomObject>
    <description>Custom table to store DPI and DSAT address qualification</description>
    <label>FTRWSAddress</label>
    <nameField>
        <label>FTRWSAddress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FTRWSAddress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/Address_Lost_checkbox__c.field-meta.xml
<CustomField>
    <fullName>Address_Lost_checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Address Lost checkbox</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <label>Opportunity ID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Service Addresses</relationshipLabel>
    <relationshipName>ServiceAddress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Opportunity/fields/Lost_MRR2__c.field-meta.xml
<CustomField>
    <fullName>Lost_MRR2__c</fullName>
    <label>Lost MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/IsSyncing__c.field-meta.xml
<CustomField>
    <fullName>IsSyncing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for the vlocity hybrid quote initiative. Determines whether the quote is synced with the opportunity.</description>
    <label>IsSyncing</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/SterlingQuote__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Object</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/IsSyncing__c.field-meta.xml
<CustomField>
    <fullName>IsSyncing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/SterlingQuoteItem__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Item</description>
    <label>Quote Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/FTRWSAddress__c.field-meta.xml
<CustomField>
    <fullName>FTRWSAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FTRWSAddress</label>
    <referenceTo>FTRWSAddress__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/NetNewMRR__c.field-meta.xml
<CustomField>
    <fullName>NetNewMRR__c</fullName>
    <label>NetNewMRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>SterlingQuote__r.OpportunityId__r.Id</formula>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/ST_AddressID__c.field-meta.xml
<CustomField>
    <fullName>ST_AddressID__c</fullName>
    <label>Address Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/SterlingQuote__c.field-meta.xml
<CustomField>
    <fullName>SterlingQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>SterlingQuote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>SterlingQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/FTRWSCalculateOppMRR.cls
public class FTRWSCalculateOppMRR {

    @InvocableMethod(label='calculateMRR' category='Wholesale')
    public static void calculateMRR(List<Id> oppId){

    try{
        //FTRWSAddress__c addr = [SELECT Opportunity_ID__c FROM FTRWSAddress__c WHERE Id=:addressId[0]];
        SterlingQuote__c quote = [SELECT Id from SterlingQuote__c WHERE OpportunityId__c =: oppId[0] and IsSyncing__c = TRUE LIMIT 1];
        double lostMRR = 0.00;

        List<FTRWSAddress__c> addrList = [SELECT Id FROM FTRWSAddress__c WHERE Opportunity_ID__c =: oppId[0] AND Address_Lost_checkbox__c = TRUE];

        List<Id> addrIdList = new List<Id>();

		for (FTRWSAddress__c a: addrList){
    		addrIdList.add(a.Id);
		}

        if (quote != null && addrList != null){
            List<SterlingQuoteItem__c> quoteItemList = [SELECT Id, NetNewMRR__c, ST_AddressID__c FROM SterlingQuoteItem__c WHERE SterlingQuote__c =:quote.Id];
            for (SterlingQuoteItem__c item: quoteItemList){
                if (addrIdList.contains(item.ST_AddressID__c)){
                    lostMRR = lostMRR +  item.NetNewMRR__c;
                    System.debug('lostMrr:' + lostMRR);
                }
            }
        }

        Opportunity opp = [SELECT Lost_MRR2__c FROM Opportunity WHERE Id =:oppId[0]];
        opp.Lost_MRR2__c = lostMRR;
        if (!Test.isRunningTest()){
            update opp;
        }
        System.debug('opp:'+opp);
    }catch(Exception e){
        System.debug(e);
    }
    }


}