UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/FTRWSAddress__c.object-meta.xml
<CustomObject>
    <description>Custom table to store DPI and DSAT address qualification</description>
    <label>FTRWSAddress</label>
    <nameField>
        <label>FTRWSAddress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FTRWSAddress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/FTRWSAddress__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <label>Opportunity ID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Service Addresses</relationshipLabel>
    <relationshipName>ServiceAddress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/FTRWSCVDRatesRequestTest.cls
/**
 * @description       : This test class covers the following Apex classes:
 *      TBD_CLASS1
 *      TBD_CLASS2
 *      TBD_CLASS3
 * @author            : TBD
 * @version           : 1 
**/
@isTest
public class FTRWSCVDRatesRequestTest {

    @isTest
    public static void TestFTRWSCVDRatesRequest() {
        Test.startTest();
        Opportunity opp = new Opportunity();
        opp.StageName = 'Investigating';
        opp.CloseDate= System.today();
        opp.Name = 'TestOpp';
        insert opp;
        FTRWSCVDRatesRequest req = new FTRWSCVDRatesRequest();
        FTRWSAddress__c address = new FTRWSAddress__c();
        address.Opportunity_ID__c = opp.Id;
        insert address;
        req.addressId=address.Id;
        req.pNUM=''; 
        
        req.locTier=''; 
        req.region='';
        req.spec='';
    
        req.los='';
        req.vta=''; 
        
        req.product=''; 
        req.serviceTierPort='';
        req.circuitType='';
        
        req.usocTier='';
        req.usocType=''; 
        req.uniSpeed=''; 
        req.evcSpeed='';
        req.nrcUsoc='';
    
        req.mrcUsoc='';
        req.cntrlKey=''; 
        
       
        req.address='';
        req.city=''; 
        req.stateCd=''; 
        req.swc='';
        Test.stopTest();
    }
}