UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Used to capture approval eligibility and status.</description>
    <inlineHelpText>Used to capture approval eligibility and status.</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Pending Approval - ICB</fullName>
            </value>
            <value>
                <fullName>Pending Approval - RSM</fullName>
            </value>
            <value>
                <fullName>Pending Approval - Pricing</fullName>
            </value>
            <value>
                <fullName>Pending Approval - Product</fullName>
            </value>
            <value>
                <fullName>Pending Approval - Finance</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
                <isActive>false</isActive>
                <label>Pending Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/ftr_Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>ftr_Approval_Type__c</fullName>
    <description>Ftr Approval Type</description>
    <label>ftr Approval Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/ApprovalProcessHelper.cls
public without sharing class ApprovalProcessHelper {
    
    public static void autoSubmitAndApprove(String contextId) {
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Auto Submitting for approval.');
        req1.setObjectId(contextId);
        
        // Submit the approval request for the account
        Approval.ProcessResult result = Approval.process(req1);
        
        // Approve the submitted request
        // First, get the ID of the newly created item
        List<Id> newWorkItemIds = result.getNewWorkitemIds();
        
        // Instantiate the new ProcessWorkitemRequest object and populate it
        Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
        req2.setComments('Auto Approving request.');
        req2.setAction('Approve');
        
        // Use the ID from the newly created item to specify the item to be worked
        req2.setWorkitemId(newWorkItemIds.get(0));
        
        // Submit the request for approval
        Approval.ProcessResult result2 =  Approval.process(req2);
    }
    
    public static void submitToDealDesk(Id quoteId){
         List<ProcessInstanceWorkitem> processItems = [SELECT Id, ProcessInstanceId, ProcessInstance.TargetObjectId FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId =: quoteId];
       			for (ProcessInstanceWorkitem item:processItems ){
                	Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
        			req.setAction('Reject');       
        			req.setWorkitemId(item.Id);
   					Approval.process(req);
                }
                //update quote
                Quote q = new Quote(Id = quoteId);
                q.ftr_Approval_Type__c = 'Deal Desk';
        		q.Approval_Status__c = 'Pending Approval - Pricing';
                update q;
                //create a new approval
                Approval.ProcessSubmitRequest approvalRequest = new Approval.ProcessSubmitRequest();
                approvalRequest.setObjectId(quoteId);
                //approvalRequest.setProcessDefinitionNameorId('Approval process name');
                Approval.ProcessResult result = Approval.process(approvalRequest);
    }
}