UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/Order_Opportunity_Unlocked__c.field-meta.xml
<CustomField>
    <fullName>Order_Opportunity_Unlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Opportunity Unlocked</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/vlocity_cmt__PriceListId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__PriceListId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price List</label>
    <referenceTo>vlocity_cmt__PriceList__c</referenceTo>
    <relationshipLabel>Quotes Using This Price List</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/OpportunityLockBatchJob.cls
global class OpportunityLockBatchJob implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext bc) {
        //collect all  open Opportunities
        return Database.getQueryLocator([Select Id,OpportunityId, Order_Opportunity_Unlocked__c from Quote where vlocity_cmt__pricelistid__c <> null AND Order_Opportunity_Unlocked__c = true]);
    }
    global void execute(Database.BatchableContext bc, List<Quote> scope){
        // process each batch of records and lock the record 
        for(Quote quoteObj: scope){
            if (!Approval.isLocked(quoteObj.OpportunityId)){
                Approval.lock(quoteObj.OpportunityId);
            }
            quoteObj.Order_Opportunity_Unlocked__c = false;
        }
        
        if(scope.size() > 0){
            update scope;
        }
    }    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    } 
}