UCF-APR2.4/ftr main/force-app/main/default/objects/Quote/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>This field is used to show which products are being quoted.</description>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIA</fullName>
            </value>
            <value>
                <fullName>EVPL</fullName>
            </value>
            <value>
                <fullName>SDWAN</fullName>
            </value>
            <value>
                <fullName>UCF</fullName>
            </value>
            <value>
                <fullName>UCaaS</fullName>
            </value>
            <value>
                <fullName>CCaaS</fullName>
            </value>
            <value>
                <fullName>Private Network</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/SterlingQuote__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Object</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/FOTS__c.field-meta.xml
<CustomField>
    <fullName>FOTS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if a quote line item discounted belongs to FOTS category</description>
    <label>FOTS</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used for setting quote status dynamically. Defined for wholesale.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/SterlingQuoteItem__c.object-meta.xml
<CustomObject>
    <description>Sterling Quote Item</description>
    <label>Quote Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Adjusted_MRC_Notes__c.field-meta.xml
<CustomField>
    <fullName>Adjusted_MRC_Notes__c</fullName>
    <description>Notes added by the user when MRC is adjusted for wholesale</description>
    <label>Adjusted MRC Notes</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Adjusted_NRC_Notes__c.field-meta.xml
<CustomField>
    <fullName>Adjusted_NRC_Notes__c</fullName>
    <description>Notes added by the user when NRC is adjusted for wholesale</description>
    <label>Adjusted NRC Notes</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedMRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedMRC__c</fullName>
    <label>Adjusted MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/AdjustedNRC__c.field-meta.xml
<CustomField>
    <fullName>AdjustedNRC__c</fullName>
    <label>Adjusted NRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/FOTS__c.field-meta.xml
<CustomField>
    <fullName>FOTS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if a quote line item discounted belongs to FOTS category</description>
    <label>FOTS</label>
    <type>Checkbox</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/MRC_Discount_Applied_By__c.field-meta.xml
<CustomField>
    <fullName>MRC_Discount_Applied_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Captured MRC discount applied by info for wholesale app</description>
    <label>MRC Discount Applied By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/MRC_Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>MRC_Discount_Type__c</fullName>
    <description>Discount type selected for the wholesale quote item</description>
    <label>MRC Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Override</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/NetNewMRR__c.field-meta.xml
<CustomField>
    <fullName>NetNewMRR__c</fullName>
    <label>NetNewMRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/NRC_Discount_Applied_By__c.field-meta.xml
<CustomField>
    <fullName>NRC_Discount_Applied_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Captures NRC discount applied by info for wholesale app</description>
    <label>NRC Discount Applied By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Items3</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/NRC_Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>NRC_Discount_Type__c</fullName>
    <description>NRC discount type selected while applying a discount. Used for wholesale app.</description>
    <label>NRC Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Override</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/OverallStatus__c.field-meta.xml
<CustomField>
    <fullName>OverallStatus__c</fullName>
    <label>OverallStatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>INA Accepted</fullName>
            </value>
            <value>
                <fullName>INA Rejected</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Pending - Business Decision Support</fullName>
            </value>
            <value>
                <fullName>Pending - Credit</fullName>
            </value>
            <value>
                <fullName>Pending - Engineering Wireless</fullName>
            </value>
            <value>
                <fullName>Pending - Engineering Wireless Final</fullName>
            </value>
            <value>
                <fullName>Pending - Finance</fullName>
            </value>
            <value>
                <fullName>Pending - INA</fullName>
            </value>
            <value>
                <fullName>Pending - Post Completion Audit Finance</fullName>
            </value>
            <value>
                <fullName>Pending - Post Completion Audit Originator</fullName>
            </value>
            <value>
                <fullName>Pending - Post Engineering Originator</fullName>
            </value>
            <value>
                <fullName>Pending - Post Engineering originator Wireless</fullName>
            </value>
            <value>
                <fullName>Pending - Regional President</fullName>
            </value>
            <value>
                <fullName>Pending - Sales Engineering</fullName>
            </value>
            <value>
                <fullName>Pending - Site Verification</fullName>
            </value>
            <value>
                <fullName>Pending - State VP</fullName>
            </value>
            <value>
                <fullName>Pending - Wireless Management</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending SIFT Status</fullName>
            </value>
            <value>
                <fullName>Pending SIFT Status-ON HOLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/StandardMRC__c.field-meta.xml
<CustomField>
    <fullName>StandardMRC__c</fullName>
    <label>Standard MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/StandardNRC__c.field-meta.xml
<CustomField>
    <fullName>StandardNRC__c</fullName>
    <label>Standard NRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending - Business Decision Support</fullName>
            </value>
            <value>
                <fullName>Pending - Credit</fullName>
            </value>
            <value>
                <fullName>Pending - Engineering Wireless</fullName>
            </value>
            <value>
                <fullName>Pending - Engineering Wireless Final</fullName>
            </value>
            <value>
                <fullName>Pending - Finance</fullName>
            </value>
            <value>
                <fullName>Pending - INA</fullName>
            </value>
            <value>
                <fullName>Pending - Post Completion Audit Finance</fullName>
            </value>
            <value>
                <fullName>Pending - Post Completion Audit Originator</fullName>
            </value>
            <value>
                <fullName>Pending - Post Engineering Originator</fullName>
            </value>
            <value>
                <fullName>Pending - Post Engineering originator Wireless</fullName>
            </value>
            <value>
                <fullName>Pending - Sales Engineering</fullName>
            </value>
            <value>
                <fullName>Pending - Site Verification</fullName>
            </value>
            <value>
                <fullName>Pending - State VP</fullName>
            </value>
            <value>
                <fullName>Pending - Regional President</fullName>
            </value>
            <value>
                <fullName>Pending - Wireless Management</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>INA Accepted</fullName>
            </value>
            <value>
                <fullName>INA Rejected</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/SterlingQuote__c.field-meta.xml
<CustomField>
    <fullName>SterlingQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>SterlingQuote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>SterlingQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/objects/SterlingQuoteItem__c/fields/UpdatedMRC__c.field-meta.xml
<CustomField>
    <fullName>UpdatedMRC__c</fullName>
    <label>UpdatedMRC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/FTRWSAdjustmentController.cls
public class FTRWSAdjustmentController {
    
    
    @AuraEnabled
    public static Boolean removeDiscount(String jsonString) {
        Boolean discRemoved = false;
        
        FTRWSDiscountRequest ftrwsDiscountObj = (FTRWSDiscountRequest)JSON.deserialize(jsonString, FTRWSDiscountRequest.class);
        String recurringType = ftrwsDiscountObj.recurringType;
        SterlingQuoteItem__c quoteItem = ftrwsDiscountObj.quoteItem;
        String discountType = ftrwsDiscountObj.discountType;
        Decimal discountVal = ftrwsDiscountObj.discountVal;
        String notes = '';
        
        System.debug('discountVal:' + discountVal);
        if(recurringType.containsIgnoreCase('MRC')) {
            quoteItem.AdjustedMRC__c = quoteItem.StandardMRC__c;
            quoteItem.MRC_Discount_Type__c = '';
            quoteItem.Adjusted_MRC_Notes__c = 'Deleted discount';
            quoteItem.MRC_Discount_Applied_By__c = null;
            quoteItem.NetNewMRR__c = quoteItem.AdjustedMRC__c;
        } else {
            quoteItem.AdjustedNRC__c = quoteItem.StandardNRC__c;
            quoteItem.Adjusted_NRC_Notes__c = 'Deleted discount';
            quoteItem.NRC_Discount_Type__c = '';
            quoteItem.NRC_Discount_Applied_By__c = null;
        }
        
        //quoteItem.Discount_Applied_By__c = null;//UserInfo.getUserId();
        quoteItem.OverallStatus__c = 'Draft';
        
        SterlingQuote__c quote = [select Id from SterlingQuote__c where Id=: quoteItem.SterlingQuote__c];
        quote.Status__c = 'Draft';
        update quoteItem;
        update quote;
        
        return discRemoved;
    }
    
    //recurringdiscType starts with mrc or nrc
    //discountType can be Percentage, Amount, Override
    @AuraEnabled
    public static Boolean applyDiscount(String jsonString) {
        Boolean discApplied = false;
        System.debug('Apply discount request: ' + jsonString);
        FTRWSDiscountRequest ftrwsDiscountObj = (FTRWSDiscountRequest)JSON.deserialize(jsonString, FTRWSDiscountRequest.class);
        String recurringType = ftrwsDiscountObj.recurringType;
        SterlingQuoteItem__c quoteItem = ftrwsDiscountObj.quoteItem;
        String discountType = ftrwsDiscountObj.discountType;
        Decimal discountVal = ftrwsDiscountObj.discountVal;
        String mrcDiscNotes = ftrwsDiscountObj.mrcDiscountNotes;
        String nrcDiscNotes = ftrwsDiscountObj.nrcDiscountNotes;
        System.debug('discountVal:' + discountVal);
        if(discountVal == 0.0 || discountVal == 0) {
            System.debug('No discount applied, as discount Value is ' + discountVal);
            return discApplied;
        }
        if(recurringType.containsIgnoreCase('MRC')) {
            mrcDiscNotes = ftrwsDiscountObj.mrcDiscountNotes;
            discApplied = applyMRCDiscount(quoteItem, discountType, discountVal, mrcDiscNotes); 
        } else {
            nrcDiscNotes = ftrwsDiscountObj.nrcDiscountNotes;
            discApplied = applyNRCDiscount(quoteItem, discountType, discountVal, nrcDiscNotes);    
        }
        return discApplied;
    }
    
    private static Boolean applyMRCDiscount(SterlingQuoteItem__c quoteItem, String discountType, Decimal discountVal, String newNotes) {
        Boolean discApplied = false;
        Decimal mrc = quoteItem.StandardMRC__c;
        if(String.isNotBlank(discountType)) {
            String discType = discountType.toUpperCase();
            if(discType == 'AMOUNT') {//amount
                quoteItem.AdjustedMRC__c = mrc + discountVal;
                discApplied = true;
            } else if(discType == 'OVERRIDE') {//override
                quoteItem.AdjustedMRC__c = discountVal;
                discApplied = true;
            } else if(discType == 'PERCENTAGE') {//percentage
                quoteItem.AdjustedMRC__c = mrc + (mrc * (discountVal/100)) ;
                discApplied = true;
            }
            
            if(discApplied) {
                System.debug('quoteItem.StandardMRC__c: ' + quoteItem.StandardMRC__c);
                System.debug('quoteItem.AdjustedMRC__c: ' + quoteItem.AdjustedMRC__c);
                quoteItem.NetNewMRR__c = quoteItem.AdjustedMRC__c; //check with Hemantha later
                quoteItem.UpdatedMRC__c = quoteItem.AdjustedMRC__c;//Added by Vara
                String existingNotes = quoteItem.Adjusted_MRC_Notes__c;
                if(String.isBlank(existingNotes)) {
                    if(String.isNotBlank(newNotes)) {
                        quoteItem.Adjusted_MRC_Notes__c = newNotes;    
                    }
                    
                } else {
                    if(String.isNotBlank(newNotes)) {
                        quoteItem.Adjusted_MRC_Notes__c = existingNotes + ' ' + newNotes;        
                    }
                }
                quoteItem.OverallStatus__c = 'Pending';
                quoteItem.MRC_Discount_Applied_By__c = UserInfo.getUserId();
                SterlingQuote__c quote = [select Id from SterlingQuote__c where Id=: quoteItem.SterlingQuote__c];
                quote.Status__c = 'Needs Review';
                
                if(String.isNotBlank(quoteItem.Products__r.Family)) {
                    if(quoteItem.Products__r.Family.contains('FOTS')) {
                        quote.FOTS__c = true;
                    }
                }
                update quoteItem;
                update quote;
            }
        }
        
        return discApplied;
    }
    
    //TODO: need to rework this based on the applyMRC logic
    private static Boolean applyNRCDiscount(SterlingQuoteItem__c quoteItem, String discountType, Decimal discountVal, String newNotes) {
        Boolean discApplied = false;
        Decimal nrc = quoteItem.StandardNRC__c;
        if(String.isNotBlank(discountType)) {
            String discType = discountType.toUpperCase();
            if(discType == 'AMOUNT') {//amount
                quoteItem.AdjustedNRC__c = nrc + discountVal;
                discApplied = true;
            } else if(discType == 'OVERRIDE') {//override
                quoteItem.AdjustedNRC__c = discountVal;
                discApplied = true;
            } else if(discType == 'PERCENTAGE') {//percentage
                quoteItem.AdjustedNRC__c = nrc + (nrc * (discountVal/100)) ;
                discApplied = true;
            }
        }
        
        if(discApplied) {
            System.debug('quoteItem.StandardNRC__c: ' + quoteItem.StandardNRC__c);
            System.debug('quoteItem.AdjustedNRC__c: ' + quoteItem.AdjustedNRC__c);
            //quoteItem. = quoteItem.AdjustedMRC__c; //check with Hemantha later
            String existingNotes = quoteItem.Adjusted_NRC_Notes__c;
            if(String.isBlank(existingNotes)) {
                if(String.isNotBlank(newNotes)) {
                    quoteItem.Adjusted_NRC_Notes__c = newNotes;    
                }
                
            } else {
                if(String.isNotBlank(newNotes)) {
                    quoteItem.Adjusted_NRC_Notes__c = existingNotes + ' ' + newNotes;        
                }
            }
            quoteItem.OverallStatus__c = 'Pending';
            quoteItem.UpdatedNRC__c=quoteItem.AdjustedNRC__c;//Added by Vara
            quoteItem.NRC_Discount_Applied_By__c = UserInfo.getUserId();
            SterlingQuote__c quote = [select Id from SterlingQuote__c where Id=: quoteItem.SterlingQuote__c];
            quote.Status__c = 'Needs Review';
            
                if(String.isNotBlank(quoteItem.Products__r.Family)) {
                    if(quoteItem.Products__r.Family.contains('FOTS')) {
                        quote.FOTS__c = true;
                    }
                }
            
            update quoteItem;
            update quote;
        }
        return discApplied;
    }
    
    @AuraEnabled
    public static FTRWSDiscountResponse getQuoteLineItemDiscountInfo(String jsonString) {
        System.debug('Apply discount request: ' + jsonString);
        FTRWSDiscountRequest discObj = (FTRWSDiscountRequest)JSON.deserialize(jsonString, FTRWSDiscountRequest.class);
        if(discObj != null) {
            String recurrType = discObj.recurringType;
            if(String.isNotBlank(recurrType)) {
                if('MRC'.equalsIgnoreCase(recurrType)) {
                    FTRWSDiscountResponse mrcDiscResp =  getMRCDiscountInfo(discObj);
                    return mrcDiscResp;
                } else {
                    FTRWSDiscountResponse nrcDiscResp = getNRCDiscountInfo(discObj);
                    return nrcDiscResp;
                }
            }
        }
        
        return null;        
    } 
    
    private static FTRWSDiscountResponse getMRCDiscountInfo(FTRWSDiscountRequest ftrwsDiscountObj) {
        FTRWSDiscountResponse response = new FTRWSDiscountResponse();
        SterlingQuoteItem__c quoteItem  = [Select Id,Primary_Competitor__c,Primary_Competitor_Amount__c,Competitors_in_area__c, Adjusted_MRC_Notes__c, AdjustedMRC__c, MRC_Discount_Applied_By__c, StandardMRC__c, Display_MRC__c from SterlingQuoteItem__c where Id=: ftrwsDiscountObj.quoteItem.Id];
        // Added by Vara from here
        Decimal PrimaryCompetitorAmount = quoteItem.Primary_Competitor_Amount__c;
        response.PrimaryCompetitor = quoteItem.Primary_Competitor__c;
        response.PrimaryCompetitorArea = quoteItem.Competitors_in_area__c;
        response.PrimaryCompetitorAmt = PrimaryCompetitorAmount;
        // Added by Vara upto Here
        Decimal actualMRC = quoteItem.StandardMRC__c;
        response.actualAmt = actualMRC;
        response.displayAmt = quoteItem.Display_MRC__c;
        Decimal adjustedMRC =  quoteItem.AdjustedMRC__c;
        response.adjustedAmt = adjustedMRC;
        response.notes = quoteItem.Adjusted_MRC_Notes__c;
        
        if(String.isNotBlank(quoteItem.MRC_Discount_Applied_By__c)) {
            User user = [Select Id, FirstName, LastName from User where Id=:quoteItem.MRC_Discount_Applied_By__c];
            response.discAppliedBy = user.FirstName +' ' + user.LastName;
        }
        response.recurringType = 'MRC';
        response.discAmt = adjustedMRC - actualMRC; 
        if(response.discAmt != 0.0) {
            response.isDiscounted = true;
        } 
        return response;        
    }
    
    private static FTRWSDiscountResponse getNRCDiscountInfo(FTRWSDiscountRequest ftrwsDiscountObj) {
        FTRWSDiscountResponse response = new FTRWSDiscountResponse();
        
        SterlingQuoteItem__c quoteItem  = [Select Id,Primary_Competitor__c,Primary_Competitor_Amount__c,Competitors_in_area__c, Adjusted_NRC_Notes__c, AdjustedNRC__c, NRC_Discount_Applied_By__c, StandardNRC__c, Display_NRC__c from SterlingQuoteItem__c where Id=: ftrwsDiscountObj.quoteItem.Id];
        // Added by Vara from here
        Decimal PrimaryCompetitorAmount = quoteItem.Primary_Competitor_Amount__c;
        response.PrimaryCompetitor = quoteItem.Primary_Competitor__c;
        response.PrimaryCompetitorArea = quoteItem.Competitors_in_area__c;
        response.PrimaryCompetitorAmt = PrimaryCompetitorAmount;
        // Added by Vara upto Here        
        Decimal actualNRC = quoteItem.StandardNRC__c;
        response.actualAmt = actualNRC;
        response.displayAmt = quoteItem.Display_NRC__c;
        Decimal adjustedNRC =  quoteItem.AdjustedNRC__c;
        response.adjustedAmt = adjustedNRC;
        response.notes = quoteItem.Adjusted_NRC_Notes__c;
        
        if(String.isNotBlank(quoteItem.NRC_Discount_Applied_By__c)) {
            User user = [Select Id, FirstName, LastName from User where Id=:quoteItem.NRC_Discount_Applied_By__c];
            response.discAppliedBy = user.FirstName +' ' + user.LastName;
        }

        response.recurringType = 'NRC';
        response.discAmt = adjustedNRC - actualNRC;
        if(response.discAmt != 0.0) {
            response.isDiscounted = true;
        }         
        return response;         
    }
/*        

*/    
    
   
}