UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_VOIP_Qualification__c/ftr_VOIP_Qualification__c.object-meta.xml
<CustomObject>
    <label>ftr_VOIP_Qualification</label>
    <nameField>
        <displayFormat>VOIPQUAL{0000}</displayFormat>
        <label>VOIP_Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ftr_VOIP_Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UCF-APR2.4/ftr main/force-app/main/default/objects/ftr_VOIP_Qualification__c/fields/NXX__c.field-meta.xml
<CustomField>
    <fullName>NXX__c</fullName>
    <label>NXX</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UCF-APR2.4/ftr main/force-app/main/default/classes/CallVoipQualificationIP_Test.cls
@isTest
global class CallVoipQualificationIP_Test {
    
    @isTest(SeeAllData=true)
    static public void test_VoipQualificationIP1()
    {
        ftr_VOIP_Qualification__c voip = [SELECT Id, NPA__c, NXX__c FROM ftr_VOIP_Qualification__c LIMIT 1];
        String npa = String.valueOf(voip.NPA__c.format()) ;
        String nxx = String.valueOf(voip.NXX__c.format()) ;
        String name = 'xyz';
        system.debug(npa + ' - ' + nxx);
        
        Test.startTest();
        Map<String,Object> ipResponse = CallVoipQualificationIP.QualifyVoip(npa,nxx, 'xyz');
        Test.stopTest();
        
        System.assertNotEquals(NULL, ipResponse);
    }
}